Version 9.9.1

{============================= Main Part ======================================}
[general]
                    File = C:\user\c\lise_pp_99\LISEpp_ActualInstaller\install\files\examples\afission\AF_208Pb_p.lpp
                    Date = 29-12-2014
                    Time = 15:05:02
           Configuration = NSCL\A1900_2005A.lcn
             Optionsfile = A1900_2005A.lopt
                   Title = NSCL A1900 Fragment Separator 2005
          BlockStructure = DSWDMSWMMDSWDMSMMM

[settings]
                   A,Z,Q = 208Pb82+                              ; Mass ElementName Charge+ Beam
                  Energy = 1000                 MeV/u            
               Intensity = 1                    pnA              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 132Sn                                 ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 1                    (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 20                   (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 1                    (±)mm            ; one-half the vertical beam extent (y)
                      BF = 20                   (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.07                 (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = 0                    degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 32                                    ; Number of points in distribution
        NP charge states = 32                                    ; Number of points in distribution
                NP wedge = 32                                    ; Number of points in distribution
           Charge states = No                                    ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,1,1,1                               ; Nomer,Z,Atoms,Mass
        Target thickness = 1,208,0.0715,0,0                      ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 5                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 32                                    ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 2                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 0                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 1                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-10    
               FisCS_TKE = 1e-6     
                      N0 = 82                                    ; default 82
                     dU0 = -2.5                                  ; default -2.5
                      C0 = 1.4                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -5.5                                  ; default -5.5
                      C1 = 0.16                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-4     
                 BeamInd = 1e-6     
               BeamTotal = 1e-8     

[convolution]
        Convolution mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 5.758 
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 16                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
          AvoidUnboundCS = 1                                     ; 1-Yes, 0-No
       ProtectedChannels = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 1                                     ; 0 - no, 1 - use
         DissipationBeta = 1                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 1                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 0                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 27       
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 19       
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       

[evapauto]
                  tun_a0 = -0.71783
                  tun_a1 = 0.41085
                  tun_a2 = 0.12612
                 A_Bound = 300                                   ; mass
               A_Pairing =  70                                   ; mass

[plot]
            Start target = Detector                              ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = M7
         dE-detector-1st = M5
         dE-detector-2nd = M6
            TKE-detector = M7
                PlotBrho = S2
               PlotWedge = S4
              X-detector = M6
              Y-detector = M6
                 Tilting = M1
                 Stopper = M2
                RO_Wedge = 
          ConditionBlock = A0
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 1
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 0
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = PublishedData\208Pb\208Pb_1H_1AGeV_fission.cs

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 1                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 2                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 250                  MeV              
                Velocity = 1                                     ; Calculat fissile nuclei speed
           LowEx_nucleus =  2H                                   ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 0.000e+00 41.60 10.65                 ; mb, MeV, Mev
           MidEx_nucleus = 198Hg                                 ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.750e+02 300.00 56.07                ; mb, MeV, Mev
          HighEx_nucleus = 194Pt                                 ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 0.000e+00 0.00 93.71                  ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 82
                   Dr_n0 = 0
                   Dr_n1 = 126

[cross sections]
1     47Ti  = 0.2 0.029 5
2     48Ti  = 0.288 0.042 5
3     49Ti  = 0.349 0.091 5
4     50Ti  = 0.277 0.061 5
5     51Ti  = 0.128 0.054 5
6     52Ti  = 0.06 0.023 5
7     49V   = 0.182 0.026 5
8     50V   = 0.303 0.038 5
9     51V   = 0.367 0.084 5
10    52V   = 0.273 0.057 5
11    53V   = 0.239 0.051 5
12    54V   = 0.121 0.022 5
13    55V   = 0.05 0.012 5
14    51Cr  = 0.215 0.024 5
15    52Cr  = 0.366 0.039 5
16    53Cr  = 0.386 0.078 5
17    54Cr  = 0.452 0.068 5
18    55Cr  = 0.25 0.048 5
19    56Cr  = 0.217 0.035 5
20    57Cr  = 0.092 0.011 5
21    53Mn  = 0.181 0.022 5
22    54Mn  = 0.335 0.035 5
23    55Mn  = 0.456 0.073 5
24    56Mn  = 0.475 0.063 5
25    57Mn  = 0.449 0.046 5
26    58Mn  = 0.262 0.033 5
27    59Mn  = 0.17 0.021 5
28    60Mn  = 0.051 0.015 5
29    55Fe  = 0.129 0.014 5
30    56Fe  = 0.382 0.027 5
31    57Fe  = 0.478 0.037 5
32    58Fe  = 0.649 0.057 5
33    59Fe  = 0.523 0.033 5
34    60Fe  = 0.446 0.035 5
35    61Fe  = 0.263 0.046 5
36    62Fe  = 0.09 0.014 5
37    57Co  = 0.086 0.011 5
38    58Co  = 0.311 0.024 5
39    59Co  = 0.549 0.039 5
40    60Co  = 0.665 0.057 5
41    61Co  = 0.714 0.041 5
42    62Co  = 0.586 0.042 5
43    63Co  = 0.429 0.048 5
44    64Co  = 0.167 0.026 5
45    65Co  = 0.108 0.046 5
46    59Ni  = 0.035 0.006 5
47    60Ni  = 0.299 0.02 5
48    61Ni  = 0.512 0.038 5
49    62Ni  = 0.865 0.057 5
50    63Ni  = 0.813 0.045 5
51    64Ni  = 0.829 0.053 5
52    65Ni  = 0.596 0.056 5
53    66Ni  = 0.318 0.072 5
54    67Ni  = 0.139 0.056 5
55    68Ni  = 0.054 0.036 5
56    61Cu  = 0.026 0.004 5
57    62Cu  = 0.179 0.016 5
58    63Cu  = 0.464 0.03 5
59    64Cu  = 0.759 0.06 5
60    65Cu  = 0.973 0.044 5
61    66Cu  = 0.951 0.055 5
62    67Cu  = 0.872 0.064 5
63    68Cu  = 0.485 0.071 5
64    69Cu  = 0.239 0.056 5
65    70Cu  = 0.088 0.032 5
66    71Cu  = 0.041 0.024 5
67    64Zn  = 0.149 0.013 5
68    65Zn  = 0.422 0.026 5
69    66Zn  = 0.813 0.059 5
70    67Zn  = 1.05 0.046 5
71    68Zn  = 1.205 0.06 5
72    69Zn  = 1.211 0.073 5
73    70Zn  = 0.754 0.082 5
74    71Zn  = 0.401 0.053 5
75    72Zn  = 0.193 0.038 5
76    73Zn  = 0.082 0.034 5
77    66Ga  = 0.082 0.008 5
78    67Ga  = 0.353 0.022 5
79    68Ga  = 0.737 0.059 5
80    69Ga  = 1.215 0.049 5
81    70Ga  = 1.299 0.087 5
82    71Ga  = 1.453 0.085 5
83    72Ga  = 1.135 0.096 5
84    73Ga  = 0.635 0.064 5
85    74Ga  = 0.334 0.037 5
86    75Ga  = 0.179 0.047 5
87    76Ga  = 0.061 0.014 5
88    68Ge  = 0.038 0.005 5
89    69Ge  = 0.286 0.019 5
90    70Ge  = 0.719 0.057 5
91    71Ge  = 1.237 0.056 5
92    72Ge  = 1.608 0.092 5
93    73Ge  = 1.626 0.089 5
94    74Ge  = 1.651 0.107 5
95    75Ge  = 0.938 0.094 5
96    76Ge  = 0.61 0.046 5
97    77Ge  = 0.233 0.076 5
98    78Ge  = 0.098 0.013 5
99    79Ge  = 0.04 0.018 5
100   71As  = 0.176 0.014 5
101   72As  = 0.493 0.041 5
102   73As  = 1.189 0.055 5
103   74As  = 1.659 0.09 5
104   75As  = 2.066 0.115 5
105   76As  = 1.838 0.119 5
106   77As  = 1.48 0.132 5
107   78As  = 0.815 0.05 5
108   79As  = 0.406 0.073 5
109   80As  = 0.201 0.013 5
110   81As  = 0.079 0.024 5
111   82As  = 0.023 0.01 5
112   73Se  = 0.102 0.011 5
113   74Se  = 0.523 0.041 5
114   75Se  = 1.136 0.056 5
115   76Se  = 1.741 0.092 5
116   77Se  = 2.144 0.115 5
117   78Se  = 2.432 0.137 5
118   79Se  = 1.904 0.156 5
119   80Se  = 1.205 0.056 5
120   81Se  = 0.698 0.075 5
121   82Se  = 0.328 0.02 5
122   83Se  = 0.147 0.045 5
123   84Se  = 0.045 0.012 5
124   75Br  = 0.048 0.006 5
125   76Br  = 0.315 0.033 5
126   77Br  = 0.973 0.052 5
127   78Br  = 1.494 0.086 5
128   79Br  = 2.269 0.113 5
129   80Br  = 2.566 0.153 5
130   81Br  = 2.469 0.162 5
131   82Br  = 1.554 0.063 5
132   83Br  = 0.991 0.094 5
133   84Br  = 0.454 0.023 5
134   85Br  = 0.196 0.048 5
135   86Br  = 0.095 0.012 5
136   87Br  = 0.033 0.02 5
137   77Kr  = 0.038 0.005 5
138   78Kr  = 0.289 0.032 5
139   79Kr  = 0.783 0.045 5
140   80Kr  = 1.577 0.089 5
141   81Kr  = 2.369 0.123 5
142   82Kr  = 3.08 0.172 5
143   83Kr  = 2.997 0.168 5
144   84Kr  = 2.044 0.076 5
145   85Kr  = 1.384 0.12 5
146   86Kr  = 0.679 0.027 5
147   87Kr  = 0.305 0.049 5
148   88Kr  = 0.153 0.012 5
149   89Kr  = 0.054 0.025 5
150   90Kr  = 0.021 0.022 5
151   80Rb  = 0.176 0.024 5
152   81Rb  = 0.677 0.04 5
153   82Rb  = 1.413 0.082 5
154   83Rb  = 2.191 0.135 5
155   84Rb  = 2.989 0.166 5
156   85Rb  = 3.41 0.173 5
157   86Rb  = 2.429 0.088 5
158   87Rb  = 1.597 0.122 5
159   88Rb  = 0.93 0.049 5
160   89Rb  = 0.457 0.069 5
161   90Rb  = 0.233 0.018 5
162   91Rb  = 0.106 0.042 5
163   92Rb  = 0.04 0.024 5
164   82Sr  = 0.112 0.015 5
165   83Sr  = 0.621 0.039 5
166   84Sr  = 1.242 0.08 5
167   85Sr  = 2.197 0.132 5
168   86Sr  = 2.962 0.165 5
169   87Sr  = 3.605 0.18 5
170   88Sr  = 2.761 0.097 5
171   89Sr  = 1.891 0.126 5
172   90Sr  = 1.177 0.067 5
173   91Sr  = 0.598 0.09 5
174   92Sr  = 0.356 0.03 5
175   93Sr  = 0.194 0.063 5
176   94Sr  = 0.073 0.034 5
177   95Sr  = 0.028 0.019 5
178   84Y   = 0.074 0.01 5
179   85Y   = 0.415 0.035 5
180   86Y   = 1.089 0.078 5
181   87Y   = 2.063 0.128 5
182   88Y   = 2.758 0.162 5
183   89Y   = 3.415 0.204 5
184   90Y   = 3.028 0.102 5
185   91Y   = 2.074 0.14 5
186   92Y   = 1.493 0.074 5
187   93Y   = 0.874 0.106 5
188   94Y   = 0.54 0.032 5
189   95Y   = 0.31 0.06 5
190   96Y   = 0.114 0.032 5
191   97Y   = 0.061 0.034 5
192   86Zr  = 0.029 0.004 5
193   87Zr  = 0.305 0.033 5
194   88Zr  = 0.949 0.05 5
195   89Zr  = 1.865 0.12 5
196   90Zr  = 2.841 0.158 5
197   91Zr  = 3.264 0.2 5
198   92Zr  = 3.124 0.104 5
199   93Zr  = 2.272 0.141 5
200   94Zr  = 1.793 0.089 5
201   95Zr  = 1.244 0.129 5
202   96Zr  = 0.74 0.049 5
203   97Zr  = 0.46 0.066 5
204   98Zr  = 0.247 0.035 5
205   99Zr  = 0.076 0.033 5
206   100Zr  = 0.024 0.007 5
207   88Nb  = 0.018 0.003 5
208   89Nb  = 0.203 0.023 5
209   90Nb  = 0.672 0.044 5
210   91Nb  = 1.611 0.115 5
211   92Nb  = 2.399 0.151 5
212   93Nb  = 2.964 0.188 5
213   94Nb  = 3.064 0.101 5
214   95Nb  = 2.667 0.139 5
215   96Nb  = 2.13 0.104 5
216   97Nb  = 1.571 0.136 5
217   98Nb  = 0.895 0.058 5
218   99Nb  = 0.645 0.069 5
219   100Nb  = 0.343 0.036 5
220   101Nb  = 0.158 0.042 5
221   102Nb  = 0.055 0.006 5
222   90Mo  = 0.022 0.004 5
223   91Mo  = 0.175 0.021 5
224   92Mo  = 0.548 0.04 5
225   93Mo  = 1.093 0.091 5
226   94Mo  = 1.781 0.135 5
227   95Mo  = 2.476 0.16 5
228   96Mo  = 2.977 0.104 5
229   97Mo  = 2.677 0.138 5
230   98Mo  = 2.29 0.107 5
231   99Mo  = 1.807 0.137 5
232   100Mo  = 1.207 0.065 5
233   101Mo  = 0.831 0.07 5
234   102Mo  = 0.486 0.038 5
235   103Mo  = 0.189 0.042 5
236   104Mo  = 0.078 0.021 5
237   105Mo  = 0.024 0.011 5
238   92Tc  = 0.022 0.005 5
239   93Tc  = 0.132 0.016 5
240   94Tc  = 0.405 0.037 5
241   95Tc  = 0.838 0.087 5
242   96Tc  = 1.531 0.122 5
243   97Tc  = 1.83 0.135 5
244   98Tc  = 2.654 0.096 5
245   99Tc  = 2.745 0.139 5
246   100Tc  = 2.266 0.106 5
247   101Tc  = 1.935 0.15 5
248   102Tc  = 1.31 0.068 5
249   103Tc  = 0.806 0.09 5
250   104Tc  = 0.549 0.04 5
251   105Tc  = 0.371 0.058 5
252   106Tc  = 0.122 0.027 5
253   107Tc  = 0.048 0.025 5
254   108Tc  = 0.014 0.009 5
255   94Ru  = 0.009 0.004 5
256   95Ru  = 0.051 0.013 5
257   96Ru  = 0.233 0.034 5
258   97Ru  = 0.549 0.081 5
259   98Ru  = 1.048 0.1 5
260   99Ru  = 1.593 0.134 5
261   100Ru  = 2.277 0.09 5
262   101Ru  = 2.289 0.121 5
263   102Ru  = 2.03 0.102 5
264   103Ru  = 2.032 0.169 5
265   104Ru  = 1.55 0.072 5
266   105Ru  = 0.863 0.094 5
267   106Ru  = 0.683 0.041 5
268   107Ru  = 0.358 0.059 5
269   108Ru  = 0.157 0.028 5
270   109Ru  = 0.067 0.023 5
271   110Ru  = 0.018 0.013 5
272   97Rh  = 0.055 0.016 5
273   98Rh  = 0.143 0.023 5
274   99Rh  = 0.417 0.066 5
275   100Rh  = 0.609 0.072 5
276   101Rh  = 1.117 0.133 5
277   102Rh  = 1.793 0.079 5
278   103Rh  = 2.148 0.098 5
279   104Rh  = 1.862 0.099 5
280   105Rh  = 1.877 0.172 5
281   106Rh  = 1.599 0.088 5
282   107Rh  = 1.068 0.096 5
283   108Rh  = 0.701 0.048 5
284   109Rh  = 0.532 0.059 5
285   110Rh  = 0.193 0.029 5
286   111Rh  = 0.125 0.022 5
287   112Rh  = 0.047 0.013 5
288   100Pd  = 0.11 0.023 5
289   101Pd  = 0.264 0.045 5
290   102Pd  = 0.479 0.056 5
291   103Pd  = 0.859 0.13 5
292   104Pd  = 1.527 0.069 5
293   105Pd  = 1.716 0.093 5
294   106Pd  = 1.774 0.092 5
295   107Pd  = 1.648 0.163 5
296   108Pd  = 1.555 0.086 5
297   109Pd  = 1.045 0.097 5
298   110Pd  = 0.778 0.055 5
299   111Pd  = 0.546 0.062 5
300   112Pd  = 0.284 0.03 5
301   113Pd  = 0.155 0.022 5
302   114Pd  = 0.04 0.012 5
303   115Pd  = 0.013 0.009 5
304   102Ag  = 0.07 0.018 5
305   103Ag  = 0.18 0.035 5
306   104Ag  = 0.278 0.052 5
307   105Ag  = 0.658 0.122 5
308   106Ag  = 1.059 0.06 5
309   107Ag  = 1.352 0.089 5
310   108Ag  = 1.493 0.078 5
311   109Ag  = 1.256 0.15 5
312   110Ag  = 1.453 0.086 5
313   111Ag  = 1.191 0.089 5
314   112Ag  = 0.812 0.053 5
315   113Ag  = 0.646 0.064 5
316   114Ag  = 0.31 0.033 5
317   115Ag  = 0.17 0.023 5
318   116Ag  = 0.066 0.012 5
319   117Ag  = 0.025 0.009 5
320   104Cd  = 0.023 0.007 5
321   105Cd  = 0.081 0.016 5
322   106Cd  = 0.172 0.031 5
323   107Cd  = 0.424 0.069 5
324   108Cd  = 0.651 0.054 5
325   109Cd  = 1.053 0.062 5
326   110Cd  = 1.129 0.07 5
327   111Cd  = 0.982 0.138 5
328   112Cd  = 1.259 0.087 5
329   113Cd  = 0.869 0.086 5
330   114Cd  = 0.729 0.063 5
331   115Cd  = 0.492 0.062 5
332   116Cd  = 0.31 0.033 5
333   117Cd  = 0.147 0.024 5
334   118Cd  = 0.088 0.012 5
335   119Cd  = 0.03 0.008 5
336   106In  = 0.01 0.005 5
337   107In  = 0.06 0.01 5
338   108In  = 0.085 0.03 5
339   109In  = 0.32 0.064 5
340   110In  = 0.529 0.053 5
341   111In  = 0.691 0.053 5
342   112In  = 0.887 0.056 5
343   113In  = 0.829 0.128 5
344   114In  = 0.922 0.077 5
345   115In  = 0.795 0.081 5
346   116In  = 0.736 0.061 5
347   117In  = 0.491 0.062 5
348   118In  = 0.249 0.034 5
349   119In  = 0.163 0.024 5
350   120In  = 0.063 0.012 5
351   121In  = 0.049 0.008 5
352   109Sn  = 0.015 0.008 5
353   110Sn  = 0.034 0.009 5
354   111Sn  = 0.151 0.051 5
355   112Sn  = 0.341 0.048 5
356   113Sn  = 0.6 0.043 5
357   114Sn  = 0.66 0.034 5
358   115Sn  = 0.733 0.124 5
359   116Sn  = 0.849 0.072 5
360   117Sn  = 0.588 0.078 5
361   118Sn  = 0.479 0.06 5
362   119Sn  = 0.374 0.058 5
363   120Sn  = 0.245 0.035 5
364   121Sn  = 0.137 0.022 5
365   122Sn  = 0.061 0.012 5
366   123Sn  = 0.039 0.008 5
367   111Sb  = 0.012 0.005 5
368   112Sb  = 0.026 0.006 5
369   113Sb  = 0.092 0.054 5
370   114Sb  = 0.176 0.033 5
371   115Sb  = 0.288 0.04 5
372   116Sb  = 0.402 0.029 5
373   117Sb  = 0.57 0.123 5
374   118Sb  = 0.577 0.068 5
375   119Sb  = 0.503 0.078 5
376   120Sb  = 0.399 0.061 5
377   121Sb  = 0.292 0.056 5
378   122Sb  = 0.189 0.03 5
379   123Sb  = 0.113 0.018 5
380   124Sb  = 0.074 0.012 5
381   125Sb  = 0.025 0.008 5
382   114Te  = 0.018 0.007 5
383   115Te  = 0.043 0.021 5
384   116Te  = 0.095 0.034 5
385   117Te  = 0.192 0.04 5
386   118Te  = 0.31 0.025 5
387   119Te  = 0.362 0.105 5
388   120Te  = 0.402 0.072 5
389   121Te  = 0.403 0.054 5
390   122Te  = 0.232 0.059 5
391   123Te  = 0.203 0.04 5
392   124Te  = 0.181 0.025 5
393   125Te  = 0.107 0.014 5
394   126Te  = 0.056 0.011 5
395   127Te  = 0.035 0.008 5

[previous]
                 Lowerst = 132Sn                                 ; Mass ElementName Charge+ Beam
                 Highest = 132Sn                                 ; Mass ElementName Charge+ Beam

[MC_options]
                   dXsel = 0
                   dYsel = 2
                  dAZQ_X = 1
                  dAZQ_Y = 5
                  dVEL_X = 1
                  dVEL_Y = 0
               dIso_mode = 0
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 0
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 2
                  CS_use = 1
           envelope_show = 0
                use_bore = 0
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
              AZQ_Xsigma = 0.1   
              AZQ_Ysigma = 0.1   
                 G1_gate = 0 0 -100.0000 100.0000
                 G2_gate = 0 0 -100.0000 100.0000
                 G3_gate = 0 0 -100.0000 100.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 0 0,R1,R1,R1                          ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 0 0,R1,R1,R1
            G3_component = 0 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = D1,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 8.719000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = A1900\A1900_D1-Z026.cal

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-150.0,100.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-150.0,100.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = -2.30370e+00,+9.20000e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.88860e+01
                    row2 = +1.07560e+00,-4.38400e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-04
                    row3 = +0.00000e+00,+0.00000e+00,+7.38100e-01,+2.30000e-03,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+3.73030e+00,+1.36630e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 60                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 40                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 14.81996             Tm               ; magnetic rigidity
                   Angle = 45                   degrees          
                  Radius = 3.1                  m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = I1_slits,1                            ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = I1_wedge,1                            ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,2.702,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[W1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W1_WedgeSettings]
             ProfileMode = 1                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 2                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = 0.00000              mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = NULL
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = D2,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 8.767000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = A1900\A1900_D2-Z048.cal

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = -1.03250e+00,-2.16000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.93010e+01
                    row2 = +3.50000e-03,-9.68500e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.01100e-01
                    row3 = +0.00000e+00,+0.00000e+00,+1.14820e+00,-1.90000e-03,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+4.11510e+00,+8.64200e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 30                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 60                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 14.81996             Tm               ; magnetic rigidity
                   Angle = -45                  degrees          
                  Radius = 3.1                  m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = I2_PPAC0,1                            ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 1,2.2,2.702,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 100,2.54,3.125       ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-200.00,-200.0,200.00,200.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = I2_slits,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-13.00,-150.0,13.00,150.0           ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK W2 - Wedge ======================================}

[W2_General]
                    Name = I2_wedge,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W2_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,2.702,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W2_WedgeSettings]
             ProfileMode = 1                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 2                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = 0.00000              mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = D4
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = I2_PPAC1,1                            ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 1,2.2,2.702,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 100,2.54,3.125       ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-200.00,-200.0,200.00,200.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = I2_SCI,1                              ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,6,9,12.011                          ; Nomer,Z,Atoms,Mass
               contents2 = 1,1,10,1.008                          ; Nomer,Z,Atoms,Mass
               thickness = 1,30,1.032,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,5                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,5                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,15,100           ns,mm,mm         ; Time&X&Y space

[M3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-175.00,-175.0,175.00,175.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-30.00,-30.0,30.00,30.0             ; joint,Bottom,B-limit,Top,T-limit

[M3_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK D3 - Dipole ======================================}

[D3_General]
                    Name = D3,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 8.767000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = A1900\A1900_D3-Z071.cal

[D3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-150.0,100.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-150.0,100.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[D3_optics]
                    row1 = -9.68500e-01,-2.16000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.83750e+01
                    row2 = +3.50000e-03,-1.03250e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.06900e-01
                    row3 = +0.00000e+00,+0.00000e+00,+8.20300e-01,-9.70000e-03,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+4.25850e+00,+1.16860e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D3_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 30                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 55                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D3_DipoleSettings]
                    Brho = 14.81996             Tm               ; magnetic rigidity
                   Angle = -45                  degrees          
                  Radius = 3.1                  m                

[D3_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = I3_slits,1                            ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK W3 - Wedge ======================================}

[W3_General]
                    Name = I3_wedge,1                            ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W3_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,2.702,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W3_WedgeSettings]
             ProfileMode = 1                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 2                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = 0.00000              mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = D4
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK D4 - Dipole ======================================}

[D4_General]
                    Name = D4,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 9.227000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = A1900\A1900_D4-Z093.cal

[D4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-150.0,100.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-150.0,100.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[D4_optics]
                    row1 = -7.26000e-01,+1.50000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.09740e+01
                    row2 = +3.82000e-01,-1.38520e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.10350e+01
                    row3 = +0.00000e+00,+0.00000e+00,+1.59310e+00,+1.33000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+3.00840e+00,+6.52800e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D4_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 28                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 50                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D4_DipoleSettings]
                    Brho = 14.81996             Tm               ; magnetic rigidity
                   Angle = 45                   degrees          
                  Radius = 3.1                  m                

[D4_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M4 - Material ======================================}

[M4_General]
                    Name = FP_PPAC0,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M4_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 1,2,2.702,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 1,1,1                ns,mm,mm         ; Time&X&Y space

[M4_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M4_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M4_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = FP_slits,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-25.00,-25.0,25.00,25.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-25.00,-25.0,25.00,25.0             ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M5 - Material ======================================}

[M5_General]
                    Name = FP_PIN,1                              ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M5_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,470,2.321,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,2                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.15                                ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.2,1,1              ns,mm,mm         ; Time&X&Y space

[M5_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-25.00,-25.0,25.00,25.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-25.00,-25.0,25.00,25.0             ; joint,Bottom,B-limit,Top,T-limit

[M5_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M5_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M6 - Material ======================================}

[M6_General]
                    Name = FP_PPAC1,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M6_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 1,2,2.702,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,1                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 1,1,1                ns,mm,mm         ; Time&X&Y space

[M6_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M6_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M6_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M7 - Material ======================================}

[M7_General]
                    Name = FP_SCI,1                              ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M7_Compound]
               contents1 = 0,6,9,12.011                          ; Nomer,Z,Atoms,Mass
               contents2 = 1,1,10,1.008                          ; Nomer,Z,Atoms,Mass
               thickness = 4,100,1.032,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,50                                  ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,5                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.2,100,100          ns,mm,mm         ; Time&X&Y space

[M7_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-75.00,-75.0,75.00,75.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M7_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M7_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= Calculations ======================================}

[Calculations]
132Sn 50+ 50+ 50+ 50+ =6.2003e-09,6.2003e-09,5,6.2003e-09,1.8081e-14,0,4.3803e-01,9.7405e+02,2.3815e+01,7.9081e-01,1,1,1,1,7.9081e-01,1,1,1,1,1,1,1,1,1,1,1,8.1662e-01,8.9530e-01,1,9.9488e-01,9.1682e-01,7.7147e-01,7.7291e-01,1,1,9.9872e-01,9.5618e-01,9.5618e-01,1,1,1,1,1,1,1,1,1,1,1,9.9635e-01,1,1,1,9.9635e-01,9.2303e-01,1,1,1,9.2317e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,9.9153e-01,1,1,1,1,9.9153e-01,1,1,1,1,1,1,1,1,1,1,1.1908e-01,1,1,1,1,1.1908e-01,1,1
