Version 9.4.101

{============================= Main Part ======================================}
[general]
                    File = C:\user\c\lise_pp_94\files\examples\RESOLUT\RESOLUT_3gap_reaction.lpp
                    Date = 28-02-2013
                    Time = 12:34:26
           Configuration = other\RESOLUT_3gap.lcn
             Optionsfile = A1900_2012.lopt
                   Title = RESOLUT 3 gpas
          BlockStructure = DDLSMBBBSSSSSDSSSSSSMLSM

[settings]
                   A,Z,Q = 24Mg12+                               ; Mass ElementName Charge+ Beam
                  Energy = 6.25                 MeV/u            
               Intensity = 1                    pnA              ; enA,pna,pps,kW
            RF frequency = 97                   MHz              
            Bunch length = 0.3                  ns               
         Settings on A,Z = 25Al                                  ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 1.5                  (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 20                   (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 1.5                  (±)mm            ; one-half the vertical beam extent (y)
                      BF = 20                   (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.5                  (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = -1                   degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 32                                    ; Number of points in distribution
        NP charge states = 32                                    ; Number of points in distribution
                NP wedge = 32                                    ; Number of points in distribution
           Charge states = No                                    ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,4,1,9.012                           ; Nomer,Z,Atoms,Mass
        Target thickness = 1,1,1.85,0,0                          ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 7                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 128                                   ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 1                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 1                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 1                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-11    
               FisCS_TKE = 1e-8     
                      N0 = 83                                    ; default 82
                     dU0 = -2.65                                 ; default -2.5
                      C0 = 0.7                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -3.8                                  ; default -5.5
                      C1 = 0.15                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-5     
                 BeamInd = 1e-20    
               BeamTotal = 1e-20    

[convolution]
        Convolution mode = 1                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 3     
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 1                                     ; 0 - no, 1 - use
         DissipationBeta = 1                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 0                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 0                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
               EE_C_mode = 0
             EE_C_Zbound = 0
             EE_C_Abound = 0
          EnergyCoef_CA0 = 0       
          EnergyCoef_CA1 = 3       
          EnergyCoef_CA2 = 0       
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CA0 = 0       
           SigmaCoef_CA1 = 2       
           SigmaCoef_CA2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       

[evapauto]
                  tun_a0 = -0.61392
                  tun_a1 = 0.44559
                  tun_a2 = 0.12008
                 A_Bound = 300                                   ; mass
               A_Pairing =   1                                   ; mass

[plot]
            Start target = RF                                    ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = T1
         dE-detector-1st = M1
         dE-detector-2nd = M1
            TKE-detector = M1
                PlotBrho = D1
               PlotWedge = S4
              X-detector = M1
              Y-detector = M1
                 Tilting = M1
                 Stopper = M2
          ConditionBlock = A10
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 2
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
           LowEx_nucleus = 39Ar                                  ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 34S                                   ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 28Si                                  ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 8.000e+02 250.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 12
                   Dr_n0 = 0
                   Dr_n1 = 12

[cross sections]

[previous]
                 Lowerst =  1H                                   ; Mass ElementName Charge+ Beam
                 Highest = 49Ti                                  ; Mass ElementName Charge+ Beam


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = Tuning Dipole,1                       ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000100             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-30.00,-200.0,30.00,200.0           ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+01
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 47                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 47                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 0.61887              Tm               ; magnetic rigidity
                   Angle = 0.0001               degrees          
                  Radius = 3                    m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = Compensat,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.001000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.00000e+01
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 0.61887              Tm               ; magnetic rigidity
                   Angle = 0.0001               degrees          
                  Radius = 3                    m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit


{============================= BLOCK L1 - Solenoid ======================================}

[L1_General]
                    Name = Solenoid 1,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 2.160000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[L1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[L1_optics]
                    row1 = -6.08821e-01,+1.01130e-02,-2.09646e+00,+3.48239e-02,+0.00000e+00,+0.00000e+00
                    row2 = -5.70405e-01,-1.18273e-01,-1.96418e+00,-4.07269e-01,+0.00000e+00,+0.00000e+00
                    row3 = +2.09646e+00,-3.48239e-02,-6.08821e-01,+1.01130e-02,+0.00000e+00,+0.00000e+00
                    row4 = +1.96418e+00,+4.07269e-01,-5.70405e-01,-1.18273e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[L1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 47                   mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 47                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[L1_SolenoidSettings]
      UseSoftCorrections = 1                                     ; 1 - Yes / 0 - No
               Direction = 1                                     ; +1 positive, -1 negative
                  Sstate = 0                                     ; 0-B_field_max, 1-Current
                 Current = 34.24883             A                
               BfieldMax = 2.657358             T                
              CoilLength = 0.6                  m                
               EffRadius = 0.05                 m                
              LengthDraw = 0.6                  m                
                    Bore = 0.045                m                
               FirstHalf = 0.65                 m                
              SecondHalf = 1.51                 m                
              MAconstant = 0.03933              T/A              
         TuningParameter = 4
         UseGlobalMatrix = 1


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = Drift 1,0                             ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.010000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 1                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 3.505487             Tm               


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = Material 1,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0.001,2.321,0,0                     ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = -251450112,-20.00,-50.0,20.00,50.0    ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = -1204013516,-20.00,-50.0,20.00,50.0   ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK B1 - RFbuncher ======================================}

[B1_General]
                    Name = RFbuncher 1,1                         ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.112000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[B1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-20.0,20.00,20.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-20.0,20.00,20.0             ; joint,Bottom,B-limit,Top,T-limit

[B1_optics]
                    row1 = +1.00000e+00,+1.12000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+1.12000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[B1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[B1_BuncherSettings]
                      La = 0.025                m                ; distance before electrodes
                      Lb = 0.05                 m                ; distance after electrodes
              PhaseShift = 35                   deg              ; Phase shift
                  EUmode = 1                                     ; 0-ElectrField, 1-Voltage
                  RFmode = 0                                     ; 0-beam, 1-manually
                RFmanual = 93.000               MHz              
                     Gap = 0.037                m                ; gap between electrodes
               ElecField = 3216.216             KV/m             
                 Voltage = 119.000              KV               
                ttf_mode = 0                                     ; 0-calc, 1-manually
              ttf_manual = 1.0000
             tuning_mode = 2                                     ; d3 , d3m, d5, d5m


{============================= BLOCK B2 - RFbuncher ======================================}

[B2_General]
                    Name = RFbuncher 2,1                         ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.176000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[B2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-20.0,20.00,20.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-20.0,20.00,20.0             ; joint,Bottom,B-limit,Top,T-limit

[B2_optics]
                    row1 = +1.00000e+00,+1.76000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+1.76000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[B2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[B2_BuncherSettings]
                      La = 0.05                 m                ; distance before electrodes
                      Lb = 0.05                 m                ; distance after electrodes
              PhaseShift = 215                  deg              ; Phase shift
                  EUmode = 1                                     ; 0-ElectrField, 1-Voltage
                  RFmode = 0                                     ; 0-beam, 1-manually
                RFmanual = 93.000               MHz              
                     Gap = 0.076                m                ; gap between electrodes
               ElecField = 3131.579             KV/m             
                 Voltage = 238.000              KV               
                ttf_mode = 0                                     ; 0-calc, 1-manually
              ttf_manual = 1.0000
             tuning_mode = 2                                     ; d3 , d3m, d5, d5m


{============================= BLOCK B3 - RFbuncher ======================================}

[B3_General]
                    Name = RFbuncher 3,1                         ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.112000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[B3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-20.0,20.00,20.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-20.0,20.00,20.0             ; joint,Bottom,B-limit,Top,T-limit

[B3_optics]
                    row1 = +1.00000e+00,+1.12000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+1.12000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[B3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[B3_BuncherSettings]
                      La = 0.05                 m                ; distance before electrodes
                      Lb = 0.025                m                ; distance after electrodes
              PhaseShift = 35                   deg              ; Phase shift
                  EUmode = 1                                     ; 0-ElectrField, 1-Voltage
                  RFmode = 0                                     ; 0-beam, 1-manually
                RFmanual = 93.000               MHz              
                     Gap = 0.037                m                ; gap between electrodes
               ElecField = 3216.216             KV/m             
                 Voltage = 119.000              KV               
                ttf_mode = 0                                     ; 0-calc, 1-manually
              ttf_manual = 1.0000
             tuning_mode = 2                                     ; d3 , d3m, d5, d5m


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = Drift 2,0                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.536000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.00000e+00,+5.36000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+5.36000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 1                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = MQ1,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.381000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.37690e+00,+4.27800e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +2.09428e+00,+1.37690e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+6.65200e-01,+3.37400e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-1.65211e+00,+6.65200e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 2                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.381                m                
           MagneticField = -3.029913            KG               
                  Radius = 10                   cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0.618865             Tm               


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = Drift 4,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.223000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +1.00000e+00,+2.23000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.23000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 1                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               


{============================= BLOCK S5 - Drift ======================================}

[S5_General]
                    Name = MQ2,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.406400             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S5_optics]
                    row1 = +8.52680e-01,+3.86200e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -7.06660e-01,+8.52680e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.15493e+00,+4.27200e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+7.81560e-01,+1.15493e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S5_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S5_DriftSettings]
                    Mode = 2                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.4064               m                
           MagneticField = 0.13362              KG               
                  Radius = 10                   cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0.618865             Tm               


{============================= BLOCK S6 - Drift ======================================}

[S6_General]
                    Name = Drift 5,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.470000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-100.0,20.00,100.0           ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S6_optics]
                    row1 = +1.00000e+00,+4.70000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+4.70000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S6_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S6_DriftSettings]
                    Mode = 1                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               


{============================= BLOCK D3 - Dipole ======================================}

[D3_General]
                    Name = Dipole,1                              ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.639000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-1.00,-200.0,1.00,200.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[D3_optics]
                    row1 = +8.66025e-01,+6.10000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.63449e+00
                    row2 = -4.09836e-01,+8.66025e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+5.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+6.38791e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = -5.00000e-01,-1.63449e-01,+0.00000e+00,+0.00000e+00,+1.00000e+00,-2.87905e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 17.453               mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 17.453               mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D3_DipoleSettings]
                    Brho = 0.61886              Tm               ; magnetic rigidity
                   Angle = 30                   degrees          
                  Radius = 1.22                 m                

[D3_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 0                                     ; Use 1/0
                 GapVert = 2                    cm               ; code 16.5
                      K1 = 0                                     ; code 16.7
                      K2 = 0                                     ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit


{============================= BLOCK S7 - Drift ======================================}

[S7_General]
                    Name = Drift 6,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.483000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S7_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-100.0,20.00,100.0           ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S7_optics]
                    row1 = +1.00000e+00,+4.83000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+4.83000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S7_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S7_DriftSettings]
                    Mode = 1                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               


{============================= BLOCK S8 - Drift ======================================}

[S8_General]
                    Name = MQ3,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.406400             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S8_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S8_optics]
                    row1 = +8.29950e-01,+3.83100e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -8.12300e-01,+8.29950e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.18027e+00,+4.30500e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+9.12910e-01,+1.18027e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S8_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S8_DriftSettings]
                    Mode = 2                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.4064               m                
           MagneticField = 1.312218             KG               
                  Radius = 10                   cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0.61886              Tm               


{============================= BLOCK S9 - Drift ======================================}

[S9_General]
                    Name = Drift 7,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.223000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S9_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S9_optics]
                    row1 = +1.00000e+00,+2.23000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.23000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S9_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S9_DriftSettings]
                    Mode = 1                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               


{============================= BLOCK S10 - Drift ======================================}

[S10_General]
                    Name = MQ4,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.381000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S10_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S10_optics]
                    row1 = +1.37690e+00,+4.27800e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +2.09428e+00,+1.37690e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+6.65200e-01,+3.37400e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-1.65211e+00,+6.65200e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S10_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S10_DriftSettings]
                    Mode = 2                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.381                m                
           MagneticField = -3.029885            KG               
                  Radius = 10                   cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0.61886              Tm               


{============================= BLOCK S11 - Drift ======================================}

[S11_General]
                    Name = Drift 8,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.743000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S11_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S11_optics]
                    row1 = +1.00000e+00,+7.43000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+7.43000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S11_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S11_DriftSettings]
                    Mode = 1                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               


{============================= BLOCK S12 - Drift ======================================}

[S12_General]
                    Name = slits1,1                              ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S12_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-300.0,150.00,300.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S12_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S12_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S12_DriftSettings]
                    Mode = 1                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = Material 2,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,10,2.321,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.2                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 436207616,-20.00,-50.0,20.00,50.0     ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 537283592,-20.00,-50.0,20.00,50.0     ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK L2 - Solenoid ======================================}

[L2_General]
                    Name = Solenoid 2,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 2.950000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[L2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[L2_optics]
                    row1 = +1.00000e+00,+2.95000e+00,+5.28558e-11,+1.55925e-10,+0.00000e+00,+0.00000e+00
                    row2 = -4.55922e-21,+1.00000e+00,+2.56363e-33,+5.28558e-11,+0.00000e+00,+0.00000e+00
                    row3 = -5.28558e-11,-1.55925e-10,+1.00000e+00,+2.95000e+00,+0.00000e+00,+0.00000e+00
                    row4 = -2.56363e-33,-5.28558e-11,-4.55922e-21,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[L2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[L2_SolenoidSettings]
      UseSoftCorrections = 1                                     ; 1 - Yes / 0 - No
               Direction = 1                                     ; +1 positive, -1 negative
                  Sstate = 0                                     ; 0-B_field_max, 1-Current
                 Current = 0                    A                
               BfieldMax = 0                    T                
              CoilLength = 0.6                  m                
               EffRadius = 0.05                 m                
              LengthDraw = 0.6                  m                
                    Bore = 0.05                 m                
               FirstHalf = 1.06                 m                
              SecondHalf = 1.89                 m                
              MAconstant = 0.03636              T/A              
         TuningParameter = 4
         UseGlobalMatrix = 1


{============================= BLOCK S13 - Drift ======================================}

[S13_General]
                    Name = slits2,1                              ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S13_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-200.00,-300.0,200.00,300.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S13_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S13_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S13_DriftSettings]
                    Mode = 1                                     ; Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = Material 3,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,10,2.33,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.1                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.2,0.3          ns,mm,mm         ; Time&X&Y space

[M3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M3_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= Calculations ======================================}

[Calculations]
25Al 13+ 13+ 13+ 13+ 13+ =2.6350e+00,2.6350e+00,7,2.6350e+00,5.2033e-01,0,1.2125e-02,3.3662e+00,1.0048e+00,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.2127e-02,6.9019e-01,1,1.5559e-01,1.1293e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6673e-01,9.6673e-01,1,1,1,1,1,1,1,1,1,1,1
