Version 9.6.110

{============================= Main Part ======================================}
[general]
                    File = G:\ElectricDipole\D-line_BTS01.lpp
                    Date = 30-07-2013
                    Time = 16:12:13
           Configuration = NSCL\A1900_2013.lcn
             Optionsfile = A1900_2013.lopt
                   Title = NSCL D-line BTS01
          BlockStructure = DSSSSSSSSSESSSSSSSSSSSSSSSS

[settings]
                   A,Z,Q = 100Ru1+                               ; Mass ElementName Charge+ Beam
                  Energy = 0.0006               MeV/u            
               Intensity = 1                    pnA              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 100Ru                                 ; Mass ElementName Charge+ Beam
           ReglageOnBeam = 1                                     ; 1-Yes, 0-No

[OpticsBeam]
                      BX = 0.6                  (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 40                   (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 0.6                  (±)mm            ; one-half the vertical beam extent (y)
                      BF = 40                   (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.01                 (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = 1                    degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 32                                    ; Number of points in distribution
        NP charge states = 32                                    ; Number of points in distribution
                NP wedge = 32                                    ; Number of points in distribution
           Charge states = Yes                                   ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,4,1,9.012                           ; Nomer,Z,Atoms,Mass
        Target thickness = 0,0,1.85,0,0                          ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 0                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 1                                     ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 3                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 1                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 1                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 1                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-11    
               FisCS_TKE = 1e-8     
                      N0 = 83                                    ; default 82
                     dU0 = -2.65                                 ; default -2.5
                      C0 = 0.7                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -3.8                                  ; default -5.5
                      C1 = 0.15                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-5     
                 BeamInd = 1e-20    
               BeamTotal = 1e-20    

[convolution]
        Convolution mode = 1                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 3     
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 1                                     ; 0 - no, 1 - use
         DissipationBeta = 1                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 0                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 0                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
               EE_C_mode = 0
             EE_C_Zbound = 0
             EE_C_Abound = 0
          EnergyCoef_CA0 = 0       
          EnergyCoef_CA1 = 3       
          EnergyCoef_CA2 = 0       
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CA0 = 0       
           SigmaCoef_CA1 = 2       
           SigmaCoef_CA2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       

[evapauto]
                  tun_a0 = -0.61392
                  tun_a1 = 0.44559
                  tun_a2 = 0.12008
                 A_Bound = 300                                   ; mass
               A_Pairing =   1                                   ; mass

[plot]
            Start target = RF                                    ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = M7
         dE-detector-1st = M7
         dE-detector-2nd = M13
            TKE-detector = M7
                PlotBrho = D1
               PlotWedge = S4
              X-detector = M4
              Y-detector = M4
                 Tilting = M1
                 Stopper = M2
          ConditionBlock = A0
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 2
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
           LowEx_nucleus = 39Ar18+                               ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 34S 16+                               ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 28Si14+                               ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 8.000e+02 250.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 44
                   Dr_n0 = 0
                   Dr_n1 = 56

[cross sections]

[previous]
                 Lowerst = 28Ar18+                               ; Mass ElementName Charge+ Beam
                 Highest = 39Ar18+                               ; Mass ElementName Charge+ Beam


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = tuning,1                              ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000100             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 43                                    ;  Z - Q  = charge state settings
        Calibration file = NULL

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 0.35232              Tm               ; magnetic rigidity
                   Angle = -1                   degrees          
                  Radius = 0.001                m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = DL_EFFEXT,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.140000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+1.40000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+1.40000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = DriftStart,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.228600             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.00000e+00,+2.28600e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.28600e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = doublet drift1,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.039224             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = B01_D957,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.100000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +1.55429e+00,+1.17900e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +1.20100e+01,+1.55429e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+5.32300e-01,+8.39000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-8.54578e+00,+5.32300e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 4                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.1                  m                
           MagneticField = 5                    KG               
                  Radius = 3                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 1.2004486e+5         J/c              ; for e-quad
                 Voltage = -5.504907            kV               ; for e-quad


{============================= BLOCK S5 - Drift ======================================}

[S5_General]
                    Name = doublet drift2,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.020000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S5_optics]
                    row1 = +1.00000e+00,+2.00000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.00000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S5_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S5_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S6 - Drift ======================================}

[S6_General]
                    Name = B01_D958,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.100000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S6_optics]
                    row1 = +6.51550e-01,+8.81000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -6.53291e+00,+6.51550e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.39430e+00,+1.12800e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+8.36744e+00,+1.39430e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S6_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S6_DriftSettings]
                    Mode = 4                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.1                  m                
           MagneticField = 0                    KG               
                  Radius = 3                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 1.2004486e+5         J/c              ; for e-quad
                 Voltage = 4.006234             kV               ; for e-quad


{============================= BLOCK S7 - Drift ======================================}

[S7_General]
                    Name = doublet drift3,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.039224             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S7_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S7_optics]
                    row1 = +1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S7_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S7_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S8 - Drift ======================================}

[S8_General]
                    Name = ---Drift----,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.238381             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S8_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S8_optics]
                    row1 = +1.00000e+00,+2.38381e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.38381e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S8_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S8_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S9 - Drift ======================================}

[S9_General]
                    Name = bender drift1,1                       ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.045550             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S9_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S9_optics]
                    row1 = +1.00000e+00,+4.55500e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+4.55500e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S9_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S9_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK E1 - ElecDip ======================================}

[E1_General]
                    Name = Bender0963,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.157100             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 43                                    ;  Z - Q  = charge state settings
        Calibration file = NULL

[E1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[E1_optics]
                    row1 = +7.07107e-01,+1.41421e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.17157e+00
                    row2 = -3.53553e+00,+7.07107e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.41421e+01
                    row3 = +0.00000e+00,+0.00000e+00,+7.07107e-01,+1.41421e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-3.53553e+00,+7.07107e-01,+0.00000e+00,+0.00000e+00
                    row5 = +1.41421e+00,+1.17157e-01,+0.00000e+00,+0.00000e+00,+1.00000e+00,-6.26330e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[E1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[E1_ElectricDipoleSettings]
                     E_F = 600.24               KV/m             ; electric field
                     gap = 0.032                m                ; distance between plates
                   Angle = -45                  degrees          
                  Radius = 0.2                  m                
               Direction = 0                                     ; X=0 or Y=1
                BendType = 1                                     ; 0-cyl,1-sph,2-tor
                  TorRad = 10                   m                
           CalcualteAuto = 1                                     ; 0 - nothing, 1 - recalculate
          CorrespondErho = 1.20048e+5           J/c              


{============================= BLOCK S10 - Drift ======================================}

[S10_General]
                    Name = bender drift2,1                       ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.078100             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S10_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S10_optics]
                    row1 = +1.00000e+00,+7.81000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+7.81000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S10_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S10_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S11 - Drift ======================================}

[S11_General]
                    Name = ---Drift-----,1                       ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.270060             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S11_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S11_optics]
                    row1 = +1.00000e+00,+2.70060e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.70060e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S11_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S11_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S12 - Drift ======================================}

[S12_General]
                    Name = doublet drift1,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.039224             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S12_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S12_optics]
                    row1 = +1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S12_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S12_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S13 - Drift ======================================}

[S13_General]
                    Name = B01_D968,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.100000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S13_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S13_optics]
                    row1 = +6.54130e-01,+8.82000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -6.48799e+00,+6.54130e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.39100e+00,+1.12700e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+8.29363e+00,+1.39100e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S13_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S13_DriftSettings]
                    Mode = 4                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.1                  m                
           MagneticField = 5                    KG               
                  Radius = 3                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 1.20048e+5           J/c              ; for e-quad
                 Voltage = 3.974699             kV               ; for e-quad


{============================= BLOCK S14 - Drift ======================================}

[S14_General]
                    Name = doublet drift2,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.020000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S14_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S14_optics]
                    row1 = +1.00000e+00,+2.00000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.00000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S14_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S14_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S15 - Drift ======================================}

[S15_General]
                    Name = B01_D969,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.100000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S15_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S15_optics]
                    row1 = +1.27850e+00,+1.09100e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +5.81529e+00,+1.27850e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+7.45170e-01,+9.14000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-4.86830e+00,+7.45170e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S15_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S15_DriftSettings]
                    Mode = 4                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.1                  m                
           MagneticField = 0                    KG               
                  Radius = 3                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 1.20048e+5           J/c              ; for e-quad
                 Voltage = -2.87891             kV               ; for e-quad


{============================= BLOCK S16 - Drift ======================================}

[S16_General]
                    Name = doublet drift3,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.039224             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S16_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S16_optics]
                    row1 = +1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S16_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S16_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S17 - Drift ======================================}

[S17_General]
                    Name = ----Drift----,1                       ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.743240             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S17_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S17_optics]
                    row1 = +1.00000e+00,+7.43240e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+7.43240e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S17_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S17_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S18 - Drift ======================================}

[S18_General]
                    Name = diagnostics,1                         ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S18_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S18_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S18_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S18_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S19 - Drift ======================================}

[S19_General]
                    Name = ---Drift------,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.258780             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S19_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S19_optics]
                    row1 = +1.00000e+00,+2.58780e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.58780e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S19_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S19_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S20 - Drift ======================================}

[S20_General]
                    Name = doublet drift1,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.039224             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S20_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S20_optics]
                    row1 = +1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S20_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S20_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S21 - Drift ======================================}

[S21_General]
                    Name = B01_D981,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.100000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S21_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-1.00,-50.0,1.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S21_optics]
                    row1 = +1.48023e+00,+1.15500e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +1.03100e+01,+1.48023e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+5.86120e-01,+8.58000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-7.65279e+00,+5.86120e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S21_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S21_DriftSettings]
                    Mode = 4                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.1                  m                
           MagneticField = 5                    KG               
                  Radius = 3                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 1.20048e+5           J/c              ; for e-quad
                 Voltage = -4.819467            kV               ; for e-quad


{============================= BLOCK S22 - Drift ======================================}

[S22_General]
                    Name = doublet drift2,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.020000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S22_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S22_optics]
                    row1 = +1.00000e+00,+2.00000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.00000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S22_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S22_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S23 - Drift ======================================}

[S23_General]
                    Name = B01_D982,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.100000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S23_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S23_optics]
                    row1 = +6.20130e-01,+8.70000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -7.07535e+00,+6.20130e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.43503e+00,+1.14100e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+9.28253e+00,+1.43503e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S23_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S23_DriftSettings]
                    Mode = 4                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0.1                  m                
           MagneticField = 0                    KG               
                  Radius = 3                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 1.20048e+5           J/c              ; for e-quad
                 Voltage = 4.394161             kV               ; for e-quad


{============================= BLOCK S24 - Drift ======================================}

[S24_General]
                    Name = doublet drift3,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.039224             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S24_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S24_optics]
                    row1 = +1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+3.92240e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S24_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S24_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad


{============================= BLOCK S25 - Drift ======================================}

[S25_General]
                    Name = LastBTS01drift,1                      ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.325540             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S25_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S25_optics]
                    row1 = +1.00000e+00,+3.25540e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+3.25540e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S25_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S25_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad

