Version 9.9.1

{============================= Main Part ======================================}
[general]
                    File = C:\user\c\lise_pp_99\LISEpp_ActualInstaller\install\files\examples\CoulombFissionExample.lpp
                    Date = 29-12-2014
                    Time = 15:08:53
           Configuration = GSI\FRS - new standard.lcn
             Optionsfile = A1900_2005A.lopt
                   Title = GSI FRS - 4dipoles - standard new mode
          BlockStructure = DSWMDMMMWSDMSDMMMMMSMMW

[settings]
                   A,Z,Q = 238U 92+                              ; Mass ElementName Charge+ Beam
                  Energy = 1000                 MeV/u            
               Intensity = 1                    pnA              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 130Te                                 ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 1                    (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 5                    (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 1.5                  (±)mm            ; one-half the vertical beam extent (y)
                      BF = 3.33                 (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.05                 (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = 0                    degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 32                                    ; Number of points in distribution
        NP charge states = 32                                    ; Number of points in distribution
                NP wedge = 32                                    ; Number of points in distribution
           Charge states = No                                    ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,82,1,207.19                         ; Nomer,Z,Atoms,Mass
        Target thickness = 6,1,11.34,0,0                         ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 4,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 3                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 8                                     ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 2                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 0                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 0                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-9     
               FisCS_TKE = 1e-6     
                      N0 = 82                                    ; default 82
                     dU0 = -2.5                                  ; default -2.5
                      C0 = 1.4                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -5.5                                  ; default -5.5
                      C1 = 0.16                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-4     
                 BeamInd = 1e-6     
               BeamTotal = 1e-8     

[convolution]
        Convolution mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 5.758 
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
          AvoidUnboundCS = 1                                     ; 1-Yes, 0-No
       ProtectedChannels = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 1                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 0                                     ; 0 - no, 1 - use
         DissipationBeta = 2                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 0                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 0                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       

[evapauto]
                  tun_a0 = -0.71783
                  tun_a1 = 0.41085
                  tun_a2 = 0.12612
                 A_Bound = 300                                   ; mass
               A_Pairing =  70                                   ; mass

[plot]
            Start target = Detector                              ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = M8
         dE-detector-1st = M8
         dE-detector-2nd = M9
            TKE-detector = M8
                PlotBrho = D1
               PlotWedge = S4
              X-detector = M4
              Y-detector = M6
                 Tilting = M1
                 Stopper = M2
                RO_Wedge = 
          ConditionBlock = A10
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 1
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
                Velocity = 1                                     ; Calculat fissile nuclei speed
           LowEx_nucleus = 39Ar                                  ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 34S                                   ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 28Si                                  ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 1.800e+03 100.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 92
                   Dr_n0 = 0
                   Dr_n1 = 146

[cross sections]

[previous]
                 Lowerst = 126Sn                                 ; Mass ElementName Charge+ Beam
                 Highest = 136Xe                                 ; Mass ElementName Charge+ Beam

[MC_options]
                   dXsel = 0
                   dYsel = 2
                  dAZQ_X = 1
                  dAZQ_Y = 5
                  dVEL_X = 1
                  dVEL_Y = 0
               dIso_mode = 0
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 0
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 2
                  CS_use = 1
           envelope_show = 0
                use_bore = 0
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
              AZQ_Xsigma = 0.1   
              AZQ_Ysigma = 0.1   
                 G1_gate = 0 0 -100.0000 100.0000
                 G2_gate = 0 0 -100.0000 100.0000
                 G3_gate = 0 0 -100.0000 100.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 0 0,R1,R1,R1                          ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 0 0,R1,R1,R1
            G3_component = 0 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = D1,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 18.169000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D1.cal

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = -5.08200e-01,-7.00000e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.15000e+01
                    row2 = -1.46000e-01,-1.96980e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.67500e+00
                    row3 = +0.00000e+00,+0.00000e+00,-5.40800e+00,-1.52000e-01,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,-3.18200e-01,-1.93900e-01,+0.00000e+00,+0.00000e+00
                    row5 = +2.28800e-01,+4.23400e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-4.99000e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 12                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 15                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 14.15087             Tm               ; magnetic rigidity
                   Angle = 30                   degrees          
                  Radius = 11.25                m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = S1_slits,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = S1-degrader,1                         ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 5,0,2.702,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W1_WedgeSettings]
             ProfileMode = 1                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 2                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = 0.00000              mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = D2
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = MW11,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,275,7.866,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = D2,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 18.110000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D2.cal

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = -1.43920e+00,+9.42940e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.38170e+01
                    row2 = -2.45440e-02,-6.94700e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.69130e+00
                    row3 = +0.00000e+00,+0.00000e+00,-2.79420e-01,+8.70930e-01,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,+1.33210e-01,-3.99300e+00,+0.00000e+00,-1.33210e-06
                    row5 = -3.26120e-01,-2.34770e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+1.03370e+01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 22                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 3.5                  mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 14.05921             Tm               ; magnetic rigidity
                   Angle = -30                  degrees          
                  Radius = 11.25                m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = MW21,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,22,1,47.9                           ; Nomer,Z,Atoms,Mass
               thickness = 1,129,4.519,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.2,0.2          ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = Scint21,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,1,11,1.008                          ; Nomer,Z,Atoms,Mass
               contents2 = 1,6,10,12.011                         ; Nomer,Z,Atoms,Mass
               thickness = 0,500,1.02,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,5                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,2                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,1,1              ns,mm,mm         ; Time&X&Y space

[M3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[M3_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M4 - Material ======================================}

[M4_General]
                    Name = MW22,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M4_Compound]
               contents1 = 0,22,1,47.9                           ; Nomer,Z,Atoms,Mass
               thickness = 1,129,4.519,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M4_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M4_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M4_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK W2 - Wedge ======================================}

[W2_General]
                    Name = S2_wedge,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W2_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 4,2,2.702,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,1.85                                ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W2_WedgeSettings]
             ProfileMode = 0                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 0                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = -0.90216             mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = D4
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = S2_slits,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK D3 - Dipole ======================================}

[D3_General]
                    Name = D3,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 18.340000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D3.cal

[D3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D3_optics]
                    row1 = -6.88070e-01,-9.66310e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.34210e+01
                    row2 = -2.38150e-02,-1.45670e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.24190e+00
                    row3 = +0.00000e+00,+0.00000e+00,-4.04360e+00,-2.74680e-01,+0.00000e+00,+4.04360e-05
                    row4 = +0.00000e+00,+0.00000e+00,+1.36120e-01,-2.38060e-01,+0.00000e+00,-1.36120e-06
                    row5 = +1.67430e-01,-3.38040e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+1.02280e+01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D3_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 16                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 14                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D3_DipoleSettings]
                    Brho = 13.74715             Tm               ; magnetic rigidity
                   Angle = -30                  degrees          
                  Radius = 11.25                m                

[D3_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M5 - Material ======================================}

[M5_General]
                    Name = MW31,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M5_Compound]
               contents1 = 0,22,1,47.9                           ; Nomer,Z,Atoms,Mass
               thickness = 1,129,4.519,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M5_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M5_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M5_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = S3_slits,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK D4 - Dipole ======================================}

[D4_General]
                    Name = D4,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 19.240000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D4.cal

[D4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D4_optics]
                    row1 = -1.75400e+00,+1.16390e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+3.72550e+01
                    row2 = +1.97440e-02,-5.71380e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.38850e+00
                    row3 = +0.00000e+00,+0.00000e+00,-2.74520e-01,+3.16960e-01,+0.00000e+00,+1.15320e-05
                    row4 = +0.00000e+00,+0.00000e+00,-1.82360e-01,-3.43230e+00,+0.00000e+00,+2.70160e-06
                    row5 = +1.69950e-01,+2.11270e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-5.28860e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D4_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 26                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 3                    mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D4_DipoleSettings]
                    Brho = 13.70289             Tm               ; magnetic rigidity
                   Angle = 30                   degrees          
                  Radius = 11.25                m                

[D4_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M6 - Material ======================================}

[M6_General]
                    Name = MW41,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M6_Compound]
               contents1 = 0,22,1,47.9                           ; Nomer,Z,Atoms,Mass
               thickness = 1,129,4.519,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.2                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.2,0.2          ns,mm,mm         ; Time&X&Y space

[M6_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M6_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M6_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M7 - Material ======================================}

[M7_General]
                    Name = Exit_window,1                         ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M7_Compound]
               contents1 = 0,22,1,47.9                           ; Nomer,Z,Atoms,Mass
               thickness = 1,90,4.519,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,1                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 1,1,1                ns,mm,mm         ; Time&X&Y space

[M7_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-40.00,-40.0,40.00,40.0             ; joint,Bottom,B-limit,Top,T-limit

[M7_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M7_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M8 - Material ======================================}

[M8_General]
                    Name = Music-P10,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M8_Compound]
               contents1 = 0,18,90,39.948                        ; Nomer,Z,Atoms,Mass
               contents2 = 1,6,2,12.011                          ; Nomer,Z,Atoms,Mass
               contents3 = 2,1,8,1.008                           ; Nomer,Z,Atoms,Mass
               thickness = 1,100,0.0171,0,1                      ; State,Thickness,density,angle,SolidGas
                  Defect = 0,1                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,1,1              ns,mm,mm         ; Time&X&Y space

[M8_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[M8_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M8_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M9 - Material ======================================}

[M9_General]
                    Name = Music_Kapton,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M9_Compound]
               contents1 = 0,1,8,1.008                           ; Nomer,Z,Atoms,Mass
               contents2 = 1,6,8,12.011                          ; Nomer,Z,Atoms,Mass
               thickness = 1,14,1.11,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,100                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,5                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.3,1,1              ns,mm,mm         ; Time&X&Y space

[M9_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-75.00,-75.0,75.00,75.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M9_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M9_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M10 - Material ======================================}

[M10_General]
                    Name = MW42,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M10_Compound]
               contents1 = 0,6,22,12.011                         ; Nomer,Z,Atoms,Mass
               contents2 = 1,1,10,1.008                          ; Nomer,Z,Atoms,Mass
               contents3 = 2,7,2,14.007                          ; Nomer,Z,Atoms,Mass
               contents4 = 3,8,4,15.999                          ; Nomer,Z,Atoms,Mass
               thickness = 1,58,1.42,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.408                               ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M10_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M10_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M10_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = S4_slits,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M11 - Material ======================================}

[M11_General]
                    Name = air,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M11_Compound]
               contents1 = 0,8,23,15.999                         ; Nomer,Z,Atoms,Mass
               contents2 = 1,7,76,14.007                         ; Nomer,Z,Atoms,Mass
               contents3 = 2,18,1,39.948                         ; Nomer,Z,Atoms,Mass
               thickness = 1,100,0.0012,0,1                      ; State,Thickness,density,angle,SolidGas
                  Defect = 1,833.333                             ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M11_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M11_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M11_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M12 - Material ======================================}

[M12_General]
                    Name = Scint41,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M12_Compound]
               contents1 = 0,1,6,1.008                           ; Nomer,Z,Atoms,Mass
               contents2 = 1,6,4,12.011                          ; Nomer,Z,Atoms,Mass
               contents3 = 2,8,2,15.999                          ; Nomer,Z,Atoms,Mass
               thickness = 0,500,1.17,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.22                                ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.11,0.31,0.32       ns,mm,mm         ; Time&X&Y space

[M12_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M12_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M12_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK W3 - Wedge ======================================}

[W3_General]
                    Name = S4_degrader,1                         ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W3_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 1,50000,2.702,0,0                     ; State,Thickness,density,angle,SolidGas
                  Defect = 1,74.019                              ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[W3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W3_WedgeSettings]
             ProfileMode = 1                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 2                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = 0.00000              mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = NULL
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= Calculations ======================================}

[Calculations]
136Xe 54+ 54+ 54+ 54+ =1.5247e+04,1.5247e+04,3,1.5247e+04,5.1291e+00,0,1.4430e-01,9.5795e+02,3.1967e+01,9.7495e-01,1,1,1,1,9.7495e-01,1,1,1,1,1,1,1,1,1,1,1,4.6112e-01,1,1,6.3065e-01,7.3117e-01,6.5909e-01,6.5909e-01,1,1,1,1,1,1,1,1,1,1,1,9.8568e-01,1,1,1,1,9.8568e-01,1,1,5.8878e-01,6.8100e-01,1,8.8099e-01,9.8137e-01,9.9254e-01,1,1,1,1,9.9254e-01,1,1,9.8939e-01,1,1,1,1,9.8939e-01,1,1,9.9254e-01,1,1,1,1,9.9254e-01,1,1,9.5646e-01,1,1,1,1,9.5646e-01,1,1,9.7576e-01,9.7576e-01,1,1,1,9.8757e-01,1,1,9.8757e-01,1,9.9254e-01,1,1,1,1,9.9254e-01,1,1,1,1,1,1,1,9.7112e-01,1,1,1,9.7120e-01,9.9254e-01,1,1,1,1,9.9254e-01,1,1,9.9479e-01,1,1,1,1,9.9479e-01,1,1,9.9321e-01,1,1,1,1,9.9321e-01,1,1,9.9716e-01,1,1,1,1,9.9716e-01,1,1,9.9102e-01,1,1,1,1,9.9102e-01,1,1,1,1,1,1,1,9.8809e-01,1,1,1,1,9.8809e-01,1,1,9.8905e-01,1,1,1,1,9.8905e-01,1,1,0,1,1,1,1,1,1,0
135Xe 54+ 54+ 54+ 54+ =1.5003e+03,1.5003e+03,3,1.5003e+03,5.2891e-01,0,1.3770e-01,9.5787e+02,3.2310e+01,9.7497e-01,1,1,1,1,9.7497e-01,1,1,1,1,1,1,1,1,1,1,1,4.4005e-01,1,1,6.2124e-01,7.0833e-01,5.7463e-01,5.7463e-01,1,1,1,1,1,1,1,1,1,1,1,9.8572e-01,1,1,1,1,9.8572e-01,1,1,6.6424e-01,7.6248e-01,1,8.8816e-01,9.8086e-01,9.9256e-01,1,1,1,1,9.9256e-01,1,1,9.8943e-01,1,1,1,1,9.8943e-01,1,1,9.9256e-01,1,1,1,1,9.9256e-01,1,1,9.5659e-01,1,1,1,1,9.5659e-01,1,1,9.7991e-01,9.7991e-01,1,1,1,9.9177e-01,1,1,9.9177e-01,1,9.9256e-01,1,1,1,1,9.9256e-01,1,1,1,1,1,1,1,9.7857e-01,1,1,1,9.7870e-01,9.9256e-01,1,1,1,1,9.9256e-01,1,1,9.9480e-01,1,1,1,1,9.9480e-01,1,1,9.9323e-01,1,1,1,1,9.9323e-01,1,1,9.9717e-01,1,1,1,1,9.9717e-01,1,1,9.9106e-01,1,1,1,1,9.9106e-01,1,1,1,1,1,1,1,9.8813e-01,1,1,1,1,9.8813e-01,1,1,9.8909e-01,1,1,1,1,9.8909e-01,1,1,0,1,1,1,1,1,1,0
134Xe 54+ 54+ 54+ 54+ =4.8050e+02,4.8050e+02,3,4.8050e+02,2.2481e-01,0,1.0375e-01,9.5777e+02,3.2657e+01,9.7499e-01,1,1,1,1,9.7499e-01,1,1,1,1,1,1,1,1,1,1,1,4.2474e-01,1,1,6.1445e-01,6.9125e-01,5.4136e-01,5.4136e-01,1,1,1,1,1,1,1,1,1,1,1,9.8576e-01,1,1,1,1,9.8576e-01,1,1,5.6247e-01,6.5036e-01,1,8.8156e-01,9.8106e-01,9.9258e-01,1,1,1,1,9.9258e-01,1,1,9.8947e-01,1,1,1,1,9.8947e-01,1,1,9.9258e-01,1,1,1,1,9.9258e-01,1,1,9.5673e-01,1,1,1,1,9.5673e-01,1,1,9.4804e-01,9.4804e-01,1,1,1,9.9140e-01,1,1,9.9140e-01,1,9.9258e-01,1,1,1,1,9.9258e-01,1,1,1,1,1,1,1,9.8969e-01,1,1,1,9.9008e-01,9.9258e-01,1,1,1,1,9.9258e-01,1,1,9.9482e-01,1,1,1,1,9.9482e-01,1,1,9.9325e-01,1,1,1,1,9.9325e-01,1,1,9.9718e-01,1,1,1,1,9.9718e-01,1,1,9.9109e-01,1,1,1,1,9.9109e-01,1,1,1,1,1,1,1,9.8817e-01,1,1,1,1,9.8817e-01,1,1,9.8913e-01,1,1,1,1,9.8913e-01,1,1,0,1,1,1,1,1,1,0
133Xe 54+ 54+ 54+ 54+ =1.2945e+01,1.2945e+01,3,1.2945e+01,1.3701e-02,0,4.5865e-02,9.5764e+02,3.2474e+01,9.7501e-01,1,1,1,1,9.7501e-01,1,1,1,1,1,1,1,1,1,1,1,4.3346e-01,1,1,6.1834e-01,7.0102e-01,5.2536e-01,5.2536e-01,1,1,1,1,1,1,1,1,1,1,1,9.8580e-01,1,1,1,1,9.8580e-01,1,1,2.7535e-01,3.1580e-01,1,8.8846e-01,9.8137e-01,9.9260e-01,1,1,1,1,9.9260e-01,1,1,9.8951e-01,1,1,1,1,9.8951e-01,1,1,9.9260e-01,1,1,1,1,9.9260e-01,1,1,9.5686e-01,1,1,1,1,9.5686e-01,1,1,8.6519e-01,8.6519e-01,1,1,1,9.8337e-01,1,1,9.8337e-01,1,9.9260e-01,1,1,1,1,9.9260e-01,1,1,1,1,1,1,1,9.9648e-01,1,1,1,9.9669e-01,9.9260e-01,1,1,1,1,9.9260e-01,1,1,9.9483e-01,1,1,1,1,9.9483e-01,1,1,9.9327e-01,1,1,1,1,9.9327e-01,1,1,9.9719e-01,1,1,1,1,9.9719e-01,1,1,9.9112e-01,1,1,1,1,9.9112e-01,1,1,1,1,1,1,1,9.8821e-01,1,1,1,1,9.8821e-01,1,1,9.8917e-01,1,1,1,1,9.8917e-01,1,1,0,1,1,1,1,1,1,0
132Xe 54+ 54+ 54+ 54+ =2.8776e-02,2.8776e-02,3,2.8776e-02,2.2910e-04,0,6.0972e-03,9.5753e+02,3.2587e+01,9.7503e-01,1,1,1,1,9.7503e-01,1,1,1,1,1,1,1,1,1,1,1,4.2869e-01,1,1,6.1658e-01,6.9526e-01,5.0646e-01,5.0646e-01,1,1,1,1,1,1,1,1,1,1,1,9.8584e-01,1,1,1,1,9.8584e-01,1,1,4.7710e-02,5.6448e-02,1,8.6125e-01,9.8137e-01,9.9262e-01,1,1,1,1,9.9262e-01,1,1,9.8955e-01,1,1,1,1,9.8955e-01,1,1,9.9262e-01,1,1,1,1,9.9262e-01,1,1,9.5699e-01,1,1,1,1,9.5699e-01,1,1,6.9786e-01,6.9786e-01,1,1,1,9.8062e-01,1,1,9.8062e-01,1,9.9262e-01,1,1,1,1,9.9262e-01,1,1,1,1,1,1,1,9.9658e-01,1,1,9.9862e-01,9.9795e-01,9.9262e-01,1,1,1,1,9.9262e-01,1,1,9.9485e-01,1,1,1,1,9.9485e-01,1,1,9.9329e-01,1,1,1,1,9.9329e-01,1,1,9.9720e-01,1,1,1,1,9.9720e-01,1,1,9.9115e-01,1,1,1,1,9.9115e-01,1,1,1,1,1,1,1,9.8825e-01,1,1,1,1,9.8825e-01,1,1,9.8921e-01,1,1,1,1,9.8921e-01,1,1,0,1,1,1,1,1,1,0
131Xe 54+ 54+ 54+ 54+ =8.1676e-07,8.1676e-07,3,8.1676e-07,1.6974e-05,0,2.3358e-06,9.5738e+02,3.2264e+01,9.7505e-01,1,1,1,1,9.7505e-01,1,1,1,1,1,1,1,1,1,1,1,4.4245e-01,1,1,6.2261e-01,7.1063e-01,4.6172e-01,4.6172e-01,1,1,1,1,1,1,1,1,1,1,1,9.8588e-01,1,1,1,1,9.8588e-01,1,1,5.8976e-05,7.1925e-05,1,8.3547e-01,9.8144e-01,9.9264e-01,1,1,1,1,9.9264e-01,1,1,9.8959e-01,1,1,1,1,9.8959e-01,1,1,9.9264e-01,1,1,1,1,9.9264e-01,1,1,9.5713e-01,1,1,1,1,9.5713e-01,1,1,2.3106e-01,2.3106e-01,1,1,1,9.7946e-01,1,1,9.7946e-01,1,9.9264e-01,1,1,1,1,9.9264e-01,1,1,1,1,1,1,1,9.9214e-01,1,1,9.9414e-01,9.9799e-01,9.9264e-01,1,1,1,1,9.9264e-01,1,1,9.9486e-01,1,1,1,1,9.9486e-01,1,1,9.9331e-01,1,1,1,1,9.9331e-01,1,1,9.9722e-01,1,1,1,1,9.9722e-01,1,1,9.9119e-01,1,1,1,1,9.9119e-01,1,1,1,1,1,1,1,9.8829e-01,1,1,1,1,9.8829e-01,1,1,9.8926e-01,1,1,1,1,9.8926e-01,1,1,0,1,1,1,1,1,1,0
135I  53+ 53+ 53+ 53+ =1.8838e+04,1.8838e+04,3,1.8838e+04,1.1268e+01,0,8.1150e-02,9.5847e+02,3.2353e+01,9.7497e-01,1,1,1,1,9.7497e-01,1,1,1,1,1,1,1,1,1,1,1,4.4791e-01,1,1,6.2470e-01,7.1699e-01,8.5381e-01,8.5381e-01,1,1,1,1,1,1,1,1,1,1,1,9.8573e-01,1,1,1,1,9.8573e-01,1,1,2.9088e-01,3.3969e-01,1,8.7222e-01,9.8174e-01,9.9256e-01,1,1,1,1,9.9256e-01,1,1,9.8943e-01,1,1,1,1,9.8943e-01,1,1,9.9256e-01,1,1,1,1,9.9256e-01,1,1,9.5660e-01,1,1,1,1,9.5660e-01,1,1,9.1880e-01,9.1880e-01,1,1,1,9.8627e-01,1,1,9.8627e-01,1,9.9256e-01,1,1,1,1,9.9256e-01,1,1,1,1,1,1,1,9.3381e-01,1,1,9.9197e-01,9.4137e-01,9.9256e-01,1,1,1,1,9.9256e-01,1,1,9.9481e-01,1,1,1,1,9.9481e-01,1,1,9.9323e-01,1,1,1,1,9.9323e-01,1,1,9.9717e-01,1,1,1,1,9.9717e-01,1,1,9.9106e-01,1,1,1,1,9.9106e-01,1,1,1,1,1,1,1,9.8813e-01,1,1,1,1,9.8813e-01,1,1,9.8909e-01,1,1,1,1,9.8909e-01,1,1,0,1,1,1,1,1,1,0
134I  53+ 53+ 53+ 53+ =7.0033e+03,7.0033e+03,3,7.0033e+03,3.0273e+00,0,1.1230e-01,9.5839e+02,3.2996e+01,9.7499e-01,1,1,1,1,9.7499e-01,1,1,1,1,1,1,1,1,1,1,1,4.1865e-01,1,1,6.1163e-01,6.8449e-01,6.8753e-01,6.8753e-01,1,1,1,1,1,1,1,1,1,1,1,9.8577e-01,1,1,1,1,9.8577e-01,1,1,5.0297e-01,5.8226e-01,1,8.8050e-01,9.8106e-01,9.9258e-01,1,1,1,1,9.9258e-01,1,1,9.8947e-01,1,1,1,1,9.8947e-01,1,1,9.9258e-01,1,1,1,1,9.9258e-01,1,1,9.5674e-01,1,1,1,1,9.5674e-01,1,1,9.5436e-01,9.5436e-01,1,1,1,9.8618e-01,1,1,9.8862e-01,9.9753e-01,9.9258e-01,1,1,1,1,9.9258e-01,1,1,1,1,1,1,1,9.5562e-01,1,1,9.9490e-01,9.6052e-01,9.9258e-01,1,1,1,1,9.9258e-01,1,1,9.9482e-01,1,1,1,1,9.9482e-01,1,1,9.9325e-01,1,1,1,1,9.9325e-01,1,1,9.9718e-01,1,1,1,1,9.9718e-01,1,1,9.9109e-01,1,1,1,1,9.9109e-01,1,1,1,1,1,1,1,9.8817e-01,1,1,1,1,9.8817e-01,1,1,9.8913e-01,1,1,1,1,9.8913e-01,1,1,0,1,1,1,1,1,1,0
133I  53+ 53+ 53+ 53+ =5.9037e+03,5.9037e+03,3,5.9037e+03,2.1765e+00,0,1.3167e-01,9.5830e+02,3.3408e+01,9.7501e-01,1,1,1,1,9.7501e-01,1,1,1,1,1,1,1,1,1,1,1,4.0046e-01,1,1,6.0298e-01,6.6413e-01,5.8649e-01,5.8649e-01,1,1,1,1,1,1,1,1,1,1,1,9.8581e-01,1,1,1,1,9.8581e-01,1,1,6.8801e-01,8.0045e-01,1,8.7652e-01,9.8061e-01,9.9260e-01,1,1,1,1,9.9260e-01,1,1,9.8951e-01,1,1,1,1,9.8951e-01,1,1,9.9260e-01,1,1,1,1,9.9260e-01,1,1,9.5687e-01,1,1,1,1,9.5687e-01,1,1,9.8187e-01,9.8187e-01,1,1,1,9.9269e-01,1,1,9.9269e-01,1,9.9260e-01,1,1,1,1,9.9260e-01,1,1,1,1,1,1,1,9.6894e-01,1,1,1,9.6898e-01,9.9260e-01,1,1,1,1,9.9260e-01,1,1,9.9483e-01,1,1,1,1,9.9483e-01,1,1,9.9327e-01,1,1,1,1,9.9327e-01,1,1,9.9719e-01,1,1,1,1,9.9719e-01,1,1,9.9112e-01,1,1,1,1,9.9112e-01,1,1,1,1,1,1,1,9.8821e-01,1,1,1,1,9.8821e-01,1,1,9.8917e-01,1,1,1,1,9.8917e-01,1,1,0,1,1,1,1,1,1,0
132I  53+ 53+ 53+ 53+ =5.7016e+02,5.7016e+02,3,5.7016e+02,2.2744e-01,0,1.2169e-01,9.5818e+02,3.3131e+01,9.7503e-01,1,1,1,1,9.7503e-01,1,1,1,1,1,1,1,1,1,1,1,4.0550e-01,1,1,6.0548e-01,6.6971e-01,5.4930e-01,5.4930e-01,1,1,1,1,1,1,1,1,1,1,1,9.8585e-01,1,1,1,1,9.8585e-01,1,1,6.6884e-01,7.8054e-01,1,8.7369e-01,9.8079e-01,9.9262e-01,1,1,1,1,9.9262e-01,1,1,9.8955e-01,1,1,1,1,9.8955e-01,1,1,9.9262e-01,1,1,1,1,9.9262e-01,1,1,9.5700e-01,1,1,1,1,9.5700e-01,1,1,9.7315e-01,9.7315e-01,1,1,1,9.9309e-01,1,1,9.9309e-01,1,9.9263e-01,1,1,1,1,9.9263e-01,1,1,1,1,1,1,1,9.7922e-01,1,1,1,9.7934e-01,9.9263e-01,1,1,1,1,9.9263e-01,1,1,9.9485e-01,1,1,1,1,9.9485e-01,1,1,9.9329e-01,1,1,1,1,9.9329e-01,1,1,9.9720e-01,1,1,1,1,9.9720e-01,1,1,9.9115e-01,1,1,1,1,9.9115e-01,1,1,1,1,1,1,1,9.8825e-01,1,1,1,1,9.8825e-01,1,1,9.8921e-01,1,1,1,1,9.8921e-01,1,1,0,1,1,1,1,1,1,0
131I  53+ 53+ 53+ 53+ =1.1428e+01,1.1428e+01,3,1.1428e+01,6.8694e-03,0,8.0754e-02,9.5807e+02,3.3269e+01,9.7505e-01,1,1,1,1,9.7505e-01,1,1,1,1,1,1,1,1,1,1,1,3.9948e-01,1,1,6.0263e-01,6.6290e-01,5.3234e-01,5.3234e-01,1,1,1,1,1,1,1,1,1,1,1,9.8589e-01,1,1,1,1,9.8589e-01,1,1,4.8454e-01,5.6011e-01,1,8.8175e-01,9.8110e-01,9.9265e-01,1,1,1,1,9.9265e-01,1,1,9.8959e-01,1,1,1,1,9.8959e-01,1,1,9.9265e-01,1,1,1,1,9.9265e-01,1,1,9.5714e-01,1,1,1,1,9.5714e-01,1,1,9.2378e-01,9.2378e-01,1,1,1,9.8838e-01,1,1,9.8838e-01,1,9.9265e-01,1,1,1,1,9.9265e-01,1,1,1,1,1,1,1,9.9401e-01,1,1,9.9898e-01,9.9502e-01,9.9265e-01,1,1,1,1,9.9265e-01,1,1,9.9486e-01,1,1,1,1,9.9486e-01,1,1,9.9331e-01,1,1,1,1,9.9331e-01,1,1,9.9722e-01,1,1,1,1,9.9722e-01,1,1,9.9119e-01,1,1,1,1,9.9119e-01,1,1,1,1,1,1,1,9.8829e-01,1,1,1,1,9.8829e-01,1,1,9.8926e-01,1,1,1,1,9.8926e-01,1,1,0,1,1,1,1,1,1,0
130I  53+ 53+ 53+ 53+ =5.3306e-01,5.3306e-01,3,5.3306e-01,1.0633e-03,0,2.4337e-02,9.5794e+02,3.3055e+01,9.7507e-01,1,1,1,1,9.7507e-01,1,1,1,1,1,1,1,1,1,1,1,4.0865e-01,1,1,6.0710e-01,6.7312e-01,5.1983e-01,5.1983e-01,1,1,1,1,1,1,1,1,1,1,1,9.8593e-01,1,1,1,1,9.8593e-01,1,1,1.6578e-01,1.9219e-01,1,8.7908e-01,9.8121e-01,9.9267e-01,1,1,1,1,9.9267e-01,1,1,9.8963e-01,1,1,1,1,9.8963e-01,1,1,9.9267e-01,1,1,1,1,9.9267e-01,1,1,9.5727e-01,1,1,1,1,9.5727e-01,1,1,8.1628e-01,8.1628e-01,1,1,1,9.8281e-01,1,1,9.8281e-01,1,9.9267e-01,1,1,1,1,9.9267e-01,1,1,1,1,1,1,1,9.9719e-01,1,1,1,9.9741e-01,9.9267e-01,1,1,1,1,9.9267e-01,1,1,9.9488e-01,1,1,1,1,9.9488e-01,1,1,9.9333e-01,1,1,1,1,9.9333e-01,1,1,9.9723e-01,1,1,1,1,9.9723e-01,1,1,9.9122e-01,1,1,1,1,9.9122e-01,1,1,1,1,1,1,1,9.8833e-01,1,1,1,1,9.8833e-01,1,1,9.8930e-01,1,1,1,1,9.8930e-01,1,1,0,1,1,1,1,1,1,0
129I  53+ 53+ 53+ 53+ =4.0469e-03,4.0469e-03,3,4.0469e-03,2.1371e-04,0,9.1920e-04,9.5782e+02,3.3132e+01,9.7510e-01,1,1,1,1,9.7510e-01,1,1,1,1,1,1,1,1,1,1,1,4.0551e-01,1,1,6.0596e-01,6.6920e-01,4.9937e-01,4.9937e-01,1,1,1,1,1,1,1,1,1,1,1,9.8597e-01,1,1,1,1,9.8597e-01,1,1,1.0379e-02,1.2425e-02,1,8.5150e-01,9.8108e-01,9.9269e-01,1,1,1,1,9.9269e-01,1,1,9.8967e-01,1,1,1,1,9.8967e-01,1,1,9.9269e-01,1,1,1,1,9.9269e-01,1,1,9.5741e-01,1,1,1,1,9.5741e-01,1,1,5.1825e-01,5.1825e-01,1,1,1,9.8033e-01,1,1,9.8033e-01,1,9.9269e-01,1,1,1,1,9.9269e-01,1,1,1,1,1,1,1,9.9608e-01,1,1,9.9830e-01,9.9777e-01,9.9269e-01,1,1,1,1,9.9269e-01,1,1,9.9489e-01,1,1,1,1,9.9489e-01,1,1,9.9335e-01,1,1,1,1,9.9335e-01,1,1,9.9724e-01,1,1,1,1,9.9724e-01,1,1,9.9125e-01,1,1,1,1,9.9125e-01,1,1,1,1,1,1,1,9.8837e-01,1,1,1,1,9.8837e-01,1,1,9.8934e-01,1,1,1,1,9.8934e-01,1,1,0,1,1,1,1,1,1,0
134Te 52+ 52+ 52+ 52+ =5.1936e+03,5.1936e+03,3,5.1936e+03,1.0659e+01,0,2.3654e-02,9.5899e+02,3.2931e+01,9.7499e-01,1,1,1,1,9.7499e-01,1,1,1,1,1,1,1,1,1,1,1,4.2505e-01,1,1,6.1445e-01,6.9176e-01,9.8931e-01,9.8931e-01,1,1,1,1,1,1,1,1,1,1,1,9.8577e-01,1,1,1,1,9.8577e-01,1,1,1.0102e-01,1.1948e-01,1,8.6122e-01,9.8174e-01,9.9259e-01,1,1,1,1,9.9259e-01,1,1,9.8947e-01,1,1,1,1,9.8947e-01,1,1,9.9259e-01,1,1,1,1,9.9259e-01,1,1,9.5675e-01,1,1,1,1,9.5675e-01,1,1,8.8556e-01,8.8556e-01,1,1,1,9.8201e-01,1,1,9.8314e-01,9.9885e-01,9.9259e-01,1,1,1,1,9.9259e-01,1,1,1,1,1,1,1,7.4242e-01,1,1,1,7.4250e-01,9.9259e-01,1,1,1,1,9.9259e-01,1,1,9.9482e-01,1,1,1,1,9.9482e-01,1,1,9.9326e-01,1,1,1,1,9.9326e-01,1,1,9.9718e-01,1,1,1,1,9.9718e-01,1,1,9.9109e-01,1,1,1,1,9.9109e-01,1,1,1,1,1,1,1,9.8817e-01,1,1,1,1,9.8817e-01,1,1,9.8913e-01,1,1,1,1,9.8913e-01,1,1,0,1,1,1,1,1,1,0
133Te 52+ 52+ 52+ 52+ =3.9038e+03,3.9038e+03,3,3.9038e+03,6.1518e+00,0,3.0804e-02,9.5893e+02,3.3736e+01,9.7501e-01,1,1,1,1,9.7501e-01,1,1,1,1,1,1,1,1,1,1,1,3.8869e-01,1,1,5.9696e-01,6.5113e-01,8.9036e-01,8.9036e-01,1,1,1,1,1,1,1,1,1,1,1,9.8581e-01,1,1,1,1,9.8581e-01,1,1,1.4071e-01,1.6669e-01,1,8.6033e-01,9.8119e-01,9.9261e-01,1,1,1,1,9.9261e-01,1,1,9.8951e-01,1,1,1,1,9.8951e-01,1,1,9.9261e-01,1,1,1,1,9.9261e-01,1,1,9.5688e-01,1,1,1,1,9.5688e-01,1,1,8.8127e-01,8.8127e-01,1,1,1,9.7154e-01,1,1,9.8383e-01,9.8751e-01,9.9261e-01,1,1,1,1,9.9261e-01,1,1,1,1,1,1,1,8.5629e-01,1,1,9.8562e-01,8.6879e-01,9.9261e-01,1,1,1,1,9.9261e-01,1,1,9.9484e-01,1,1,1,1,9.9484e-01,1,1,9.9328e-01,1,1,1,1,9.9328e-01,1,1,9.9719e-01,1,1,1,1,9.9719e-01,1,1,9.9112e-01,1,1,1,1,9.9112e-01,1,1,1,1,1,1,1,9.8821e-01,1,1,1,1,9.8821e-01,1,1,9.8917e-01,1,1,1,1,9.8917e-01,1,1,0,1,1,1,1,1,1,0
132Te 52+ 52+ 52+ 52+ =1.1419e+04,1.1419e+04,3,1.1419e+04,8.7780e+00,0,6.3148e-02,9.5885e+02,3.4263e+01,9.7503e-01,1,1,1,1,9.7503e-01,1,1,1,1,1,1,1,1,1,1,1,3.6554e-01,1,1,5.8537e-01,6.2445e-01,7.1578e-01,7.1578e-01,1,1,1,1,1,1,1,1,1,1,1,9.8585e-01,1,1,1,1,9.8585e-01,1,1,3.2676e-01,3.8110e-01,1,8.7416e-01,9.8083e-01,9.9263e-01,1,1,1,1,9.9263e-01,1,1,9.8955e-01,1,1,1,1,9.8955e-01,1,1,9.9263e-01,1,1,1,1,9.9263e-01,1,1,9.5701e-01,1,1,1,1,9.5701e-01,1,1,9.1721e-01,9.1721e-01,1,1,1,9.8643e-01,1,1,9.8643e-01,1,9.9263e-01,1,1,1,1,9.9263e-01,1,1,1,1,1,1,1,9.4580e-01,1,1,9.9318e-01,9.5229e-01,9.9263e-01,1,1,1,1,9.9263e-01,1,1,9.9485e-01,1,1,1,1,9.9485e-01,1,1,9.9330e-01,1,1,1,1,9.9330e-01,1,1,9.9720e-01,1,1,1,1,9.9720e-01,1,1,9.9115e-01,1,1,1,1,9.9115e-01,1,1,1,1,1,1,1,9.8825e-01,1,1,1,1,9.8825e-01,1,1,9.8921e-01,1,1,1,1,9.8921e-01,1,1,0,1,1,1,1,1,1,0
131Te 52+ 52+ 52+ 52+ =3.6130e+03,3.6130e+03,3,3.6130e+03,1.5708e+00,0,1.1165e-01,9.5873e+02,3.4015e+01,9.7505e-01,1,1,1,1,9.7505e-01,1,1,1,1,1,1,1,1,1,1,1,3.6793e-01,1,1,5.8729e-01,6.2648e-01,5.9563e-01,5.9563e-01,1,1,1,1,1,1,1,1,1,1,1,9.8589e-01,1,1,1,1,9.8589e-01,1,1,6.3999e-01,7.4007e-01,1,8.8185e-01,9.8063e-01,9.9265e-01,1,1,1,1,9.9265e-01,1,1,9.8959e-01,1,1,1,1,9.8959e-01,1,1,9.9265e-01,1,1,1,1,9.9265e-01,1,1,9.5715e-01,1,1,1,1,9.5715e-01,1,1,9.6535e-01,9.6535e-01,1,1,1,9.8490e-01,1,1,9.8669e-01,9.9818e-01,9.9265e-01,1,1,1,1,9.9265e-01,1,1,1,1,1,1,1,9.6965e-01,1,1,9.9625e-01,9.7330e-01,9.9265e-01,1,1,1,1,9.9265e-01,1,1,9.9487e-01,1,1,1,1,9.9487e-01,1,1,9.9332e-01,1,1,1,1,9.9332e-01,1,1,9.9722e-01,1,1,1,1,9.9722e-01,1,1,9.9119e-01,1,1,1,1,9.9119e-01,1,1,1,1,1,1,1,9.8829e-01,1,1,1,1,9.8829e-01,1,1,9.8926e-01,1,1,1,1,9.8926e-01,1,1,0,1,1,1,1,1,1,0
130Te 52+ 52+ 52+ 52+ =2.1980e+02,2.1980e+02,3,2.1980e+02,8.4937e-02,0,1.2562e-01,9.5864e+02,3.4266e+01,9.7507e-01,1,1,1,1,9.7507e-01,1,1,1,1,1,1,1,1,1,1,1,3.6080e-01,1,1,5.8186e-01,6.2008e-01,5.4686e-01,5.4686e-01,1,1,1,1,1,1,1,1,1,1,1,9.8593e-01,1,1,1,1,9.8593e-01,1,1,7.7381e-01,8.9771e-01,1,8.7907e-01,9.8056e-01,9.9267e-01,1,1,1,1,9.9267e-01,1,1,9.8963e-01,1,1,1,1,9.8963e-01,1,1,9.9267e-01,1,1,1,1,9.9267e-01,1,1,9.5728e-01,1,1,1,1,9.5728e-01,1,1,9.8869e-01,9.8869e-01,1,1,1,9.8694e-01,1,1,9.8694e-01,1,9.9267e-01,1,1,1,1,9.9267e-01,1,1,1,1,1,1,1,9.7607e-01,1,1,1,9.7609e-01,9.9267e-01,1,1,1,1,9.9267e-01,1,1,9.9488e-01,1,1,1,1,9.9488e-01,1,1,9.9334e-01,1,1,1,1,9.9334e-01,1,1,9.9723e-01,1,1,1,1,9.9723e-01,1,1,9.9122e-01,1,1,1,1,9.9122e-01,1,1,1,1,1,1,1,9.8833e-01,1,1,1,1,9.8833e-01,1,1,9.8930e-01,1,1,1,1,9.8930e-01,1,1,0,1,1,1,1,1,1,0
129Te 52+ 52+ 52+ 52+ =4.7223e+01,4.7223e+01,3,4.7223e+01,2.1439e-02,0,1.0692e-01,9.5851e+02,3.4098e+01,9.7509e-01,1,1,1,1,9.7509e-01,1,1,1,1,1,1,1,1,1,1,1,3.6557e-01,1,1,5.8561e-01,6.2425e-01,5.3410e-01,5.3410e-01,1,1,1,1,1,1,1,1,1,1,1,9.8598e-01,1,1,1,1,9.8598e-01,1,1,6.7628e-01,7.8079e-01,1,8.8305e-01,9.8086e-01,9.9269e-01,1,1,1,1,9.9269e-01,1,1,9.8967e-01,1,1,1,1,9.8967e-01,1,1,9.9269e-01,1,1,1,1,9.9269e-01,1,1,9.5742e-01,1,1,1,1,9.5742e-01,1,1,9.6299e-01,9.6299e-01,1,1,1,9.8920e-01,1,1,9.8920e-01,1,9.9269e-01,1,1,1,1,9.9269e-01,1,1,1,1,1,1,1,9.8362e-01,1,1,1,9.8372e-01,9.9269e-01,1,1,1,1,9.9269e-01,1,1,9.9490e-01,1,1,1,1,9.9490e-01,1,1,9.9336e-01,1,1,1,1,9.9336e-01,1,1,9.9724e-01,1,1,1,1,9.9724e-01,1,1,9.9125e-01,1,1,1,1,9.9125e-01,1,1,1,1,1,1,1,9.8837e-01,1,1,1,1,9.8837e-01,1,1,9.8934e-01,1,1,1,1,9.8934e-01,1,1,0,1,1,1,1,1,1,0
128Te 52+ 52+ 52+ 52+ =9.7914e+00,9.7914e+00,3,9.7914e+00,7.9963e-03,0,5.9440e-02,9.5841e+02,3.4303e+01,9.7512e-01,1,1,1,1,9.7512e-01,1,1,1,1,1,1,1,1,1,1,1,3.5974e-01,1,1,5.8121e-01,6.1896e-01,5.2885e-01,5.2885e-01,1,1,1,1,1,1,1,1,1,1,1,9.8602e-01,1,1,1,1,9.8602e-01,1,1,4.1014e-01,4.6736e-01,1,8.9475e-01,9.8080e-01,9.9271e-01,1,1,1,1,9.9271e-01,1,1,9.8972e-01,1,1,1,1,9.8972e-01,1,1,9.9271e-01,1,1,1,1,9.9271e-01,1,1,9.5755e-01,1,1,1,1,9.5755e-01,1,1,8.9718e-01,8.9718e-01,1,1,1,9.8725e-01,1,1,9.8725e-01,1,9.9271e-01,1,1,1,1,9.9271e-01,1,1,1,1,1,1,1,9.9473e-01,1,1,1,9.9528e-01,9.9272e-01,1,1,1,1,9.9272e-01,1,1,9.9491e-01,1,1,1,1,9.9491e-01,1,1,9.9338e-01,1,1,1,1,9.9338e-01,1,1,9.9725e-01,1,1,1,1,9.9725e-01,1,1,9.9129e-01,1,1,1,1,9.9129e-01,1,1,1,1,1,1,1,9.8841e-01,1,1,1,1,9.8841e-01,1,1,9.8938e-01,1,1,1,1,9.8938e-01,1,1,0,1,1,1,1,1,1,0
133Sb 51+ 51+ 51+ 51+ =3.1378e+03,3.1378e+03,3,3.1378e+03,3.6697e+00,0,4.1506e-02,9.5947e+02,3.3047e+01,9.7501e-01,1,1,1,1,9.7501e-01,1,1,1,1,1,1,1,1,1,1,1,4.2105e-01,1,1,6.1259e-01,6.8733e-01,8.7047e-01,8.7047e-01,1,1,1,1,1,1,1,1,1,1,1,9.8582e-01,1,1,1,1,9.8582e-01,1,1,1.6524e-01,1.9524e-01,1,8.6216e-01,9.8167e-01,9.9261e-01,1,1,1,1,9.9261e-01,1,1,9.8951e-01,1,1,1,1,9.8951e-01,1,1,9.9261e-01,1,1,1,1,9.9261e-01,1,1,9.5690e-01,1,1,1,1,9.5690e-01,1,1,8.9796e-01,8.9796e-01,1,1,1,9.8241e-01,1,1,9.8410e-01,9.9828e-01,9.9261e-01,1,1,1,1,9.9261e-01,1,1,1,1,1,1,1,9.0036e-01,1,1,9.9492e-01,9.0495e-01,9.9261e-01,1,1,1,1,9.9261e-01,1,1,9.9484e-01,1,1,1,1,9.9484e-01,1,1,9.9328e-01,1,1,1,1,9.9328e-01,1,1,9.9719e-01,1,1,1,1,9.9719e-01,1,1,9.9112e-01,1,1,1,1,9.9112e-01,1,1,1,1,1,1,1,9.8821e-01,1,1,1,1,9.8821e-01,1,1,9.8918e-01,1,1,1,1,9.8918e-01,1,1,0,1,1,1,1,1,1,0
132Sb 51+ 51+ 51+ 51+ =1.4316e+03,1.4316e+03,3,1.4316e+03,5.8439e+00,0,1.1892e-02,9.5943e+02,3.4065e+01,9.7503e-01,1,1,1,1,9.7503e-01,1,1,1,1,1,1,1,1,1,1,1,3.7688e-01,1,1,5.9079e-01,6.3792e-01,9.6626e-01,9.6626e-01,1,1,1,1,1,1,1,1,1,1,1,9.8586e-01,1,1,1,1,9.8586e-01,1,1,5.8702e-02,7.0098e-02,1,8.5340e-01,9.8129e-01,9.9263e-01,1,1,1,1,9.9263e-01,1,1,9.8955e-01,1,1,1,1,9.8955e-01,1,1,9.9263e-01,1,1,1,1,9.9263e-01,1,1,9.5703e-01,1,1,1,1,9.5703e-01,1,1,8.6362e-01,8.6362e-01,1,1,1,9.7974e-01,1,1,9.8317e-01,9.9651e-01,9.9263e-01,1,1,1,1,9.9263e-01,1,1,1,1,1,1,1,7.6163e-01,1,1,1,7.6174e-01,9.9263e-01,1,1,1,1,9.9263e-01,1,1,9.9486e-01,1,1,1,1,9.9486e-01,1,1,9.9330e-01,1,1,1,1,9.9330e-01,1,1,9.9721e-01,1,1,1,1,9.9721e-01,1,1,9.9115e-01,1,1,1,1,9.9115e-01,1,1,1,1,1,1,1,9.8825e-01,1,1,1,1,9.8825e-01,1,1,9.8922e-01,1,1,1,1,9.8922e-01,1,1,0,1,1,1,1,1,1,0
131Sb 51+ 51+ 51+ 51+ =2.8072e+03,2.8072e+03,3,2.8072e+03,1.2571e+01,0,1.0840e-02,9.5936e+02,3.4643e+01,9.7505e-01,1,1,1,1,9.7505e-01,1,1,1,1,1,1,1,1,1,1,1,3.5681e-01,1,1,5.7855e-01,6.1674e-01,9.3746e-01,9.3746e-01,1,1,1,1,1,1,1,1,1,1,1,9.8590e-01,1,1,1,1,9.8590e-01,1,1,5.7666e-02,6.9030e-02,1,8.5161e-01,9.8094e-01,9.9265e-01,1,1,1,1,9.9265e-01,1,1,9.8959e-01,1,1,1,1,9.8959e-01,1,1,9.9265e-01,1,1,1,1,9.9265e-01,1,1,9.5716e-01,1,1,1,1,9.5716e-01,1,1,8.4893e-01,8.4893e-01,1,1,1,9.6534e-01,1,1,9.8164e-01,9.8340e-01,9.9266e-01,1,1,1,1,9.9266e-01,1,1,1,1,1,1,1,7.9406e-01,1,1,9.7992e-01,8.1034e-01,9.9266e-01,1,1,1,1,9.9266e-01,1,1,9.9487e-01,1,1,1,1,9.9487e-01,1,1,9.9332e-01,1,1,1,1,9.9332e-01,1,1,9.9722e-01,1,1,1,1,9.9722e-01,1,1,9.9119e-01,1,1,1,1,9.9119e-01,1,1,1,1,1,1,1,9.8829e-01,1,1,1,1,9.8829e-01,1,1,9.8926e-01,1,1,1,1,9.8926e-01,1,1,0,1,1,1,1,1,1,0
130Sb 51+ 51+ 51+ 51+ =2.5933e+03,2.5933e+03,3,2.5933e+03,3.7749e+00,0,3.3348e-02,9.5925e+02,3.4639e+01,9.7507e-01,1,1,1,1,9.7507e-01,1,1,1,1,1,1,1,1,1,1,1,3.5690e-01,1,1,5.7869e-01,6.1674e-01,7.9791e-01,7.9791e-01,1,1,1,1,1,1,1,1,1,1,1,9.8594e-01,1,1,1,1,9.8594e-01,1,1,1.7528e-01,2.0691e-01,1,8.6371e-01,9.8081e-01,9.9268e-01,1,1,1,1,9.9268e-01,1,1,9.8963e-01,1,1,1,1,9.8963e-01,1,1,9.9268e-01,1,1,1,1,9.9268e-01,1,1,9.5729e-01,1,1,1,1,9.5729e-01,1,1,8.8348e-01,8.8348e-01,1,1,1,9.7488e-01,1,1,9.8425e-01,9.9048e-01,9.9268e-01,1,1,1,1,9.9268e-01,1,1,1,1,1,1,1,8.9789e-01,1,1,9.8388e-01,9.1260e-01,9.9268e-01,1,1,1,1,9.9268e-01,1,1,9.9488e-01,1,1,1,1,9.9488e-01,1,1,9.9334e-01,1,1,1,1,9.9334e-01,1,1,9.9723e-01,1,1,1,1,9.9723e-01,1,1,9.9122e-01,1,1,1,1,9.9122e-01,1,1,1,1,1,1,1,9.8833e-01,1,1,1,1,9.8833e-01,1,1,9.8930e-01,1,1,1,1,9.8930e-01,1,1,0,1,1,1,1,1,1,0
129Sb 51+ 51+ 51+ 51+ =5.8199e+02,5.8199e+02,3,5.8199e+02,3.7477e-01,0,7.5383e-02,9.5916e+02,3.4904e+01,9.7509e-01,1,1,1,1,9.7509e-01,1,1,1,1,1,1,1,1,1,1,1,3.4932e-01,1,1,5.7292e-01,6.0972e-01,6.3944e-01,6.3944e-01,1,1,1,1,1,1,1,1,1,1,1,9.8598e-01,1,1,1,1,9.8598e-01,1,1,4.4707e-01,5.1501e-01,1,8.8528e-01,9.8058e-01,9.9270e-01,1,1,1,1,9.9270e-01,1,1,9.8967e-01,1,1,1,1,9.8967e-01,1,1,9.9270e-01,1,1,1,1,9.9270e-01,1,1,9.5743e-01,1,1,1,1,9.5743e-01,1,1,9.3414e-01,9.3414e-01,1,1,1,9.7361e-01,1,1,9.8249e-01,9.9096e-01,9.9270e-01,1,1,1,1,9.9270e-01,1,1,1,1,1,1,1,9.6034e-01,1,1,1,9.6050e-01,9.9270e-01,1,1,1,1,9.9270e-01,1,1,9.9490e-01,1,1,1,1,9.9490e-01,1,1,9.9336e-01,1,1,1,1,9.9336e-01,1,1,9.9724e-01,1,1,1,1,9.9724e-01,1,1,9.9125e-01,1,1,1,1,9.9125e-01,1,1,1,1,1,1,1,9.8837e-01,1,1,1,1,9.8837e-01,1,1,9.8934e-01,1,1,1,1,9.8934e-01,1,1,0,1,1,1,1,1,1,0
128Sb 51+ 51+ 51+ 51+ =4.0630e+02,4.0630e+02,3,4.0630e+02,1.6968e-01,0,1.1623e-01,9.5904e+02,3.4810e+01,9.7511e-01,1,1,1,1,9.7511e-01,1,1,1,1,1,1,1,1,1,1,1,3.5195e-01,1,1,5.7503e-01,6.1206e-01,5.6452e-01,5.6452e-01,1,1,1,1,1,1,1,1,1,1,1,9.8602e-01,1,1,1,1,9.8602e-01,1,1,7.2560e-01,8.3460e-01,1,8.8672e-01,9.8046e-01,9.9272e-01,1,1,1,1,9.9272e-01,1,1,9.8971e-01,1,1,1,1,9.8971e-01,1,1,9.9272e-01,1,1,1,1,9.9272e-01,1,1,9.5756e-01,1,1,1,1,9.5756e-01,1,1,9.7548e-01,9.7548e-01,1,1,1,9.8446e-01,1,1,9.8514e-01,1,9.9272e-01,1,1,1,1,9.9272e-01,1,1,1,1,1,1,1,9.7103e-01,1,1,1,9.7109e-01,9.9272e-01,1,1,1,1,9.9272e-01,1,1,9.9491e-01,1,1,1,1,9.9491e-01,1,1,9.9338e-01,1,1,1,1,9.9338e-01,1,1,9.9725e-01,1,1,1,1,9.9725e-01,1,1,9.9128e-01,1,1,1,1,9.9128e-01,1,1,1,1,1,1,1,9.8841e-01,1,1,1,1,9.8841e-01,1,1,9.8938e-01,1,1,1,1,9.8938e-01,1,1,0,1,1,1,1,1,1,0
127Sb 51+ 51+ 51+ 51+ =2.5745e+02,2.5745e+02,3,2.5745e+02,1.0447e-01,0,1.1962e-01,9.5894e+02,3.4847e+01,9.7514e-01,1,1,1,1,9.7514e-01,1,1,1,1,1,1,1,1,1,1,1,3.4568e-01,1,1,5.7024e-01,6.0620e-01,5.3552e-01,5.3552e-01,1,1,1,1,1,1,1,1,1,1,1,9.8606e-01,1,1,1,1,9.8606e-01,1,1,7.8803e-01,9.0001e-01,1,8.9289e-01,9.8062e-01,9.9274e-01,1,1,1,1,9.9274e-01,1,1,9.8976e-01,1,1,1,1,9.8976e-01,1,1,9.9274e-01,1,1,1,1,9.9274e-01,1,1,9.5770e-01,1,1,1,1,9.5770e-01,1,1,9.8426e-01,9.8426e-01,1,1,1,9.8752e-01,1,1,9.8752e-01,1,9.9274e-01,1,1,1,1,9.9274e-01,1,1,1,1,1,1,1,9.7536e-01,1,1,1,9.7537e-01,9.9274e-01,1,1,1,1,9.9274e-01,1,1,9.9493e-01,1,1,1,1,9.9493e-01,1,1,9.9340e-01,1,1,1,1,9.9340e-01,1,1,9.9726e-01,1,1,1,1,9.9726e-01,1,1,9.9132e-01,1,1,1,1,9.9132e-01,1,1,1,1,1,1,1,9.8846e-01,1,1,1,1,9.8846e-01,1,1,9.8942e-01,1,1,1,1,9.8942e-01,1,1,0,1,1,1,1,1,1,0
132Sn 50+ 50+ 50+ 50+ =7.7379e+02,7.7379e+02,3,7.7379e+02,4.6280e-01,0,8.1163e-02,9.6002e+02,3.4179e+01,9.7503e-01,1,1,1,1,9.7503e-01,1,1,1,1,1,1,1,1,1,1,1,3.7083e-01,1,1,5.8912e-01,6.2945e-01,5.5737e-01,5.5737e-01,1,1,1,1,1,1,1,1,1,1,1,9.8587e-01,1,1,1,1,9.8587e-01,1,1,5.0940e-01,5.9398e-01,1,8.7482e-01,9.8032e-01,9.9264e-01,1,1,1,1,9.9264e-01,1,1,9.8955e-01,1,1,1,1,9.8955e-01,1,1,9.9264e-01,1,1,1,1,9.9264e-01,1,1,9.5704e-01,1,1,1,1,9.5704e-01,1,1,9.4879e-01,9.4879e-01,1,1,1,9.7975e-01,1,1,9.8667e-01,9.9299e-01,9.9264e-01,1,1,1,1,9.9264e-01,1,1,1,1,1,1,1,9.6063e-01,1,1,9.8988e-01,9.7045e-01,9.9264e-01,1,1,1,1,9.9264e-01,1,1,9.9486e-01,1,1,1,1,9.9486e-01,1,1,9.9331e-01,1,1,1,1,9.9331e-01,1,1,9.9721e-01,1,1,1,1,9.9721e-01,1,1,9.9116e-01,1,1,1,1,9.9116e-01,1,1,1,1,1,1,1,9.8825e-01,1,1,1,1,9.8825e-01,1,1,9.8922e-01,1,1,1,1,9.8922e-01,1,1,0,1,1,1,1,1,1,0
131Sn 50+ 50+ 50+ 50+ =1.5236e+03,1.5236e+03,3,1.5236e+03,1.7256e+00,0,4.2861e-02,9.5994e+02,3.4593e+01,9.7505e-01,1,1,1,1,9.7505e-01,1,1,1,1,1,1,1,1,1,1,1,3.5908e-01,1,1,5.8010e-01,6.1900e-01,6.8965e-01,6.8965e-01,1,1,1,1,1,1,1,1,1,1,1,9.8591e-01,1,1,1,1,9.8591e-01,1,1,2.4148e-01,2.8374e-01,1,8.6775e-01,9.8075e-01,9.9266e-01,1,1,1,1,9.9266e-01,1,1,9.8959e-01,1,1,1,1,9.8959e-01,1,1,9.9266e-01,1,1,1,1,9.9266e-01,1,1,9.5718e-01,1,1,1,1,9.5718e-01,1,1,9.0042e-01,9.0042e-01,1,1,1,9.8493e-01,1,1,9.8493e-01,1,9.9266e-01,1,1,1,1,9.9266e-01,1,1,1,1,1,1,1,9.3583e-01,1,1,9.9557e-01,9.3999e-01,9.9266e-01,1,1,1,1,9.9266e-01,1,1,9.9487e-01,1,1,1,1,9.9487e-01,1,1,9.9333e-01,1,1,1,1,9.9333e-01,1,1,9.9722e-01,1,1,1,1,9.9722e-01,1,1,9.9119e-01,1,1,1,1,9.9119e-01,1,1,1,1,1,1,1,9.8829e-01,1,1,1,1,9.8829e-01,1,1,9.8926e-01,1,1,1,1,9.8926e-01,1,1,0,1,1,1,1,1,1,0
130Sn 50+ 50+ 50+ 50+ =1.4605e+03,1.4605e+03,3,1.4605e+03,7.3159e+00,0,9.6908e-03,9.5989e+02,3.5314e+01,9.7507e-01,1,1,1,1,9.7507e-01,1,1,1,1,1,1,1,1,1,1,1,3.3920e-01,1,1,5.6508e-01,6.0026e-01,8.5258e-01,8.5258e-01,1,1,1,1,1,1,1,1,1,1,1,9.8595e-01,1,1,1,1,9.8595e-01,1,1,5.6336e-02,6.7316e-02,1,8.5325e-01,9.8081e-01,9.9268e-01,1,1,1,1,9.9268e-01,1,1,9.8964e-01,1,1,1,1,9.8964e-01,1,1,9.9268e-01,1,1,1,1,9.9268e-01,1,1,9.5731e-01,1,1,1,1,9.5731e-01,1,1,8.4535e-01,8.4535e-01,1,1,1,9.6905e-01,1,1,9.8100e-01,9.8782e-01,9.9268e-01,1,1,1,1,9.9268e-01,1,1,1,1,1,1,1,8.4045e-01,1,1,9.9391e-01,8.4560e-01,9.9268e-01,1,1,1,1,9.9268e-01,1,1,9.9489e-01,1,1,1,1,9.9489e-01,1,1,9.9335e-01,1,1,1,1,9.9335e-01,1,1,9.9723e-01,1,1,1,1,9.9723e-01,1,1,9.9122e-01,1,1,1,1,9.9122e-01,1,1,1,1,1,1,1,9.8833e-01,1,1,1,1,9.8833e-01,1,1,9.8930e-01,1,1,1,1,9.8930e-01,1,1,0,1,1,1,1,1,1,0
129Sn 50+ 50+ 50+ 50+ =3.4148e+02,3.4148e+02,3,3.4148e+02,3.8911e+00,0,4.2601e-03,9.5978e+02,3.5328e+01,9.7509e-01,1,1,1,1,9.7509e-01,1,1,1,1,1,1,1,1,1,1,1,3.3869e-01,1,1,5.6484e-01,5.9963e-01,9.5572e-01,9.5572e-01,1,1,1,1,1,1,1,1,1,1,1,9.8599e-01,1,1,1,1,9.8599e-01,1,1,2.6874e-02,3.2458e-02,1,8.4403e-01,9.8095e-01,9.9270e-01,1,1,1,1,9.9270e-01,1,1,9.8967e-01,1,1,1,1,9.8967e-01,1,1,9.9270e-01,1,1,1,1,9.9270e-01,1,1,9.5744e-01,1,1,1,1,9.5744e-01,1,1,8.2230e-01,8.2230e-01,1,1,1,9.7905e-01,1,1,9.8201e-01,9.9698e-01,9.9270e-01,1,1,1,1,9.9270e-01,1,1,1,1,1,1,1,7.0380e-01,1,1,1,7.0398e-01,9.9270e-01,1,1,1,1,9.9270e-01,1,1,9.9490e-01,1,1,1,1,9.9490e-01,1,1,9.9336e-01,1,1,1,1,9.9336e-01,1,1,9.9724e-01,1,1,1,1,9.9724e-01,1,1,9.9125e-01,1,1,1,1,9.9125e-01,1,1,1,1,1,1,1,9.8837e-01,1,1,1,1,9.8837e-01,1,1,9.8934e-01,1,1,1,1,9.8934e-01,1,1,0,1,1,1,1,1,1,0
128Sn 50+ 50+ 50+ 50+ =1.3150e+02,1.3150e+02,3,1.3150e+02,6.6844e-01,0,9.5497e-03,9.5970e+02,3.5711e+01,9.7511e-01,1,1,1,1,9.7511e-01,1,1,1,1,1,1,1,1,1,1,1,3.2630e-01,1,1,5.5697e-01,5.8584e-01,8.5363e-01,8.5363e-01,1,1,1,1,1,1,1,1,1,1,1,9.8603e-01,1,1,1,1,9.8603e-01,1,1,5.9465e-02,7.1110e-02,1,8.5276e-01,9.8063e-01,9.9272e-01,1,1,1,1,9.9272e-01,1,1,9.8971e-01,1,1,1,1,9.8971e-01,1,1,9.9272e-01,1,1,1,1,9.9272e-01,1,1,9.5758e-01,1,1,1,1,9.5758e-01,1,1,8.3671e-01,8.3671e-01,1,1,1,9.7049e-01,1,1,9.8127e-01,9.8902e-01,9.9272e-01,1,1,1,1,9.9272e-01,1,1,1,1,1,1,1,8.2117e-01,1,1,9.9179e-01,8.2797e-01,9.9272e-01,1,1,1,1,9.9272e-01,1,1,9.9492e-01,1,1,1,1,9.9492e-01,1,1,9.9338e-01,1,1,1,1,9.9338e-01,1,1,9.9725e-01,1,1,1,1,9.9725e-01,1,1,9.9128e-01,1,1,1,1,9.9128e-01,1,1,1,1,1,1,1,9.8841e-01,1,1,1,1,9.8841e-01,1,1,9.8938e-01,1,1,1,1,9.8938e-01,1,1,0,1,1,1,1,1,1,0
127Sn 50+ 50+ 50+ 50+ =3.8792e+02,3.8792e+02,3,3.8792e+02,4.9648e-01,0,3.7929e-02,9.5958e+02,3.5649e+01,9.7514e-01,1,1,1,1,9.7514e-01,1,1,1,1,1,1,1,1,1,1,1,3.2801e-01,1,1,5.5827e-01,5.8755e-01,6.9156e-01,6.9156e-01,1,1,1,1,1,1,1,1,1,1,1,9.8607e-01,1,1,1,1,9.8607e-01,1,1,2.3968e-01,2.8028e-01,1,8.7214e-01,9.8051e-01,9.9274e-01,1,1,1,1,9.9274e-01,1,1,9.8976e-01,1,1,1,1,9.8976e-01,1,1,9.9274e-01,1,1,1,1,9.9274e-01,1,1,9.5771e-01,1,1,1,1,9.5771e-01,1,1,8.9215e-01,8.9215e-01,1,1,1,9.8372e-01,1,1,9.8449e-01,1,9.9274e-01,1,1,1,1,9.9274e-01,1,1,1,1,1,1,1,9.1894e-01,1,1,9.9025e-01,9.2799e-01,9.9274e-01,1,1,1,1,9.9274e-01,1,1,9.9493e-01,1,1,1,1,9.9493e-01,1,1,9.9340e-01,1,1,1,1,9.9340e-01,1,1,9.9726e-01,1,1,1,1,9.9726e-01,1,1,9.9132e-01,1,1,1,1,9.9132e-01,1,1,1,1,1,1,1,9.8846e-01,1,1,1,1,9.8846e-01,1,1,9.8942e-01,1,1,1,1,9.8942e-01,1,1,0,1,1,1,1,1,1,0
126Sn 50+ 50+ 50+ 50+ =9.2109e+02,9.2109e+02,3,9.2109e+02,5.5026e-01,0,8.1256e-02,9.5950e+02,3.6027e+01,9.7516e-01,1,1,1,1,9.7516e-01,1,1,1,1,1,1,1,1,1,1,1,3.1826e-01,1,1,5.5143e-01,5.7715e-01,5.7179e-01,5.7179e-01,1,1,1,1,1,1,1,1,1,1,1,9.8611e-01,1,1,1,1,9.8611e-01,1,1,5.7709e-01,6.5391e-01,1,9.0021e-01,9.8035e-01,9.9277e-01,1,1,1,1,9.9277e-01,1,1,9.8980e-01,1,1,1,1,9.8980e-01,1,1,9.9277e-01,1,1,1,1,9.9277e-01,1,1,9.5785e-01,1,1,1,1,9.5785e-01,1,1,9.4513e-01,9.4513e-01,1,1,1,9.8005e-01,1,1,9.8720e-01,9.9275e-01,9.9277e-01,1,1,1,1,9.9277e-01,1,1,1,1,1,1,1,9.6529e-01,1,1,1,9.6557e-01,9.9277e-01,1,1,1,1,9.9277e-01,1,1,9.9495e-01,1,1,1,1,9.9495e-01,1,1,9.9342e-01,1,1,1,1,9.9342e-01,1,1,9.9727e-01,1,1,1,1,9.9727e-01,1,1,9.9135e-01,1,1,1,1,9.9135e-01,1,1,1,1,1,1,1,9.8850e-01,1,1,1,1,9.8850e-01,1,1,9.8946e-01,1,1,1,1,9.8946e-01,1,1,0,1,1,1,1,1,1,0
