Version 9.9.1

{============================= Main Part ======================================}
[general]
                    File = C:\user\c\lise_pp_99\LISEpp_ActualInstaller\install\files\examples\de_e_test.lpp
                    Date = 29-12-2014
                    Time = 15:32:47
           Configuration = LISEstandard.lcn
             Optionsfile = default.opt
                   Title = LISEstandard
          BlockStructure = DWDMMMMMMM

[settings]
                   A,Z,Q = 40Ar18+                               ; Mass ElementName Charge+ Beam
                  Energy = 50                   MeV/u            
               Intensity = 1000                 enA              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 36Ar                                  ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 1.5                  (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 3.3                  (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 1.5                  (±)mm            ; one-half the vertical beam extent (y)
                      BF = 3.3                  (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.15                 (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = 45                   degrees          
                  ShapeX = 32769
                  ShapeT = 32769
                  ShapeY = 32769
                  ShapeF = 32769
                  ShapeL = 32769
                  ShapeD = 32769

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 64                                    ; Number of points in distribution
        NP charge states = 32                                    ; Number of points in distribution
                NP wedge = 16                                    ; Number of points in distribution
           Charge states = No                                    ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,73,1,180.948                        ; Nomer,Z,Atoms,Mass
        Target thickness = 0,100,16.6,0,0                        ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,73,1,180.948                        ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,16.6,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 0                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 1                                     ; calculate other reactions
           V calculation = 0                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 0                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 2                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 0                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 0                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-9     
               FisCS_TKE = 1e-6     
                      N0 = 82                                    ; default 82
                     dU0 = -2.5                                  ; default -2.5
                      C0 = 1.4                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -5.5                                  ; default -5.5
                      C1 = 0.16                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-4     
                 BeamInd = 1e-6     
               BeamTotal = 1e-8     

[convolution]
        Convolution mode = 0                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 5.758 
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 1                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 0                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
          AvoidUnboundCS = 1                                     ; 1-Yes, 0-No
       ProtectedChannels = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 6                    fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 0                                     ; 0 - no, 1 - use
         DissipationBeta = 2                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 1                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 1                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       

[evapauto]
                  tun_a0 = 1.00938
                  tun_a1 = -0.36149
                  tun_a2 = 0.21551
                 A_Bound =  40                                   ; mass
               A_Pairing =  70                                   ; mass

[plot]
            Start target = Detector                              ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = M5
         dE-detector-1st = M3
         dE-detector-2nd = M2
            TKE-detector = M3
                PlotBrho = D1
               PlotWedge = D2
              X-detector = M1
              Y-detector = M2
                 Tilting = M1
                 Stopper = M2
                RO_Wedge = 
          ConditionBlock = A10
          Plot threshold = 1e-2                 pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 1
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
                Velocity = 1                                     ; Calculat fissile nuclei speed
           LowEx_nucleus = 39Ar                                  ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 34S                                   ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 28Si                                  ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 1.800e+03 100.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 18
                   Dr_n0 = 0
                   Dr_n1 = 22

[cross sections]

[previous]
                 Lowerst = 25Na                                  ; Mass ElementName Charge+ Beam
                 Highest = 40K                                   ; Mass ElementName Charge+ Beam

[MC_options]
                   dXsel = 12
                   dYsel = 12
                  dAZQ_X = 1
                  dAZQ_Y = 5
                  dVEL_X = 1
                  dVEL_Y = 0
               dIso_mode = 0
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 0
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 1
                  CS_use = 1
           envelope_show = 0
                use_bore = 0
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
              AZQ_Xsigma = 0.1   
              AZQ_Ysigma = 0.1   
                 G1_gate = 0 0 -100.0000 100.0000
                 G2_gate = 0 0 -100.0000 100.0000
                 G3_gate = 0 0 -100.0000 100.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 0 0,R1,R1,R1                          ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 0 0,R1,R1,R1
            G3_component = 0 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = Dipole 1,0                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 8.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-35.00,-50.0,35.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = -7.83000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.73000e+01
                    row2 = +2.67000e-01,-1.28400e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+3.51000e+00
                    row3 = +0.00000e+00,+0.00000e+00,-4.26000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,-8.58000e-01,-2.73000e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 17.453               mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 17.453               mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 1.85545              Tm               ; magnetic rigidity
                   Angle = -45                  degrees          
                  Radius = 2.6                  m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = Wedge,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 0,100,2.7,0,1                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.001                               ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[W1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W1_WedgeSettings]
             ProfileMode = 1                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 2                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = 0.05936              mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = NULL
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = Dipole 2,0                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 10.000000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-10.00,-50.0,10.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-10.00,-50.0,10.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = -2.56100e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+4.43000e+01
                    row2 = +4.00000e-01,-3.89000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-5.56000e+00
                    row3 = +0.00000e+00,+0.00000e+00,-4.32000e-01,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,-3.20000e-01,-2.40000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 20.265               mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 6                    mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 1.78925              Tm               ; magnetic rigidity
                   Angle = -45                  degrees          
                  Radius = 2.003                m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = Material 1,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,300,2.33,0,1                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.2                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 0,12.3,0,ns                           ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 0,8,9,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = Material 2,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,250,2.33,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.2,0.3          ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = Material 3,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,350,2.33,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.2,0.3          ns,mm,mm         ; Time&X&Y space

[M3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M3_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M4 - Material ======================================}

[M4_General]
                    Name = Material 4,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M4_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,500,2.33,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.1                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.2,0.3          ns,mm,mm         ; Time&X&Y space

[M4_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M4_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M4_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M5 - Material ======================================}

[M5_General]
                    Name = Material 5,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M5_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,2.33,0,0                          ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.1                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.2,0.3          ns,mm,mm         ; Time&X&Y space

[M5_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M5_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M5_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M6 - Material ======================================}

[M6_General]
                    Name = Material 6,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M6_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,2.33,0,0                          ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.1                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.2,0.3          ns,mm,mm         ; Time&X&Y space

[M6_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M6_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M6_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M7 - Material ======================================}

[M7_General]
                    Name = Material 7,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M7_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,2.33,0,0                          ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.1                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.2,0.3          ns,mm,mm         ; Time&X&Y space

[M7_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M7_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M7_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= Calculations ======================================}

[Calculations]
40K  19+ 19+ =8.7320e+00,8.7320e+00,0,8.7320e+00,1.6737e+00,1.6737e+00,2.7197e-05,4.0801e+01,7.6059e-01,9.9737e-01,1,1,1,1,9.9737e-01,1,1,1,1,1,1,1,1,1,1,1,2.5440e-04,3.9702e-04,1,8.0048e-01,8.0048e-01,9.9840e-01,1,1,1,1,9.9840e-01,1,1,1.0736e-01,1.4653e-01,1,8.1241e-01,9.0185e-01,9.9595e-01,1,1,1,1,9.9595e-01,1,1,9.9653e-01,1,1,1,1,9.9653e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
39K  19+ 19+ =6.3321e+03,6.3321e+03,0,6.3321e+03,7.9141e-01,7.9141e-01,4.1709e-02,4.0738e+01,8.0611e-01,9.9738e-01,1,1,1,1,9.9738e-01,1,1,1,1,1,1,1,1,1,1,1,7.3170e-02,2.7847e-01,1,5.1260e-01,5.1260e-01,9.9843e-01,1,1,1,1,9.9843e-01,1,1,5.7242e-01,7.8600e-01,1,8.2133e-01,8.8669e-01,9.9603e-01,1,1,1,1,9.9603e-01,1,1,9.9657e-01,1,1,1,1,9.9657e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
38K  19+ 19+ =5.1497e+03,5.1497e+03,0,5.1497e+03,2.5250e-01,2.5250e-01,1.0632e-01,4.0601e+01,1.0834e+00,9.9740e-01,1,1,1,1,9.9740e-01,1,1,1,1,1,1,1,1,1,1,1,1.9838e-01,8.5958e-01,1,4.8041e-01,4.8041e-01,9.9845e-01,1,1,1,1,9.9845e-01,1,1,5.3816e-01,7.0058e-01,1,8.6798e-01,8.8500e-01,9.9608e-01,1,1,1,1,9.9608e-01,1,1,9.9662e-01,1,1,1,1,9.9662e-01,1,1,1.5546e-01,1,1,1,1,9.9582e-01,1,1.5612e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
37K  19+ 19+ =3.6424e+02,3.6424e+02,0,3.6424e+02,4.8254e-02,4.8254e-02,3.9350e-02,4.0456e+01,1.3331e+00,9.9741e-01,1,1,1,1,9.9741e-01,1,1,1,1,1,1,1,1,1,1,1,5.7842e-02,2.8339e-01,1,4.5178e-01,4.5178e-01,9.9848e-01,1,1,1,1,9.9848e-01,1,1,6.8310e-01,9.2035e-01,1,8.3939e-01,8.8424e-01,9.9615e-01,1,1,1,1,9.9615e-01,1,1,9.9667e-01,1,1,1,1,9.9667e-01,1,1,2.4220e-01,1,1,1,1,9.9582e-01,1,2.4321e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
36K  19+ 19+ =1.8588e+00,1.8588e+00,0,1.8588e+00,4.6508e-03,4.6508e-03,2.0835e-03,4.0303e+01,1.5513e+00,9.9742e-01,1,1,1,1,9.9742e-01,1,1,1,1,1,1,1,1,1,1,1,3.8706e-03,2.1508e-02,1,4.2422e-01,4.2422e-01,9.9851e-01,1,1,1,1,9.9851e-01,1,1,5.4049e-01,7.4578e-01,1,8.1852e-01,8.8541e-01,9.9624e-01,1,1,1,1,9.9624e-01,1,1,9.9673e-01,1,1,1,1,9.9673e-01,1,1,9.9539e-01,1,1,1,1,9.9575e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
35K  19+ 19+ =1.1468e-04,1.1468e-04,0,1.1468e-04,1.7579e-04,1.7579e-04,3.4007e-06,4.0140e+01,1.7520e+00,9.9743e-01,1,1,1,1,9.9743e-01,1,1,1,1,1,1,1,1,1,1,1,8.9721e-05,5.5999e-04,1,4.0028e-01,4.0028e-01,9.9855e-01,1,1,1,1,9.9855e-01,1,1,3.8056e-02,5.3729e-02,1,7.9794e-01,8.8763e-01,9.9634e-01,1,1,1,1,9.9634e-01,1,1,9.9681e-01,1,1,1,1,9.9681e-01,1,1,9.9549e-01,1,1,1,1,9.9549e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
38Ar 18+ 18+ =2.1267e+03,2.1267e+03,0,2.1267e+03,7.9141e+01,7.9141e+01,1.4009e-04,4.1145e+01,1.0109e+00,9.9739e-01,1,1,1,1,9.9739e-01,1,1,1,1,1,1,1,1,1,1,1,2.6051e-04,1.1074e-03,1,4.8503e-01,4.8503e-01,9.9843e-01,1,1,1,1,9.9843e-01,1,1,5.3999e-01,7.8464e-01,1,7.7880e-01,8.8367e-01,9.9602e-01,1,1,1,1,9.9602e-01,1,1,9.9658e-01,1,1,1,1,9.9658e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
37Ar 18+ 18+ =1.6436e+05,1.6436e+05,0,1.6436e+05,2.5250e+01,2.5250e+01,3.3933e-02,4.1017e+01,1.2659e+00,9.9740e-01,1,1,1,1,9.9740e-01,1,1,1,1,1,1,1,1,1,1,1,5.0623e-02,2.4555e-01,1,4.5404e-01,4.5404e-01,9.9846e-01,1,1,1,1,9.9846e-01,1,1,6.7311e-01,9.1270e-01,1,8.3388e-01,8.8441e-01,9.9610e-01,1,1,1,1,9.9610e-01,1,1,9.9663e-01,1,1,1,1,9.9663e-01,1,1,3.8400e-01,1,1,1,1,9.9587e-01,1,3.8560e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
36Ar 18+ 18+ =7.0964e+04,7.0964e+04,0,7.0964e+04,4.8254e+00,4.8254e+00,7.6664e-02,4.0880e+01,1.4771e+00,9.9741e-01,1,1,1,1,9.9741e-01,1,1,1,1,1,1,1,1,1,1,1,1.3433e-01,7.2394e-01,1,4.3076e-01,4.3076e-01,9.9849e-01,1,1,1,1,9.9849e-01,1,1,5.7306e-01,7.5416e-01,1,8.5894e-01,8.8466e-01,9.9617e-01,1,1,1,1,9.9617e-01,1,1,9.9668e-01,1,1,1,1,9.9668e-01,1,1,5.6972e-01,1,1,1,1,9.9573e-01,1,5.7217e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
35Ar 18+ 18+ =2.1537e+03,2.1537e+03,0,2.1537e+03,4.6508e-01,4.6508e-01,2.4140e-02,4.0736e+01,1.6691e+00,9.9742e-01,1,1,1,1,9.9742e-01,1,1,1,1,1,1,1,1,1,1,1,5.6801e-02,3.4786e-01,1,4.0409e-01,4.0409e-01,9.9851e-01,1,1,1,1,9.9851e-01,1,1,4.2673e-01,5.7058e-01,1,8.4601e-01,8.8403e-01,9.9624e-01,1,1,1,1,9.9624e-01,1,1,9.9674e-01,1,1,1,1,9.9674e-01,1,1,8.9992e-01,1,1,1,1,9.9575e-01,1,9.0376e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
34Ar 18+ 18+ =1.8076e+00,1.8076e+00,0,1.8076e+00,2.8675e-02,2.8675e-02,3.2861e-04,4.0585e+01,1.8889e+00,9.9743e-01,1,1,1,1,9.9743e-01,1,1,1,1,1,1,1,1,1,1,1,7.1681e-03,4.9033e-02,1,3.8235e-01,3.8235e-01,9.9855e-01,1,1,1,1,9.9855e-01,1,1,4.6028e-02,6.2657e-02,1,8.2925e-01,8.8588e-01,9.9633e-01,1,1,1,1,9.9633e-01,1,1,9.9681e-01,1,1,1,1,9.9681e-01,1,1,9.9552e-01,1,1,1,1,9.9552e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
33Ar 18+ 18+ =2.1694e-08,2.1694e-08,0,2.1694e-08,1.7806e-03,1.7806e-03,6.3512e-11,4.0422e+01,2.0648e+00,9.9744e-01,1,1,1,1,9.9744e-01,1,1,1,1,1,1,1,1,1,1,1,3.3143e-04,2.5084e-03,1,3.6349e-01,3.6349e-01,9.9859e-01,1,1,1,1,9.9859e-01,1,1,1.9240e-07,2.6659e-07,1,8.1267e-01,8.8803e-01,9.9642e-01,1,1,1,1,9.9642e-01,1,1,9.9688e-01,1,1,1,1,9.9688e-01,1,1,9.9553e-01,1,1,1,1,9.9553e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
36Cl 17+ 17+ =1.4065e+04,1.4065e+04,0,1.4065e+04,9.0095e+01,9.0095e+01,8.1384e-04,4.1426e+01,1.4553e+00,9.9740e-01,1,1,1,1,9.9740e-01,1,1,1,1,1,1,1,1,1,1,1,1.2060e-03,6.4347e-03,1,4.3292e-01,4.3292e-01,9.9845e-01,1,1,1,1,9.9845e-01,1,1,6.7764e-01,9.5538e-01,1,8.0454e-01,8.8161e-01,9.9609e-01,1,1,1,1,9.9609e-01,1,1,9.9664e-01,1,1,1,1,9.9664e-01,1,1,4.6890e-03,1,1,1,1,9.9603e-01,1,4.7077e-03,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
35Cl 17+ 17+ =1.2119e+05,1.2119e+05,0,1.2119e+05,3.9336e+01,3.9336e+01,1.6061e-02,4.1298e+01,1.6463e+00,9.9741e-01,1,1,1,1,9.9741e-01,1,1,1,1,1,1,1,1,1,1,1,3.5943e-02,2.1607e-01,1,4.0786e-01,4.0786e-01,9.9849e-01,1,1,1,1,9.9849e-01,1,1,4.4868e-01,6.0635e-01,1,8.3809e-01,8.8292e-01,9.9617e-01,1,1,1,1,9.9617e-01,1,1,9.9669e-01,1,1,1,1,9.9669e-01,1,1,7.6098e-01,1,1,1,1,9.9572e-01,1,7.6425e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
34Cl 17+ 17+ =4.1458e+04,4.1458e+04,0,4.1458e+04,8.9434e+00,8.9434e+00,2.4165e-02,4.1163e+01,1.8248e+00,9.9742e-01,1,1,1,1,9.9742e-01,1,1,1,1,1,1,1,1,1,1,1,9.0911e-02,6.1274e-01,1,3.8518e-01,3.8518e-01,9.9852e-01,1,1,1,1,9.9852e-01,1,1,2.6689e-01,3.5395e-01,1,8.5369e-01,8.8328e-01,9.9625e-01,1,1,1,1,9.9625e-01,1,1,9.9675e-01,1,1,1,1,9.9675e-01,1,1,8.7501e-01,1,1,1,1,9.9566e-01,1,8.7882e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
33Cl 17+ 17+ =4.2866e+02,4.2866e+02,0,4.2866e+02,9.3549e-01,9.3549e-01,2.3887e-03,4.1019e+01,2.0086e+00,9.9743e-01,1,1,1,1,9.9743e-01,1,1,1,1,1,1,1,1,1,1,1,5.0687e-02,3.7804e-01,1,3.6617e-01,3.6617e-01,9.9855e-01,1,1,1,1,9.9855e-01,1,1,4.7317e-02,6.3105e-02,1,8.4795e-01,8.8426e-01,9.9633e-01,1,1,1,1,9.9633e-01,1,1,9.9681e-01,1,1,1,1,9.9681e-01,1,1,9.9555e-01,1,1,1,1,9.9555e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
32Cl 17+ 17+ =6.8765e-05,6.8765e-05,0,6.8765e-05,5.2019e-02,5.2019e-02,6.8911e-09,4.0866e+01,2.1745e+00,9.9744e-01,1,1,1,1,9.9744e-01,1,1,1,1,1,1,1,1,1,1,1,8.9665e-03,7.3941e-02,1,3.4823e-01,3.4823e-01,9.9859e-01,1,1,1,1,9.9859e-01,1,1,7.7160e-07,1.0426e-06,1,8.3501e-01,8.8630e-01,9.9641e-01,1,1,1,1,9.9641e-01,1,1,9.9688e-01,1,1,1,1,9.9688e-01,1,1,9.9556e-01,1,1,1,1,9.9556e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
35S  16+ 16+ =3.5244e+01,3.5244e+01,0,3.5244e+01,7.6751e+01,7.6751e+01,2.3938e-06,4.1826e+01,1.6683e+00,9.9740e-01,1,1,1,1,9.9740e-01,1,1,1,1,1,1,1,1,1,1,1,3.6491e-06,2.1520e-05,1,4.1178e-01,4.1178e-01,9.9845e-01,1,1,1,1,9.9845e-01,1,1,6.5874e-01,9.8912e-01,1,7.6409e-01,8.7161e-01,9.9608e-01,1,1,1,1,9.9608e-01,1,1,9.9665e-01,1,1,1,1,9.9665e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
34S  16+ 16+ =1.5204e+04,1.5204e+04,0,1.5204e+04,8.0688e+01,8.0688e+01,9.8230e-04,4.1706e+01,1.8501e+00,9.9741e-01,1,1,1,1,9.9741e-01,1,1,1,1,1,1,1,1,1,1,1,1.9539e-03,1.2097e-02,1,4.0189e-01,4.0189e-01,9.9848e-01,1,1,1,1,9.9848e-01,1,1,5.0481e-01,7.0008e-01,1,8.1934e-01,8.8007e-01,9.9616e-01,1,1,1,1,9.9616e-01,1,1,9.9670e-01,1,1,1,1,9.9670e-01,1,1,7.5581e-01,1,1,1,1,9.9584e-01,1,7.5897e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
33S  16+ 16+ =4.0438e+04,4.0438e+04,0,4.0438e+04,4.4545e+01,4.4545e+01,4.7324e-03,4.1582e+01,2.0107e+00,9.9742e-01,1,1,1,1,9.9742e-01,1,1,1,1,1,1,1,1,1,1,1,2.6133e-02,1.9135e-01,1,3.6956e-01,3.6956e-01,9.9851e-01,1,1,1,1,9.9851e-01,1,1,1.8182e-01,2.4553e-01,1,8.4001e-01,8.8158e-01,9.9625e-01,1,1,1,1,9.9625e-01,1,1,9.9676e-01,1,1,1,1,9.9676e-01,1,1,9.1097e-01,1,1,1,1,9.9564e-01,1,9.1496e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
32S  16+ 16+ =6.1793e+03,6.1793e+03,0,6.1793e+03,1.1999e+01,1.1999e+01,2.6845e-03,4.1448e+01,2.1785e+00,9.9743e-01,1,1,1,1,9.9743e-01,1,1,1,1,1,1,1,1,1,1,1,6.4396e-02,5.2206e-01,1,3.5121e-01,3.5121e-01,9.9855e-01,1,1,1,1,9.9855e-01,1,1,4.1856e-02,5.5731e-02,1,8.5055e-01,8.8298e-01,9.9632e-01,1,1,1,1,9.9632e-01,1,1,9.9682e-01,1,1,1,1,9.9682e-01,1,1,9.9558e-01,1,1,1,1,9.9558e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
31S  16+ 16+ =3.5164e-01,3.5164e-01,0,3.5164e-01,1.4245e+00,1.4245e+00,1.2869e-06,4.1305e+01,2.3416e+00,9.9744e-01,1,1,1,1,9.9744e-01,1,1,1,1,1,1,1,1,1,1,1,4.3087e-02,3.8384e-01,1,3.3504e-01,3.3504e-01,9.9858e-01,1,1,1,1,9.9858e-01,1,1,2.9985e-05,3.9962e-05,1,8.4792e-01,8.8492e-01,9.9640e-01,1,1,1,1,9.9640e-01,1,1,9.9688e-01,1,1,1,1,9.9688e-01,1,1,9.9559e-01,1,1,1,1,9.9559e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
33P  15+ 15+ =1.5849e+02,1.5849e+02,0,1.5849e+02,4.7528e+01,4.7528e+01,1.7384e-05,4.2107e+01,2.0653e+00,9.9741e-01,1,1,1,1,9.9741e-01,1,1,1,1,1,1,1,1,1,1,1,2.7926e-05,2.0094e-04,1,3.7279e-01,3.7279e-01,9.9847e-01,1,1,1,1,9.9847e-01,1,1,6.2507e-01,9.0585e-01,1,7.9342e-01,8.6970e-01,9.9615e-01,1,1,1,1,9.9615e-01,1,1,9.9670e-01,1,1,1,1,9.9670e-01,1,1,5.2097e-01,1,1,1,1,9.9602e-01,1,5.2305e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
32P  15+ 15+ =4.5074e+03,4.5074e+03,0,4.5074e+03,6.6491e+01,6.6491e+01,3.5339e-04,4.1990e+01,2.2072e+00,9.9742e-01,1,1,1,1,9.9742e-01,1,1,1,1,1,1,1,1,1,1,1,1.9071e-03,1.5180e-02,1,3.5445e-01,3.5445e-01,9.9851e-01,1,1,1,1,9.9851e-01,1,1,1.8606e-01,2.5663e-01,1,8.2492e-01,8.7888e-01,9.9623e-01,1,1,1,1,9.9623e-01,1,1,9.9676e-01,1,1,1,1,9.9676e-01,1,1,9.0931e-01,1,1,1,1,9.9571e-01,1,9.1323e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
31P  15+ 15+ =6.6157e+03,6.6157e+03,0,6.6157e+03,4.4462e+01,4.4462e+01,7.7567e-04,4.1866e+01,2.3740e+00,9.9743e-01,1,1,1,1,9.9743e-01,1,1,1,1,1,1,1,1,1,1,1,1.9492e-02,1.7069e-01,1,3.3793e-01,3.3793e-01,9.9854e-01,1,1,1,1,9.9854e-01,1,1,3.9955e-02,5.3956e-02,1,8.4071e-01,8.8080e-01,9.9631e-01,1,1,1,1,9.9631e-01,1,1,9.9682e-01,1,1,1,1,9.9682e-01,1,1,9.9558e-01,1,1,1,1,9.9565e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
30P  15+ 15+ =1.7509e+01,1.7509e+01,0,1.7509e+01,1.4292e+01,1.4292e+01,6.3865e-06,4.1735e+01,2.5223e+00,9.9744e-01,1,1,1,1,9.9744e-01,1,1,1,1,1,1,1,1,1,1,1,4.5948e-02,4.5103e-01,1,3.1918e-01,3.1918e-01,9.9858e-01,1,1,1,1,9.9858e-01,1,1,1.3955e-04,1.8637e-04,1,8.4818e-01,8.8280e-01,9.9639e-01,1,1,1,1,9.9639e-01,1,1,9.9688e-01,1,1,1,1,9.9688e-01,1,1,9.9563e-01,1,1,1,1,9.9563e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
31Si 14+ 14+ =6.7373e+01,6.7373e+01,0,6.7373e+01,2.9946e+01,2.9946e+01,1.1728e-05,4.2388e+01,2.4231e+00,9.9742e-01,1,1,1,1,9.9742e-01,1,1,1,1,1,1,1,1,1,1,1,5.0715e-05,4.3728e-04,1,3.4056e-01,3.4056e-01,9.9850e-01,1,1,1,1,9.9850e-01,1,1,2.3220e-01,3.3487e-01,1,7.9869e-01,8.6819e-01,9.9622e-01,1,1,1,1,9.9622e-01,1,1,9.9677e-01,1,1,1,1,9.9677e-01,1,1,8.9583e-01,1,1,1,1,9.9584e-01,1,8.9957e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
30Si 14+ 14+ =8.6265e+02,8.6265e+02,0,8.6265e+02,5.1304e+01,5.1304e+01,8.7655e-05,4.2274e+01,2.5909e+00,9.9743e-01,1,1,1,1,9.9743e-01,1,1,1,1,1,1,1,1,1,1,1,1.8862e-03,1.8195e-02,1,3.2197e-01,3.2197e-01,9.9854e-01,1,1,1,1,9.9854e-01,1,1,4.6660e-02,6.4097e-02,1,8.2927e-01,8.7783e-01,9.9630e-01,1,1,1,1,9.9630e-01,1,1,9.9683e-01,1,1,1,1,9.9683e-01,1,1,9.6949e-01,1,1,1,1,9.9570e-01,1,9.7368e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
29Si 14+ 14+ =8.8905e+01,8.8905e+01,0,8.8905e+01,4.2268e+01,4.2268e+01,1.0965e-05,4.2152e+01,2.7223e+00,9.9745e-01,1,1,1,1,9.9745e-01,1,1,1,1,1,1,1,1,1,1,1,1.4354e-02,1.5163e-01,1,3.0768e-01,3.0768e-01,9.9858e-01,1,1,1,1,9.9858e-01,1,1,7.6695e-04,1.0361e-03,1,8.4092e-01,8.8023e-01,9.9638e-01,1,1,1,1,9.9638e-01,1,1,9.9688e-01,1,1,1,1,9.9688e-01,1,1,9.9568e-01,1,1,1,1,9.9568e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
30Al 13+ 13+ =3.6759e-05,3.6759e-05,0,3.6759e-05,6.1550e+00,6.1550e+00,3.1133e-11,4.2776e+01,2.6633e+00,9.9742e-01,1,1,1,1,9.9742e-01,1,1,1,1,1,1,1,1,1,1,1,9.6165e-09,9.1157e-08,1,3.2480e-01,3.2480e-01,9.9849e-01,1,1,1,1,9.9849e-01,1,1,3.2507e-03,5.1792e-03,1,7.2617e-01,8.6433e-01,9.9621e-01,1,1,1,1,9.9621e-01,1,1,9.9677e-01,1,1,1,1,9.9677e-01,1,1,9.7665e-01,1,1,1,1,9.9598e-01,1,9.8060e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
29Al 13+ 13+ =2.0285e+01,2.0285e+01,0,2.0285e+01,1.8782e+01,1.8782e+01,5.6301e-06,4.2674e+01,2.8339e+00,9.9743e-01,1,1,1,1,9.9743e-01,1,1,1,1,1,1,1,1,1,1,1,8.2367e-05,8.5517e-04,1,3.1035e-01,3.1035e-01,9.9853e-01,1,1,1,1,9.9853e-01,1,1,6.8631e-02,9.6365e-02,1,8.2182e-01,8.6661e-01,9.9629e-01,1,1,1,1,9.9629e-01,1,1,9.9683e-01,1,1,1,1,9.9683e-01,1,1,9.5929e-01,1,1,1,1,9.9576e-01,1,9.6338e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
28Al 13+ 13+ =4.1114e+01,4.1114e+01,0,4.1114e+01,3.7888e+01,3.7888e+01,5.6568e-06,4.2560e+01,2.9464e+00,9.9745e-01,1,1,1,1,9.9745e-01,1,1,1,1,1,1,1,1,1,1,1,1.6092e-03,1.8390e-02,1,2.9581e-01,2.9581e-01,9.9857e-01,1,1,1,1,9.9857e-01,1,1,3.5294e-03,4.8416e-03,1,8.3152e-01,8.7669e-01,9.9637e-01,1,1,1,1,9.9637e-01,1,1,9.9689e-01,1,1,1,1,9.9689e-01,1,1,9.9574e-01,1,1,1,1,9.9574e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
28Mg 12+ 12+ =4.2733e-03,4.2733e-03,0,4.2733e-03,3.2953e+00,3.2953e+00,6.7601e-09,4.3055e+01,3.0294e+00,9.9744e-01,1,1,1,1,9.9744e-01,1,1,1,1,1,1,1,1,1,1,1,2.9243e-07,3.2851e-06,1,2.9836e-01,2.9836e-01,9.9852e-01,1,1,1,1,9.9852e-01,1,1,2.3210e-02,3.4694e-02,1,7.7571e-01,8.6243e-01,9.9628e-01,1,1,1,1,9.9628e-01,1,1,9.9684e-01,1,1,1,1,9.9684e-01,1,1,9.9581e-01,1,1,1,1,9.9582e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
27Mg 12+ 12+ =2.3340e+00,2.3340e+00,0,2.3340e+00,1.1556e+01,1.1556e+01,1.0529e-06,4.2956e+01,3.1924e+00,9.9745e-01,1,1,1,1,9.9745e-01,1,1,1,1,1,1,1,1,1,1,1,8.5991e-05,1.0541e-03,1,2.8562e-01,2.8562e-01,9.9856e-01,1,1,1,1,9.9856e-01,1,1,1.2293e-02,1.7208e-02,1,8.2575e-01,8.6517e-01,9.9636e-01,1,1,1,1,9.9636e-01,1,1,9.9689e-01,1,1,1,1,9.9689e-01,1,1,9.9422e-01,1,1,1,1,9.9584e-01,1,9.9837e-01,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
26Mg 12+ 12+ =2.3930e-03,2.3930e-03,0,2.3930e-03,2.7031e+01,2.7031e+01,4.6150e-10,4.2849e+01,3.3685e+00,9.9746e-01,1,1,1,1,9.9746e-01,1,1,1,1,1,1,1,1,1,1,1,1.4428e-03,1.9615e-02,1,2.7121e-01,2.7121e-01,9.9860e-01,1,1,1,1,9.9860e-01,1,1,3.2113e-07,4.4317e-07,1,8.3361e-01,8.6926e-01,9.9643e-01,1,1,1,1,9.9643e-01,1,1,9.9695e-01,1,1,1,1,9.9695e-01,1,1,9.9581e-01,1,1,1,1,9.9581e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
26Na 11+ 11+ =8.4988e-05,8.4988e-05,0,8.4988e-05,1.7407e+00,1.7407e+00,2.5452e-10,4.3334e+01,3.3933e+00,9.9745e-01,1,1,1,1,9.9745e-01,1,1,1,1,1,1,1,1,1,1,1,7.7520e-07,1.0374e-05,1,2.7336e-01,2.7336e-01,9.9855e-01,1,1,1,1,9.9855e-01,1,1,3.2964e-04,4.9227e-04,1,7.7833e-01,8.6036e-01,9.9635e-01,1,1,1,1,9.9635e-01,1,1,9.9690e-01,1,1,1,1,9.9690e-01,1,1,9.9581e-01,1,1,1,1,9.9581e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
25Na 11+ 11+ =1.2755e-02,1.2755e-02,0,1.2755e-02,6.9920e+00,6.9920e+00,9.5096e-09,4.3240e+01,3.5746e+00,9.9746e-01,1,1,1,1,9.9746e-01,1,1,1,1,1,1,1,1,1,1,1,8.6836e-05,1.1624e-03,1,2.7333e-01,2.7333e-01,9.9859e-01,1,1,1,1,9.9859e-01,1,1,1.0995e-04,1.5372e-04,1,8.2806e-01,8.6376e-01,9.9642e-01,1,1,1,1,9.9642e-01,1,1,9.9696e-01,1,1,1,1,9.9696e-01,1,1,9.9588e-01,1,1,1,1,9.9588e-01,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
