Version 9.8.54

{============================= Main Part ======================================}
[general]
                    File = G:\Solenoid.lpp
                    Date = 27-03-2014
                    Time = 13:22:49
           Configuration = other\one_dipole.lcn
             Optionsfile = A1900_2013_myopt.lopt
                   Title = one dipole
          BlockStructure = SLSSSSMM

[settings]
                   A,Z,Q = 32S 16+                               ; Mass ElementName Charge+ Beam
                  Energy = 23                   MeV/u            
               Intensity = 10                   pnA              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 32Ar                                  ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 1                    (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 5                    (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 1                    (±)mm            ; one-half the vertical beam extent (y)
                      BF = 5                    (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.1                  (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = 0                    degrees          
                  ShapeX = 32769
                  ShapeT = 32769
                  ShapeY = 32769
                  ShapeF = 32769
                  ShapeL = 32769
                  ShapeD = 32769

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 32                                    ; Number of points in distribution
        NP charge states = 32                                    ; Number of points in distribution
                NP wedge = 32                                    ; Number of points in distribution
           Charge states = No                                    ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,2,1,3                               ; Nomer,Z,Atoms,Mass
        Target thickness = 4,100,0.0006248,0,1                   ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 1                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 2                                     ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 1                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 1                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 1                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 1                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-11    
               FisCS_TKE = 1e-8     
                      N0 = 83                                    ; default 82
                     dU0 = -2.65                                 ; default -2.5
                      C0 = 0.7                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -3.8                                  ; default -5.5
                      C1 = 0.15                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-5     
                 BeamInd = 1e-20    
               BeamTotal = 1e-20    

[convolution]
        Convolution mode = 1                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 3     
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
          AvoidUnboundCS = 1                                     ; 1-Yes, 0-No
       ProtectedChannels = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 1                                     ; 0 - no, 1 - use
         DissipationBeta = 1                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 0                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 0                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       

[evapauto]
                  tun_a0 = -0.61392
                  tun_a1 = 0.44559
                  tun_a2 = 0.12008
                 A_Bound = 300                                   ; mass
               A_Pairing =   1                                   ; mass

[plot]
            Start target = RF                                    ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = T1
         dE-detector-1st = M4
         dE-detector-2nd = M5
            TKE-detector = M4
                PlotBrho = S8
               PlotWedge = D1
              X-detector = M4
              Y-detector = M4
                 Tilting = M1
                 Stopper = M2
                RO_Wedge = n
          ConditionBlock = A0
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 2
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
           LowEx_nucleus = 39Ar                                  ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 34S                                   ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 28Si                                  ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 8.000e+02 250.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 16
                   Dr_n0 = 0
                   Dr_n1 = 16

[cross sections]

[previous]
                 Lowerst =  1H                                   ; Mass ElementName Charge+ Beam
                 Highest = 35Ar                                  ; Mass ElementName Charge+ Beam

[MC_options]
                   dXsel = 14
                   dYsel = 5
                  dAZQ_X = 3
                  dAZQ_Y = 2
                  dVEL_X = 1
                  dVEL_Y = 0
               dIso_mode = 0
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 0
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 1
                  CS_use = 1
           envelope_show = 0
                use_bore = 1
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
              AZQ_Xsigma = 0.12  
              AZQ_Ysigma = 0.08  
                 G1_gate = 0 1 -1.0000 1.0000
                 G2_gate = 1 2 -14.0000 14.0000
                 G3_gate = 0 1 -2.0000 2.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 5 0,S2,R1,R1                          ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 5 0,S4,R1,R1
            G3_component = 5 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = Slits 1,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-2.00,-50.0,2.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-2.00,-50.0,2.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK L1 - Solenoid ======================================}

[L1_General]
                    Name = Solenoid 1,0                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 1.954000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[L1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[L1_optics]
                    row1 = -3.05468e-01,+4.30304e-02,-8.24048e-01,+1.16081e-01,+0.00000e+00,+0.00000e+00
                    row2 = -6.39099e-01,-3.05468e-01,-1.72407e+00,-8.24048e-01,+0.00000e+00,+0.00000e+00
                    row3 = +8.24048e-01,-1.16081e-01,-3.05468e-01,+4.30304e-02,+0.00000e+00,+0.00000e+00
                    row4 = +1.72407e+00,+8.24048e-01,-6.39099e-01,-3.05468e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[L1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[L1_SolenoidSettings]
      UseSoftCorrections = 0                                     ; 1 - Yes / 0 - No
               Direction = 1                                     ; +1 positive, -1 negative
                  Sstate = 0                                     ; 0-B_field_max, 1-Current
                 Current = 70.834781            A                
               BfieldMax = 4.25                 T                
              CoilLength = 0.62                 m                
               EffRadius = 0.2123               m                
              LengthDraw = 1                    m                
                    Bore = 0.15                 m                
               FirstHalf = 0.977                m                
              SecondHalf = 0.977                m                
              MAconstant = 0.03636              T/A              
         TuningParameter = 4
         UseGlobalMatrix = 1


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = Slits 2,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-2.00,-50.0,2.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-2.00,-50.0,2.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = drift 1,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.500000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.00000e+00,+5.00000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+5.00000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = Blocker,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S5 - Drift ======================================}

[S5_General]
                    Name = drift 2,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.250000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S5_optics]
                    row1 = +1.00000e+00,+2.50000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.50000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S5_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S5_DriftSettings]
                    Mode = 1                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = dE,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,50,2.321,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 168867279,-20.00,-50.0,20.00,50.0     ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 25690373,-20.00,-50.0,20.00,50.0      ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = TKE,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 4,1,2.33,0,0                          ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.1                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.2,0.3          ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= Calculations ======================================}

[Calculations]
34Ar 18+ =5.4733e-04,5.4733e-04,1,5.4733e-04,4.7250e-08,0,1.4777e-01,1.7476e+01,4.1557e-01,9.9882e-01,1,1,1,1,9.9882e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.6151e-01,3.8440e-01,4.2016e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
33Ar 18+ =7.0695e-01,7.0695e-01,1,7.0695e-01,5.8575e-05,0,1.5397e-01,1.7445e+01,5.3376e-01,9.9883e-01,1,1,1,1,9.9883e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.6828e-01,3.9940e-01,4.2133e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
32Ar 18+ =1.3391e+00,1.3391e+00,1,1.3391e+00,5.3493e-05,0,3.1935e-01,1.7414e+01,6.6337e-01,9.9885e-01,1,1,1,1,9.9885e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,3.4903e-01,5.8137e-01,6.0036e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
31Ar 18+ =5.7918e-04,5.7918e-04,1,5.7918e-04,8.3847e-09,0,8.8121e-01,1.7382e+01,7.8668e-01,9.9886e-01,1,1,1,1,9.9886e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,9.6309e-01,9.8137e-01,9.8137e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
34Cl 17+ =1.9502e-03,1.9502e-03,1,1.9502e-03,3.5052e-07,0,7.0979e-02,1.7581e+01,3.6922e-01,9.9880e-01,1,1,1,1,9.9880e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,7.7579e-02,2.5381e-01,3.0565e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
33Cl 17+ =4.6074e-01,4.6074e-01,1,4.6074e-01,1.0717e-04,0,5.4845e-02,1.7555e+01,5.1590e-01,9.9881e-01,1,1,1,1,9.9881e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,5.9944e-02,2.2491e-01,2.6652e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
32Cl 17+ =2.4589e+02,2.4589e+02,1,2.4589e+02,5.2251e-02,0,6.0034e-02,1.7527e+01,6.4498e-01,9.9883e-01,1,1,1,1,9.9883e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,6.5614e-02,2.3839e-01,2.7524e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
31Cl 17+ =7.9841e+01,7.9841e+01,1,7.9841e+01,1.0312e-02,0,9.8767e-02,1.7495e+01,7.1857e-01,9.9885e-01,1,1,1,1,9.9885e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.0795e-01,3.1123e-01,3.4683e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
33S  16+ =2.4518e+00,2.4518e+00,1,2.4518e+00,1.1069e-03,0,2.8257e-02,1.7657e+01,4.8509e-01,9.9880e-01,1,1,1,1,9.9880e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,3.0885e-02,1.5688e-01,1.9687e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
31S  16+ =1.7937e+04,1.7937e+04,1,1.7937e+04,8.0976e+00,0,2.8259e-02,1.7606e+01,7.0507e-01,9.9883e-01,1,1,1,1,9.9883e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,3.0885e-02,1.6074e-01,1.9214e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
30S  16+ =5.8268e+02,5.8268e+02,1,5.8268e+02,1.8943e-01,0,3.9240e-02,1.7577e+01,7.9962e-01,9.9884e-01,1,1,1,1,9.9884e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,4.2887e-02,1.9204e-01,2.2332e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
29S  16+ =5.0532e+00,5.0532e+00,1,5.0532e+00,8.4090e-04,0,7.6660e-02,1.7547e+01,8.9899e-01,9.9886e-01,1,1,1,1,9.9886e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,8.3783e-02,2.7339e-01,3.0646e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
28S  16+ =7.7846e-02,7.7846e-02,1,7.7846e-02,2.9289e-06,0,3.3906e-01,1.7514e+01,9.8765e-01,9.9888e-01,1,1,1,1,9.9888e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,3.7056e-01,6.0218e-01,6.1537e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
32P  15+ =1.0873e+03,1.0873e+03,1,1.0873e+03,9.6442e-01,0,1.4382e-02,1.7734e+01,5.8724e-01,9.9880e-01,1,1,1,1,9.9880e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.5719e-02,1.1026e-01,1.4256e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
31P  15+ =6.9363e+04,6.9363e+04,1,6.9363e+04,6.3659e+01,0,1.3900e-02,1.7710e+01,6.8111e-01,9.9881e-01,1,1,1,1,9.9881e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.5192e-02,1.0963e-01,1.3858e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
30P  15+ =2.3251e+05,2.3251e+05,1,2.3251e+05,1.9810e+02,0,1.4973e-02,1.7685e+01,7.7154e-01,9.9883e-01,1,1,1,1,9.9883e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.6364e-02,1.1534e-01,1.4188e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
29P  15+ =2.7948e+02,2.7948e+02,1,2.7948e+02,1.8965e-01,0,1.8800e-02,1.7658e+01,8.5513e-01,9.9884e-01,1,1,1,1,9.9884e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,2.0547e-02,1.3102e-01,1.5682e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
28P  15+ =1.4711e+03,1.4711e+03,1,1.4711e+03,6.5642e-01,0,2.8589e-02,1.7629e+01,9.4676e-01,9.9886e-01,1,1,1,1,9.9886e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,3.1246e-02,1.6401e-01,1.9051e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
27P  15+ =9.2271e-02,9.2271e-02,1,9.2271e-02,1.7132e-05,0,6.8708e-02,1.7601e+01,1.0505e+00,9.9888e-01,1,1,1,1,9.9888e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,7.5091e-02,2.6083e-01,2.8789e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
31Si 14+ =4.0064e+03,4.0064e+03,1,4.0064e+03,6.0841e+00,0,8.4006e-03,1.7809e+01,6.8586e-01,9.9879e-01,1,1,1,1,9.9879e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,9.1817e-03,8.3204e-02,1.1035e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
30Si 14+ =7.1965e+04,7.1965e+04,1,7.1965e+04,1.0924e+02,0,8.4043e-03,1.7787e+01,7.6380e-01,9.9881e-01,1,1,1,1,9.9881e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,9.1857e-03,8.4043e-02,1.0930e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
29Si 14+ =3.3782e+04,3.3782e+04,1,3.3782e+04,4.8218e+01,0,8.9377e-03,1.7764e+01,8.4534e-01,9.9882e-01,1,1,1,1,9.9882e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,9.7685e-03,8.7786e-02,1.1128e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
28Si 14+ =3.6741e+04,3.6741e+04,1,3.6741e+04,4.4157e+01,0,1.0614e-02,1.7739e+01,9.1943e-01,9.9884e-01,1,1,1,1,9.9884e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.1601e-02,9.6956e-02,1.1965e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
27Si 14+ =6.6433e+03,6.6433e+03,1,6.6433e+03,6.0762e+00,0,1.3948e-02,1.7712e+01,1.0093e+00,9.9886e-01,1,1,1,1,9.9886e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.5244e-02,1.1289e-01,1.3503e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
26Si 14+ =2.2305e+00,2.2305e+00,1,2.2305e+00,1.1769e-03,0,2.4177e-02,1.7683e+01,1.0824e+00,9.9888e-01,1,1,1,1,9.9888e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,2.6423e-02,1.5101e-01,1.7498e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
25Si 14+ =5.7373e-01,5.7373e-01,1,5.7373e-01,1.0435e-04,0,7.0139e-02,1.7652e+01,1.1722e+00,9.9889e-01,1,1,1,1,9.9889e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,7.6653e-02,2.6239e-01,2.9214e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
30Al 13+ =4.5823e+02,4.5823e+02,1,4.5823e+02,1.1243e+00,0,5.1991e-03,1.7884e+01,7.8342e-01,9.9879e-01,1,1,1,1,9.9879e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,5.6826e-03,6.4738e-02,8.7778e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
29Al 13+ =4.2718e+01,4.2718e+01,1,4.2718e+01,1.0421e-01,0,5.2294e-03,1.7864e+01,8.5520e-01,9.9881e-01,1,1,1,1,9.9881e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,5.7156e-03,6.5537e-02,8.7212e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
28Al 13+ =9.6796e+03,9.6796e+03,1,9.6796e+03,2.2262e+01,0,5.5467e-03,1.7842e+01,9.2706e-01,9.9882e-01,1,1,1,1,9.9882e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,6.0624e-03,6.8153e-02,8.8952e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
27Al 13+ =5.8932e+04,5.8932e+04,1,5.8932e+04,1.1969e+02,0,6.2814e-03,1.7819e+01,9.9743e-01,9.9884e-01,1,1,1,1,9.9884e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,6.8652e-03,7.3459e-02,9.3456e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
26Al 13+ =3.2048e+02,3.2048e+02,1,3.2048e+02,5.2794e-01,0,7.7440e-03,1.7794e+01,1.0736e+00,9.9886e-01,1,1,1,1,9.9886e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,8.4636e-03,8.2759e-02,1.0227e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
25Al 13+ =4.6330e+02,4.6330e+02,1,4.6330e+02,5.2253e-01,0,1.1311e-02,1.7767e+01,1.1385e+00,9.9887e-01,1,1,1,1,9.9887e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.2362e-02,1.0170e-01,1.2156e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
24Al 13+ =3.5263e+00,3.5263e+00,1,3.5263e+00,2.1246e-03,0,2.1174e-02,1.7738e+01,1.2223e+00,9.9889e-01,1,1,1,1,9.9889e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,2.3140e-02,1.4146e-01,1.6359e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
27Mg 12+ =2.5208e+02,2.5208e+02,1,2.5208e+02,8.7368e-01,0,3.6807e-03,1.7919e+01,1,9.9882e-01,1,1,1,1,9.9882e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,4.0229e-03,5.4724e-02,7.3512e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
26Mg 12+ =3.1975e+02,3.1975e+02,1,3.1975e+02,9.9663e-01,0,4.0929e-03,1.7898e+01,1.0596e+00,9.9884e-01,1,1,1,1,9.9884e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,4.4732e-03,5.8369e-02,7.6637e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
25Mg 12+ =1.9615e+03,1.9615e+03,1,1.9615e+03,5.2351e+00,0,4.7797e-03,1.7875e+01,1.1287e+00,9.9885e-01,1,1,1,1,9.9885e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,5.2239e-03,6.3970e-02,8.1661e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
24Mg 12+ =1.0050e+04,1.0050e+04,1,1.0050e+04,2.0104e+01,0,6.3769e-03,1.7850e+01,1.1807e+00,9.9887e-01,1,1,1,1,9.9887e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,6.9693e-03,7.5052e-02,9.2859e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
23Mg 12+ =4.5633e+00,4.5633e+00,1,4.5633e+00,6.0983e-03,0,9.5460e-03,1.7823e+01,1.2626e+00,9.9889e-01,1,1,1,1,9.9889e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,1.0433e-02,9.3445e-02,1.1165e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
22Mg 12+ =4.5537e-01,4.5537e-01,1,4.5537e-01,2.8114e-04,0,2.0663e-02,1.7794e+01,1.3304e+00,9.9891e-01,1,1,1,1,9.9891e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,2.2582e-02,1.4011e-01,1.6117e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
24Na 11+ =3.6663e+02,3.6663e+02,1,3.6663e+02,1.5346e+00,0,3.0478e-03,1.7955e+01,1.2017e+00,9.9885e-01,1,1,1,1,9.9885e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,3.3310e-03,5.0238e-02,6.6304e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
23Na 11+ =3.7113e-01,3.7113e-01,1,3.7113e-01,1.2574e-03,0,3.7652e-03,1.7932e+01,1.2525e+00,9.9887e-01,1,1,1,1,9.9887e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,4.1150e-03,5.6663e-02,7.2623e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
22Na 11+ =1.1778e+03,1.1778e+03,1,1.1778e+03,2.9326e+00,0,5.1236e-03,1.7907e+01,1.3111e+00,9.9889e-01,1,1,1,1,9.9889e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,5.5995e-03,6.7222e-02,8.3299e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
21Na 11+ =1.0748e+01,1.0748e+01,1,1.0748e+01,1.6011e-02,0,8.5639e-03,1.7880e+01,1.3631e+00,9.9891e-01,1,1,1,1,9.9891e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,9.3591e-03,8.8578e-02,1.0566e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
21Ne 10+ =2.2506e+02,2.2506e+02,1,2.2506e+02,9.1836e-01,0,3.1264e-03,1.7989e+01,1.3492e+00,9.9889e-01,1,1,1,1,9.9889e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,3.4168e-03,5.1535e-02,6.6301e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
20Ne 10+ =4.2652e-01,4.2652e-01,1,4.2652e-01,1.1843e-03,0,4.5943e-03,1.7963e+01,1.3800e+00,9.9891e-01,1,1,1,1,9.9891e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,5.0210e-03,6.3619e-02,7.8922e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
19Ne 10+ =3.1770e-01,3.1770e-01,1,3.1770e-01,5.2484e-04,0,7.7222e-03,1.7938e+01,1.4765e+00,9.9893e-01,1,1,1,1,9.9893e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,8.4391e-03,8.4207e-02,1.0022e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
18Ne 10+ =1.8574e-07,1.8574e-07,1,1.8574e-07,9.6528e-11,0,2.4547e-02,1.7907e+01,1.5315e+00,9.9895e-01,1,1,1,1,9.9895e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,2.6825e-02,1.5363e-01,1.7461e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
18F  9+ =3.0496e+01,3.0496e+01,1,3.0496e+01,9.8961e-02,0,3.9312e-03,1.8022e+01,1.4831e+00,9.9893e-01,1,1,1,1,9.9893e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,4.2962e-03,5.8804e-02,7.3059e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
17O  8+ =1.3634e-07,1.3634e-07,1,1.3634e-07,7.3444e-10,0,2.3682e-03,1.8103e+01,1.4809e+00,9.9893e-01,1,1,1,1,9.9893e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,2.5881e-03,4.4592e-02,5.8040e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
15O  8+ =1.2493e-01,1.2493e-01,1,1.2493e-01,1.9095e-04,0,8.3462e-03,1.8049e+01,1.5558e+00,9.9898e-01,1,1,1,1,9.9898e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,9.1206e-03,8.7896e-02,1.0377e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
14N  7+ =5.5513e-07,5.5513e-07,1,5.5513e-07,1.9566e-09,0,3.6195e-03,1.8134e+01,1.5308e+00,9.9898e-01,1,1,1,1,9.9898e-01,1,1,1,1,1,1,1,1,1,1,1,9.1603e-01,9.5709e-01,9.5709e-01,1,1,1,3.9554e-03,5.6355e-02,7.0187e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
