Version 10.1.77

{============================= Main Part ======================================}
[general]
                    File = C:\buffer\GANIL\LISE3_3Q_2018.lpp
                    Date = 17-02-2018
                    Time = 12:51:53
           Configuration = C:\buffer\GANIL\e_LISE3_2018_FIT.lcn
             Optionsfile = A1900_2009
                   Title = LISE3 Nominal 2018 FIT
          BlockStructure = DSMWDSMDSDSNSSSSSSFSSSSFFFFFSSFFMM

[settings]
                   A,Z,Q = 58Ni28+                               ; Mass ElementName Charge+ Beam
                  Energy = 74.5                 MeV/u            
               Intensity = 2500                 enA              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 56Ni                                  ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 1.5                  (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 3.3                  (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 1.5                  (±)mm            ; one-half the vertical beam extent (y)
                      BF = 3.3                  (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.05                 (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = 60                   degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1
               OptBeam_X = 1                    (±)mm            
               OptBeam_T = 20                   (±)mrad          
               OptBeam_Y = 1                    (±)mm            
               OptBeam_F = 20                   (±)mrad          
               OptBeam_L = 0                    (±)mm            
               OptBeam_D = 2                    (±)%             

[options]
               NP simple = 64                                    ; Number of points in distribution
        NP charge states = 64                                    ; Number of points in distribution
                NP wedge = 64                                    ; Number of points in distribution
           Charge states = No                                    ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,4,1,9.012                           ; Nomer,Z,Atoms,Mass
        Target thickness = 0,730,1.85,24,0                       ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 0                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 1                                     ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
                 AA_fast = 0                                     ; 1-Yes, 0-No
            BarrierShape = 1                                     ; 0-classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
            UseVanishing = 1                                     ; 1-Yes, 0-No
              VanishMode = 0                                     ; 0-Sierk, 1-Cohen
           NuclPotential = 1                                     ; 0-Bass, 1-WS
                   WS_V0 = 105                  MeV              
                   WS_R0 = 1.12                 fm               
                    WS_a = 0.75                 fm               
          FusDiffuseness = 1    
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 3                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 1                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 1                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 1                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 1                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-11    
               FisCS_TKE = 1e-8     
                      N0 = 83                                    ; default 82
                     dU0 = -2.65                                 ; default -2.5
                      C0 = 0.7                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -3.8                                  ; default -5.5
                      C1 = 0.15                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-5     
                 BeamInd = 1e-20    
               BeamTotal = 1e-20    

[convolution]
        Convolution mode = 1                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 3     
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
          AvoidUnboundCS = 1                                     ; 1-Yes, 0-No
       ProtectedChannels = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 1                                     ; 0 - no, 1 - use
         DissipationBeta = 1                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 0                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 0                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       

[evapauto]
                  tun_a0 = -0.61392
                  tun_a1 = 0.44559
                  tun_a2 = 0.12008
                 A_Bound = 300                                   ; mass
               A_Pairing =   1                                   ; mass

[plot]
            Start target = RF                                    ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = T1
         dE-detector-1st = M3
         dE-detector-2nd = M3
            TKE-detector = M3
                PlotBrho = D1
               PlotWedge = S2
              X-detector = M4
              Y-detector = M4
                 Tilting = M1
                 Stopper = n
                RO_Wedge = n
          ConditionBlock = A0
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 2
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
                Velocity = 1                                     ; Calculat fissile nuclei speed
           LowEx_nucleus = 47Ca                                  ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 42Ar                                  ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 36S                                   ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 8.000e+02 250.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 28
                   Dr_n0 = 0
                   Dr_n1 = 30

[cross sections]

[previous]
                 Lowerst =  1H                                   ; Mass ElementName Charge+ Beam
                 Highest = 61Cu                                  ; Mass ElementName Charge+ Beam

[MC_options]
                   dXsel = 0
                   dYsel = 1
                  dAZQ_X = 1
                  dAZQ_Y = 5
                  dVEL_X = 1
                  dVEL_Y = 0
               dIso_mode = 0
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 0
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 1
                  CS_use = 1
           envelope_show = 0
                use_bore = 0
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
              AZQ_Xsigma = 0.1   
              AZQ_Ysigma = 0.1   
                 G1_gate = 0 0 -100.0000 100.0000
                 G2_gate = 0 0 -100.0000 100.0000
                 G3_gate = 0 0 -100.0000 100.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 0 0,R1,R1,R1                          ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 0 0,R1,R1,R1
            G3_component = 0 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1

[Levmar_fit]
                   Niter = 1000                                  ; # iterations
               UseBounds = 1                                     ; yes-1, no-0
                 Example = 4                                     ; 0-15
                    opt0 = 1e-3     
                    opt1 = 1e-15    
                    opt2 = 1e-15    
                    opt3 = 1e-20    
                    opt4 = 1e-6     


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = DP1,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 7.463000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = LISE\LISE_D3.cal

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-40.00,-40.0,40.00,40.0             ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = -7.40480e-01,+3.45800e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.65343e+01
                    row2 = +8.66330e-01,-1.35444e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.59874e+00
                    row3 = +0.00000e+00,+0.00000e+00,-3.73336e+00,-2.16600e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-6.97630e-01,-2.71880e-01,+0.00000e+00,+0.00000e+00
                    row5 = -1.69891e+00,+2.24076e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-2.03560e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 18                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 17                   mrad             ; acceptance
                   Shape = 0                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 2.22597              Tm               ; magnetic rigidity
                   Angle = -45                  degrees          
                  Radius = 2.6                  m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Entrance Use 1/0
          UseExitFringeF = 1                                     ; Exit Use 1/0


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = Slits 31,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-49.00,-49.0,49.00,49.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = Detector,1                            ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,100,2.321,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.2                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = Wedge,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,4,1,9.012                           ; Nomer,Z,Atoms,Mass
               thickness = 4,1,1.848,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.3                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W1_WedgeSettings]
             ProfileMode = 2                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 0                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = -1.03309             mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = Slits 43
           DirectReverse = 0                                     ; 0-direct, 1-LISE reverse, 2-COSY
         ProfileFileName = NULL
        ExternalInternal = 1                                     ; external=0 / internal=1
            ReadInternal = 1                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          

[W1_CurvedProfile]
; Curved profile*  Version 10.1.77   17-02-2018   11:31:56
; Block: "Wedge"    Settings: 44S16+      Energy before block: 53.78 MeV/u
; Degrader: Be (500.00 micron)     Dispersion: -16.53 mm/%
; Mode: Achromatic for Block "Slits 43"    Wedge angle=-1.0418 mrad
; NP      X0      L       h       E0 (as it was created)
; 128     49.53   99.07   46.32   448.39 
; comments here: 
;========================== curved degrader ===============================
; N	X(mm)	Thick(um)	H(mm)	Tan(reduced)
0	-49.5300	1103.2027	46.3212	0.7165
1	-48.7560	1101.5911	45.7678	0.71341
2	-47.9820	1099.9789	45.2168	0.71031
3	-47.2080	1098.3662	44.6683	0.7072
4	-46.4341	1096.7530	44.1221	0.70408
5	-45.6601	1095.1395	43.5784	0.70095
6	-44.8861	1093.5257	43.0371	0.69781
7	-44.1121	1091.9116	42.4982	0.69466
8	-43.3381	1090.3025	41.9618	0.69151
9	-42.5641	1088.6881	41.4278	0.68834
10	-41.7902	1087.0737	40.8962	0.68516
11	-41.0162	1085.4644	40.3672	0.68198
12	-40.2422	1083.8501	39.8406	0.67878
13	-39.4682	1082.2361	39.3164	0.67557
14	-38.6942	1080.6222	38.7948	0.67235
15	-37.9202	1079.0137	38.2757	0.66913
16	-37.1463	1077.4006	37.7590	0.66589
17	-36.3723	1075.7880	37.2449	0.66264
18	-35.5983	1074.1709	36.7333	0.65937
19	-34.8243	1072.5595	36.2242	0.6561
20	-34.0503	1070.9487	35.7177	0.65282
21	-33.2763	1069.3339	35.2137	0.64952
22	-32.5023	1067.7248	34.7122	0.64622
23	-31.7284	1066.1118	34.2133	0.6429
24	-30.9544	1064.4950	33.7170	0.63956
25	-30.1804	1062.8842	33.2233	0.63622
26	-29.4064	1061.2698	32.7322	0.63286
27	-28.6324	1059.6568	32.2437	0.62949
28	-27.8584	1058.0451	31.7578	0.62611
29	-27.0845	1056.4350	31.2745	0.62272
30	-26.3105	1054.8217	30.7938	0.61931
31	-25.5365	1053.2101	30.3158	0.61589
32	-24.7625	1051.5957	29.8405	0.61245
33	-23.9885	1049.9831	29.3678	0.609
34	-23.2145	1048.3679	28.8978	0.60553
35	-22.4405	1046.7549	28.4304	0.60205
36	-21.6666	1045.1440	27.9658	0.59856
37	-20.8926	1043.5309	27.5039	0.59505
38	-20.1186	1041.9203	27.0447	0.59153
39	-19.3446	1040.3076	26.5882	0.58799
40	-18.5706	1038.6931	26.1345	0.58443
41	-17.7966	1037.0814	25.6835	0.58086
42	-17.0227	1035.4681	25.2354	0.57727
43	-16.2487	1033.8534	24.7900	0.57366
44	-15.4747	1032.2418	24.3474	0.57004
45	-14.7007	1030.6292	23.9076	0.5664
46	-13.9267	1029.0156	23.4706	0.56274
47	-13.1527	1027.4055	23.0365	0.55907
48	-12.3788	1025.7904	22.6052	0.55537
49	-11.6048	1024.1792	22.1768	0.55166
50	-10.8308	1022.5677	21.7512	0.54793
51	-10.0568	1020.9517	21.3286	0.54417
52	-9.2828	1019.3401	20.9089	0.5404
53	-8.5088	1017.7286	20.4921	0.53661
54	-7.7348	1016.1133	20.0782	0.53279
55	-6.9609	1014.5028	19.6673	0.52896
56	-6.1869	1012.8889	19.2594	0.5251
57	-5.4129	1011.2760	18.8545	0.52122
58	-4.6389	1009.6642	18.4526	0.51732
59	-3.8649	1008.0498	18.0537	0.51339
60	-3.0909	1006.4369	17.6579	0.50944
61	-2.3170	1004.8258	17.2651	0.50547
62	-1.5430	1003.2127	16.8755	0.50147
63	-0.7690	1001.6019	16.4889	0.49745
64	0.0050	999.9896	16.1054	0.4934
65	0.7790	998.3760	15.7251	0.48932
66	1.5530	996.7616	15.3480	0.48521
67	2.3270	995.1504	14.9741	0.48108
68	3.1009	993.5349	14.6033	0.47691
69	3.8749	991.9232	14.2358	0.47272
70	4.6489	990.3118	13.8716	0.4685
71	5.4229	988.6971	13.5106	0.46424
72	6.1969	987.0871	13.1529	0.45996
73	6.9709	985.4745	12.7986	0.45564
74	7.7448	983.8598	12.4476	0.45128
75	8.5188	982.2470	12.1001	0.44689
76	9.2928	980.6364	11.7559	0.44247
77	10.0668	979.0213	11.4152	0.438
78	10.8408	977.4092	11.0779	0.4335
79	11.6148	975.7971	10.7441	0.42896
80	12.3887	974.1852	10.4139	0.42438
81	13.1627	972.5707	10.0872	0.41975
82	13.9367	970.9575	9.7641	0.41508
83	14.7107	969.3461	9.4447	0.41037
84	15.4847	967.7336	9.1289	0.40561
85	16.2587	966.1206	8.8169	0.4008
86	17.0327	964.5076	8.5085	0.39594
87	17.8066	962.8954	8.2040	0.39103
88	18.5806	961.2812	7.9032	0.38606
89	19.3546	959.6691	7.6064	0.38104
90	20.1286	958.0564	7.3134	0.37596
91	20.9026	956.4440	7.0244	0.37082
92	21.6766	954.8327	6.7394	0.36562
93	22.4505	953.2172	6.4585	0.36034
94	23.2245	951.6044	6.1817	0.355
95	23.9985	949.9924	5.9090	0.34959
96	24.7725	948.3790	5.6405	0.3441
97	25.5465	946.7684	5.3764	0.33854
98	26.3205	945.1559	5.1165	0.33289
99	27.0945	943.5427	4.8611	0.32715
100	27.8684	941.9302	4.6101	0.32132
101	28.6424	940.3170	4.3637	0.31539
102	29.4164	938.7047	4.1220	0.30936
103	30.1904	937.0921	3.8849	0.30322
104	30.9644	935.4786	3.6526	0.29696
105	31.7384	933.8660	3.4253	0.29058
106	32.5123	932.2538	3.2029	0.28407
107	33.2863	930.6395	2.9856	0.27741
108	34.0603	929.0280	2.7735	0.27061
109	34.8343	927.4149	2.5668	0.26364
110	35.6083	925.8011	2.3655	0.25649
111	36.3823	924.1899	2.1698	0.24916
112	37.1562	922.5763	1.9799	0.24161
113	37.9302	920.9648	1.7959	0.23384
114	38.7042	919.3519	1.6180	0.22581
115	39.4782	917.7392	1.4464	0.2175
116	40.2522	916.1256	1.2814	0.20887
117	41.0262	914.5131	1.1233	0.19989
118	41.8002	912.8999	0.9722	0.1905
119	42.5741	911.2882	0.8286	0.18065
120	43.3481	909.6750	0.6928	0.17024
121	44.1221	908.0617	0.5653	0.15917
122	44.8961	906.4494	0.4467	0.1473
123	45.6701	904.8359	0.3377	0.1344
124	46.4441	903.2236	0.2392	0.12016
125	47.2180	901.6114	0.1524	0.10402
126	47.9920	899.9983	0.0793	0.084891
127	48.7660	898.3856	0.0232	0.06
128	49.5400	896.7728	0.0000	0


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = DP2,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 11.646000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 4                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = LISE\LISE_D4.cal

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-30.00,-30.0,30.00,30.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-30.00,-30.0,30.00,30.0             ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = -2.70712e+00,-7.53612e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,-4.48030e+01
                    row2 = -2.31818e-01,-3.70029e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-5.16776e+00
                    row3 = +0.00000e+00,+0.00000e+00,-3.11281e-01,+3.26366e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-1.02021e+00,-2.14290e+00,+0.00000e+00,+0.00000e+00
                    row5 = -3.60364e-01,+1.65401e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-1.56566e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 25                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 5.8                  mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 1.61513              Tm               ; magnetic rigidity
                   Angle = -45                  degrees          
                  Radius = 2.003                m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Entrance Use 1/0
          UseExitFringeF = 1                                     ; Exit Use 1/0


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = Slits 43,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-8.00,-30.0,8.00,30.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-30.00,-30.0,30.00,30.0             ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = SiD4,1                                ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,500,2.321,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.2                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK D3 - Dipole ======================================}

[D3_General]
                    Name = DA1,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 5.535000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = LISE\LISE_DA1.cal

[D3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-30.00,-30.0,30.00,30.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D3_optics]
                    row1 = -1.01028e+00,+1.77179e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+6.89395e+00
                    row2 = -4.27091e-01,-9.82231e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.37462e-03
                    row3 = +0.00000e+00,+0.00000e+00,-2.22669e+00,+7.26574e-05,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-2.10972e-02,-4.49091e-01,+0.00000e+00,+0.00000e+00
                    row5 = -2.94254e-01,-6.77265e-01,+0.00000e+00,+0.00000e+00,+1.00000e+00,-8.94022e-02
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D3_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 13                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 35                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D3_DipoleSettings]
                    Brho = 1.61513              Tm               ; magnetic rigidity
                   Angle = 15                   degrees          
                  Radius = 3                    m                

[D3_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Entrance Use 1/0
          UseExitFringeF = 1                                     ; Exit Use 1/0


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = Slits 51,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-30.00,-30.0,30.00,30.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK D4 - Dipole ======================================}

[D4_General]
                    Name = DA2,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 5.537000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = LISE\LISE_DA2.cal

[D4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-30.00,-30.0,30.00,30.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-30.00,-30.0,30.00,30.0             ; joint,Bottom,B-limit,Top,T-limit

[D4_optics]
                    row1 = -9.03790e-01,+1.31991e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+6.23697e+00
                    row2 = -4.24909e-01,-1.04433e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.92499e+00
                    row3 = +0.00000e+00,+0.00000e+00,-4.45865e-01,+3.83155e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-1.45679e-02,-2.23047e+00,+0.00000e+00,+0.00000e+00
                    row5 = -6.52210e-04,-6.89953e-01,+0.00000e+00,+0.00000e+00,+1.00000e+00,-8.94351e-02
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D4_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 13                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 16                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D4_DipoleSettings]
                    Brho = 1.61513              Tm               ; magnetic rigidity
                   Angle = 15                   degrees          
                  Radius = 3                    m                

[D4_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Entrance Use 1/0
          UseExitFringeF = 1                                     ; Exit Use 1/0


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = Slits 61,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-30.00,-30.0,30.00,30.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-30.00,-30.0,30.00,30.0             ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK N1 - Wien ======================================}

[N1_General]
                    Name = Wien 1,0                              ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 12.201000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = LISE\LISE_DFW.cal

[N1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-30.00,-30.0,30.00,30.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 0,-30.00,-30.0,30.00,30.0             ; joint,Bottom,B-limit,Top,T-limit

[N1_optics]
                    row1 = -1.00296e+00,-1.60660e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +8.23400e-01,-8.65190e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.70800e-04
                    row3 = +0.00000e+00,+0.00000e+00,-9.98430e-01,-1.55100e-01,+0.00000e+00,-2.62622e+00
                    row4 = +0.00000e+00,+0.00000e+00,+4.03100e-02,-9.95350e-01,+0.00000e+00,+1.00300e-02
                    row5 = +2.82700e-05,-4.69600e-05,+0.00000e+00,+0.00000e+00,+1.00000e+00,-9.31200e-07
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[N1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 18                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 15                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[N1_WienSettings]
            SelectionPla = 1                                     ; X (VAMOS) or Y (LISE)
                     E_F = 3000                 kV/m             ; electric field
                     B_F = 362.678132           G                ; magnetic field
                     DiC = -3.561e-4            mm/%             ; dispersion coefficient
               EB_LenEff = 0.9128               m                ; effect. elec/magnet length relations
                   KeepB = 0
        LengthJustFilter = 0.328                                 ; coefficient of length
                 Bending = 0                                     ; Direction : 0 - ClockWise, 1 - counterCW


{============================= BLOCK S5 - Drift ======================================}

[S5_General]
                    Name = Slits 62,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-30.00,-30.0,30.00,30.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 0,-30.00,-30.0,10.00,30.0             ; joint,Bottom,B-limit,Top,T-limit

[S5_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S5_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S5_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S6 - Drift ======================================}

[S6_General]
                    Name = Drift deg,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.250000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S6_optics]
                    row1 = +1.00000e+00,+2.50000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.50000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S6_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S6_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.25                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S7 - Drift ======================================}

[S7_General]
                    Name = Drift 2,0                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.800000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S7_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S7_optics]
                    row1 = +1.00000e+00,+8.00000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+8.00000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S7_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S7_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.8                  m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S8 - Drift ======================================}

[S8_General]
                    Name = Drift 3,0                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.650000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S8_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-6.00,-64.0,6.00,64.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-6.00,-64.0,6.00,64.0               ; joint,Bottom,B-limit,Top,T-limit

[S8_optics]
                    row1 = +1.00000e+00,+6.50000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+6.50000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S8_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S8_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.65                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S9 - Drift ======================================}

[S9_General]
                    Name = QLH1,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.330000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes
               B-fitting = 1 0 -100.000 100.000                  ; B-field: Use, Gate, Bounds

[S9_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-6.00,-64.0,6.00,64.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-6.00,-64.0,6.00,64.0               ; joint,Bottom,B-limit,Top,T-limit

[S9_optics]
                    row1 = +9.37140e-01,+3.23056e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -3.76930e-01,+9.37140e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.06421e+00,+3.37033e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+3.93238e-01,+1.06421e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S9_optics2]
                   row11 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +6.21935e-04,+6.89994e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row21 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +3.68879e-03,+6.21935e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-6.48842e-04,-7.07753e-05,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-4.01496e-03,-6.48842e-04,+0.00000e+00,+0.00000e+00
                   row51 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[S9_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S9_DriftSettings]
                    Mode = 2                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 2                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.33                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 1.884472             KG               
                  Radius = 10                   cm               ; half-aperture
       Include 2nd order = 1                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 1.615127             Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S10 - Drift ======================================}

[S10_General]
                    Name = Drift 5,0                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.570000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S10_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-70.0,50.00,70.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-70.0,50.00,70.0             ; joint,Bottom,B-limit,Top,T-limit

[S10_optics]
                    row1 = +1.00000e+00,+5.70000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+5.70000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S10_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S10_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.57                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK F1 - Fit ======================================}

[F1_General]
                    Name = Fit R3Q,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes

[F1_FitSettings]
              Constraint = 42                                    ; 0-41
                 Operand = 2                                     ; 0-2
                   Value = 45       
               Precision = 0.1     
                  Active = 1                                     ; Use 1/0
                SecOrder = 111                                   ; T***


{============================= BLOCK S11 - Drift ======================================}

[S11_General]
                    Name = q67,1                                 ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.407500             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes
               B-fitting = 1 0 -100.000 100.000                  ; B-field: Use, Gate, Bounds

[S11_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-64.00,-70.0,64.00,70.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-64.00,-70.0,64.00,70.0             ; joint,Bottom,B-limit,Top,T-limit

[S11_optics]
                    row1 = +1.27594e+00,+4.44334e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +1.41341e+00,+1.27594e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+7.47314e-01,+3.72561e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-1.18510e+00,+7.47314e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S11_optics2]
                   row11 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = -2.87982e-03,-3.78059e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row21 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -1.53367e-02,-2.87982e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+2.41464e-03,+3.40153e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,+1.07690e-02,+2.41464e-03,+0.00000e+00,+0.00000e+00
                   row51 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[S11_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S11_DriftSettings]
                    Mode = 2                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 2                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.4075               m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = -5.137656            KG               
                  Radius = 10                   cm               ; half-aperture
       Include 2nd order = 1                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 1.615127             Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S12 - Drift ======================================}

[S12_General]
                    Name = Drift 7,0                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.570000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S12_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-70.0,7.00,70.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-70.0,7.00,70.0               ; joint,Bottom,B-limit,Top,T-limit

[S12_optics]
                    row1 = +1.00000e+00,+5.70000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+5.70000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S12_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S12_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.57                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S13 - Drift ======================================}

[S13_General]
                    Name = qLHE1,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.330000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes
               B-fitting = 1 0 -100.000 100.000                  ; B-field: Use, Gate, Bounds

[S13_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-64.00,-64.0,64.00,64.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-64.00,-64.0,64.00,64.0             ; joint,Bottom,B-limit,Top,T-limit

[S13_optics]
                    row1 = +8.00626e-01,+3.07763e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -1.16647e+00,+8.00626e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.21357e+00,+3.53174e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+1.33859e+00,+1.21357e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S13_optics2]
                   row11 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +1.92468e-03,+2.17780e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row21 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +1.08393e-02,+1.92468e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-2.20868e-03,-2.36522e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-1.42824e-02,-2.20868e-03,+0.00000e+00,+0.00000e+00
                   row51 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[S13_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S13_DriftSettings]
                    Mode = 2                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 2                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.33                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 6.121616             KG               
                  Radius = 10                   cm               ; half-aperture
       Include 2nd order = 1                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 1.615127             Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S14 - Drift ======================================}

[S14_General]
                    Name = dirft_I,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 1.700000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S14_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-70.0,7.00,70.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-70.0,7.00,70.0               ; joint,Bottom,B-limit,Top,T-limit

[S14_optics]
                    row1 = +1.00000e+00,+1.70000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+1.70000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S14_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S14_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 1.7                  m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK F2 - Fit ======================================}

[F2_General]
                    Name = Foc X,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes

[F2_FitSettings]
              Constraint = 1                                     ; 0-41
                 Operand = 0                                     ; 0-2
                   Value = 0       
               Precision = 0.001   
                  Active = 1                                     ; Use 1/0
                SecOrder = 111                                   ; T***


{============================= BLOCK F3 - Fit ======================================}

[F3_General]
                    Name = Foc Y,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes

[F3_FitSettings]
              Constraint = 15                                    ; 0-41
                 Operand = 0                                     ; 0-2
                   Value = 0       
               Precision = 0.1     
                  Active = 1                                     ; Use 1/0
                SecOrder = 111                                   ; T***


{============================= BLOCK F4 - Fit ======================================}

[F4_General]
                    Name = disp X,1                              ; Name of Block, Constant name 1/0
               Available = 0                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes

[F4_FitSettings]
              Constraint = 5                                     ; 0-41
                 Operand = 0                                     ; 0-2
                   Value = 0       
               Precision = 0.01    
                  Active = 1                                     ; Use 1/0
                SecOrder = 111                                   ; T***


{============================= BLOCK F5 - Fit ======================================}

[F5_General]
                    Name = disp Y,1                              ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes

[F5_FitSettings]
              Constraint = 17                                    ; 0-41
                 Operand = 0                                     ; 0-2
                   Value = 0       
               Precision = 1       
                  Active = 1                                     ; Use 1/0
                SecOrder = 111                                   ; T***


{============================= BLOCK F6 - Fit ======================================}

[F6_General]
                    Name = R targ,1                              ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes

[F6_FitSettings]
              Constraint = 42                                    ; 0-41
                 Operand = 2                                     ; 0-2
                   Value = 10       
               Precision = 0.01    
                  Active = 1                                     ; Use 1/0
                SecOrder = 111                                   ; T***


{============================= BLOCK S15 - Drift ======================================}

[S15_General]
                    Name = slits,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S15_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S15_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S15_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S15_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S16 - Drift ======================================}

[S16_General]
                    Name = dirft_O,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.500000             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S16_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S16_optics]
                    row1 = +1.00000e+00,+5.00000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+5.00000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S16_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S16_DriftSettings]
                    Mode = 1                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.5                  m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0.001                Tm               
          CorrespondErho = 1e-2                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK F7 - Fit ======================================}

[F7_General]
                    Name = X det,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes

[F7_FitSettings]
              Constraint = 36                                    ; 0-41
                 Operand = 2                                     ; 0-2
                   Value = 25       
               Precision = 0.1     
                  Active = 1                                     ; Use 1/0
                SecOrder = 111                                   ; T***


{============================= BLOCK F8 - Fit ======================================}

[F8_General]
                    Name = Y det,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes

[F8_FitSettings]
              Constraint = 38                                    ; 0-41
                 Operand = 2                                     ; 0-2
                   Value = 25       
               Precision = 0.1     
                  Active = 0                                     ; Use 1/0
                SecOrder = 111                                   ; T***


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = DeltaE Si,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 4,0.5,2.33,0,1                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,1                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.2                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M3_BlockCalibration]
                     TOF = 0,12.3,0,ns                           ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 0,8,9,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M4 - Material ======================================}

[M4_General]
                    Name = E SI,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M4_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 4,5,2.321,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.25                                ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.2                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M4_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M4_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= Calculations ======================================}

[Calculations]
57Cu 29+ 29+ 29+ 29+ 29+ =5.5310e-02,5.5310e-02,0,5.5310e-02,2.7422e-02,2.9030e-02,3.6638e-07,5.6115e+01,1.2443e+00,9.8156e-01,1,1,1,1,9.8156e-01,1,1,1,1,1,1,1,1,1,1,1,6.6411e-01,1,1,8.2758e-01,8.0248e-01,3.5234e-01,3.5234e-01,1,1,1,9.7467e-01,1,1,1,1,9.7467e-01,1,1,6.8026e-01,1,1,8.2657e-01,8.2298e-01,1.9489e-04,1.9489e-04,1,1,1,9.9792e-01,1,1,9.9793e-01,1,6.8461e-01,6.8461e-01,1,1,1,1.9752e-01,1,1,1.9752e-01,1,6.5949e-01,6.5949e-01,1,1,1,1.4979e-01,1,1,1.7600e-01,8.5107e-01,9.2610e-01,9.2610e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1
56Ni 28+ 28+ 28+ 28+ 28+ =2.9501e+06,2.9501e+06,0,2.9501e+06,2.7422e+00,2.9030e+00,1.9541e-01,5.7599e+01,1.1758e+00,9.8164e-01,1,1,1,1,9.8164e-01,1,1,1,1,1,1,1,1,1,1,1,6.7393e-01,1,1,8.3344e-01,8.0861e-01,9.7075e-01,9.7075e-01,1,1,1,9.7474e-01,1,1,1,1,9.7474e-01,1,1,7.7910e-01,1,1,9.4675e-01,8.2292e-01,5.2982e-01,5.2982e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,9.3949e-01,1,1,9.3949e-01,1,1,1,1,1,1,8.0549e-01,1,1,9.4612e-01,8.5136e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,7.6653e-06,1,1,1,1,9.9329e-01,1,7.7171e-06,0,1,1,1,1,1,1,0
55Co 27+ 27+ 27+ 27+ 27+ =7.5820e+03,7.5820e+03,0,7.5820e+03,1.6744e+01,1.7726e+01,8.2253e-05,5.7790e+01,1.4772e+00,9.8173e-01,1,1,1,1,9.8173e-01,1,1,1,1,1,1,1,1,1,1,1,6.2895e-01,1,1,8.0615e-01,7.8020e-01,8.9678e-01,8.9678e-01,1,1,1,9.7478e-01,1,1,1,1,9.7478e-01,1,1,7.2574e-01,1,1,8.8555e-01,8.1954e-01,3.1600e-03,3.1600e-03,1,1,1,9.9682e-01,1,1,9.9684e-01,1,8.0436e-01,8.0436e-01,1,1,1,4.6616e-01,1,1,4.6616e-01,1,9.5586e-01,9.5586e-01,1,1,1,1.9741e-01,1,1,2.3224e-01,8.5004e-01,9.4213e-01,9.5031e-01,9.9139e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4.3373e-02,1,1,1,1,9.9332e-01,1,4.3665e-02,0,1,1,1,1,1,1,0
52Mn 25+ 25+ 25+ 25+ 25+ =1.7183e+05,1.7183e+05,0,1.7183e+05,2.2383e+01,2.3695e+01,1.3945e-03,5.8024e+01,2.1774e+00,9.8196e-01,1,1,1,1,9.8196e-01,1,1,1,1,1,1,1,1,1,1,1,5.2511e-01,1,1,7.3849e-01,7.1106e-01,2.4117e-01,2.4117e-01,1,1,1,9.7510e-01,1,1,1,1,9.7510e-01,1,1,6.9086e-01,1,1,8.5149e-01,8.1134e-01,1.0063e-01,1.0063e-01,1,1,1,9.9635e-01,1,1,9.9637e-01,1,3.5524e-01,3.5524e-01,1,1,1,7.4926e-01,1,1,7.4926e-01,1,1,1,1,1,1,6.8741e-01,1,1,8.1117e-01,8.4744e-01,9.0739e-01,1,9.0786e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5.4787e-01,1,1,1,1,9.9325e-01,1,5.5159e-01,0,1,1,1,1,1,1,0
51Cr 24+ 24+ 24+ 24+ 24+ =1.0762e+05,1.0762e+05,0,1.0762e+05,1.9200e+01,2.0325e+01,1.0182e-03,5.8220e+01,2.4712e+00,9.8205e-01,1,1,1,1,9.8205e-01,1,1,1,1,1,1,1,1,1,1,1,4.8529e-01,1,1,7.1058e-01,6.8295e-01,7.9921e-02,7.9921e-02,1,1,1,9.7497e-01,1,1,1,1,9.7497e-01,1,1,6.8952e-01,1,1,8.5410e-01,8.0730e-01,1.5143e-01,1.5143e-01,1,1,1,1,1,1,1,1,9.5602e-01,9.5602e-01,1,1,1,8.6996e-01,1,1,8.6997e-01,1,1,1,1,1,1,7.3478e-01,1,1,8.6785e-01,8.4667e-01,4.2989e-01,1,4.3029e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5.2764e-02,1,1,1,1,9.9341e-01,1,5.3114e-02,0,1,1,1,1,1,1,0
48Ti 22+ 22+ 22+ 22+ 22+ =5.2599e+00,5.2599e+00,0,5.2599e+00,6.7515e+00,7.1473e+00,1.4152e-07,5.8426e+01,3.2324e+00,9.8229e-01,1,1,1,1,9.8229e-01,1,1,1,1,1,1,1,1,1,1,1,3.9670e-01,1,1,6.4367e-01,6.1632e-01,3.8006e-02,3.8006e-02,1,1,1,9.7520e-01,1,1,1,1,9.7520e-01,1,1,6.8414e-01,1,1,8.5647e-01,7.9878e-01,2.8960e-02,2.8960e-02,1,1,1,9.9019e-01,1,1,9.9021e-01,1,3.1337e-01,3.1337e-01,1,1,1,6.0408e-01,1,1,6.0409e-01,1,9.9849e-01,9.9849e-01,1,1,1,5.0689e-01,1,1,6.0001e-01,8.4481e-01,5.2131e-03,9.9251e-01,5.2525e-03,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2.5498e-01,1,1,1,1,9.9340e-01,1,2.5667e-01,0,1,1,1,1,1,1,0
