Version 9.10.181

{============================= Main Part ======================================}
[general]
                    File = C:\user\c\lise_pp_910\files\examples\dubna\acculinna_27S.lpp
                    Date = 21-09-2015
                    Time = 11:05:09
           Configuration = NSCL\A1900 - 4 dipoles.lcn
             Optionsfile = default.lopt
                   Title = NSCL A1900 Fragment Separator - 4dipoles
          BlockStructure = DWDMSMMM

[settings]
                   A,Z,Q = 32S 16+                               ; Mass ElementName Charge+ Beam
                  Energy = 52                   MeV/u            
               Intensity = 100                  pnA              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 27S                                   ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 3                    (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 30                   (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 3                    (±)mm            ; one-half the vertical beam extent (y)
                      BF = 30                   (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 1                    (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0.3                  mm               ; beam respect to the spectrometer axis
                  AngleX = 3                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0.3                  mm               ; beam respect to the spectrometer axis
                  AngleY = 3                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = 30.6                 degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1
               OptBeam_X = 1                    (±)mm            
               OptBeam_T = 30                   (±)mrad          
               OptBeam_Y = 1                    (±)mm            
               OptBeam_F = 30                   (±)mrad          
               OptBeam_L = 0                    (±)mm            
               OptBeam_D = 1.5                  (±)%             

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-3.00,-50.0,3.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-50.0,3.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 64                                    ; Number of points in distribution
        NP charge states = 64                                    ; Number of points in distribution
                NP wedge = 16                                    ; Number of points in distribution
           Charge states = Yes                                   ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,4,1,9.012                           ; Nomer,Z,Atoms,Mass
        Target thickness = 0,500,1.85,0,0                        ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,73,1,180.95                         ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,4,16.6,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 0                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 1                                     ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
                 AA_fast = 0                                     ; 1-Yes, 0-No
            BarrierShape = 1                                     ; 0-classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
            UseVanishing = 1                                     ; 1-Yes, 0-No
              VanishMode = 0                                     ; 0-Sierk, 1-Cohen
           NuclPotential = 1                                     ; 0-Bass, 1-WS
                   WS_V0 = 105                  MeV              
                   WS_R0 = 1.12                 fm               
                    WS_a = 0.75                 fm               
          FusDiffuseness = 1    
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 1                                     ; charge calculations method  0-5
      EPAX Cross Section = 3                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 0                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 2                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 0                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 0                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-9     
               FisCS_TKE = 1e-6     
                      N0 = 82                                    ; default 82
                     dU0 = -2.5                                  ; default -2.5
                      C0 = 1.4                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -5.5                                  ; default -5.5
                      C1 = 0.16                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-4     
                 BeamInd = 1e-6     
               BeamTotal = 1e-8     

[convolution]
        Convolution mode = 1                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 3     
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 1                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 0                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
          AvoidUnboundCS = 1                                     ; 1-Yes, 0-No
       ProtectedChannels = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 6                    fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 0                                     ; 0 - no, 1 - use
         DissipationBeta = 2                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 1                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 1                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 1                                     ; 1-Yes, 0-No
                  mode_t = 1                                     ; 1-Yes, 0-No
                mode_3he = 1                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       

[evapauto]
                  tun_a0 = 1.00938
                  tun_a1 = -0.36149
                  tun_a2 = 0.21551
                 A_Bound = 300                                   ; mass
               A_Pairing =  70                                   ; mass

[plot]
            Start target = Detector                              ; Detector & RF      
            Start of TOF = M1
            Stop  of TOF = M2
         dE-detector-1st = M3
         dE-detector-2nd = M2
            TKE-detector = M1
                PlotBrho = D1
               PlotWedge = D2
              X-detector = M1
              Y-detector = M1
                 Tilting = M9
                 Stopper = M11
                RO_Wedge = n
          ConditionBlock = A0
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 2
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
                Velocity = 1                                     ; Calculat fissile nuclei speed
           LowEx_nucleus = 39Ar18+                               ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 34S 16+                               ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 28Si14+                               ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 1.800e+03 100.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 16
                   Dr_n0 = 0
                   Dr_n1 = 16

[cross sections]

[previous]
                 Lowerst =  1H 1+                                ; Mass ElementName Charge+ Beam
                 Highest = 35Cl17+                               ; Mass ElementName Charge+ Beam

[MC_options]
                   dXsel = 0
                   dYsel = 2
                  dAZQ_X = 1
                  dAZQ_Y = 5
                  dVEL_X = 1
                  dVEL_Y = 0
               dIso_mode = 0
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 0
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 2
                  CS_use = 1
           envelope_show = 0
                use_bore = 0
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
              AZQ_Xsigma = 0.1   
              AZQ_Ysigma = 0.1   
                 G1_gate = 0 0 -100.0000 100.0000
                 G2_gate = 0 0 -100.0000 100.0000
                 G3_gate = 0 0 -100.0000 100.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 0 0,R1,R1,R1                          ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 0 0,R1,R1,R1
            G3_component = 0 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1

[Levmar_fit]
                   Niter = 100                                   ; # iterations
               UseBounds = 1                                     ; yes-1, no-0
                 Example = 4                                     ; 0-15
                    opt0 = 1e-3     
                    opt1 = 1e-15    
                    opt2 = 1e-25    
                    opt3 = 1e-20    
                    opt4 = 1e-6     


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = D1,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 6.396000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = FLNR\Acculinna_B2.cal

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-6.00,-50.0,6.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-10.00,-50.0,10.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = -7.86300e-01,-6.30000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+6.01000e+00
                    row2 = +1.34650e+00,-1.16420e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.30300e-01
                    row3 = +0.00000e+00,+0.00000e+00,-2.03960e+00,+7.00000e-03,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-7.01100e-01,-4.87900e-01,+0.00000e+00,+0.00000e+00
                    row5 = +7.91100e-01,-7.01000e-01,+0.00000e+00,+0.00000e+00,+1.00000e+00,-7.52000e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 20                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 14                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 1.59386              Tm               ; magnetic rigidity
                   Angle = -30.6                degrees          
                  Radius = 3                    m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = Wedge,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,4,1,9.012                           ; Nomer,Z,Atoms,Mass
               thickness = 0,500,1.848,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W1_WedgeSettings]
             ProfileMode = 1                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 2                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = 0.00000              mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = Slits_Im2
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = D2,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 6.397000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = FLNR\Acculinna_B3.cal

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-10.00,-50.0,10.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = -2.17620e+00,+3.52300e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.24350e+01
                    row2 = +6.83890e-01,-4.60650e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.90750e+00
                    row3 = +0.00000e+00,+0.00000e+00,-5.06390e-01,-3.65950e-01,+0.00000e+00,+5.06390e-06
                    row4 = +0.00000e+00,+0.00000e+00,-4.43510e-01,-2.29370e+00,+0.00000e+00,+4.43510e-06
                    row5 = +1.96510e-04,-5.71220e-01,+0.00000e+00,+0.00000e+00,+1.00000e+00,-7.53730e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 25                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 11                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 1.35919              Tm               ; magnetic rigidity
                   Angle = -30.6                degrees          
                  Radius = 3                    m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = F3_Pl,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,1,10,1.008                          ; Nomer,Z,Atoms,Mass
               contents2 = 1,6,9,12.011                          ; Nomer,Z,Atoms,Mass
               thickness = 0,27,1.032,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 0,1                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,1,1              ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = Drift,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 7.950000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-25.0,20.00,25.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-25.0,20.00,25.0             ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = -1.58950e+00,+8.60000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.00000e-04
                    row2 = +4.94800e-01,-6.55300e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.00000e-04
                    row3 = +0.00000e+00,+0.00000e+00,+1.43380e+00,-6.72000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+9.20500e-01,+2.66100e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 7.95                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = F4_Pl,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,1,10,1.008                          ; Nomer,Z,Atoms,Mass
               contents2 = 1,6,9,12.011                          ; Nomer,Z,Atoms,Mass
               thickness = 0,27,1.032,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = -1610612735,-20.00,-50.0,20.00,50.0   ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 0,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = F4_dE,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,300,2.321,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,1                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,1,1              ns,mm,mm         ; Time&X&Y space

[M3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-25.00,-25.0,25.00,25.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-25.00,-25.0,25.00,25.0             ; joint,Bottom,B-limit,Top,T-limit

[M3_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M4 - Material ======================================}

[M4_General]
                    Name = F4_E,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M4_Compound]
               contents1 = 0,1,8,1.008                           ; Nomer,Z,Atoms,Mass
               contents2 = 1,6,10,12.011                         ; Nomer,Z,Atoms,Mass
               contents3 = 2,8,4,15.999                          ; Nomer,Z,Atoms,Mass
               thickness = 0,125,1.397,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,2                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,2                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,1,1              ns,mm,mm         ; Time&X&Y space

[M4_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-75.00,-75.0,75.00,75.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M4_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M4_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= Calculations ======================================}

[Calculations]
31Cl 17+ 16+ =2.0793e-02,2.0793e-02,0,2.0793e-02,1.5874e-02,3.5622e-02,3.3638e-07,4.1065e+01,1.9240e+00,4.6061e-01,6.8212e-01,6.8212e-01,1,1,9.8996e-01,1,1,1,6.4160e-01,1,1,1,1,1,6.4166e-01,1,1.7016e-03,1.9821e-02,1,3.4646e-01,2.4779e-01,4.7887e-03,1,1,1,1,9.8859e-01,4.8439e-03,1,2.0007e-01,2.3294e-01,1,9.2620e-01,9.2731e-01,1,1,1,1,1,1,1,1,6.9840e-01,6.9840e-01,1,1,1,1,1,1,1,1,1,1,1,9.9635e-01,1,1,1,1,9.9635e-01,1,1,1.4998e-01,1,1,1,1,1,1,1.5013e-01
31S  16+ 15+ =6.1501e-07,6.1501e-07,0,6.1501e-07,2.2019e+01,4.9413e+01,7.1724e-15,4.2985e+01,1.4466e+00,4.6062e-01,6.8212e-01,6.8212e-01,1,1,9.8999e-01,1,1,1,7.7088e-01,1,1,1,1,1,7.7096e-01,1,5.1580e-07,5.5879e-06,1,3.5913e-01,2.5703e-01,2.1107e-02,1,1,1,1,9.8831e-01,2.1357e-02,1,2.3944e-06,2.7983e-06,1,9.2511e-01,9.2495e-01,1,1,1,1,1,1,1,1,7.7510e-01,7.7510e-01,1,1,1,1,1,1,1,1,1,1,1,9.9654e-01,1,1,1,1,9.9654e-01,1,1,0,1,1,1,1,1,1,0
30S  16+ 15+ =1.3276e-01,1.3276e-01,0,1.3276e-01,1.5874e+00,3.5622e+00,2.1477e-08,4.2404e+01,1.8917e+00,4.6065e-01,6.8212e-01,6.8212e-01,1,1,9.9004e-01,1,1,1,7.6443e-01,1,1,1,1,1,7.6450e-01,1,1.6345e-04,1.8781e-03,1,3.4880e-01,2.4952e-01,3.0512e-03,1,1,1,1,9.8858e-01,3.0864e-03,1,1.9204e-01,2.2430e-01,1,9.2577e-01,9.2480e-01,1,1,1,1,1,1,1,1,6.3704e-01,6.3704e-01,1,1,1,1,1,1,1,1,1,1,1,9.9641e-01,1,1,1,1,9.9641e-01,1,1,2.8082e-18,1,1,1,1,1,1,2.8108e-18
28S  16+ 16+ =3.3994e-01,3.3994e-01,0,3.3994e-01,2.9843e-03,6.6970e-03,2.9250e-05,4.1284e+01,2.7532e+00,4.6070e-01,6.8212e-01,6.8212e-01,1,1,9.9014e-01,1,1,1,7.5195e-01,1,1,1,1,1,7.5202e-01,1,9.5677e-03,1.2408e-01,1,3.2853e-01,2.3471e-01,9.8924e-01,1,1,1,1,9.8925e-01,1,1,1.0502e-02,1.1986e-02,1,9.3154e-01,9.4061e-01,1,1,1,1,1,1,1,1,8.4973e-01,8.4973e-01,1,1,1,1,1,1,1,1,1,1,1,9.9637e-01,1,1,1,1,9.9637e-01,1,1,9.9834e-01,1,1,1,1,9.9834e-01,1,1
27S  16+ 16+ =8.2571e-01,8.2571e-01,0,8.2571e-01,1.2783e-04,2.8687e-04,1.6587e-03,4.0704e+01,3.1893e+00,4.6072e-01,6.8212e-01,6.8212e-01,1,1,9.9020e-01,1,1,1,7.4561e-01,1,1,1,1,1,7.4568e-01,1,1.8014e-02,2.5138e-01,1,3.1685e-01,2.2618e-01,9.8960e-01,1,1,1,1,9.8960e-01,1,1,3.2059e-01,3.6083e-01,1,9.3442e-01,9.5084e-01,1,1,1,1,1,1,1,1,8.4512e-01,8.4512e-01,1,1,1,1,1,1,1,1,1,1,1,9.9644e-01,1,1,1,1,9.9644e-01,1,1,9.9833e-01,1,1,1,1,9.9833e-01,1,1
30P  15+ 14+ =9.5275e-09,9.5275e-09,0,9.5275e-09,3.5040e+01,7.8633e+01,6.9822e-17,4.2973e+01,1.8945e+00,4.6066e-01,6.8212e-01,6.8212e-01,1,1,9.9007e-01,1,1,1,8.6578e-01,1,1,1,1,1,8.6586e-01,1,4.7261e-06,5.4039e-05,1,3.4973e-01,2.5007e-01,1.7109e-02,1,1,1,1,9.8830e-01,1.7312e-02,1,2.8594e-09,3.3540e-09,1,9.2506e-01,9.2158e-01,1,1,1,1,1,1,1,1,7.5742e-01,7.5742e-01,1,1,1,1,1,1,1,1,1,1,1,9.9672e-01,1,1,1,1,9.9672e-01,1,1,0,1,1,1,1,1,1,0
29P  15+ 14+ =3.9074e-01,3.9074e-01,0,3.9074e-01,7.9361e+00,1.7809e+01,1.2643e-08,4.2435e+01,2.3084e+00,4.6069e-01,6.8212e-01,6.8212e-01,1,1,9.9012e-01,1,1,1,8.6087e-01,1,1,1,1,1,8.6096e-01,1,1.2437e-04,1.5003e-03,1,3.4055e-01,2.4342e-01,2.0191e-03,1,1,1,1,9.8857e-01,2.0425e-03,1,1.8895e-01,2.2152e-01,1,9.2524e-01,9.2190e-01,1,1,1,1,1,1,1,1,6.7209e-01,6.7209e-01,1,1,1,1,1,1,1,1,1,1,1,9.9649e-01,1,1,1,1,9.9649e-01,1,1,0,1,1,1,1,1,1,0
27P  15+ 15+ =5.2531e-01,5.2531e-01,0,5.2531e-01,5.2383e-02,1.1755e-01,2.5751e-06,4.1327e+01,3.1622e+00,4.6074e-01,6.8212e-01,6.8212e-01,1,1,9.9023e-01,1,1,1,8.5176e-01,1,1,1,1,1,8.5185e-01,1,3.7838e-03,5.1922e-02,1,3.1948e-01,2.2810e-01,9.8923e-01,1,1,1,1,9.8923e-01,1,1,2.0005e-03,2.2946e-03,1,9.3019e-01,9.3726e-01,1,1,1,1,1,1,1,1,8.7659e-01,8.7659e-01,1,1,1,1,1,1,1,1,1,1,1,9.9639e-01,1,1,1,1,9.9639e-01,1,1,9.9837e-01,1,1,1,1,9.9837e-01,1,1
26P  15+ 15+ =9.2438e+00,9.2438e+00,0,9.2438e+00,2.2996e-03,5.1604e-03,1.0322e-03,4.1103e+01,3.2684e+00,4.6076e-01,6.8212e-01,6.8212e-01,1,1,9.9028e-01,1,1,1,8.4647e-01,1,1,1,1,1,8.4655e-01,1,1.0752e-02,1.5467e-01,1,3.1213e-01,2.2271e-01,9.8960e-01,1,1,1,1,9.8960e-01,1,1,2.9894e-01,3.3905e-01,1,9.3330e-01,9.4472e-01,1,1,1,1,1,1,1,1,8.3228e-01,8.3228e-01,1,1,1,1,1,1,1,1,1,1,1,9.9646e-01,1,1,1,1,9.9646e-01,1,1,9.9835e-01,1,1,1,1,9.9835e-01,1,1
28Si 14+ 13+ =5.7902e-01,5.7902e-01,0,5.7902e-01,2.1352e+01,4.7916e+01,6.9635e-09,4.2468e+01,2.7602e+00,4.6072e-01,6.8212e-01,6.8212e-01,1,1,9.9021e-01,1,1,1,9.3769e-01,1,1,1,1,1,9.3778e-01,1,9.0996e-05,1.1677e-03,1,3.3026e-01,2.3597e-01,1.4035e-03,1,1,1,1,9.8857e-01,1.4197e-03,1,1.8559e-01,2.1854e-01,1,9.2441e-01,9.1869e-01,1,1,1,1,1,1,1,1,6.8026e-01,6.8026e-01,1,1,1,1,1,1,1,1,1,1,1,9.9241e-01,1,1,1,1,9.9669e-01,1,9.9571e-01,0,1,1,1,1,1,1,0
26Si 14+ 14+ =5.5461e-02,5.5461e-02,0,5.5461e-02,7.6018e-01,1.7059e+00,1.8735e-08,4.1718e+01,3.2723e+00,4.6078e-01,6.8212e-01,6.8212e-01,1,1,9.9032e-01,1,1,1,9.3174e-01,1,1,1,1,1,9.3183e-01,1,1.4379e-03,2.0549e-02,1,3.1315e-01,2.2346e-01,9.8921e-01,1,1,1,1,9.8921e-01,1,1,3.4665e-05,4.0080e-05,1,9.2637e-01,9.3363e-01,1,1,1,1,1,1,1,1,8.8528e-01,8.8528e-01,1,1,1,1,1,1,1,1,1,1,1,9.9642e-01,1,1,1,1,9.9642e-01,1,1,9.9839e-01,1,1,1,1,9.9839e-01,1,1
25Si 14+ 14+ =7.7244e+01,7.7244e+01,0,7.7244e+01,4.1410e-02,9.2927e-02,4.7900e-04,4.1138e+01,3.7346e+00,4.6080e-01,6.8212e-01,6.8212e-01,1,1,9.9037e-01,1,1,1,9.2798e-01,1,1,1,1,1,9.2807e-01,1,4.4820e-03,6.9825e-02,1,3.0029e-01,2.1376e-01,9.8959e-01,1,1,1,1,9.8959e-01,1,1,3.0400e-01,3.4642e-01,1,9.3184e-01,9.4173e-01,1,1,1,1,1,1,1,1,8.3102e-01,8.3102e-01,1,1,1,1,1,1,1,1,1,1,1,9.9648e-01,1,1,1,1,9.9648e-01,1,1,9.9837e-01,1,1,1,1,9.9837e-01,1,1
24Si 14+ 14+ =8.4249e-02,8.4249e-02,0,8.4249e-02,2.0631e-03,4.6297e-03,1.0487e-05,4.0492e+01,4.2250e+00,4.6083e-01,6.8212e-01,6.8212e-01,1,1,9.9043e-01,1,1,1,9.2375e-01,1,1,1,1,1,9.2383e-01,1,1.0066e-02,1.6887e-01,1,2.8949e-01,2.0591e-01,9.8999e-01,1,1,1,1,9.8999e-01,1,1,2.7939e-03,3.1398e-03,1,9.3405e-01,9.5266e-01,1,1,1,1,1,1,1,1,8.8508e-01,8.8508e-01,1,1,1,1,1,1,1,1,1,1,1,9.9655e-01,1,1,1,1,9.9655e-01,1,1,9.9838e-01,1,1,1,1,9.9838e-01,1,1
27Al 13+ 12+ =4.2128e-01,4.2128e-01,0,4.2128e-01,2.4822e+01,5.5702e+01,4.3583e-09,4.2474e+01,3.1982e+00,4.6076e-01,6.8212e-01,6.8212e-01,1,1,9.9029e-01,1,1,1,9.8218e-01,1,1,1,1,1,9.8228e-01,1,6.5948e-05,9.0256e-04,1,3.1993e-01,2.2839e-01,1.0961e-03,1,1,1,1,9.8858e-01,1.1088e-03,1,1.8255e-01,2.1603e-01,1,9.2353e-01,9.1498e-01,1,1,1,1,1,1,1,1,7.3002e-01,7.3002e-01,1,1,1,1,1,1,1,1,1,1,1,8.2359e-01,1,1,1,1,9.9681e-01,1,8.2622e-01,0,1,1,1,1,1,1,0
24Al 13+ 13+ =6.1457e+02,6.1457e+02,0,6.1457e+02,6.6194e-01,1.4854e+00,2.3841e-04,4.1100e+01,4.2334e+00,4.6084e-01,6.8212e-01,6.8212e-01,1,1,9.9046e-01,1,1,1,9.7784e-01,1,1,1,1,1,9.7793e-01,1,2.1267e-03,3.5340e-02,1,2.9085e-01,2.0690e-01,9.8956e-01,1,1,1,1,9.8956e-01,1,1,3.1170e-01,3.5732e-01,1,9.3012e-01,9.3786e-01,1,1,1,1,1,1,1,1,8.0679e-01,8.0679e-01,1,1,1,1,1,1,1,1,1,1,1,9.9650e-01,1,1,1,1,9.9650e-01,1,1,9.9840e-01,1,1,1,1,9.9840e-01,1,1
23Al 13+ 13+ =2.0039e+00,2.0039e+00,0,2.0039e+00,3.9063e-02,8.7661e-02,1.3173e-05,4.0841e+01,4.3733e+00,4.6087e-01,6.8212e-01,6.8212e-01,1,1,9.9052e-01,1,1,1,9.7624e-01,1,1,1,1,1,9.7633e-01,1,4.9764e-03,8.7003e-02,1,2.8364e-01,2.0166e-01,9.8997e-01,1,1,1,1,9.8997e-01,1,1,7.2643e-03,8.1915e-03,1,9.3323e-01,9.5026e-01,1,1,1,1,1,1,1,1,8.1835e-01,8.1835e-01,1,1,1,1,1,1,1,1,1,1,1,9.9657e-01,1,1,1,1,9.9657e-01,1,1,9.9839e-01,1,1,1,1,9.9839e-01,1,1
23Mg 12+ 12+ =1.9130e+03,1.9130e+03,0,1.9130e+03,4.8650e+00,1.0917e+01,1.0098e-04,4.1438e+01,4.4140e+00,4.6089e-01,6.8212e-01,6.8212e-01,1,1,9.9055e-01,1,1,1,9.9673e-01,1,1,1,1,1,9.9683e-01,1,9.6463e-04,1.6747e-02,1,2.8463e-01,2.0237e-01,9.8954e-01,1,1,1,1,9.8954e-01,1,1,2.9490e-01,3.4110e-01,1,9.2622e-01,9.3345e-01,1,1,1,1,1,1,1,1,7.8109e-01,7.8109e-01,1,1,1,1,1,1,1,1,1,1,1,9.9653e-01,1,1,1,1,9.9653e-01,1,1,9.9842e-01,1,1,1,1,9.9842e-01,1,1
22Mg 12+ 12+ =5.4650e+01,5.4650e+01,0,5.4650e+01,6.5037e-01,1.4595e+00,2.1578e-05,4.0788e+01,4.9128e+00,4.6092e-01,6.8212e-01,6.8212e-01,1,1,9.9061e-01,1,1,1,9.9629e-01,1,1,1,1,1,9.9638e-01,1,2.3514e-03,4.4982e-02,1,2.7123e-01,1.9273e-01,9.8994e-01,1,1,1,1,9.8994e-01,1,1,2.6323e-02,2.9983e-02,1,9.3183e-01,9.4217e-01,1,1,1,1,1,1,1,1,7.6712e-01,7.6712e-01,1,1,1,1,1,1,1,1,1,1,1,9.9659e-01,1,1,1,1,9.9659e-01,1,1,9.9841e-01,1,1,1,1,9.9841e-01,1,1
25Na 11+ 10+ =5.8406e-03,5.8406e-03,0,5.8406e-03,2.4485e+00,5.4946e+00,6.1255e-10,4.2773e+01,3.8442e+00,4.6085e-01,6.8212e-01,6.8212e-01,1,1,9.9047e-01,1,1,1,1,1,1,1,1,1,1,1,1.9310e-05,2.9547e-04,1,3.0297e-01,2.1571e-01,1.0679e-03,1,1,1,1,9.8864e-01,1.0801e-03,1,9.8633e-02,1.1956e-01,1,9.1644e-01,9.0015e-01,1,1,1,1,1,1,1,1,6.5381e-01,6.5381e-01,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1
22Na 11+ 11+ =1.7820e+03,1.7820e+03,0,1.7820e+03,1.5371e+01,3.4493e+01,2.9772e-05,4.1344e+01,4.9647e+00,4.6093e-01,6.8212e-01,6.8212e-01,1,1,9.9065e-01,1,1,1,1,1,1,1,1,1,1,1,5.2471e-04,9.9552e-03,1,2.7234e-01,1.9353e-01,9.8951e-01,1,1,1,1,9.8951e-01,1,1,1.6418e-01,1.9259e-01,1,9.2478e-01,9.2183e-01,1,1,1,1,1,1,1,1,7.5808e-01,7.5808e-01,1,1,1,1,1,1,1,1,1,1,1,9.9656e-01,1,1,1,1,9.9656e-01,1,1,9.9846e-01,1,1,1,1,9.9846e-01,1,1
21Na 11+ 11+ =6.7058e+02,6.7058e+02,0,6.7058e+02,4.7838e+00,1.0735e+01,3.5997e-05,4.1051e+01,5.1550e+00,4.6096e-01,6.8212e-01,6.8212e-01,1,1,9.9071e-01,1,1,1,1,1,1,1,1,1,1,1,1.1406e-03,2.2732e-02,1,2.6579e-01,1.8879e-01,9.8990e-01,1,1,1,1,9.8990e-01,1,1,9.7453e-02,1.1179e-01,1,9.2980e-01,9.3756e-01,1,1,1,1,1,1,1,1,7.1003e-01,7.1003e-01,1,1,1,1,1,1,1,1,1,1,1,9.9662e-01,1,1,1,1,9.9662e-01,1,1,9.9844e-01,1,1,1,1,9.9844e-01,1,1
24Ne 10+ 9+ =2.8963e-06,2.8963e-06,0,2.8963e-06,3.1900e-01,7.1587e-01,2.3315e-12,4.2668e+01,4.3542e+00,4.6089e-01,6.8212e-01,6.8212e-01,1,1,9.9056e-01,1,1,1,1,1,1,1,1,1,1,1,1.6003e-05,2.6190e-04,1,2.9303e-01,2.0852e-01,1.5222e-03,1,1,1,1,9.8871e-01,1.5396e-03,1,4.2096e-04,5.1439e-04,1,9.1519e-01,8.9421e-01,1,1,1,1,1,1,1,1,4.9350e-01,4.9350e-01,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1
21Ne 10+ 10+ =5.2982e+01,5.2982e+01,0,5.2982e+01,1.7023e+01,3.8201e+01,7.9923e-07,4.1588e+01,5.1598e+00,4.6098e-01,6.8212e-01,6.8212e-01,1,1,9.9075e-01,1,1,1,1,1,1,1,1,1,1,1,2.4823e-04,4.9211e-03,1,2.6646e-01,1.8931e-01,9.8950e-01,1,1,1,1,9.8950e-01,1,1,9.2656e-03,1.1000e-02,1,9.2207e-01,9.1350e-01,1,1,1,1,1,1,1,1,7.6211e-01,7.6211e-01,1,1,1,1,1,1,1,1,1,1,1,9.9660e-01,1,1,1,1,9.9660e-01,1,1,9.9850e-01,1,1,1,1,9.9850e-01,1,1
20Ne 10+ 10+ =2.5181e+03,2.5181e+03,0,2.5181e+03,1.4529e+01,3.2605e+01,4.4504e-05,4.0876e+01,5.7789e+00,4.6101e-01,6.8212e-01,6.8212e-01,1,1,9.9081e-01,1,1,1,1,1,1,1,1,1,1,1,6.0049e-04,1.3424e-02,1,2.5105e-01,1.7819e-01,9.8987e-01,1,1,1,1,9.8987e-01,1,1,2.3147e-01,2.6992e-01,1,9.2552e-01,9.2656e-01,1,1,1,1,1,1,1,1,7.0191e-01,7.0191e-01,1,1,1,1,1,1,1,1,1,1,1,9.9665e-01,1,1,1,1,9.9665e-01,1,1,9.9846e-01,1,1,1,1,9.9846e-01,1,1
19F  9+ 9+ =2.0223e+03,2.0223e+03,0,2.0223e+03,1.4455e+01,3.2438e+01,3.5925e-05,4.0630e+01,6.4471e+00,4.6106e-01,6.8212e-01,6.8212e-01,1,1,9.9092e-01,1,1,1,1,1,1,1,1,1,1,1,3.3966e-04,8.3945e-03,1,2.3885e-01,1.6940e-01,9.8984e-01,1,1,1,1,9.8984e-01,1,1,2.8925e-01,3.4121e-01,1,9.2343e-01,9.1801e-01,1,1,1,1,1,1,1,1,8.0156e-01,8.0156e-01,1,1,1,1,1,1,1,1,1,1,1,9.9669e-01,1,1,1,1,9.9669e-01,1,1,9.9850e-01,1,1,1,1,9.9850e-01,1,1
18O  8+ 8+ =2.0766e+02,2.0766e+02,0,2.0766e+02,4.6524e+00,1.0440e+01,1.1462e-05,4.0856e+01,6.7714e+00,4.6110e-01,6.8212e-01,6.8212e-01,1,1,9.9103e-01,1,1,1,1,1,1,1,1,1,1,1,1.6559e-04,4.4412e-03,1,2.2933e-01,1.6258e-01,9.8984e-01,1,1,1,1,9.8984e-01,1,1,2.0864e-01,2.5306e-01,1,9.1574e-01,9.0034e-01,1,1,1,1,1,1,1,1,7.2717e-01,7.2717e-01,1,1,1,1,1,1,1,1,1,1,1,9.9675e-01,1,1,1,1,9.9675e-01,1,1,9.9856e-01,1,1,1,1,9.9856e-01,1,1
17O  8+ 8+ =2.6421e+00,2.6421e+00,0,2.6421e+00,1.2117e+01,2.7191e+01,5.5993e-08,4.0450e+01,7.1007e+00,4.6113e-01,6.8212e-01,6.8212e-01,1,1,9.9110e-01,1,1,1,1,1,1,1,1,1,1,1,3.1601e-04,9.1318e-03,1,2.2098e-01,1.5660e-01,9.9021e-01,1,1,1,1,9.9021e-01,1,1,4.8247e-04,5.6610e-04,1,9.2439e-01,9.2199e-01,1,1,1,1,1,1,1,1,8.0462e-01,8.0462e-01,1,1,1,1,1,1,1,1,1,1,1,9.9679e-01,1,1,1,1,9.9679e-01,1,1,9.9853e-01,1,1,1,1,9.9853e-01,1,1
17N  7+ 7+ =3.1502e-04,3.1502e-04,0,3.1502e-04,7.3868e-01,1.6577e+00,1.0951e-10,4.0516e+01,7.4958e+00,4.6113e-01,6.8212e-01,6.8212e-01,1,1,9.9114e-01,1,1,1,1,1,1,1,1,1,1,1,9.7013e-05,2.9173e-03,1,2.1664e-01,1.5350e-01,9.8987e-01,1,1,1,1,9.8987e-01,1,1,3.9643e-06,4.9663e-06,1,9.1159e-01,8.7564e-01,1,1,1,1,1,1,1,1,6.2407e-01,6.2407e-01,1,1,1,1,1,1,1,1,1,1,1,9.9682e-01,1,1,1,1,9.9682e-01,1,1,9.9863e-01,1,1,1,1,9.9863e-01,1,1
16N  7+ 7+ =1.4609e+02,1.4609e+02,0,1.4609e+02,3.5508e+00,7.9682e+00,1.0565e-05,4.0102e+01,7.8502e+00,4.6114e-01,6.8212e-01,6.8212e-01,1,1,9.9122e-01,1,1,1,1,1,1,1,1,1,1,1,1.7243e-04,5.6629e-03,1,2.0734e-01,1.4685e-01,9.9020e-01,1,1,1,1,9.9020e-01,1,1,2.0120e-01,2.4181e-01,1,9.2082e-01,9.0358e-01,1,1,1,1,1,1,1,1,6.6723e-01,6.6723e-01,1,1,1,1,1,1,1,1,1,1,1,9.9685e-01,1,1,1,1,9.9685e-01,1,1,9.9857e-01,1,1,1,1,9.9857e-01,1,1
15C  6+ 6+ =1.3167e+01,1.3167e+01,0,1.3167e+01,5.1570e-01,1.1573e+00,6.5562e-06,4.0830e+01,8.7735e+00,4.6111e-01,6.8212e-01,6.8212e-01,1,1,9.9134e-01,1,1,1,1,1,1,1,1,1,1,1,8.3407e-05,3.1595e-03,1,1.9312e-01,1.3670e-01,9.9024e-01,1,1,1,1,9.9024e-01,1,1,2.3837e-01,2.9817e-01,1,9.1157e-01,8.7700e-01,1,1,1,1,1,1,1,1,7.2253e-01,7.2253e-01,1,1,1,1,1,1,1,1,1,1,1,9.9693e-01,1,1,1,1,9.9693e-01,1,1,9.9865e-01,1,1,1,1,9.9865e-01,1,1
13B  5+ 5+ =5.2258e+00,5.2258e+00,0,5.2258e+00,3.5966e-01,8.0711e-01,3.7311e-06,4.2113e+01,1.0449e+01,4.6096e-01,6.8212e-01,6.8212e-01,1,1,9.9155e-01,1,1,1,1,1,1,1,1,1,1,1,6.0386e-05,2.9921e-03,1,1.6889e-01,1.1950e-01,9.9063e-01,1,1,1,1,9.9063e-01,1,1,2.0625e-01,2.5847e-01,1,9.1126e-01,8.7567e-01,1,1,1,1,1,1,1,1,6.5641e-01,6.5641e-01,1,1,1,1,1,1,1,1,1,1,1,9.9704e-01,1,1,1,1,9.9704e-01,1,1,9.9867e-01,1,1,1,1,9.9867e-01,1,1
12Be 4+ 4+ =6.0861e-05,6.0861e-05,0,6.0861e-05,7.8907e-02,1.7707e-01,1.9806e-10,4.3199e+01,1.1720e+01,4.6075e-01,6.8212e-01,6.8212e-01,1,1,9.9170e-01,1,9.9856e-01,1,1,1,1,1,1,1,1,1,2.7674e-05,1.6452e-03,1,1.5417e-01,1.0911e-01,9.9079e-01,1,1,1,1,9.9079e-01,1,1,3.8637e-05,5.2781e-05,1,8.8927e-01,8.2317e-01,1,1,1,1,1,1,1,1,4.0600e-01,4.0600e-01,1,1,1,1,1,1,1,1,1,1,1,9.9719e-01,1,1,1,1,9.9719e-01,1,1,9.9879e-01,1,1,1,1,9.9879e-01,1,1
11Be 4+ 4+ =2.2109e-04,2.2109e-04,0,2.2109e-04,7.5650e-01,1.6976e+00,7.5047e-11,4.3775e+01,1.2621e+01,4.6063e-01,6.8212e-01,6.8212e-01,1,1,9.9179e-01,1,9.9819e-01,1,1,1,1,1,1,1,1,1,3.9433e-05,2.7258e-03,1,1.4298e-01,1.0118e-01,9.9107e-01,1,1,1,1,9.9107e-01,1,1,7.3673e-06,9.3145e-06,1,9.0883e-01,8.7030e-01,1,1,1,1,1,1,1,1,5.6626e-01,5.6626e-01,1,1,1,1,1,1,1,1,1,1,1,9.9719e-01,1,1,1,1,9.9719e-01,1,1,9.9873e-01,1,1,1,1,9.9873e-01,1,1
