Version 9.9.1

{============================= Main Part ======================================}
[general]
                    File = C:\user\c\lise_pp_99\LISEpp_ActualInstaller\install\files\examples\dubna\acculinna_6he.lpp
                    Date = 29-12-2014
                    Time = 15:02:51
           Configuration = NSCL\A1900 - 4 dipoles.lcn
             Optionsfile = default.lopt
                   Title = NSCL A1900 Fragment Separator - 4dipoles
          BlockStructure = DWDMSMM

[settings]
                   A,Z,Q = 18O 8+                                ; Mass ElementName Charge+ Beam
                  Energy = 36                   MeV/u            
               Intensity = 1000                 pnA              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z =  6He                                  ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 2                    (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 10                   (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 2                    (±)mm            ; one-half the vertical beam extent (y)
                      BF = 10                   (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.5                  (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = 30.6                 degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-3.00,-50.0,3.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-50.0,3.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 32                                    ; Number of points in distribution
        NP charge states = 16                                    ; Number of points in distribution
                NP wedge = 16                                    ; Number of points in distribution
           Charge states = No                                    ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,4,1,9.012                           ; Nomer,Z,Atoms,Mass
        Target thickness = 1,350,1.85,0,0                        ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 0                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 1                                     ; calculate other reactions
           V calculation = 0                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 0                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 2                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 0                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 0                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-9     
               FisCS_TKE = 1e-6     
                      N0 = 82                                    ; default 82
                     dU0 = -2.5                                  ; default -2.5
                      C0 = 1.4                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -5.5                                  ; default -5.5
                      C1 = 0.16                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-4     
                 BeamInd = 1e-6     
               BeamTotal = 1e-8     

[convolution]
        Convolution mode = 0                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 5.758 
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 1                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 0                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
          AvoidUnboundCS = 1                                     ; 1-Yes, 0-No
       ProtectedChannels = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 6                    fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 0                                     ; 0 - no, 1 - use
         DissipationBeta = 2                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 1                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 1                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 1                                     ; 1-Yes, 0-No
                  mode_t = 1                                     ; 1-Yes, 0-No
                mode_3he = 1                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       

[evapauto]
                  tun_a0 = 1.00938
                  tun_a1 = -0.36149
                  tun_a2 = 0.21551
                 A_Bound = 300                                   ; mass
               A_Pairing =  70                                   ; mass

[plot]
            Start target = Detector                              ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = M3
         dE-detector-1st = M2
         dE-detector-2nd = M1
            TKE-detector = M2
                PlotBrho = D1
               PlotWedge = D2
              X-detector = M1
              Y-detector = M1
                 Tilting = M9
                 Stopper = M11
                RO_Wedge = 
          ConditionBlock = A10
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 2
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
                Velocity = 1                                     ; Calculat fissile nuclei speed
           LowEx_nucleus = 39Ar                                  ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 34S                                   ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 28Si                                  ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 1.800e+03 100.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 8
                   Dr_n0 = 0
                   Dr_n1 = 10

[cross sections]

[previous]
                 Lowerst =  3H                                   ; Mass ElementName Charge+ Beam
                 Highest = 18C                                   ; Mass ElementName Charge+ Beam

[MC_options]
                   dXsel = 0
                   dYsel = 2
                  dAZQ_X = 1
                  dAZQ_Y = 5
                  dVEL_X = 1
                  dVEL_Y = 0
               dIso_mode = 0
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 0
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 2
                  CS_use = 1
           envelope_show = 0
                use_bore = 0
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
              AZQ_Xsigma = 0.1   
              AZQ_Ysigma = 0.1   
                 G1_gate = 0 0 -100.0000 100.0000
                 G2_gate = 0 0 -100.0000 100.0000
                 G3_gate = 0 0 -100.0000 100.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 0 0,R1,R1,R1                          ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 0 0,R1,R1,R1
            G3_component = 0 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = D1,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 6.396000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-11.00,-50.0,11.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = -7.86300e-01,-6.30000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+6.01000e+00
                    row2 = +1.34650e+00,-1.16420e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.30300e-01
                    row3 = +0.00000e+00,+0.00000e+00,-2.03960e+00,+7.00000e-03,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-7.01100e-01,-4.87900e-01,+0.00000e+00,+0.00000e+00
                    row5 = +7.91100e-01,-7.01000e-01,+0.00000e+00,+0.00000e+00,+1.00000e+00,-7.52000e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 20                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 14                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 2.26405              Tm               ; magnetic rigidity
                   Angle = -30.6                degrees          
                  Radius = 3                    m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = Wedge,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,2.702,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W1_WedgeSettings]
             ProfileMode = 1                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 2                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = 0.00000              mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = Slits_Im2
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = D2,1                                  ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 6.397000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 2                                     ; number of quadrupoles before optic device
              After_Quad = 2                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-5.00,-50.0,5.00,50.0               ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = -2.17620e+00,+3.52300e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.24350e+01
                    row2 = +6.83890e-01,-4.60650e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.90750e+00
                    row3 = +0.00000e+00,+0.00000e+00,-5.06390e-01,-3.65950e-01,+0.00000e+00,+5.06390e-06
                    row4 = +0.00000e+00,+0.00000e+00,-4.43510e-01,-2.29370e+00,+0.00000e+00,+4.43510e-06
                    row5 = +1.96510e-04,-5.71220e-01,+0.00000e+00,+0.00000e+00,+1.00000e+00,-7.53730e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 25                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 11                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 2.26405              Tm               ; magnetic rigidity
                   Angle = -30.6                degrees          
                  Radius = 3                    m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = F3_PPAC,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 1,3,2.702,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,1                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,1,1              ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = Drift,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 8.790000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-10.00,-25.0,10.00,25.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-10.00,-25.0,10.00,25.0             ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = -1.58950e+00,+8.60000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.00000e-04
                    row2 = +4.94800e-01,-6.55300e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.00000e-04
                    row3 = +0.00000e+00,+0.00000e+00,+1.43380e+00,-6.72000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+9.20500e-01,+2.66100e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 8.79                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = F4_dE,1                               ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,300,2.321,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,1                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,1,1              ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-25.00,-25.0,25.00,25.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-25.00,-25.0,25.00,25.0             ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = F4_E,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,14,9,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 4,10,2.321,0,0                        ; State,Thickness,density,angle,SolidGas
                  Defect = 1,2                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 1,2                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,1,1              ns,mm,mm         ; Time&X&Y space

[M3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-75.00,-75.0,75.00,75.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M3_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= Calculations ======================================}

[Calculations]
17C  6+ 6+ =6.4257e-05,6.4257e-05,0,6.4257e-05,2.0981e-02,2.2496e-02,2.0951e-11,1.9438e+01,3.6112e+00,7.2778e-01,8.6874e-01,8.6874e-01,1,1,9.6433e-01,1,1,1,1,1,1,1,1,1,1,1,9.4322e-11,3.6546e-09,1,1.9874e-01,1.2986e-01,1,1,1,1,1,1,1,1,3.0594e-01,3.1406e-01,9.7419e-01,1,1,1,1,1,1,1,1,1,1,9.9773e-01,9.9773e-01,1,1,1,9.9684e-01,1,1,1,1,9.9684e-01,1,1,0,1,1,1,1,1,1,0
17B  5+ 5+ =3.1354e-01,3.1354e-01,0,3.1354e-01,1.3596e-06,1.4578e-06,1.5776e-03,1.7714e+01,4.5671e+00,7.2762e-01,8.6874e-01,8.6874e-01,1,1,9.6412e-01,1,1,1,1,1,1,1,1,1,1,1,2.5973e-03,1.1235e-01,1,1.8857e-01,1.2259e-01,1,1,1,1,1,1,1,1,8.5659e-01,8.9131e-01,9.7417e-01,9.8653e-01,1,1,1,1,1,1,1,1,1,9.7466e-01,9.7466e-01,1,1,1,9.9666e-01,1,1,1,1,9.9666e-01,1,1,0,1,1,1,1,1,1,0
15B  5+ 5+ =1.0109e+04,1.0109e+04,0,1.0109e+04,6.7982e-02,7.2888e-02,1.0173e-03,2.1201e+01,4.2440e+00,7.2849e-01,8.6874e-01,8.6874e-01,1,1,9.6527e-01,1,1,1,1,1,1,1,1,1,1,1,1.6697e-03,9.0246e-02,1,1.6989e-01,1.0891e-01,1,1,1,1,1,1,1,1,8.5797e-01,8.9273e-01,9.7413e-01,9.8658e-01,1,1,1,1,1,1,1,1,1,9.7492e-01,9.7492e-01,1,1,1,9.9692e-01,1,1,1,1,9.9692e-01,1,1,0,1,1,1,1,1,1,0
14B  5+ 5+ =1.2726e+04,1.2726e+04,0,1.2726e+04,5.6683e-01,6.0774e-01,1.5359e-04,2.1043e+01,4.7015e+00,7.2873e-01,8.6874e-01,8.6874e-01,1,1,9.6559e-01,1,1,1,1,1,1,1,1,1,1,1,2.5114e-04,1.6678e-02,1,1.5391e-01,9.7838e-02,1,1,1,1,1,1,1,1,8.5937e-01,8.9429e-01,9.7411e-01,9.8650e-01,1,1,1,1,1,1,1,1,1,9.7666e-01,9.7666e-01,1,1,1,9.9708e-01,1,1,1,1,9.9708e-01,1,1,0,1,1,1,1,1,1,0
13B  5+ 5+ =1.4916e+03,1.4916e+03,0,1.4916e+03,3.0423e+00,3.2619e+00,3.3541e-06,2.0507e+01,4.4852e+00,7.2898e-01,8.6874e-01,8.6874e-01,1,1,9.6591e-01,1,1,1,1,1,1,1,1,1,1,1,5.4448e-06,2.5245e-04,1,1.6662e-01,1.2944e-01,1,1,1,1,1,1,1,1,8.6315e-01,8.9813e-01,9.7408e-01,9.8663e-01,1,1,1,1,1,1,1,1,1,9.7913e-01,9.7913e-01,1,1,1,9.9726e-01,1,1,1,1,9.9726e-01,1,1,0,1,1,1,1,1,1,0
14Be 4+ 4+ =1.3107e+02,1.3107e+02,0,1.3107e+02,1.2728e-03,1.3647e-03,7.0446e-04,2.3019e+01,5.7665e+00,7.2897e-01,8.6874e-01,8.6874e-01,1,1,9.6590e-01,1,1,1,1,1,1,1,1,1,1,1,1.1581e-03,7.2805e-02,1,1.5810e-01,1.0061e-01,1,1,1,1,1,1,1,1,8.5636e-01,8.9117e-01,9.7412e-01,9.8647e-01,1,1,1,1,1,1,1,1,1,9.7455e-01,9.7455e-01,1,1,1,9.9685e-01,1,1,1,1,9.9685e-01,1,1,0,1,1,1,1,1,1,0
12Be 4+ 4+ =1.5887e+04,1.5887e+04,0,1.5887e+04,1.5436e-01,1.6550e-01,7.0410e-04,2.2406e+01,5.4025e+00,7.2951e-01,8.6874e-01,8.6874e-01,1,1,9.6662e-01,1,1,1,1,1,1,1,1,1,1,1,1.1567e-03,1.0808e-01,1,1.3069e-01,8.1886e-02,1,1,1,1,1,1,1,1,8.5634e-01,8.9124e-01,9.7408e-01,9.8641e-01,1,1,1,1,1,1,1,1,1,9.7453e-01,9.7453e-01,1,1,1,9.9715e-01,1,1,1,1,9.9715e-01,1,1,0,1,1,1,1,1,1,0
11Be 4+ 4+ =3.8262e+04,3.8262e+04,0,3.8262e+04,1.2576e+00,1.3483e+00,2.0814e-04,2.2204e+01,5.8448e+00,7.2979e-01,8.6874e-01,8.6874e-01,1,1,9.6699e-01,1,1,1,1,1,1,1,1,1,1,1,3.4119e-04,4.0016e-02,1,1.1706e-01,7.2835e-02,1,1,1,1,1,1,1,1,8.5696e-01,8.9191e-01,9.7406e-01,9.8640e-01,1,1,1,1,1,1,1,1,1,9.7557e-01,9.7557e-01,1,1,1,9.9734e-01,1,1,1,1,9.9734e-01,1,1,0,1,1,1,1,1,1,0
10Be 4+ 4+ =8.5128e+03,8.5128e+03,0,8.5128e+03,6.0976e+00,6.5377e+00,9.5507e-06,2.1638e+01,5.7162e+00,7.3008e-01,8.6874e-01,8.6874e-01,1,1,9.6737e-01,1,1,1,1,1,1,1,1,1,1,1,1.5610e-05,2.3152e-03,1,1.0440e-01,6.4582e-02,1,1,1,1,1,1,1,1,8.5850e-01,8.9353e-01,9.7404e-01,9.8640e-01,1,1,1,1,1,1,1,1,1,9.7625e-01,9.7625e-01,1,1,1,9.9758e-01,1,1,1,1,9.9758e-01,1,1,0,1,1,1,1,1,1,0
11Li 3+ 3+ =1.9794e+02,1.9794e+02,0,1.9794e+02,4.2515e-03,4.5583e-03,3.1850e-04,2.3983e+01,6.2812e+00,7.3005e-01,8.6874e-01,8.6874e-01,1,1,9.6734e-01,1,1,1,1,1,1,1,1,1,1,1,5.2296e-04,5.4532e-02,1,1.2385e-01,7.7433e-02,1,1,1,1,1,1,1,1,8.5618e-01,8.9109e-01,9.7407e-01,9.8641e-01,1,1,1,1,1,1,1,1,1,9.7450e-01,9.7450e-01,1,1,1,9.9706e-01,1,1,1,1,9.9706e-01,1,1,0,1,1,1,1,1,1,0
 9Li 3+ 3+ =3.0382e+04,3.0382e+04,0,3.0382e+04,5.6455e-01,6.0530e-01,3.6816e-04,2.3507e+01,6.7101e+00,7.3069e-01,8.6874e-01,8.6874e-01,1,1,9.6818e-01,1,1,1,1,1,1,1,1,1,1,1,6.0390e-04,1.0075e-01,1,9.8573e-02,6.0809e-02,1,1,1,1,1,1,1,1,8.5622e-01,8.9118e-01,9.7404e-01,9.8638e-01,1,1,1,1,1,1,1,1,1,9.7455e-01,9.7455e-01,1,1,1,9.9741e-01,1,1,1,1,9.9741e-01,1,1,0,1,1,1,1,1,1,0
 8Li 3+ 3+ =6.3743e+04,6.3743e+04,0,6.3743e+04,3.3513e+00,3.5931e+00,1.3012e-04,2.3345e+01,7.3097e+00,7.3100e-01,8.6874e-01,8.6874e-01,1,1,9.6863e-01,1,1,1,1,1,1,1,1,1,1,1,2.1315e-04,4.6575e-02,1,8.6413e-02,5.2961e-02,1,1,1,1,1,1,1,1,8.5626e-01,8.9127e-01,9.7402e-01,9.8634e-01,1,1,1,1,1,1,1,1,1,9.7540e-01,9.7540e-01,1,1,1,9.9766e-01,1,1,1,1,9.9766e-01,1,1,0,1,1,1,1,1,1,0
 7Li 3+ 3+ =1.2172e+04,1.2172e+04,0,1.2172e+04,1.1803e+01,1.2655e+01,7.0549e-06,2.2728e+01,7.2836e+00,7.3134e-01,8.6874e-01,8.6874e-01,1,1,9.6909e-01,1,1,1,1,1,1,1,1,1,1,1,1.1534e-05,3.3510e-03,1,7.5133e-02,4.5813e-02,1,1,1,1,1,1,1,1,8.5731e-01,8.9237e-01,9.7401e-01,9.8635e-01,1,1,1,1,1,1,1,1,1,9.7561e-01,9.7561e-01,1,1,1,9.9798e-01,1,1,1,1,9.9798e-01,1,1,0,1,1,1,1,1,1,0
 8He 2+ 2+ =2.7000e+02,2.7000e+02,0,2.7000e+02,2.1539e-02,2.3093e-02,8.5758e-05,2.5005e+01,7.7155e+00,7.3130e-01,8.6874e-01,8.6874e-01,1,1,9.6902e-01,1,1,1,1,1,1,1,1,1,1,1,1.4062e-04,2.7615e-02,1,9.1025e-02,5.5941e-02,1,1,1,1,1,1,1,1,8.5594e-01,8.9092e-01,9.7403e-01,9.8636e-01,1,1,1,1,1,1,1,1,1,9.7442e-01,9.7442e-01,1,1,1,9.9730e-01,1,1,1,1,9.9730e-01,1,1,0,1,1,1,1,1,1,0
 6He 2+ 2+ =4.0000e+04,4.0000e+04,0,4.0000e+04,1.9490e+00,2.0897e+00,1.4040e-04,2.5127e+01,9.3105e+00,7.3148e-01,8.6874e-01,8.6874e-01,1,1,9.7009e-01,1,1,1,1,1,1,1,1,1,1,1,2.3019e-04,8.0486e-02,1,6.8587e-02,4.1700e-02,1,1,1,1,1,1,1,1,8.5577e-01,8.9080e-01,9.7401e-01,9.8632e-01,1,1,1,1,1,1,1,1,1,9.7442e-01,9.7442e-01,1,1,1,9.9773e-01,1,1,1,1,9.9773e-01,1,1,0,1,1,1,1,1,1,0
 4He 2+ 2+ =3.1765e+03,3.1765e+03,0,3.1765e+03,1.4133e+01,1.5153e+01,1.5376e-06,2.4598e+01,1.0765e+01,7.2982e-01,8.6874e-01,8.6874e-01,1,1,9.7126e-01,1,9.9565e-01,1,1,1,1,1,1,1,1,1,2.5211e-06,1.9274e-03,1,4.6624e-02,2.8055e-02,1,1,1,1,1,1,1,1,8.5673e-01,8.9182e-01,9.7399e-01,9.8631e-01,1,1,1,1,1,1,1,1,1,9.7546e-01,9.7546e-01,1,1,1,9.9856e-01,1,1,1,1,9.9856e-01,1,1,9.4838e-01,1,1,1,1,9.4838e-01,1,1
 3H  1+ 1+ =2.9087e+04,2.9087e+04,0,2.9087e+04,5.5646e+00,5.9661e+00,3.5760e-05,2.6262e+01,1.2459e+01,7.3024e-01,8.6874e-01,8.6874e-01,1,1,9.7269e-01,1,9.9475e-01,1,1,1,1,1,1,1,1,1,5.8735e-05,6.1036e-02,1,4.0029e-02,2.4040e-02,1,1,1,1,1,1,1,1,8.5570e-01,8.9076e-01,9.7398e-01,9.8630e-01,1,1,1,1,1,1,1,1,1,9.7442e-01,9.7442e-01,1,1,1,9.9818e-01,1,1,1,1,9.9818e-01,1,1,9.3815e-01,1,1,1,1,9.3815e-01,1,1
