Version 9.9.1

{============================= Main Part ======================================}
[general]
                    File = C:\user\c\lise_pp_99\LISEpp_ActualInstaller\install\files\examples\GSI-SFRS\124Xe-100Sn-leb14std.lpp
                    Date = 29-12-2014
                    Time = 15:07:48
           Configuration = GSI\Super-FRS.lcn
             Optionsfile = A1900_2006.lopt
                   Title = Super-FRS pfrs3_m.dat
          BlockStructure = DSMWDMSDSDSMWDSSMDMS

[settings]
                   A,Z,Q = 124Xe54+                              ; Mass ElementName Charge+ Beam
                  Energy = 1000                 MeV/u            
               Intensity = 1e+12                pps              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 100Sn                                 ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 1                    (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 2                    (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 2                    (±)mm            ; one-half the vertical beam extent (y)
                      BF = 2                    (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.08                 (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = -56                  degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 64                                    ; Number of points in distribution
        NP charge states = 32                                    ; Number of points in distribution
                NP wedge = 16                                    ; Number of points in distribution
           Charge states = Yes                                   ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
        Target thickness = 5,4,1.84,0,0                          ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 0                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 1                                     ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 1                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 2                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 0                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 1                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-11    
               FisCS_TKE = 1e-8     
                      N0 = 83                                    ; default 82
                     dU0 = -2.65                                 ; default -2.5
                      C0 = 0.7                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -3.8                                  ; default -5.5
                      C1 = 0.15                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-5     
                 BeamInd = 1e-9     
               BeamTotal = 1e-11    

[convolution]
        Convolution mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 5.758 
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
          AvoidUnboundCS = 1                                     ; 1-Yes, 0-No
       ProtectedChannels = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 1                                     ; 0 - no, 1 - use
         DissipationBeta = 1                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 0                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 0                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       

[evapauto]
                  tun_a0 = -0.61392
                  tun_a1 = 0.44559
                  tun_a2 = 0.12008
                 A_Bound = 300                                   ; mass
               A_Pairing =  70                                   ; mass

[plot]
            Start target = Detector                              ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = M5
         dE-detector-1st = M5
         dE-detector-2nd = M6
            TKE-detector = M4
                PlotBrho = D1
               PlotWedge = S4
              X-detector = M4
              Y-detector = M5
                 Tilting = M1
                 Stopper = M2
                RO_Wedge = n
          ConditionBlock = A10
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 1
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
                Velocity = 1                                     ; Calculat fissile nuclei speed
           LowEx_nucleus = 237U 92+                              ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 232Th90+                              ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 226Ra88+                              ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 8.000e+02 250.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 1                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-5 
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 54
                   Dr_n0 = 0
                   Dr_n1 = 70

[cross sections]

[previous]
                 Lowerst = 97Cd48+                               ; Mass ElementName Charge+ Beam
                 Highest = 104Sb51+                              ; Mass ElementName Charge+ Beam

[MC_options]
                   dXsel = 0
                   dYsel = 2
                  dAZQ_X = 1
                  dAZQ_Y = 5
                  dVEL_X = 1
                  dVEL_Y = 0
               dIso_mode = 0
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 0
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 2
                  CS_use = 1
           envelope_show = 0
                use_bore = 0
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
              AZQ_Xsigma = 0.1   
              AZQ_Ysigma = 0.1   
                 G1_gate = 0 0 -100.0000 100.0000
                 G2_gate = 0 0 -100.0000 100.0000
                 G3_gate = 0 0 -100.0000 100.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 0 0,R1,R1,R1                          ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 0 0,R1,R1,R1
            G3_component = 0 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = TA->FPF2,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 35.599000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\OUTPUT\LISE_HEB14-FPF2.TXT
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = +1.72303e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.57611e+01
                    row2 = -5.52820e-01,+5.80370e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+5.00000e-05
                    row3 = +0.00000e+00,+0.00000e+00,-2.07009e+00,-5.00000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+8.54340e-01,-4.62450e-01,+0.00000e+00,+0.00000e+00
                    row5 = +1.42410e+00,-1.49510e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-7.31780e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_optics2]
                   row11 = +1.13306e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -1.37023e-02,-6.19245e-08,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-4.95189e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+3.06339e-02,-3.43895e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = -5.09841e-02,-3.88840e-06,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.94173e-06
                   row21 = +3.90849e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -3.23675e-03,+2.30771e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+1.13893e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,-1.30138e-02,+3.13184e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -3.62471e-02,+1.71743e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+4.97648e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -1.05864e-02,-3.96765e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +1.47447e-02,+9.15170e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+2.65980e-01,+1.81771e-05,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +1.18575e-02,-1.13916e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -3.43409e-03,+4.81160e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-1.63221e-01,-6.33665e-02,+0.00000e+00,+0.00000e+00
                   row51 = -5.06049e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +5.37932e-03,-5.94502e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-3.39876e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+2.04515e-02,-8.23822e-03,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +9.04680e-02,-5.91936e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-6.13250e-01
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D1_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  +1.3657e-05
                Line0001 = 3; 1;  0 0 0 0 0 0  -2.4646e-05
                Line0002 = 3; 4;  0 0 0 0 0 0  +1.4830e-05
                Line0003 = 3; 0;  0 0 1 0 0 0  -3.3463e-05
                Line0004 = 3; 1;  0 0 1 0 0 0  -2.2392e-05
                Line0005 = 3; 4;  0 0 1 0 0 0  -3.0348e-07
                Line0006 = 3; 0;  0 1 1 0 0 0  -5.8628e-05
                Line0007 = 3; 1;  0 1 1 0 0 0  -5.4884e-07
                Line0008 = 3; 4;  0 1 1 0 0 0  +1.0124e-05
                Line0009 = 3; 0;  1 1 1 0 0 0  +6.3365e-05
                Line0010 = 3; 1;  1 1 1 0 0 0  -1.7052e-06
                Line0011 = 3; 4;  1 1 1 0 0 0  +1.3318e-05
                Line0012 = 3; 2;  0 0 2 0 0 0  +1.0307e-03
                Line0013 = 3; 3;  0 0 2 0 0 0  +2.4915e-04
                Line0014 = 3; 2;  0 1 2 0 0 0  -3.8349e-04
                Line0015 = 3; 3;  0 1 2 0 0 0  -1.1160e-04
                Line0016 = 3; 2;  1 1 2 0 0 0  +6.4537e-05
                Line0017 = 3; 3;  1 1 2 0 0 0  +9.6465e-06
                Line0018 = 3; 0;  0 2 2 0 0 0  -1.5351e-03
                Line0019 = 3; 1;  0 2 2 0 0 0  -6.9237e-04
                Line0020 = 3; 4;  0 2 2 0 0 0  -2.8730e-04
                Line0021 = 3; 0;  1 2 2 0 0 0  +5.2269e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  +6.5351e-06
                Line0023 = 3; 4;  1 2 2 0 0 0  +2.0310e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  +1.1557e-03
                Line0025 = 3; 3;  2 2 2 0 0 0  +4.9320e-05
                Line0026 = 3; 2;  0 0 3 0 0 0  -4.4439e-04
                Line0027 = 3; 3;  0 0 3 0 0 0  -1.0780e-04
                Line0028 = 3; 2;  0 1 3 0 0 0  +2.1840e-04
                Line0029 = 3; 3;  0 1 3 0 0 0  +6.2928e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -2.2799e-04
                Line0031 = 3; 3;  1 1 3 0 0 0  +3.8208e-05
                Line0032 = 3; 0;  0 2 3 0 0 0  +1.2983e-03
                Line0033 = 3; 1;  0 2 3 0 0 0  +5.1300e-04
                Line0034 = 3; 4;  0 2 3 0 0 0  +2.8714e-04
                Line0035 = 3; 0;  1 2 3 0 0 0  -4.9414e-04
                Line0036 = 3; 1;  1 2 3 0 0 0  -9.8834e-06
                Line0037 = 3; 4;  1 2 3 0 0 0  -4.4090e-05
                Line0038 = 3; 2;  2 2 3 0 0 0  -1.2385e-03
                Line0039 = 3; 3;  2 2 3 0 0 0  +2.5189e-05
                Line0040 = 3; 0;  0 0 5 0 0 0  -3.0902e-04
                Line0041 = 3; 1;  0 0 5 0 0 0  +1.2216e-03
                Line0042 = 3; 4;  0 0 5 0 0 0  -5.5710e-04
                Line0043 = 3; 0;  0 1 5 0 0 0  +1.8786e-04
                Line0044 = 3; 1;  0 1 5 0 0 0  +1.1449e-04
                Line0045 = 3; 4;  0 1 5 0 0 0  +1.8781e-04
                Line0046 = 3; 0;  1 1 5 0 0 0  +4.4838e-04
                Line0047 = 3; 1;  1 1 5 0 0 0  -3.8918e-05
                Line0048 = 3; 4;  1 1 5 0 0 0  -2.3242e-04
                Line0049 = 3; 2;  0 2 5 0 0 0  -2.8317e-02
                Line0050 = 3; 3;  0 2 5 0 0 0  -6.6080e-03
                Line0051 = 3; 2;  1 2 5 0 0 0  +5.9311e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  +1.3488e-03
                Line0053 = 3; 0;  2 2 5 0 0 0  +1.6426e-02
                Line0054 = 3; 1;  2 2 5 0 0 0  +7.5122e-03
                Line0055 = 3; 4;  2 2 5 0 0 0  +8.5651e-03
                Line0056 = 3; 0;  0 3 3 0 0 0  -2.6563e-04
                Line0057 = 3; 1;  0 3 3 0 0 0  -8.7773e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  -6.6840e-05
                Line0059 = 3; 0;  1 3 3 0 0 0  +2.1231e-04
                Line0060 = 3; 1;  1 3 3 0 0 0  -3.8289e-05
                Line0061 = 3; 4;  1 3 3 0 0 0  +9.8651e-05
                Line0062 = 3; 2;  2 3 3 0 0 0  +2.1534e-04
                Line0063 = 3; 3;  2 3 3 0 0 0  +7.6702e-05
                Line0064 = 3; 2;  0 3 5 0 0 0  +1.3684e-02
                Line0065 = 3; 3;  0 3 5 0 0 0  +1.5640e-03
                Line0066 = 3; 2;  1 3 5 0 0 0  +1.7569e-03
                Line0067 = 3; 3;  1 3 5 0 0 0  +5.3694e-04
                Line0068 = 3; 0;  2 3 5 0 0 0  -1.1840e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  -8.4472e-03
                Line0070 = 3; 4;  2 3 5 0 0 0  +1.2814e-03
                Line0071 = 3; 0;  0 5 5 0 0 0  +3.2750e-03
                Line0072 = 3; 1;  0 5 5 0 0 0  -1.6958e-02
                Line0073 = 3; 4;  0 5 5 0 0 0  +7.8227e-03
                Line0074 = 3; 0;  1 5 5 0 0 0  -4.7077e-03
                Line0075 = 3; 1;  1 5 5 0 0 0  +9.1554e-04
                Line0076 = 3; 4;  1 5 5 0 0 0  -2.8843e-03
                Line0077 = 3; 2;  2 5 5 0 0 0  +2.0742e-01
                Line0078 = 3; 3;  2 5 5 0 0 0  +4.9926e-02
                Line0079 = 3; 2;  3 3 3 0 0 0  -1.5009e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  +6.3199e-05
                Line0081 = 3; 0;  3 3 5 0 0 0  -1.0748e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  +2.5946e-03
                Line0083 = 3; 4;  3 3 5 0 0 0  -1.3330e-03
                Line0084 = 3; 2;  3 5 5 0 0 0  -1.1731e-01
                Line0085 = 3; 3;  3 5 5 0 0 0  -4.8572e-03
                Line0086 = 3; 0;  5 5 5 0 0 0  -4.7880e-04
                Line0087 = 3; 1;  5 5 5 0 0 0  +7.1825e-02
                Line0088 = 3; 4;  5 5 5 0 0 0  -2.9629e-02

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 38                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 20                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 9.66086              Tm               ; magnetic rigidity
                   Angle = 33                   degrees          
                  Radius = 12.5                 m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = Beam-blocker,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-17.00,-190.0,190.00,190.0          ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = FPF2-MW,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = FPF2degrader,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 5,5.7,2.702,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W1_WedgeSettings]
             ProfileMode = 0                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 0                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = -15.10757            mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = FPF4-slit
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = FPF2->FPF4,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 35.900000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\OUTPUT\LISE_HEB14-FPF4.TXT
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = +1.16074e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.99017e+01
                    row2 = -4.76500e-02,+8.61520e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.22751e+00
                    row3 = +0.00000e+00,+0.00000e+00,-7.53370e-01,-4.82000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+5.23980e-01,-1.29382e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+2.57610e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-5.62660e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_optics2]
                   row11 = +6.42725e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -1.33237e-02,+2.14419e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+8.88794e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+1.57500e-02,+1.39590e-02,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +4.52069e-02,-3.43239e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+7.38069e-01
                   row21 = +6.39238e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -4.07138e-04,+4.94446e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-3.85484e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,-7.28508e-04,+8.77866e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +2.28480e-02,-1.94630e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.21457e-01
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -3.25919e-05,-1.01485e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +1.63601e-02,-1.74652e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-2.20617e-03,+4.28241e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +1.09810e-03,+9.09128e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -1.12525e-02,+3.01584e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-8.02139e-02,-2.99199e-01,+0.00000e+00,+0.00000e+00
                   row51 = +5.84242e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +1.04175e-03,-4.81914e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-3.92552e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,-3.21308e-04,-4.93032e-04,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +4.00638e-02,+5.26016e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-9.10558e-02
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D2_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  -2.6328e-06
                Line0001 = 3; 1;  0 0 0 0 0 0  -4.6194e-06
                Line0002 = 3; 4;  0 0 0 0 0 0  -1.0345e-05
                Line0003 = 3; 0;  0 0 1 0 0 0  -7.0522e-05
                Line0004 = 3; 1;  0 0 1 0 0 0  -5.4641e-06
                Line0005 = 3; 4;  0 0 1 0 0 0  -4.8210e-06
                Line0006 = 3; 0;  0 1 1 0 0 0  +2.8291e-04
                Line0007 = 3; 1;  0 1 1 0 0 0  +3.5200e-05
                Line0008 = 3; 4;  0 1 1 0 0 0  +3.7496e-05
                Line0009 = 3; 0;  1 1 1 0 0 0  -3.7201e-04
                Line0010 = 3; 1;  1 1 1 0 0 0  -1.6997e-05
                Line0011 = 3; 4;  1 1 1 0 0 0  -3.0645e-05
                Line0012 = 3; 2;  0 0 2 0 0 0  -7.5110e-06
                Line0013 = 3; 3;  0 0 2 0 0 0  +2.9084e-05
                Line0014 = 3; 2;  0 1 2 0 0 0  -2.5479e-04
                Line0015 = 3; 3;  0 1 2 0 0 0  +2.0958e-06
                Line0016 = 3; 2;  1 1 2 0 0 0  +4.0612e-04
                Line0017 = 3; 3;  1 1 2 0 0 0  +1.2112e-04
                Line0018 = 3; 0;  0 2 2 0 0 0  -7.6473e-05
                Line0019 = 3; 1;  0 2 2 0 0 0  -1.0947e-05
                Line0020 = 3; 4;  0 2 2 0 0 0  -1.5057e-05
                Line0021 = 3; 0;  1 2 2 0 0 0  +3.4255e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  +3.3470e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  -7.4986e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  +1.9886e-05
                Line0025 = 3; 3;  2 2 2 0 0 0  +9.8685e-06
                Line0026 = 3; 2;  0 0 3 0 0 0  -1.7756e-04
                Line0027 = 3; 3;  0 0 3 0 0 0  +1.1490e-04
                Line0028 = 3; 2;  0 1 3 0 0 0  +2.6223e-04
                Line0029 = 3; 3;  0 1 3 0 0 0  +2.3369e-04
                Line0030 = 3; 2;  1 1 3 0 0 0  -1.5567e-03
                Line0031 = 3; 3;  1 1 3 0 0 0  +1.9764e-04
                Line0032 = 3; 0;  0 2 3 0 0 0  +3.6139e-04
                Line0033 = 3; 1;  0 2 3 0 0 0  -6.4887e-07
                Line0034 = 3; 4;  0 2 3 0 0 0  -1.8541e-06
                Line0035 = 3; 0;  1 2 3 0 0 0  -1.5580e-03
                Line0036 = 3; 1;  1 2 3 0 0 0  -2.5028e-04
                Line0037 = 3; 4;  1 2 3 0 0 0  -2.1738e-04
                Line0038 = 3; 2;  2 2 3 0 0 0  -1.7359e-04
                Line0039 = 3; 3;  2 2 3 0 0 0  +3.4025e-05
                Line0040 = 3; 0;  0 0 5 0 0 0  -9.0347e-05
                Line0041 = 3; 1;  0 0 5 0 0 0  -7.5654e-05
                Line0042 = 3; 4;  0 0 5 0 0 0  -1.1942e-04
                Line0043 = 3; 0;  0 1 5 0 0 0  -2.8962e-03
                Line0044 = 3; 1;  0 1 5 0 0 0  -3.4975e-04
                Line0045 = 3; 4;  0 1 5 0 0 0  -4.5114e-04
                Line0046 = 3; 0;  1 1 5 0 0 0  +6.2659e-03
                Line0047 = 3; 1;  1 1 5 0 0 0  +5.7214e-04
                Line0048 = 3; 4;  1 1 5 0 0 0  +1.9454e-04
                Line0049 = 3; 2;  0 2 5 0 0 0  +1.0153e-03
                Line0050 = 3; 3;  0 2 5 0 0 0  +1.0637e-04
                Line0051 = 3; 2;  1 2 5 0 0 0  -6.3328e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  -7.8159e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  -1.6096e-03
                Line0054 = 3; 1;  2 2 5 0 0 0  -1.6742e-04
                Line0055 = 3; 4;  2 2 5 0 0 0  +7.1102e-04
                Line0056 = 3; 0;  0 3 3 0 0 0  -4.9183e-04
                Line0057 = 3; 1;  0 3 3 0 0 0  -1.7689e-04
                Line0058 = 3; 4;  0 3 3 0 0 0  -5.5066e-04
                Line0059 = 3; 0;  1 3 3 0 0 0  +2.1886e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  +1.9731e-05
                Line0061 = 3; 4;  1 3 3 0 0 0  -7.6215e-05
                Line0062 = 3; 2;  2 3 3 0 0 0  -7.2045e-05
                Line0063 = 3; 3;  2 3 3 0 0 0  +3.8675e-04
                Line0064 = 3; 2;  0 3 5 0 0 0  -2.6123e-04
                Line0065 = 3; 3;  0 3 5 0 0 0  -3.9153e-04
                Line0066 = 3; 2;  1 3 5 0 0 0  +7.6559e-03
                Line0067 = 3; 3;  1 3 5 0 0 0  +2.4170e-03
                Line0068 = 3; 0;  2 3 5 0 0 0  +9.1182e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  +1.4889e-03
                Line0070 = 3; 4;  2 3 5 0 0 0  +2.8957e-03
                Line0071 = 3; 0;  0 5 5 0 0 0  +7.6199e-05
                Line0072 = 3; 1;  0 5 5 0 0 0  -3.9051e-04
                Line0073 = 3; 4;  0 5 5 0 0 0  -1.8754e-04
                Line0074 = 3; 0;  1 5 5 0 0 0  -3.6763e-02
                Line0075 = 3; 1;  1 5 5 0 0 0  -4.5438e-03
                Line0076 = 3; 4;  1 5 5 0 0 0  -3.1553e-03
                Line0077 = 3; 2;  2 5 5 0 0 0  +2.1362e-02
                Line0078 = 3; 3;  2 5 5 0 0 0  +5.8095e-03
                Line0079 = 3; 2;  3 3 3 0 0 0  -6.8217e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  +6.5487e-04
                Line0081 = 3; 0;  3 3 5 0 0 0  -1.3326e-02
                Line0082 = 3; 1;  3 3 5 0 0 0  +3.7422e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  +9.3813e-04
                Line0084 = 3; 2;  3 5 5 0 0 0  -1.2337e-03
                Line0085 = 3; 3;  3 5 5 0 0 0  +1.1015e-02
                Line0086 = 3; 0;  5 5 5 0 0 0  +3.7291e-02
                Line0087 = 3; 1;  5 5 5 0 0 0  +3.0773e-03
                Line0088 = 3; 4;  5 5 5 0 0 0  +2.9757e-03

[D2_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 25                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 13.5                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 7.18896              Tm               ; magnetic rigidity
                   Angle = 33                   degrees          
                  Radius = 12.5                 m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = FPF4-MW,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = FPF4-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-10.00,-190.0,6.00,190.0            ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK D3 - Dipole ======================================}

[D3_General]
                    Name = FPF4->FMF1,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 26.581000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\OUTPUT\LISE_HEB14-FMF1.TXT
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D1.cal

[D3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D3_optics]
                    row1 = -2.10584e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+6.39979e+01
                    row2 = -1.72000e-03,-4.74870e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.18360e+00
                    row3 = +0.00000e+00,+0.00000e+00,-1.09307e+00,+2.73000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+1.82240e-01,-9.19400e-01,+0.00000e+00,+0.00000e+00
                    row5 = +2.38260e-01,-3.03910e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-3.64180e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D3_optics2]
                   row11 = -4.67394e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +1.73374e-02,+2.61654e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-5.03058e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-1.28072e-02,+1.12292e-02,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +1.18851e-03,+5.51799e-06,+0.00000e+00,+0.00000e+00,+0.00000e+00,+5.65387e-06
                   row21 = +1.41862e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +2.24933e-04,-1.95480e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-9.55761e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+3.61737e-03,-2.84499e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -4.81825e-03,-2.68001e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+7.99959e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -8.24085e-03,-6.66080e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +1.29311e-02,+1.14915e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+2.54245e-01,-2.36118e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -2.30709e-03,+1.54761e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +4.83317e-03,+3.64798e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,+4.90650e-02,-1.75708e-01,+0.00000e+00,+0.00000e+00
                   row51 = -3.63124e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = -6.68967e-04,-1.25105e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-9.59255e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+1.15211e-03,-8.42982e-03,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +7.59037e-03,-3.21070e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.00741e-01
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D3_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  +2.2523e-05
                Line0001 = 3; 1;  0 0 0 0 0 0  +8.0706e-06
                Line0002 = 3; 4;  0 0 0 0 0 0  +4.3021e-08
                Line0003 = 3; 0;  0 0 1 0 0 0  -3.1729e-05
                Line0004 = 3; 1;  0 0 1 0 0 0  -1.5596e-05
                Line0005 = 3; 4;  0 0 1 0 0 0  +4.7592e-06
                Line0006 = 3; 0;  0 1 1 0 0 0  -3.2330e-05
                Line0007 = 3; 1;  0 1 1 0 0 0  +7.9957e-06
                Line0008 = 3; 4;  0 1 1 0 0 0  +1.1714e-05
                Line0009 = 3; 0;  1 1 1 0 0 0  -7.3892e-05
                Line0010 = 3; 1;  1 1 1 0 0 0  -8.1755e-06
                Line0011 = 3; 4;  1 1 1 0 0 0  -2.2307e-05
                Line0012 = 3; 2;  0 0 2 0 0 0  -1.3911e-05
                Line0013 = 3; 3;  0 0 2 0 0 0  -7.7206e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -1.0501e-04
                Line0015 = 3; 3;  0 1 2 0 0 0  +5.5139e-07
                Line0016 = 3; 2;  1 1 2 0 0 0  +1.1836e-04
                Line0017 = 3; 3;  1 1 2 0 0 0  +8.4547e-05
                Line0018 = 3; 0;  0 2 2 0 0 0  +2.4562e-05
                Line0019 = 3; 1;  0 2 2 0 0 0  -4.7604e-06
                Line0020 = 3; 4;  0 2 2 0 0 0  +5.9643e-06
                Line0021 = 3; 0;  1 2 2 0 0 0  -2.3584e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  -1.9093e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  -3.8332e-07
                Line0024 = 3; 2;  2 2 2 0 0 0  +2.9735e-05
                Line0025 = 3; 3;  2 2 2 0 0 0  +1.0682e-05
                Line0026 = 3; 2;  0 0 3 0 0 0  -2.8514e-05
                Line0027 = 3; 3;  0 0 3 0 0 0  +7.5024e-06
                Line0028 = 3; 2;  0 1 3 0 0 0  +1.0198e-04
                Line0029 = 3; 3;  0 1 3 0 0 0  +2.0296e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -1.2767e-03
                Line0031 = 3; 3;  1 1 3 0 0 0  +7.3053e-05
                Line0032 = 3; 0;  0 2 3 0 0 0  -2.3147e-04
                Line0033 = 3; 1;  0 2 3 0 0 0  +5.9785e-06
                Line0034 = 3; 4;  0 2 3 0 0 0  -1.9512e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  +6.6207e-04
                Line0036 = 3; 1;  1 2 3 0 0 0  +7.5921e-05
                Line0037 = 3; 4;  1 2 3 0 0 0  +9.5279e-05
                Line0038 = 3; 2;  2 2 3 0 0 0  -2.4379e-04
                Line0039 = 3; 3;  2 2 3 0 0 0  -6.0958e-05
                Line0040 = 3; 0;  0 0 5 0 0 0  -1.9459e-03
                Line0041 = 3; 1;  0 0 5 0 0 0  -6.9682e-04
                Line0042 = 3; 4;  0 0 5 0 0 0  +6.4489e-06
                Line0043 = 3; 0;  0 1 5 0 0 0  +1.9965e-03
                Line0044 = 3; 1;  0 1 5 0 0 0  +9.1915e-04
                Line0045 = 3; 4;  0 1 5 0 0 0  -1.5214e-04
                Line0046 = 3; 0;  1 1 5 0 0 0  -1.3221e-03
                Line0047 = 3; 1;  1 1 5 0 0 0  -2.2799e-04
                Line0048 = 3; 4;  1 1 5 0 0 0  -4.8991e-05
                Line0049 = 3; 2;  0 2 5 0 0 0  +1.4656e-03
                Line0050 = 3; 3;  0 2 5 0 0 0  +6.5796e-04
                Line0051 = 3; 2;  1 2 5 0 0 0  +3.6804e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  +4.2238e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  -4.3377e-04
                Line0054 = 3; 1;  2 2 5 0 0 0  +2.7542e-04
                Line0055 = 3; 4;  2 2 5 0 0 0  -5.2389e-05
                Line0056 = 3; 0;  0 3 3 0 0 0  +1.9969e-04
                Line0057 = 3; 1;  0 3 3 0 0 0  +1.3626e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  +5.8267e-05
                Line0059 = 3; 0;  1 3 3 0 0 0  -2.5601e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  -5.1054e-05
                Line0061 = 3; 4;  1 3 3 0 0 0  +2.7627e-04
                Line0062 = 3; 2;  2 3 3 0 0 0  +3.2911e-04
                Line0063 = 3; 3;  2 3 3 0 0 0  +1.7420e-04
                Line0064 = 3; 2;  0 3 5 0 0 0  +1.5883e-03
                Line0065 = 3; 3;  0 3 5 0 0 0  -1.4394e-04
                Line0066 = 3; 2;  1 3 5 0 0 0  -4.9863e-03
                Line0067 = 3; 3;  1 3 5 0 0 0  -5.3667e-04
                Line0068 = 3; 0;  2 3 5 0 0 0  +3.9231e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  -2.4376e-04
                Line0070 = 3; 4;  2 3 5 0 0 0  +9.5786e-04
                Line0071 = 3; 0;  0 5 5 0 0 0  +5.7843e-02
                Line0072 = 3; 1;  0 5 5 0 0 0  +2.0164e-02
                Line0073 = 3; 4;  0 5 5 0 0 0  -7.6326e-05
                Line0074 = 3; 0;  1 5 5 0 0 0  -2.9088e-02
                Line0075 = 3; 1;  1 5 5 0 0 0  -1.3069e-02
                Line0076 = 3; 4;  1 5 5 0 0 0  +9.9556e-04
                Line0077 = 3; 2;  2 5 5 0 0 0  -3.2372e-02
                Line0078 = 3; 3;  2 5 5 0 0 0  -1.1692e-02
                Line0079 = 3; 2;  3 3 3 0 0 0  -4.4286e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  -2.2366e-05
                Line0081 = 3; 0;  3 3 5 0 0 0  -3.6297e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  -5.9268e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  -1.3015e-03
                Line0084 = 3; 2;  3 5 5 0 0 0  -2.6684e-02
                Line0085 = 3; 3;  3 5 5 0 0 0  +1.6983e-03
                Line0086 = 3; 0;  5 5 5 0 0 0  -5.6997e-01
                Line0087 = 3; 1;  5 5 5 0 0 0  -1.9429e-01
                Line0088 = 3; 4;  5 5 5 0 0 0  +1.6407e-03

[D3_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 25.5                 mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 15                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D3_DipoleSettings]
                    Brho = 7.18896              Tm               ; magnetic rigidity
                   Angle = 29.25                degrees          
                  Radius = 12.5                 m                

[D3_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = FMF1-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-190.00,-190.0,50.00,190.0          ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK D4 - Dipole ======================================}

[D4_General]
                    Name = FMF1->FMF2,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 25.780000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\OUTPUT\LISE_HEB14-FMF2.TXT
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D2.cal

[D4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D4_optics]
                    row1 = -4.09780e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.62252e+01
                    row2 = -2.20700e-02,-2.44031e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+4.30069e+00
                    row3 = +0.00000e+00,+0.00000e+00,-1.15471e+00,+1.10200e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+2.47290e-01,-8.89610e-01,+0.00000e+00,+0.00000e+00
                    row5 = +2.34110e-01,+6.39980e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-3.64180e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D4_optics2]
                   row11 = -8.31427e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -2.54281e-03,-2.03732e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-1.59884e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+7.13375e-03,-2.26663e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +5.93095e-03,+1.62745e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.90470e-02
                   row21 = +1.00522e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +8.53314e-04,+7.57136e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-6.23385e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+2.37313e-04,-3.65870e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -2.90673e-03,-2.65554e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-7.42926e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +1.18010e-04,+1.92421e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +3.35358e-03,-1.08559e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-1.24441e-01,+3.39167e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -4.06614e-04,+2.63699e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -7.70303e-04,-1.27512e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-4.21654e-02,+2.72611e-02,+0.00000e+00,+0.00000e+00
                   row51 = -2.98487e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = -2.59158e-03,-3.97134e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-1.50788e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+7.81748e-03,-4.61774e-03,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +3.25924e-03,+8.27056e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.17200e-01
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D4_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  -5.7222e-07
                Line0001 = 3; 1;  0 0 0 0 0 0  +1.4246e-06
                Line0002 = 3; 4;  0 0 0 0 0 0  -3.4581e-06
                Line0003 = 3; 0;  0 0 1 0 0 0  -4.9765e-06
                Line0004 = 3; 1;  0 0 1 0 0 0  +1.0854e-05
                Line0005 = 3; 4;  0 0 1 0 0 0  -2.3724e-05
                Line0006 = 3; 0;  0 1 1 0 0 0  -4.6982e-05
                Line0007 = 3; 1;  0 1 1 0 0 0  +2.3836e-05
                Line0008 = 3; 4;  0 1 1 0 0 0  -5.4492e-05
                Line0009 = 3; 0;  1 1 1 0 0 0  +2.6851e-04
                Line0010 = 3; 1;  1 1 1 0 0 0  +7.0354e-05
                Line0011 = 3; 4;  1 1 1 0 0 0  +6.4492e-06
                Line0012 = 3; 2;  0 0 2 0 0 0  +5.2761e-06
                Line0013 = 3; 3;  0 0 2 0 0 0  -2.5139e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -1.4203e-05
                Line0015 = 3; 3;  0 1 2 0 0 0  -2.3606e-05
                Line0016 = 3; 2;  1 1 2 0 0 0  +1.3291e-03
                Line0017 = 3; 3;  1 1 2 0 0 0  +2.5801e-04
                Line0018 = 3; 0;  0 2 2 0 0 0  +6.7660e-06
                Line0019 = 3; 1;  0 2 2 0 0 0  -2.4991e-06
                Line0020 = 3; 4;  0 2 2 0 0 0  +1.3342e-05
                Line0021 = 3; 0;  1 2 2 0 0 0  -2.6635e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  -3.4857e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  +2.3455e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  +1.8891e-05
                Line0025 = 3; 3;  2 2 2 0 0 0  +5.9297e-06
                Line0026 = 3; 2;  0 0 3 0 0 0  +1.3430e-05
                Line0027 = 3; 3;  0 0 3 0 0 0  -5.5990e-06
                Line0028 = 3; 2;  0 1 3 0 0 0  +6.6790e-05
                Line0029 = 3; 3;  0 1 3 0 0 0  -2.6776e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -2.7653e-03
                Line0031 = 3; 3;  1 1 3 0 0 0  -6.4626e-04
                Line0032 = 3; 0;  0 2 3 0 0 0  +6.1954e-06
                Line0033 = 3; 1;  0 2 3 0 0 0  -2.1708e-05
                Line0034 = 3; 4;  0 2 3 0 0 0  +5.2934e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  +1.1254e-03
                Line0036 = 3; 1;  1 2 3 0 0 0  +6.7554e-05
                Line0037 = 3; 4;  1 2 3 0 0 0  +1.6282e-04
                Line0038 = 3; 2;  2 2 3 0 0 0  -1.3113e-04
                Line0039 = 3; 3;  2 2 3 0 0 0  -1.0312e-05
                Line0040 = 3; 0;  0 0 5 0 0 0  -1.1867e-05
                Line0041 = 3; 1;  0 0 5 0 0 0  -9.5262e-07
                Line0042 = 3; 4;  0 0 5 0 0 0  -2.1106e-06
                Line0043 = 3; 0;  0 1 5 0 0 0  +1.3626e-04
                Line0044 = 3; 1;  0 1 5 0 0 0  +7.4615e-05
                Line0045 = 3; 4;  0 1 5 0 0 0  -7.4955e-05
                Line0046 = 3; 0;  1 1 5 0 0 0  -2.9915e-03
                Line0047 = 3; 1;  1 1 5 0 0 0  -5.0588e-04
                Line0048 = 3; 4;  1 1 5 0 0 0  -1.8038e-04
                Line0049 = 3; 2;  0 2 5 0 0 0  +2.9009e-04
                Line0050 = 3; 3;  0 2 5 0 0 0  +7.7100e-05
                Line0051 = 3; 2;  1 2 5 0 0 0  -7.2898e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  -1.6859e-03
                Line0053 = 3; 0;  2 2 5 0 0 0  +9.2559e-04
                Line0054 = 3; 1;  2 2 5 0 0 0  +1.5799e-04
                Line0055 = 3; 4;  2 2 5 0 0 0  +1.7502e-04
                Line0056 = 3; 0;  0 3 3 0 0 0  -3.5093e-06
                Line0057 = 3; 1;  0 3 3 0 0 0  -2.5251e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  +3.7959e-05
                Line0059 = 3; 0;  1 3 3 0 0 0  -1.0512e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  -1.6022e-04
                Line0061 = 3; 4;  1 3 3 0 0 0  -7.8090e-05
                Line0062 = 3; 2;  2 3 3 0 0 0  +1.4945e-04
                Line0063 = 3; 3;  2 3 3 0 0 0  +7.7973e-05
                Line0064 = 3; 2;  0 3 5 0 0 0  +2.3639e-04
                Line0065 = 3; 3;  0 3 5 0 0 0  +4.6300e-05
                Line0066 = 3; 2;  1 3 5 0 0 0  +1.4681e-02
                Line0067 = 3; 3;  1 3 5 0 0 0  +3.2996e-03
                Line0068 = 3; 0;  2 3 5 0 0 0  -2.6754e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  -3.9710e-04
                Line0070 = 3; 4;  2 3 5 0 0 0  -1.1109e-04
                Line0071 = 3; 0;  0 5 5 0 0 0  -4.1343e-04
                Line0072 = 3; 1;  0 5 5 0 0 0  -1.3484e-04
                Line0073 = 3; 4;  0 5 5 0 0 0  +4.7075e-05
                Line0074 = 3; 0;  1 5 5 0 0 0  +1.0805e-02
                Line0075 = 3; 1;  1 5 5 0 0 0  +3.7463e-03
                Line0076 = 3; 4;  1 5 5 0 0 0  -5.2372e-04
                Line0077 = 3; 2;  2 5 5 0 0 0  +1.8872e-02
                Line0078 = 3; 3;  2 5 5 0 0 0  +4.8336e-03
                Line0079 = 3; 2;  3 3 3 0 0 0  -2.6948e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  +2.1836e-06
                Line0081 = 3; 0;  3 3 5 0 0 0  +2.1935e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  +2.1831e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  -1.7899e-04
                Line0084 = 3; 2;  3 5 5 0 0 0  -1.3440e-02
                Line0085 = 3; 3;  3 5 5 0 0 0  -2.6831e-03
                Line0086 = 3; 0;  5 5 5 0 0 0  -1.6408e-02
                Line0087 = 3; 1;  5 5 5 0 0 0  -5.1484e-03
                Line0088 = 3; 4;  5 5 5 0 0 0  +3.2351e-03

[D4_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 12                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 16.5                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D4_DipoleSettings]
                    Brho = 7.18896              Tm               ; magnetic rigidity
                   Angle = -29.5                degrees          
                  Radius = 12.5                 m                

[D4_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = FMF2-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = FMF2-MW,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M3_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK W2 - Wedge ======================================}

[W2_General]
                    Name = FMF2degrader,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W2_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 5,2.85,2.702,0,0                      ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W2_WedgeSettings]
             ProfileMode = 0                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 0                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = -4.48007             mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = FLF2-slit
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK D5 - Dipole ======================================}

[D5_General]
                    Name = FMF2->FMF3,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 25.780000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\OUTPUT\LISE_HEB14-FMF3.TXT
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D3.cal

[D5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D5_optics]
                    row1 = -2.44031e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-6.39979e+01
                    row2 = -1.57800e-02,-4.09780e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.17589e+00
                    row3 = +0.00000e+00,+0.00000e+00,-7.99950e-01,-1.10300e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+2.68000e-01,-1.21313e+00,+0.00000e+00,+0.00000e+00
                    row5 = -4.30000e-01,+2.62250e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-3.64180e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D5_optics2]
                   row11 = -3.32045e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +6.38334e-03,-1.18668e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-5.83670e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-1.00118e-02,-2.79747e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = -7.36596e-03,+3.34821e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+5.27076e-01
                   row21 = +7.07485e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +1.52790e-04,-5.35955e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-6.18048e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+3.85764e-04,+3.79025e-04,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +1.13724e-03,+3.40184e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.50116e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -9.12501e-04,-3.27664e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = -1.42915e-03,-1.38145e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-2.94023e-02,+2.30743e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -6.90672e-05,+1.15757e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +1.85310e-03,+5.59153e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-3.56122e-02,-3.76276e-02,+0.00000e+00,+0.00000e+00
                   row51 = -3.99705e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +7.12966e-04,-3.43024e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-1.32835e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,-1.44369e-03,-1.73049e-02,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = -7.94689e-03,+3.41102e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.04417e-01
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D5_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  -5.5101e-06
                Line0001 = 3; 1;  0 0 0 0 0 0  -2.8343e-06
                Line0002 = 3; 4;  0 0 0 0 0 0  +1.2935e-07
                Line0003 = 3; 0;  0 0 1 0 0 0  +8.4021e-06
                Line0004 = 3; 1;  0 0 1 0 0 0  +2.4183e-06
                Line0005 = 3; 4;  0 0 1 0 0 0  +3.2945e-06
                Line0006 = 3; 0;  0 1 1 0 0 0  +1.1966e-05
                Line0007 = 3; 1;  0 1 1 0 0 0  -1.1917e-06
                Line0008 = 3; 4;  0 1 1 0 0 0  +6.9121e-06
                Line0009 = 3; 0;  1 1 1 0 0 0  -5.2135e-05
                Line0010 = 3; 1;  1 1 1 0 0 0  -1.7710e-06
                Line0011 = 3; 4;  1 1 1 0 0 0  -8.7109e-06
                Line0012 = 3; 2;  0 0 2 0 0 0  +2.0171e-05
                Line0013 = 3; 3;  0 0 2 0 0 0  +9.3810e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -3.9362e-05
                Line0015 = 3; 3;  0 1 2 0 0 0  +8.7822e-07
                Line0016 = 3; 2;  1 1 2 0 0 0  -6.1104e-05
                Line0017 = 3; 3;  1 1 2 0 0 0  +4.7023e-05
                Line0018 = 3; 0;  0 2 2 0 0 0  +1.1392e-05
                Line0019 = 3; 1;  0 2 2 0 0 0  +5.3836e-06
                Line0020 = 3; 4;  0 2 2 0 0 0  -3.0704e-06
                Line0021 = 3; 0;  1 2 2 0 0 0  -5.1634e-05
                Line0022 = 3; 1;  1 2 2 0 0 0  -2.7872e-06
                Line0023 = 3; 4;  1 2 2 0 0 0  -1.8897e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  +9.7485e-07
                Line0025 = 3; 3;  2 2 2 0 0 0  +1.1983e-06
                Line0026 = 3; 2;  0 0 3 0 0 0  -5.4292e-05
                Line0027 = 3; 3;  0 0 3 0 0 0  -1.3344e-05
                Line0028 = 3; 2;  0 1 3 0 0 0  -8.3142e-06
                Line0029 = 3; 3;  0 1 3 0 0 0  +5.0572e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -3.5417e-04
                Line0031 = 3; 3;  1 1 3 0 0 0  +1.9742e-04
                Line0032 = 3; 0;  0 2 3 0 0 0  -1.1573e-04
                Line0033 = 3; 1;  0 2 3 0 0 0  -2.0207e-05
                Line0034 = 3; 4;  0 2 3 0 0 0  -2.7512e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  -3.2010e-04
                Line0036 = 3; 1;  1 2 3 0 0 0  +1.7177e-05
                Line0037 = 3; 4;  1 2 3 0 0 0  -1.2051e-04
                Line0038 = 3; 2;  2 2 3 0 0 0  -4.3711e-05
                Line0039 = 3; 3;  2 2 3 0 0 0  +8.9671e-06
                Line0040 = 3; 0;  0 0 5 0 0 0  -4.3148e-04
                Line0041 = 3; 1;  0 0 5 0 0 0  -2.1000e-04
                Line0042 = 3; 4;  0 0 5 0 0 0  +1.4700e-07
                Line0043 = 3; 0;  0 1 5 0 0 0  +3.1565e-04
                Line0044 = 3; 1;  0 1 5 0 0 0  +1.2313e-04
                Line0045 = 3; 4;  0 1 5 0 0 0  +1.1126e-04
                Line0046 = 3; 0;  1 1 5 0 0 0  -2.5493e-04
                Line0047 = 3; 1;  1 1 5 0 0 0  -3.3113e-05
                Line0048 = 3; 4;  1 1 5 0 0 0  +5.3222e-05
                Line0049 = 3; 2;  0 2 5 0 0 0  +1.0445e-03
                Line0050 = 3; 3;  0 2 5 0 0 0  +4.0726e-04
                Line0051 = 3; 2;  1 2 5 0 0 0  -5.7170e-04
                Line0052 = 3; 3;  1 2 5 0 0 0  -2.2570e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  +2.7359e-04
                Line0054 = 3; 1;  2 2 5 0 0 0  +1.3225e-04
                Line0055 = 3; 4;  2 2 5 0 0 0  +1.1722e-04
                Line0056 = 3; 0;  0 3 3 0 0 0  -3.2689e-05
                Line0057 = 3; 1;  0 3 3 0 0 0  +2.6223e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  -2.1206e-05
                Line0059 = 3; 0;  1 3 3 0 0 0  -1.0943e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  -3.9090e-06
                Line0061 = 3; 4;  1 3 3 0 0 0  -1.9781e-04
                Line0062 = 3; 2;  2 3 3 0 0 0  -2.7398e-05
                Line0063 = 3; 3;  2 3 3 0 0 0  +7.6826e-05
                Line0064 = 3; 2;  0 3 5 0 0 0  -2.3148e-03
                Line0065 = 3; 3;  0 3 5 0 0 0  -8.2127e-04
                Line0066 = 3; 2;  1 3 5 0 0 0  +9.4085e-04
                Line0067 = 3; 3;  1 3 5 0 0 0  +7.2747e-05
                Line0068 = 3; 0;  2 3 5 0 0 0  -1.6790e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  -4.8689e-04
                Line0070 = 3; 4;  2 3 5 0 0 0  -1.1842e-05
                Line0071 = 3; 0;  0 5 5 0 0 0  -1.0505e-02
                Line0072 = 3; 1;  0 5 5 0 0 0  -5.2143e-03
                Line0073 = 3; 4;  0 5 5 0 0 0  +9.9738e-05
                Line0074 = 3; 0;  1 5 5 0 0 0  +1.8917e-03
                Line0075 = 3; 1;  1 5 5 0 0 0  +1.6071e-03
                Line0076 = 3; 4;  1 5 5 0 0 0  +1.7820e-03
                Line0077 = 3; 2;  2 5 5 0 0 0  +1.5783e-02
                Line0078 = 3; 3;  2 5 5 0 0 0  +6.4088e-03
                Line0079 = 3; 2;  3 3 3 0 0 0  -2.4112e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  +9.5605e-05
                Line0081 = 3; 0;  3 3 5 0 0 0  +2.5606e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  +4.9533e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  -3.8856e-04
                Line0084 = 3; 2;  3 5 5 0 0 0  -1.8774e-02
                Line0085 = 3; 3;  3 5 5 0 0 0  -5.1084e-03
                Line0086 = 3; 0;  5 5 5 0 0 0  -9.9103e-02
                Line0087 = 3; 1;  5 5 5 0 0 0  -4.3267e-02
                Line0088 = 3; 4;  5 5 5 0 0 0  +4.9956e-03

[D5_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 30                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 14.5                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D5_DipoleSettings]
                    Brho = 5.53477              Tm               ; magnetic rigidity
                   Angle = -29.25               degrees          
                  Radius = 12.5                 m                

[D5_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S5 - Drift ======================================}

[S5_General]
                    Name = FMF3-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-100.00,-190.0,55.00,190.0          ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S5_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S5_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S5_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK S6 - Drift ======================================}

[S6_General]
                    Name = FMF3 -> FLF1,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 25.400000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 84                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\OUTPUT\LISE_LEB14-FLF1.TXT
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S6_optics]
                    row1 = -8.70240e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -2.42100e-02,-1.14911e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,-1.31420e+00,-1.39900e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+5.40360e-01,-7.03400e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S6_optics2]
                   row11 = -6.91389e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -4.11104e-03,-2.35956e-08,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-2.17877e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-2.77143e-03,-1.11973e-02,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +4.42520e-03,+2.63108e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row21 = +1.00069e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +6.82220e-05,+2.71419e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-4.09800e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+1.56093e-03,+2.97784e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -2.98566e-03,+1.47615e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -1.86859e-03,-3.48482e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = -7.32444e-03,-3.33738e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-3.53135e-02,+1.87461e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +7.94311e-04,+5.24300e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +4.09629e-03,+1.61457e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-3.63705e-02,-6.20496e-02,+0.00000e+00,+0.00000e+00
                   row51 = -1.45803e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = -5.08500e-04,-1.51169e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-2.98894e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+2.05076e-03,-7.07621e-03,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[S6_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  -9.1400e-09
                Line0001 = 3; 1;  0 0 0 0 0 0  +1.4018e-07
                Line0002 = 3; 4;  0 0 0 0 0 0  -1.5963e-10
                Line0003 = 3; 0;  0 0 1 0 0 0  -1.0132e-05
                Line0004 = 3; 1;  0 0 1 0 0 0  +6.8793e-07
                Line0005 = 3; 4;  0 0 1 0 0 0  +1.6958e-06
                Line0006 = 3; 0;  0 1 1 0 0 0  -4.0061e-05
                Line0007 = 3; 1;  0 1 1 0 0 0  +1.1786e-05
                Line0008 = 3; 4;  0 1 1 0 0 0  -1.7882e-06
                Line0009 = 3; 0;  1 1 1 0 0 0  -5.4698e-04
                Line0010 = 3; 1;  1 1 1 0 0 0  -6.3158e-06
                Line0011 = 3; 4;  1 1 1 0 0 0  +2.7614e-05
                Line0012 = 3; 2;  0 0 2 0 0 0  -1.4272e-06
                Line0013 = 3; 3;  0 0 2 0 0 0  +1.5104e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -4.8715e-05
                Line0015 = 3; 3;  0 1 2 0 0 0  +7.8992e-06
                Line0016 = 3; 2;  1 1 2 0 0 0  +1.2659e-04
                Line0017 = 3; 3;  1 1 2 0 0 0  +9.8424e-05
                Line0018 = 3; 0;  0 2 2 0 0 0  +3.6112e-06
                Line0019 = 3; 1;  0 2 2 0 0 0  +1.9990e-06
                Line0020 = 3; 4;  0 2 2 0 0 0  -8.5666e-06
                Line0021 = 3; 0;  1 2 2 0 0 0  -1.8198e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  -1.8076e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  -4.0797e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  +3.2196e-05
                Line0025 = 3; 3;  2 2 2 0 0 0  +1.0561e-05
                Line0026 = 3; 2;  0 0 3 0 0 0  -1.0175e-05
                Line0027 = 3; 3;  0 0 3 0 0 0  +3.7107e-06
                Line0028 = 3; 2;  0 1 3 0 0 0  -5.5917e-05
                Line0029 = 3; 3;  0 1 3 0 0 0  +6.5459e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -4.3005e-04
                Line0031 = 3; 3;  1 1 3 0 0 0  +2.0976e-04
                Line0032 = 3; 0;  0 2 3 0 0 0  -4.6357e-05
                Line0033 = 3; 1;  0 2 3 0 0 0  -2.0847e-07
                Line0034 = 3; 4;  0 2 3 0 0 0  -3.5479e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  +1.4697e-05
                Line0036 = 3; 1;  1 2 3 0 0 0  +3.0126e-05
                Line0037 = 3; 4;  1 2 3 0 0 0  -9.7379e-05
                Line0038 = 3; 2;  2 2 3 0 0 0  -1.1529e-04
                Line0039 = 3; 3;  2 2 3 0 0 0  -6.5999e-06
                Line0040 = 3; 0;  0 0 5 0 0 0  -2.6042e-05
                Line0041 = 3; 1;  0 0 5 0 0 0  -2.2355e-06
                Line0042 = 3; 4;  0 0 5 0 0 0  +2.4257e-06
                Line0043 = 3; 0;  0 1 5 0 0 0  +3.1820e-05
                Line0044 = 3; 1;  0 1 5 0 0 0  -4.8412e-06
                Line0045 = 3; 4;  0 1 5 0 0 0  +9.3688e-07
                Line0046 = 3; 0;  1 1 5 0 0 0  +5.2200e-04
                Line0047 = 3; 1;  1 1 5 0 0 0  -6.4849e-06
                Line0048 = 3; 4;  1 1 5 0 0 0  +6.5939e-05
                Line0049 = 3; 2;  0 2 5 0 0 0  -3.4531e-05
                Line0050 = 3; 3;  0 2 5 0 0 0  -4.7762e-05
                Line0051 = 3; 2;  1 2 5 0 0 0  -3.8852e-04
                Line0052 = 3; 3;  1 2 5 0 0 0  -2.4093e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  +9.9998e-05
                Line0054 = 3; 1;  2 2 5 0 0 0  +3.4771e-06
                Line0055 = 3; 4;  2 2 5 0 0 0  +2.4112e-04
                Line0056 = 3; 0;  0 3 3 0 0 0  -3.0828e-06
                Line0057 = 3; 1;  0 3 3 0 0 0  +1.0831e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  +2.0072e-05
                Line0059 = 3; 0;  1 3 3 0 0 0  -3.4174e-04
                Line0060 = 3; 1;  1 3 3 0 0 0  +1.6056e-05
                Line0061 = 3; 4;  1 3 3 0 0 0  +1.6866e-04
                Line0062 = 3; 2;  2 3 3 0 0 0  -6.5386e-05
                Line0063 = 3; 3;  2 3 3 0 0 0  +7.7753e-05
                Line0064 = 3; 2;  0 3 5 0 0 0  -2.9588e-04
                Line0065 = 3; 3;  0 3 5 0 0 0  -2.0280e-04
                Line0066 = 3; 2;  1 3 5 0 0 0  -2.0143e-03
                Line0067 = 3; 3;  1 3 5 0 0 0  -9.3029e-04
                Line0068 = 3; 0;  2 3 5 0 0 0  +9.7693e-05
                Line0069 = 3; 1;  2 3 5 0 0 0  -1.6492e-05
                Line0070 = 3; 4;  2 3 5 0 0 0  +4.9220e-04
                Line0071 = 3; 0;  0 5 5 0 0 0  +3.4617e-04
                Line0072 = 3; 1;  0 5 5 0 0 0  +6.7360e-05
                Line0073 = 3; 0;  1 5 5 0 0 0  -5.7384e-04
                Line0074 = 3; 1;  1 5 5 0 0 0  +4.3713e-04
                Line0075 = 3; 2;  2 5 5 0 0 0  +2.5206e-03
                Line0076 = 3; 3;  2 5 5 0 0 0  +1.1620e-03
                Line0077 = 3; 2;  3 3 3 0 0 0  -1.7615e-04
                Line0078 = 3; 3;  3 3 3 0 0 0  +9.1723e-05
                Line0079 = 3; 0;  3 3 5 0 0 0  -8.4017e-04
                Line0080 = 3; 1;  3 3 5 0 0 0  -1.2344e-04
                Line0081 = 3; 4;  3 3 5 0 0 0  -3.4602e-04
                Line0082 = 3; 2;  3 5 5 0 0 0  +5.4683e-03
                Line0083 = 3; 3;  3 5 5 0 0 0  +3.3815e-03

[S6_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 21                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 33                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S6_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 25.4                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M4 - Material ======================================}

[M4_General]
                    Name = FLF1-MW,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M4_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M4_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 168583119,-20.00,-50.0,20.00,50.0     ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 66881,-20.00,-50.0,20.00,50.0         ; joint,Bottom,B-limit,Top,T-limit

[M4_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M4_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK D6 - Dipole ======================================}

[D6_General]
                    Name = FLF1 -> FLF2,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 26.581000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\OUTPUT\LISE_LEB14-FLF2.TXT
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 8                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D4.cal

[D6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D6_optics]
                    row1 = -5.45680e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.03906e+01
                    row2 = +5.80000e-02,-1.83259e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+3.23019e+00
                    row3 = +0.00000e+00,+0.00000e+00,-1.11011e+00,-2.63500e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+2.01060e-01,-8.53080e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+5.56930e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-3.64180e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D6_optics2]
                   row11 = -1.18240e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +8.46735e-03,-2.91961e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+1.83972e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-1.43120e-03,+1.87584e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = -1.44546e-02,+4.71586e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-4.38285e-01
                   row21 = -2.43960e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -1.05786e-04,-1.42183e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-6.51868e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,-5.60100e-03,-8.85720e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -4.50275e-03,-1.57986e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.16475e-01
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +3.35376e-03,-4.68861e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +9.66180e-03,+8.32347e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-1.50842e-02,+1.69677e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -1.05603e-03,-5.22490e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -4.57782e-03,+8.55175e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-1.91229e-02,-2.36788e-02,+0.00000e+00,+0.00000e+00
                   row51 = -3.66103e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +2.35311e-04,-8.34534e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+2.85333e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+1.83199e-02,+1.86498e-02,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +2.32035e-03,+6.88034e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.05379e-01
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D6_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  +2.3627e-07
                Line0001 = 3; 1;  0 0 0 0 0 0  -1.3085e-07
                Line0002 = 3; 4;  0 0 0 0 0 0  +3.7451e-07
                Line0003 = 3; 0;  0 0 1 0 0 0  +7.9799e-06
                Line0004 = 3; 1;  0 0 1 0 0 0  -2.4350e-06
                Line0005 = 3; 4;  0 0 1 0 0 0  +5.9094e-06
                Line0006 = 3; 0;  0 1 1 0 0 0  -1.5064e-04
                Line0007 = 3; 1;  0 1 1 0 0 0  -4.3348e-06
                Line0008 = 3; 4;  0 1 1 0 0 0  +3.7301e-05
                Line0009 = 3; 0;  1 1 1 0 0 0  +5.3865e-04
                Line0010 = 3; 1;  1 1 1 0 0 0  -3.7869e-05
                Line0011 = 3; 4;  1 1 1 0 0 0  -1.2500e-04
                Line0012 = 3; 2;  0 0 2 0 0 0  -6.1809e-06
                Line0013 = 3; 3;  0 0 2 0 0 0  +3.0503e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -1.4769e-04
                Line0015 = 3; 3;  0 1 2 0 0 0  +1.9786e-05
                Line0016 = 3; 2;  1 1 2 0 0 0  +6.8037e-04
                Line0017 = 3; 3;  1 1 2 0 0 0  +3.3131e-04
                Line0018 = 3; 0;  0 2 2 0 0 0  -1.1240e-06
                Line0019 = 3; 1;  0 2 2 0 0 0  +4.4950e-06
                Line0020 = 3; 4;  0 2 2 0 0 0  +1.5844e-06
                Line0021 = 3; 0;  1 2 2 0 0 0  -3.0368e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  -5.1707e-06
                Line0023 = 3; 4;  1 2 2 0 0 0  -1.0796e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  +3.3158e-06
                Line0025 = 3; 3;  2 2 2 0 0 0  +3.2603e-06
                Line0026 = 3; 2;  0 0 3 0 0 0  -3.7992e-05
                Line0027 = 3; 3;  0 0 3 0 0 0  +7.7142e-06
                Line0028 = 3; 2;  0 1 3 0 0 0  -1.2439e-05
                Line0029 = 3; 3;  0 1 3 0 0 0  +1.9585e-04
                Line0030 = 3; 2;  1 1 3 0 0 0  -3.9087e-03
                Line0031 = 3; 3;  1 1 3 0 0 0  +2.9824e-04
                Line0032 = 3; 0;  0 2 3 0 0 0  -8.4895e-05
                Line0033 = 3; 1;  0 2 3 0 0 0  +2.4147e-05
                Line0034 = 3; 4;  0 2 3 0 0 0  -4.2631e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  +5.3890e-04
                Line0036 = 3; 1;  1 2 3 0 0 0  +1.1766e-04
                Line0037 = 3; 4;  1 2 3 0 0 0  -3.7496e-04
                Line0038 = 3; 2;  2 2 3 0 0 0  -1.3536e-04
                Line0039 = 3; 3;  2 2 3 0 0 0  -1.1074e-06
                Line0040 = 3; 0;  0 0 5 0 0 0  +1.2874e-05
                Line0041 = 3; 1;  0 0 5 0 0 0  +2.2060e-06
                Line0042 = 3; 4;  0 0 5 0 0 0  +1.2011e-07
                Line0043 = 3; 0;  0 1 5 0 0 0  +5.6645e-04
                Line0044 = 3; 1;  0 1 5 0 0 0  -3.2186e-05
                Line0045 = 3; 4;  0 1 5 0 0 0  +6.6648e-05
                Line0046 = 3; 0;  1 1 5 0 0 0  -6.3888e-03
                Line0047 = 3; 1;  1 1 5 0 0 0  +1.5423e-04
                Line0048 = 3; 4;  1 1 5 0 0 0  +5.6397e-04
                Line0049 = 3; 2;  0 2 5 0 0 0  +3.5686e-04
                Line0050 = 3; 3;  0 2 5 0 0 0  +1.1799e-04
                Line0051 = 3; 2;  1 2 5 0 0 0  -5.0620e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  -7.8589e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  +6.7855e-04
                Line0054 = 3; 1;  2 2 5 0 0 0  +7.2755e-05
                Line0055 = 3; 4;  2 2 5 0 0 0  +1.1475e-04
                Line0056 = 3; 0;  0 3 3 0 0 0  +3.6495e-05
                Line0057 = 3; 1;  0 3 3 0 0 0  +6.3269e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  -2.0005e-04
                Line0059 = 3; 0;  1 3 3 0 0 0  -1.8917e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  +1.6372e-04
                Line0061 = 3; 4;  1 3 3 0 0 0  -7.5634e-04
                Line0062 = 3; 2;  2 3 3 0 0 0  -1.4714e-04
                Line0063 = 3; 3;  2 3 3 0 0 0  +1.0348e-04
                Line0064 = 3; 2;  0 3 5 0 0 0  -2.9628e-04
                Line0065 = 3; 3;  0 3 5 0 0 0  +1.2578e-04
                Line0066 = 3; 2;  1 3 5 0 0 0  +1.1923e-02
                Line0067 = 3; 3;  1 3 5 0 0 0  +2.5797e-03
                Line0068 = 3; 0;  2 3 5 0 0 0  -1.3453e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  -3.9105e-05
                Line0070 = 3; 4;  2 3 5 0 0 0  -8.1375e-05
                Line0071 = 3; 0;  0 5 5 0 0 0  +5.8349e-04
                Line0072 = 3; 1;  0 5 5 0 0 0  +1.6798e-04
                Line0073 = 3; 4;  0 5 5 0 0 0  +1.5397e-05
                Line0074 = 3; 0;  1 5 5 0 0 0  +1.5055e-02
                Line0075 = 3; 1;  1 5 5 0 0 0  +3.4483e-04
                Line0076 = 3; 4;  1 5 5 0 0 0  +1.7066e-04
                Line0077 = 3; 2;  2 5 5 0 0 0  +1.0109e-02
                Line0078 = 3; 3;  2 5 5 0 0 0  +2.3873e-03
                Line0079 = 3; 2;  3 3 3 0 0 0  -3.7104e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  +1.2712e-04
                Line0081 = 3; 0;  3 3 5 0 0 0  +4.9610e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  +4.8810e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  -8.6609e-04
                Line0084 = 3; 2;  3 5 5 0 0 0  -1.3872e-02
                Line0085 = 3; 3;  3 5 5 0 0 0  -1.4497e-03
                Line0086 = 3; 0;  5 5 5 0 0 0  +6.4810e-03
                Line0087 = 3; 1;  5 5 5 0 0 0  +3.3898e-03
                Line0088 = 3; 4;  5 5 5 0 0 0  +1.9300e-03

[D6_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 15.5                 mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 15                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D6_DipoleSettings]
                    Brho = 5.53477              Tm               ; magnetic rigidity
                   Angle = -29.25               degrees          
                  Radius = 12.5                 m                

[D6_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M5 - Material ======================================}

[M5_General]
                    Name = FLF2-MW,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M5_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M5_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M5_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M5_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S7 - Drift ======================================}

[S7_General]
                    Name = FLF2-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S7_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-20.00,-190.0,30.00,190.0           ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S7_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S7_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S7_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= Calculations ======================================}

[Calculations]
103Sn 50+ 50+ 50+ 50+ 49+ 49+ =2.3521e-07,2.3521e-07,0,2.3521e-07,2.2297e-04,2.2297e-04,5.2599e-12,7.9647e+02,6.3936e+00,5.9887e-01,1,1,1,1,6.0488e-01,9.9007e-01,1,1,1,1,1,1,1,1,1,1,9.9637e-01,1,1,1,9.9637e-01,3.1026e-05,3.1026e-05,1,1,1,1,1,1,1,1,1,1,1,6.5041e-01,1,1,1,1,6.5938e-01,9.8640e-01,1,9.9815e-01,1,1,1,9.9815e-01,1,1,1,1,1,1,1,1,2.1059e-05,2.1059e-05,1,1,1,9.8395e-01,1,1,1,9.8395e-01,9.4907e-01,9.4907e-01,1,1,1,9.9552e-01,1,1,1,9.9552e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,2.6161e-02,1,1,1,1,8.1268e-01,3.2190e-02,1,9.6676e-01,1,1,1,9.6676e-01,9.9341e-01,9.9341e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6185e-01,1,1,1,9.6185e-01,1,1,1,1,1,1,1,1,9.2501e-01,9.2501e-01,1,1,1
102Sn 50+ 50+ 50+ 50+ 49+ 49+ =1.7487e-04,1.7487e-04,0,1.7487e-04,6.4810e-06,6.4810e-06,1.3454e-07,7.9546e+02,6.6276e+00,5.9953e-01,1,1,1,1,6.0556e-01,9.9004e-01,1,1,1,1,1,1,1,1,1,1,9.9544e-01,1,1,1,9.9544e-01,3.1347e-03,3.1347e-03,1,1,1,1,1,1,1,1,1,1,1,6.5185e-01,1,1,1,1,6.6046e-01,9.8697e-01,1,9.9792e-01,1,1,1,9.9792e-01,1,1,1,1,1,1,1,1,2.8323e-02,2.8323e-02,1,1,1,9.8308e-01,1,1,1,9.8308e-01,8.2118e-01,8.2118e-01,1,1,1,9.9521e-01,1,1,1,9.9521e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,2.5032e-02,1,1,1,1,8.1333e-01,3.0777e-02,1,9.6608e-01,1,1,1,9.6608e-01,9.9822e-01,9.9822e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6168e-01,1,1,1,9.6168e-01,1,1,1,1,1,1,1,1,2.0929e-01,2.0929e-01,1,1,1
101Sn 50+ 50+ 50+ 50+ 50+ 50+ =1.3804e-03,1.3804e-03,0,1.3804e-03,1.7884e-07,1.7884e-07,3.8486e-05,7.9430e+02,6.8892e+00,6.0019e-01,1,1,1,1,6.0624e-01,9.9002e-01,1,1,1,1,1,1,1,1,1,1,9.9429e-01,1,1,1,9.9429e-01,1.4568e-01,1.4568e-01,1,1,1,1,1,1,1,1,1,1,1,6.5329e-01,1,1,1,1,6.6155e-01,9.8752e-01,1,9.9768e-01,1,1,1,9.9768e-01,1,1,1,1,1,1,1,1,6.1828e-01,6.1828e-01,1,1,1,9.8218e-01,1,1,1,9.8218e-01,7.6211e-01,7.6211e-01,1,1,1,9.9489e-01,1,1,1,9.9489e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,7.8995e-01,1,1,1,1,8.1399e-01,9.7047e-01,1,9.6537e-01,1,1,1,9.6537e-01,1.4346e-01,1.4346e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6149e-01,1,1,1,9.6149e-01,1,1,1,1,1,1,1,1,1.4024e-02,1.4024e-02,1,1,1
101Sn 50+ 50+ 50+ 50+ 49+ 49+ =1.0876e-10,1.3804e-03,0,1.3804e-03,1.7884e-07,1.7884e-07,3.0323e-12,7.9430e+02,6.8892e+00,6.0019e-01,1,1,1,1,6.0624e-01,9.9002e-01,1,1,1,1,1,1,1,1,1,1,9.9429e-01,1,1,1,9.9429e-01,1.4568e-01,1.4568e-01,1,1,1,1,1,1,1,1,1,1,1,6.5329e-01,1,1,1,1,6.6155e-01,9.8752e-01,1,9.9768e-01,1,1,1,9.9768e-01,1,1,1,1,1,1,1,1,6.1828e-01,6.1828e-01,1,1,1,9.8218e-01,1,1,1,9.8218e-01,7.6211e-01,7.6211e-01,1,1,1,9.9489e-01,1,1,1,9.9489e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,2.3859e-02,1,1,1,1,8.1399e-01,2.9311e-02,1,9.6537e-01,1,1,1,9.6537e-01,9.4990e-01,9.4990e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6149e-01,1,1,1,9.6149e-01,1,1,1,1,1,1,1,1,5.5251e-09,5.5251e-09,1,1,1
100Sn 50+ 50+ 50+ 50+ 50+ 50+ =2.2396e-01,2.2396e-01,0,2.2396e-01,5.9937e-09,5.9937e-09,1.8632e-01,7.9082e+02,7.2010e+00,6.0085e-01,1,1,1,1,6.0693e-01,9.8999e-01,1,1,1,1,1,1,1,1,1,1,9.9260e-01,1,1,1,9.9260e-01,8.8032e-01,8.8032e-01,1,1,1,1,1,1,1,1,1,1,1,6.5468e-01,1,1,1,1,6.6264e-01,9.8798e-01,1,9.9737e-01,1,1,1,9.9737e-01,1,1,1,1,1,1,1,1,8.4268e-01,8.4268e-01,1,1,1,9.8103e-01,1,1,1,9.8106e-01,9.6380e-01,9.6380e-01,1,1,1,9.9449e-01,1,1,1,9.9449e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,7.9174e-01,1,1,1,1,8.1465e-01,9.7187e-01,1,9.6513e-01,1,1,1,9.6513e-01,9.4910e-01,9.4910e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6128e-01,1,1,1,9.6128e-01,1,1,1,1,1,1,1,1,9.8383e-01,9.8383e-01,1,1,1
99Sn 50+ 50+ 50+ 50+ 50+ 50+ =6.4494e-06,6.4494e-06,0,6.4494e-06,1.9554e-10,1.9554e-10,1.6446e-04,7.8887e+02,8.2895e+00,6.0152e-01,1,1,1,1,6.0762e-01,9.8996e-01,1,1,1,1,1,1,1,1,1,1,9.9039e-01,1,1,1,9.9039e-01,9.9859e-01,9.9859e-01,1,1,1,1,1,1,1,1,1,1,1,6.5610e-01,1,1,1,1,6.6375e-01,9.8848e-01,1,9.9698e-01,1,1,1,9.9698e-01,1,1,1,1,1,1,1,1,8.2927e-02,8.2927e-02,1,1,1,9.7389e-01,9.9392e-01,1,1,9.7984e-01,9.9702e-01,9.9702e-01,1,1,1,9.9403e-01,1,1,1,9.9403e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,7.9346e-01,1,1,1,1,8.1531e-01,9.7320e-01,1,9.6431e-01,1,1,1,9.6431e-01,5.2282e-01,5.2282e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6102e-01,1,1,1,9.6102e-01,1,1,1,1,1,1,1,1,1.3735e-02,1.3735e-02,1,1,1
102In 49+ 49+ 49+ 49+ 48+ 48+ =7.2558e-05,7.2558e-05,0,7.2558e-05,9.7151e-03,9.7151e-03,3.7240e-11,7.9957e+02,6.0594e+00,6.0038e-01,1,1,1,1,6.0554e-01,9.9147e-01,1,1,1,1,1,1,1,1,1,1,9.9596e-01,1,1,1,9.9596e-01,1.3295e-07,1.3295e-07,1,1,1,1,1,1,1,1,1,1,1,6.5263e-01,1,1,1,1,6.6058e-01,9.8796e-01,1,9.9803e-01,1,1,1,9.9803e-01,1,1,1,1,1,1,1,1,1.4107e-01,1.4107e-01,1,1,1,9.8348e-01,1,1,1,9.8348e-01,7.8596e-01,7.8596e-01,1,1,1,9.9537e-01,1,1,1,9.9537e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,2.3594e-02,1,1,1,1,8.1343e-01,2.9005e-02,1,9.6631e-01,1,1,1,9.6631e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6180e-01,1,1,1,9.6180e-01,1,1,1,1,1,1,1,1,3.0216e-01,3.0216e-01,1,1,1
101In 49+ 49+ 49+ 49+ 49+ 49+ =1.1835e-04,1.1894e-04,0,1.1894e-04,5.1966e-04,5.1966e-04,1.1356e-09,7.9858e+02,6.2986e+00,6.0104e-01,1,1,1,1,6.0623e-01,9.9145e-01,1,1,1,1,1,1,1,1,1,1,9.9452e-01,1,1,1,9.9452e-01,1.7476e-05,1.7476e-05,1,1,1,1,1,1,1,1,1,1,1,6.5404e-01,1,1,1,1,6.6167e-01,9.8847e-01,1,9.9771e-01,1,1,1,9.9771e-01,1,1,1,1,1,1,1,1,9.0514e-01,9.0514e-01,1,1,1,9.8224e-01,1,1,1,9.8224e-01,7.5646e-01,7.5646e-01,1,1,1,9.9494e-01,1,1,1,9.9494e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,7.9148e-01,1,1,1,1,8.1408e-01,9.7224e-01,1,9.6538e-01,1,1,1,9.6538e-01,6.0132e-02,6.0132e-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6162e-01,1,1,1,9.6162e-01,1,1,1,1,1,1,1,1,5.6350e-03,5.6350e-03,1,1,1
101In 49+ 49+ 49+ 49+ 48+ 48+ =5.8654e-07,1.1894e-04,0,1.1894e-04,5.1966e-04,5.1966e-04,5.6280e-12,7.9858e+02,6.2986e+00,6.0104e-01,1,1,1,1,6.0623e-01,9.9145e-01,1,1,1,1,1,1,1,1,1,1,9.9452e-01,1,1,1,9.9452e-01,1.7476e-05,1.7476e-05,1,1,1,1,1,1,1,1,1,1,1,6.5404e-01,1,1,1,1,6.6167e-01,9.8847e-01,1,9.9771e-01,1,1,1,9.9771e-01,1,1,1,1,1,1,1,1,9.0514e-01,9.0514e-01,1,1,1,9.8224e-01,1,1,1,9.8224e-01,7.5646e-01,7.5646e-01,1,1,1,9.9494e-01,1,1,1,9.9494e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,2.2438e-02,1,1,1,1,8.1408e-01,2.7563e-02,1,9.6538e-01,1,1,1,9.6538e-01,9.8675e-01,9.8675e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6167e-01,1,1,1,9.6167e-01,1,1,1,1,1,1,1,1,6.0028e-05,6.0028e-05,1,1,1
100In 49+ 49+ 49+ 49+ 49+ 49+ =2.0372e-01,2.0372e-01,0,2.0372e-01,1.5482e-05,1.5482e-05,6.5610e-05,7.9752e+02,6.5017e+00,6.0171e-01,1,1,1,1,6.0691e-01,9.9143e-01,1,1,1,1,1,1,1,1,1,1,9.9315e-01,1,1,1,9.9315e-01,1.5235e-03,1.5235e-03,1,1,1,1,1,1,1,1,1,1,1,6.5545e-01,1,1,1,1,6.6277e-01,9.8896e-01,1,9.9749e-01,1,1,1,9.9749e-01,1,1,1,1,1,1,1,1,5.1191e-01,5.1191e-01,1,1,1,9.8132e-01,1,1,1,9.8132e-01,6.0374e-01,6.0374e-01,1,1,1,9.9462e-01,1,1,1,9.9462e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,7.9325e-01,1,1,1,1,8.1474e-01,9.7362e-01,1,9.6548e-01,1,1,1,9.6548e-01,4.9829e-01,4.9829e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6137e-01,1,1,1,9.6137e-01,1,1,1,1,1,1,1,1,9.9600e-01,9.9600e-01,1,1,1
99In 49+ 49+ 49+ 49+ 49+ 49+ =4.1421e-05,4.1421e-05,0,4.1421e-05,3.7766e-07,3.7766e-07,5.4688e-07,7.9649e+02,6.6236e+00,6.0238e-01,1,1,1,1,6.0760e-01,9.9141e-01,1,1,1,1,1,1,1,1,1,1,9.9211e-01,1,1,1,9.9211e-01,7.5838e-02,7.5838e-02,1,1,1,1,1,1,1,1,1,1,1,6.5686e-01,1,1,1,1,6.6387e-01,9.8943e-01,1,9.9736e-01,1,1,1,9.9736e-01,1,1,1,1,1,1,1,1,3.3040e-03,3.3040e-03,1,1,1,9.8072e-01,1,1,1,9.8072e-01,5.6094e-01,5.6094e-01,1,1,1,9.9441e-01,1,1,1,9.9441e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,7.9494e-01,1,1,1,1,8.1540e-01,9.7490e-01,1,9.6559e-01,1,1,1,9.6559e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6132e-01,1,1,1,9.6132e-01,1,1,1,1,1,1,1,1,1.3821e-02,1.3821e-02,1,1,1
101Cd 48+ 48+ 48+ 48+ 47+ 47+ =1.2568e-10,1.2568e-10,0,1.2568e-10,1.8360e-01,1.8360e-01,3.4132e-18,8.0288e+02,6.8462e+00,6.0178e-01,1,1,1,1,6.0621e-01,9.9269e-01,1,1,1,1,1,1,1,1,1,1,9.7647e-01,9.8153e-01,1,1,9.9484e-01,2.6130e-10,2.6130e-10,1,1,1,1,1,1,1,1,1,1,1,6.5478e-01,1,1,1,1,6.6180e-01,9.8940e-01,1,9.9776e-01,1,1,1,9.9776e-01,1,1,1,1,1,1,1,1,8.9183e-01,8.9183e-01,1,1,1,9.8244e-01,1,1,1,9.8244e-01,5.1091e-01,5.1091e-01,1,1,1,9.9502e-01,1,1,1,9.9502e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,2.1153e-02,1,1,1,1,8.1417e-01,2.5981e-02,1,9.6545e-01,1,1,1,9.6545e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6154e-01,1,1,1,9.6154e-01,1,1,1,1,1,1,1,1,3.8901e-06,3.8901e-06,1,1,1
100Cd 48+ 48+ 48+ 48+ 48+ 48+ =4.7480e-03,4.7480e-03,0,4.7480e-03,1.8108e-02,1.8108e-02,1.3074e-09,8.0184e+02,6.4803e+00,6.0245e-01,1,1,1,1,6.0690e-01,9.9267e-01,1,1,1,1,1,1,1,1,1,1,9.9361e-01,1,1,1,9.9361e-01,2.1239e-07,2.1239e-07,1,1,1,1,1,1,1,1,1,1,1,6.5617e-01,1,1,1,1,6.6290e-01,9.8986e-01,1,9.9754e-01,1,1,1,9.9754e-01,1,1,1,1,1,1,1,1,1.4219e-01,1.4219e-01,1,1,1,9.8153e-01,1,1,1,9.8153e-01,5.5416e-01,5.5416e-01,1,1,1,9.9472e-01,1,1,1,9.9472e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,7.9462e-01,1,1,1,1,8.1483e-01,9.7519e-01,1,9.6500e-01,1,1,1,9.6500e-01,2.7767e-01,2.7767e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6139e-01,1,1,1,9.6139e-01,1,1,1,1,1,1,1,1,9.9768e-01,9.9768e-01,1,1,1
99Cd 48+ 48+ 48+ 48+ 48+ 48+ =1.1058e-07,1.1058e-07,0,1.1058e-07,1.0083e-03,1.0083e-03,5.4687e-13,8.0087e+02,6.6465e+00,6.0312e-01,1,1,1,1,6.0759e-01,9.9265e-01,1,1,1,1,1,1,1,1,1,1,9.9229e-01,1,1,1,9.9229e-01,1.3299e-05,1.3299e-05,1,1,1,1,1,1,1,1,1,1,1,6.5756e-01,1,1,1,1,6.6400e-01,9.9030e-01,1,9.9734e-01,1,1,1,9.9734e-01,1,1,1,1,1,1,1,1,1.7854e-05,1.7854e-05,1,1,1,9.8071e-01,1,1,1,9.8071e-01,4.4620e-01,4.4620e-01,1,1,1,9.9443e-01,1,1,1,9.9443e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,7.9629e-01,1,1,1,1,8.1550e-01,9.7645e-01,1,9.6530e-01,1,1,1,9.6530e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9.6129e-01,1,1,1,9.6129e-01,1,1,1,1,1,1,1,1,1.8251e-02,1.8251e-02,1,1,1
