Version 9.8.18

{============================= Main Part ======================================}
[general]
                    File = \\WinFileSvH\KP2$Root\winfield\Eigene Dateien\LISE\files\Super-FRS\RB\238U-132Sn-RB14y8.lpp
                    Date = 29-01-2014
                    Time = 12:02:11
           Configuration = GSI\Super-FRS.lcn
             Optionsfile = A1900_2006.lopt
                   Title = Super-FRS pfrs3_m.dat
          BlockStructure = DSMWDMSDSDSMWSSMDSMDMS

[settings]
                   A,Z,Q = 238U 92+                              ; Mass ElementName Charge+ Beam
                  Energy = 1500                 MeV/u            
               Intensity = 1e+12                pps              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 132Sn                                 ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 4                    (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 2                    (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 8                    (±)mm            ; one-half the vertical beam extent (y)
                      BF = 2                    (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.04                 (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = -56                  degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 64                                    ; Number of points in distribution
        NP charge states = 32                                    ; Number of points in distribution
                NP wedge = 16                                    ; Number of points in distribution
           Charge states = Yes                                   ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
        Target thickness = 3,4000,2.253,0,0                      ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,17.232                              ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 6                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 64                                    ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 1                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 2                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 0                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 1                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-11    
               FisCS_TKE = 1e-8     
                      N0 = 83                                    ; default 82
                     dU0 = -2.65                                 ; default -2.5
                      C0 = 0.7                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -3.8                                  ; default -5.5
                      C1 = 0.15                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-5     
                 BeamInd = 1e-9     
               BeamTotal = 1e-11    

[convolution]
        Convolution mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 5.758 
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 1                                     ; 0 - no, 1 - use
         DissipationBeta = 1                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 0                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 0                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
               EE_C_mode = 0
             EE_C_Zbound = 0
             EE_C_Abound = 0
          EnergyCoef_CA0 = 0       
          EnergyCoef_CA1 = 3       
          EnergyCoef_CA2 = 0       
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CA0 = 0       
           SigmaCoef_CA1 = 2       
           SigmaCoef_CA2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       

[evapauto]
                  tun_a0 = -0.61392
                  tun_a1 = 0.44559
                  tun_a2 = 0.12008
                 A_Bound = 300                                   ; mass
               A_Pairing =  70                                   ; mass

[plot]
            Start target = Detector                              ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = M5
         dE-detector-1st = M5
         dE-detector-2nd = M6
            TKE-detector = M4
                PlotBrho = D1
               PlotWedge = S4
              X-detector = M4
              Y-detector = M5
                 Tilting = M1
                 Stopper = M2
                RO_Wedge = 

          ConditionBlock = A10
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 1
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 22
          fiss_ZdeltaBot = 15
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
           LowEx_nucleus = 237U 92+                              ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 232Th90+                              ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 226Ra88+                              ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 8.000e+02 250.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 1                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-5 
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 92
                   Dr_n0 = 0
                   Dr_n1 = 146

[cross sections]

[previous]
                 Lowerst = 127In49+                              ; Mass ElementName Charge+ Beam
                 Highest = 135Te52+                              ; Mass ElementName Charge+ Beam


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = TA->FPF2,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 35.599000            m                ; Length block for optical blocks
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\FOR_LISE\LISE_RB14-FPF2.TXT
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = +1.70642e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.55143e+01
                    row2 = -5.59080e-01,+5.86020e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+5.00000e-05
                    row3 = +0.00000e+00,+0.00000e+00,-9.72560e-01,-4.61100e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+1.07993e+00,-5.16200e-01,+0.00000e+00,+0.00000e+00
                    row5 = +1.42645e+00,-1.49520e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-7.31780e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_optics2]
                   row11 = +1.13069e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -1.36320e-02,-9.30861e-08,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-3.47011e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+1.88569e-02,-1.27068e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = -5.06958e-02,-1.11099e-06,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.84650e-06
                   row21 = +3.73125e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -3.29966e-03,+2.34078e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+8.85893e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,-1.05617e-02,+2.46838e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -2.97836e-02,+1.74102e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.42825e-05
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -3.32437e-03,-2.95012e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +1.02604e-02,+6.54397e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-6.33184e-02,-1.01609e-03,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +1.25005e-02,-9.06056e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -3.70190e-03,+4.09591e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-2.21599e-01,-7.03293e-02,+0.00000e+00,+0.00000e+00
                   row51 = -5.08474e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +5.44808e-03,-5.97237e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-3.62726e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+2.04956e-02,-8.01217e-03,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +9.02636e-02,-5.93727e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-6.10561e-01
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D1_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  +1.5906e-05
                Line0001 = 3; 1;  0 0 0 0 0 0  -2.0748e-05
                Line0002 = 3; 4;  0 0 0 0 0 0  +1.3820e-05
                Line0003 = 3; 0;  0 0 1 0 0 0  -3.2643e-05
                Line0004 = 3; 1;  0 0 1 0 0 0  -2.1306e-05
                Line0005 = 3; 4;  0 0 1 0 0 0  -3.9883e-07
                Line0006 = 3; 0;  0 1 1 0 0 0  -6.1364e-05
                Line0007 = 3; 1;  0 1 1 0 0 0  +6.2923e-09
                Line0008 = 3; 4;  0 1 1 0 0 0  +1.0546e-05
                Line0009 = 3; 0;  1 1 1 0 0 0  +6.3432e-05
                Line0010 = 3; 1;  1 1 1 0 0 0  -1.4838e-06
                Line0011 = 3; 4;  1 1 1 0 0 0  +1.3144e-05
                Line0012 = 3; 2;  0 0 2 0 0 0  +9.6020e-04
                Line0013 = 3; 3;  0 0 2 0 0 0  +2.2750e-04
                Line0014 = 3; 2;  0 1 2 0 0 0  -2.9358e-04
                Line0015 = 3; 3;  0 1 2 0 0 0  -9.4297e-05
                Line0016 = 3; 2;  1 1 2 0 0 0  +8.8281e-05
                Line0017 = 3; 3;  1 1 2 0 0 0  +1.8243e-05
                Line0018 = 3; 0;  0 2 2 0 0 0  -1.0903e-03
                Line0019 = 3; 1;  0 2 2 0 0 0  -6.4950e-04
                Line0020 = 3; 4;  0 2 2 0 0 0  -3.4749e-04
                Line0021 = 3; 0;  1 2 2 0 0 0  +4.6987e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  -1.2945e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  +2.8121e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  +1.6842e-03
                Line0025 = 3; 3;  2 2 2 0 0 0  +2.1357e-04
                Line0026 = 3; 2;  0 0 3 0 0 0  -3.8702e-04
                Line0027 = 3; 3;  0 0 3 0 0 0  -9.1412e-05
                Line0028 = 3; 2;  0 1 3 0 0 0  +1.5621e-04
                Line0029 = 3; 3;  0 1 3 0 0 0  +4.7766e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -1.3973e-04
                Line0031 = 3; 3;  1 1 3 0 0 0  +5.4009e-05
                Line0032 = 3; 0;  0 2 3 0 0 0  +8.8155e-04
                Line0033 = 3; 1;  0 2 3 0 0 0  +4.5993e-04
                Line0034 = 3; 4;  0 2 3 0 0 0  +3.1744e-04
                Line0035 = 3; 0;  1 2 3 0 0 0  -3.8277e-04
                Line0036 = 3; 1;  1 2 3 0 0 0  -3.2617e-06
                Line0037 = 3; 4;  1 2 3 0 0 0  -5.3121e-05
                Line0038 = 3; 2;  2 2 3 0 0 0  -1.6570e-03
                Line0039 = 3; 3;  2 2 3 0 0 0  -1.2971e-04
                Line0040 = 3; 0;  0 0 5 0 0 0  -4.0896e-04
                Line0041 = 3; 1;  0 0 5 0 0 0  +1.0276e-03
                Line0042 = 3; 4;  0 0 5 0 0 0  -5.0868e-04
                Line0043 = 3; 0;  0 1 5 0 0 0  +2.4922e-04
                Line0044 = 3; 1;  0 1 5 0 0 0  +1.0842e-04
                Line0045 = 3; 4;  0 1 5 0 0 0  +1.7774e-04
                Line0046 = 3; 0;  1 1 5 0 0 0  +4.6596e-04
                Line0047 = 3; 1;  1 1 5 0 0 0  -5.6371e-05
                Line0048 = 3; 4;  1 1 5 0 0 0  -2.3547e-04
                Line0049 = 3; 2;  0 2 5 0 0 0  -2.7237e-02
                Line0050 = 3; 3;  0 2 5 0 0 0  -6.1062e-03
                Line0051 = 3; 2;  1 2 5 0 0 0  +3.0572e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  +7.2097e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  +9.5345e-03
                Line0054 = 3; 1;  2 2 5 0 0 0  +7.6559e-03
                Line0055 = 3; 4;  2 2 5 0 0 0  +9.7148e-03
                Line0056 = 3; 0;  0 3 3 0 0 0  -1.7117e-04
                Line0057 = 3; 1;  0 3 3 0 0 0  -7.4656e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  -6.8496e-05
                Line0059 = 3; 0;  1 3 3 0 0 0  +1.7580e-04
                Line0060 = 3; 1;  1 3 3 0 0 0  -3.7853e-05
                Line0061 = 3; 4;  1 3 3 0 0 0  +9.8945e-05
                Line0062 = 3; 2;  2 3 3 0 0 0  +4.6046e-04
                Line0063 = 3; 3;  2 3 3 0 0 0  +1.5457e-04
                Line0064 = 3; 2;  0 3 5 0 0 0  +1.1898e-02
                Line0065 = 3; 3;  0 3 5 0 0 0  +1.1819e-03
                Line0066 = 3; 2;  1 3 5 0 0 0  +1.4373e-03
                Line0067 = 3; 3;  1 3 5 0 0 0  +4.7147e-04
                Line0068 = 3; 0;  2 3 5 0 0 0  +8.3888e-04
                Line0069 = 3; 1;  2 3 5 0 0 0  -7.6514e-03
                Line0070 = 3; 4;  2 3 5 0 0 0  +1.3168e-03
                Line0071 = 3; 0;  0 5 5 0 0 0  +4.1654e-03
                Line0072 = 3; 1;  0 5 5 0 0 0  -1.4008e-02
                Line0073 = 3; 4;  0 5 5 0 0 0  +7.1706e-03
                Line0074 = 3; 0;  1 5 5 0 0 0  -5.4533e-03
                Line0075 = 3; 1;  1 5 5 0 0 0  +8.7343e-04
                Line0076 = 3; 4;  1 5 5 0 0 0  -2.7601e-03
                Line0077 = 3; 2;  2 5 5 0 0 0  +2.2797e-01
                Line0078 = 3; 3;  2 5 5 0 0 0  +5.2140e-02
                Line0079 = 3; 2;  3 3 3 0 0 0  -9.4315e-05
                Line0080 = 3; 3;  3 3 3 0 0 0  +7.0773e-05
                Line0081 = 3; 0;  3 3 5 0 0 0  -7.9890e-04
                Line0082 = 3; 1;  3 3 5 0 0 0  +2.2097e-03
                Line0083 = 3; 4;  3 3 5 0 0 0  -1.3174e-03
                Line0084 = 3; 2;  3 5 5 0 0 0  -8.4175e-02
                Line0085 = 3; 3;  3 5 5 0 0 0  +1.5377e-03
                Line0086 = 3; 0;  5 5 5 0 0 0  -4.9694e-04
                Line0087 = 3; 1;  5 5 5 0 0 0  +5.7453e-02
                Line0088 = 3; 4;  5 5 5 0 0 0  -2.6938e-02

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 38                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 20                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 17.80712             Tm               ; magnetic rigidity
                   Angle = 33                   degrees          
                  Radius = 12.5                 m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = Beam-blocker,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-190.00,-190.0,20.00,190.0          ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 0                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
          sextLength_eff = 0                    m                
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = FPF2-TPC,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = PF2-degrader,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 4,34.788,2.702,0,0                    ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.08                                ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W1_WedgeSettings]
             ProfileMode = 0                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 0                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = -19.37527            mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = FPF4-slit
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = FPF2->FPF4,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 35.900000            m                ; Length block for optical blocks
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\FOR_LISE\LISE_RB14-FPF4.TXT
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = +1.17197e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.99017e+01
                    row2 = -5.18900e-02,+8.53260e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.32401e+00
                    row3 = +0.00000e+00,+0.00000e+00,-4.83450e-01,-7.40100e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+6.40000e-01,-1.08877e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+2.55140e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-5.62660e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_optics2]
                   row11 = +6.37437e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -1.33425e-02,+2.03344e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+2.24056e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+1.01999e-02,+3.16867e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +4.54152e-02,-3.40434e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+7.43802e-01
                   row21 = +7.13269e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -3.37411e-04,+4.85708e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-5.50186e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,-2.70247e-03,+2.05451e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +2.29765e-02,-1.79914e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.21886e-01
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -3.38140e-04,-3.92461e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +4.43932e-03,+3.82661e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-4.78444e-02,+2.36471e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +3.06702e-03,+5.98633e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -4.20385e-04,+1.29365e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-9.09926e-02,-3.44582e-01,+0.00000e+00,+0.00000e+00
                   row51 = +7.83380e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +1.09962e-03,-4.73126e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-5.19132e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,-7.78154e-03,-1.94636e-02,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +3.99796e-02,+5.35746e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-9.43065e-02
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D2_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  -2.0992e-06
                Line0001 = 3; 1;  0 0 0 0 0 0  -3.8404e-06
                Line0002 = 3; 4;  0 0 0 0 0 0  -7.7221e-06
                Line0003 = 3; 0;  0 0 1 0 0 0  -7.1666e-05
                Line0004 = 3; 1;  0 0 1 0 0 0  -8.1121e-06
                Line0005 = 3; 4;  0 0 1 0 0 0  -1.4146e-05
                Line0006 = 3; 0;  0 1 1 0 0 0  +2.8841e-04
                Line0007 = 3; 1;  0 1 1 0 0 0  +3.4067e-05
                Line0008 = 3; 4;  0 1 1 0 0 0  +3.5745e-05
                Line0009 = 3; 0;  1 1 1 0 0 0  -3.6523e-04
                Line0010 = 3; 1;  1 1 1 0 0 0  -1.7073e-05
                Line0011 = 3; 4;  1 1 1 0 0 0  -3.2277e-05
                Line0012 = 3; 2;  0 0 2 0 0 0  +1.0655e-05
                Line0013 = 3; 3;  0 0 2 0 0 0  +2.8207e-05
                Line0014 = 3; 2;  0 1 2 0 0 0  -2.4685e-04
                Line0015 = 3; 3;  0 1 2 0 0 0  -3.7742e-05
                Line0016 = 3; 2;  1 1 2 0 0 0  +4.9751e-04
                Line0017 = 3; 3;  1 1 2 0 0 0  +1.2026e-04
                Line0018 = 3; 0;  0 2 2 0 0 0  -1.0044e-04
                Line0019 = 3; 1;  0 2 2 0 0 0  -1.2146e-05
                Line0020 = 3; 4;  0 2 2 0 0 0  -3.0601e-05
                Line0021 = 3; 0;  1 2 2 0 0 0  +4.3862e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  +4.5333e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  -4.0067e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  +3.0954e-05
                Line0025 = 3; 3;  2 2 2 0 0 0  +1.6346e-05
                Line0026 = 3; 2;  0 0 3 0 0 0  -9.7844e-05
                Line0027 = 3; 3;  0 0 3 0 0 0  +1.2084e-04
                Line0028 = 3; 2;  0 1 3 0 0 0  +2.8813e-04
                Line0029 = 3; 3;  0 1 3 0 0 0  +3.1931e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -9.3084e-04
                Line0031 = 3; 3;  1 1 3 0 0 0  +1.4379e-04
                Line0032 = 3; 0;  0 2 3 0 0 0  +2.9935e-04
                Line0033 = 3; 1;  0 2 3 0 0 0  -2.1912e-06
                Line0034 = 3; 4;  0 2 3 0 0 0  -5.8931e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  -1.2639e-03
                Line0036 = 3; 1;  1 2 3 0 0 0  -1.7010e-04
                Line0037 = 3; 4;  1 2 3 0 0 0  +2.8372e-05
                Line0038 = 3; 2;  2 2 3 0 0 0  -1.5434e-04
                Line0039 = 3; 3;  2 2 3 0 0 0  +8.9686e-05
                Line0040 = 3; 0;  0 0 5 0 0 0  -1.0339e-04
                Line0041 = 3; 1;  0 0 5 0 0 0  -7.5102e-05
                Line0042 = 3; 4;  0 0 5 0 0 0  -1.0695e-04
                Line0043 = 3; 0;  0 1 5 0 0 0  -2.9526e-03
                Line0044 = 3; 1;  0 1 5 0 0 0  -3.6185e-04
                Line0045 = 3; 4;  0 1 5 0 0 0  -4.8700e-04
                Line0046 = 3; 0;  1 1 5 0 0 0  +6.2686e-03
                Line0047 = 3; 1;  1 1 5 0 0 0  +5.5420e-04
                Line0048 = 3; 4;  1 1 5 0 0 0  +1.9356e-04
                Line0049 = 3; 2;  0 2 5 0 0 0  +9.2071e-04
                Line0050 = 3; 3;  0 2 5 0 0 0  +2.2802e-05
                Line0051 = 3; 2;  1 2 5 0 0 0  -6.3218e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  -8.4239e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  -2.0080e-03
                Line0054 = 3; 1;  2 2 5 0 0 0  -2.1747e-04
                Line0055 = 3; 4;  2 2 5 0 0 0  +8.3962e-04
                Line0056 = 3; 0;  0 3 3 0 0 0  -2.3547e-04
                Line0057 = 3; 1;  0 3 3 0 0 0  -1.5519e-04
                Line0058 = 3; 4;  0 3 3 0 0 0  -3.9101e-04
                Line0059 = 3; 0;  1 3 3 0 0 0  +1.2767e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  +6.4609e-05
                Line0061 = 3; 4;  1 3 3 0 0 0  +1.6826e-04
                Line0062 = 3; 2;  2 3 3 0 0 0  -7.9162e-05
                Line0063 = 3; 3;  2 3 3 0 0 0  +6.0094e-04
                Line0064 = 3; 2;  0 3 5 0 0 0  -1.1379e-03
                Line0065 = 3; 3;  0 3 5 0 0 0  -9.1436e-04
                Line0066 = 3; 2;  1 3 5 0 0 0  +7.7820e-03
                Line0067 = 3; 3;  1 3 5 0 0 0  +1.9571e-03
                Line0068 = 3; 0;  2 3 5 0 0 0  +8.5558e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  +1.2872e-03
                Line0070 = 3; 4;  2 3 5 0 0 0  +3.3976e-03
                Line0071 = 3; 0;  0 5 5 0 0 0  +2.0650e-04
                Line0072 = 3; 1;  0 5 5 0 0 0  -3.9015e-04
                Line0073 = 3; 4;  0 5 5 0 0 0  -1.7276e-04
                Line0074 = 3; 0;  1 5 5 0 0 0  -3.7101e-02
                Line0075 = 3; 1;  1 5 5 0 0 0  -4.4824e-03
                Line0076 = 3; 4;  1 5 5 0 0 0  -3.1159e-03
                Line0077 = 3; 2;  2 5 5 0 0 0  +2.4817e-02
                Line0078 = 3; 3;  2 5 5 0 0 0  +6.4914e-03
                Line0079 = 3; 2;  3 3 3 0 0 0  -4.6006e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  +1.0156e-03
                Line0081 = 3; 0;  3 3 5 0 0 0  -7.4349e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  +6.8123e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  +5.9219e-04
                Line0084 = 3; 2;  3 5 5 0 0 0  +1.4129e-02
                Line0085 = 3; 3;  3 5 5 0 0 0  +1.3949e-02
                Line0086 = 3; 0;  5 5 5 0 0 0  +3.8104e-02
                Line0087 = 3; 1;  5 5 5 0 0 0  +2.9942e-03
                Line0088 = 3; 4;  5 5 5 0 0 0  +3.0005e-03

[D2_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 27                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 13                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 14.60293             Tm               ; magnetic rigidity
                   Angle = 33                   degrees          
                  Radius = 12.5                 m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = FPF4-TPC,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = FPF4-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-2.50,-190.0,3.50,190.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 0                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
          sextLength_eff = 0                    m                
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK D3 - Dipole ======================================}

[D3_General]
                    Name = FPF4->FMF1,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 26.581000            m                ; Length block for optical blocks
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\FOR_LISE\LISE_RB14-FMF1.TXT
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D1.cal

[D3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D3_optics]
                    row1 = -2.08939e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+6.34979e+01
                    row2 = +6.70000e-03,-4.78610e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+9.25870e-01
                    row3 = +0.00000e+00,+0.00000e+00,-1.00743e+00,+4.35000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+1.79280e-01,-1.00037e+00,+0.00000e+00,+0.00000e+00
                    row5 = +2.36020e-01,-3.03910e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-3.64180e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D3_optics2]
                   row11 = -4.61069e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +1.71747e-02,+1.95854e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-4.82676e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-1.26737e-02,+1.40850e-02,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +1.38112e-03,+5.14199e-06,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.66891e-05
                   row21 = +1.12385e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +1.56128e-04,-1.96707e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-8.73043e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+3.88956e-03,-3.62333e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -4.68103e-03,-3.16379e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+8.00070e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -7.94247e-03,-6.13092e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +1.47132e-02,+1.33184e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+2.41706e-01,-2.94522e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -2.21432e-03,+1.54969e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +5.36417e-03,+3.65083e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,+4.63147e-02,-1.89602e-01,+0.00000e+00,+0.00000e+00
                   row51 = -3.67507e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = -6.64868e-04,-1.24906e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-9.09008e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+1.48218e-03,-9.14528e-03,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +7.87640e-03,-3.24017e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.03738e-01
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D3_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  +2.1047e-05
                Line0001 = 3; 1;  0 0 0 0 0 0  +7.3738e-06
                Line0002 = 3; 4;  0 0 0 0 0 0  +3.2065e-08
                Line0003 = 3; 0;  0 0 1 0 0 0  -3.4077e-05
                Line0004 = 3; 1;  0 0 1 0 0 0  -1.4608e-05
                Line0005 = 3; 4;  0 0 1 0 0 0  +4.6880e-06
                Line0006 = 3; 0;  0 1 1 0 0 0  +2.6172e-06
                Line0007 = 3; 1;  0 1 1 0 0 0  +8.6681e-06
                Line0008 = 3; 4;  0 1 1 0 0 0  +8.8383e-06
                Line0009 = 3; 0;  1 1 1 0 0 0  -2.2515e-06
                Line0010 = 3; 1;  1 1 1 0 0 0  -1.0788e-05
                Line0011 = 3; 4;  1 1 1 0 0 0  -3.9728e-05
                Line0012 = 3; 2;  0 0 2 0 0 0  -9.2328e-06
                Line0013 = 3; 3;  0 0 2 0 0 0  -5.5348e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -9.3449e-05
                Line0015 = 3; 3;  0 1 2 0 0 0  +7.3362e-07
                Line0016 = 3; 2;  1 1 2 0 0 0  +8.4262e-05
                Line0017 = 3; 3;  1 1 2 0 0 0  +8.3708e-05
                Line0018 = 3; 0;  0 2 2 0 0 0  +2.0860e-05
                Line0019 = 3; 1;  0 2 2 0 0 0  -3.1372e-06
                Line0020 = 3; 4;  0 2 2 0 0 0  +5.6708e-06
                Line0021 = 3; 0;  1 2 2 0 0 0  -2.0375e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  -1.6521e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  +5.5072e-07
                Line0024 = 3; 2;  2 2 2 0 0 0  +2.6074e-05
                Line0025 = 3; 3;  2 2 2 0 0 0  +9.0906e-06
                Line0026 = 3; 2;  0 0 3 0 0 0  -3.3659e-05
                Line0027 = 3; 3;  0 0 3 0 0 0  +5.4462e-06
                Line0028 = 3; 2;  0 1 3 0 0 0  +8.8167e-05
                Line0029 = 3; 3;  0 1 3 0 0 0  +2.2289e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -1.2787e-03
                Line0031 = 3; 3;  1 1 3 0 0 0  +9.7949e-05
                Line0032 = 3; 0;  0 2 3 0 0 0  -2.2261e-04
                Line0033 = 3; 1;  0 2 3 0 0 0  +3.4064e-06
                Line0034 = 3; 4;  0 2 3 0 0 0  -2.0966e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  +5.6154e-04
                Line0036 = 3; 1;  1 2 3 0 0 0  +7.6167e-05
                Line0037 = 3; 4;  1 2 3 0 0 0  +1.0575e-04
                Line0038 = 3; 2;  2 2 3 0 0 0  -2.4842e-04
                Line0039 = 3; 3;  2 2 3 0 0 0  -6.0386e-05
                Line0040 = 3; 0;  0 0 5 0 0 0  -1.8041e-03
                Line0041 = 3; 1;  0 0 5 0 0 0  -6.3615e-04
                Line0042 = 3; 4;  0 0 5 0 0 0  +7.2545e-06
                Line0043 = 3; 0;  0 1 5 0 0 0  +2.0917e-03
                Line0044 = 3; 1;  0 1 5 0 0 0  +8.5852e-04
                Line0045 = 3; 4;  0 1 5 0 0 0  -1.5412e-04
                Line0046 = 3; 0;  1 1 5 0 0 0  -1.7686e-03
                Line0047 = 3; 1;  1 1 5 0 0 0  -2.3618e-04
                Line0048 = 3; 4;  1 1 5 0 0 0  -5.0021e-05
                Line0049 = 3; 2;  0 2 5 0 0 0  +1.1455e-03
                Line0050 = 3; 3;  0 2 5 0 0 0  +5.2351e-04
                Line0051 = 3; 2;  1 2 5 0 0 0  +3.4097e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  +4.3600e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  -4.0930e-04
                Line0054 = 3; 1;  2 2 5 0 0 0  +2.1508e-04
                Line0055 = 3; 4;  2 2 5 0 0 0  -4.7011e-05
                Line0056 = 3; 0;  0 3 3 0 0 0  +2.0925e-04
                Line0057 = 3; 1;  0 3 3 0 0 0  +1.6781e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  +6.7350e-05
                Line0059 = 3; 0;  1 3 3 0 0 0  -2.7796e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  -4.7500e-05
                Line0061 = 3; 4;  1 3 3 0 0 0  +3.0160e-04
                Line0062 = 3; 2;  2 3 3 0 0 0  +4.4847e-04
                Line0063 = 3; 3;  2 3 3 0 0 0  +1.9763e-04
                Line0064 = 3; 2;  0 3 5 0 0 0  +1.8717e-03
                Line0065 = 3; 3;  0 3 5 0 0 0  -3.5202e-05
                Line0066 = 3; 2;  1 3 5 0 0 0  -5.1327e-03
                Line0067 = 3; 3;  1 3 5 0 0 0  -6.2027e-04
                Line0068 = 3; 0;  2 3 5 0 0 0  +3.7925e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  -1.8892e-04
                Line0070 = 3; 4;  2 3 5 0 0 0  +9.7477e-04
                Line0071 = 3; 0;  0 5 5 0 0 0  +5.3431e-02
                Line0072 = 3; 1;  0 5 5 0 0 0  +1.8401e-02
                Line0073 = 3; 4;  0 5 5 0 0 0  -1.0581e-04
                Line0074 = 3; 0;  1 5 5 0 0 0  -2.9520e-02
                Line0075 = 3; 1;  1 5 5 0 0 0  -1.2145e-02
                Line0076 = 3; 4;  1 5 5 0 0 0  +1.0082e-03
                Line0077 = 3; 2;  2 5 5 0 0 0  -2.6886e-02
                Line0078 = 3; 3;  2 5 5 0 0 0  -9.6116e-03
                Line0079 = 3; 2;  3 3 3 0 0 0  -5.5576e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  -5.8253e-05
                Line0081 = 3; 0;  3 3 5 0 0 0  -3.8868e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  -6.9512e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  -1.5708e-03
                Line0084 = 3; 2;  3 5 5 0 0 0  -2.9602e-02
                Line0085 = 3; 3;  3 5 5 0 0 0  +4.3112e-04
                Line0086 = 3; 0;  5 5 5 0 0 0  -5.2521e-01
                Line0087 = 3; 1;  5 5 5 0 0 0  -1.7728e-01
                Line0088 = 3; 4;  5 5 5 0 0 0  +1.9521e-03

[D3_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 25                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 14                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D3_DipoleSettings]
                    Brho = 14.60293             Tm               ; magnetic rigidity
                   Angle = 29.25                degrees          
                  Radius = 12.5                 m                

[D3_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = FMF1-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-10.00,-200.0,190.00,200.0          ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 0                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
          sextLength_eff = 0                    m                
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK D4 - Dipole ======================================}

[D4_General]
                    Name = FMF1->FMF2,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 25.780000            m                ; Length block for optical blocks
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\FOR_LISE\LISE_RB14-FMF2.TXT
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D2.cal

[D4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D4_optics]
                    row1 = -4.39850e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.79297e+01
                    row2 = -2.19600e-02,-2.27349e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+3.49943e+00
                    row3 = +0.00000e+00,+0.00000e+00,-1.10563e+00,+2.21200e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+2.54030e-01,-9.55280e-01,+0.00000e+00,+0.00000e+00
                    row5 = +2.15260e-01,+6.34980e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-3.64180e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D4_optics2]
                   row11 = -8.78878e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -2.71363e-03,+1.92630e-09,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-1.53091e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+7.83357e-03,-2.96189e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +5.89808e-03,+1.72320e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.01562e-02
                   row21 = +9.37081e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +7.73058e-04,+7.01303e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-5.85948e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+3.86521e-04,-3.77552e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -2.57327e-03,-2.18824e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-6.37638e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +1.01359e-04,+1.81511e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +3.52879e-03,-1.09513e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-1.16046e-01,+3.48569e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -4.28690e-04,+2.12560e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -8.12593e-04,-1.35919e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-4.02211e-02,+2.82241e-02,+0.00000e+00,+0.00000e+00
                   row51 = -2.98866e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = -2.55043e-03,-3.91756e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-1.38473e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+8.09814e-03,-5.27410e-03,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +3.29405e-03,+7.34771e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.03200e-01
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D4_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  -4.8755e-07
                Line0001 = 3; 1;  0 0 0 0 0 0  +9.6536e-07
                Line0002 = 3; 4;  0 0 0 0 0 0  -2.5015e-06
                Line0003 = 3; 0;  0 0 1 0 0 0  -5.6383e-06
                Line0004 = 3; 1;  0 0 1 0 0 0  +8.1242e-06
                Line0005 = 3; 4;  0 0 1 0 0 0  -1.8045e-05
                Line0006 = 3; 0;  0 1 1 0 0 0  -6.8113e-05
                Line0007 = 3; 1;  0 1 1 0 0 0  +2.2770e-05
                Line0008 = 3; 4;  0 1 1 0 0 0  -5.2521e-05
                Line0009 = 3; 0;  1 1 1 0 0 0  -6.1156e-06
                Line0010 = 3; 1;  1 1 1 0 0 0  +8.3464e-05
                Line0011 = 3; 4;  1 1 1 0 0 0  -3.3754e-05
                Line0012 = 3; 2;  0 0 2 0 0 0  +4.0224e-06
                Line0013 = 3; 3;  0 0 2 0 0 0  -1.8183e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -2.1634e-05
                Line0015 = 3; 3;  0 1 2 0 0 0  -2.2728e-05
                Line0016 = 3; 2;  1 1 2 0 0 0  +1.1467e-03
                Line0017 = 3; 3;  1 1 2 0 0 0  +2.0630e-04
                Line0018 = 3; 0;  0 2 2 0 0 0  +7.2770e-06
                Line0019 = 3; 1;  0 2 2 0 0 0  -9.9864e-07
                Line0020 = 3; 4;  0 2 2 0 0 0  +1.0102e-05
                Line0021 = 3; 0;  1 2 2 0 0 0  -2.3758e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  -3.1368e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  +1.8642e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  +1.6716e-05
                Line0025 = 3; 3;  2 2 2 0 0 0  +5.0449e-06
                Line0026 = 3; 2;  0 0 3 0 0 0  +1.0977e-05
                Line0027 = 3; 3;  0 0 3 0 0 0  -4.3402e-06
                Line0028 = 3; 2;  0 1 3 0 0 0  +9.9006e-05
                Line0029 = 3; 3;  0 1 3 0 0 0  -2.5171e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -2.4932e-03
                Line0031 = 3; 3;  1 1 3 0 0 0  -6.6318e-04
                Line0032 = 3; 0;  0 2 3 0 0 0  +1.6095e-06
                Line0033 = 3; 1;  0 2 3 0 0 0  -1.5798e-05
                Line0034 = 3; 4;  0 2 3 0 0 0  +3.8248e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  +1.1503e-03
                Line0036 = 3; 1;  1 2 3 0 0 0  +8.6441e-05
                Line0037 = 3; 4;  1 2 3 0 0 0  +1.4190e-04
                Line0038 = 3; 2;  2 2 3 0 0 0  -1.2509e-04
                Line0039 = 3; 3;  2 2 3 0 0 0  -1.0470e-05
                Line0040 = 3; 0;  0 0 5 0 0 0  -1.3105e-05
                Line0041 = 3; 1;  0 0 5 0 0 0  -1.3386e-06
                Line0042 = 3; 4;  0 0 5 0 0 0  -1.7807e-06
                Line0043 = 3; 0;  0 1 5 0 0 0  +1.4981e-04
                Line0044 = 3; 1;  0 1 5 0 0 0  +7.3284e-05
                Line0045 = 3; 4;  0 1 5 0 0 0  -7.1391e-05
                Line0046 = 3; 0;  1 1 5 0 0 0  -1.7558e-03
                Line0047 = 3; 1;  1 1 5 0 0 0  -4.3759e-04
                Line0048 = 3; 4;  1 1 5 0 0 0  -9.1163e-05
                Line0049 = 3; 2;  0 2 5 0 0 0  +3.0167e-04
                Line0050 = 3; 3;  0 2 5 0 0 0  +7.8877e-05
                Line0051 = 3; 2;  1 2 5 0 0 0  -6.2301e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  -1.4290e-03
                Line0053 = 3; 0;  2 2 5 0 0 0  +8.6048e-04
                Line0054 = 3; 1;  2 2 5 0 0 0  +1.5135e-04
                Line0055 = 3; 4;  2 2 5 0 0 0  +1.6283e-04
                Line0056 = 3; 0;  0 3 3 0 0 0  +1.5592e-06
                Line0057 = 3; 1;  0 3 3 0 0 0  -1.8820e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  +2.2452e-05
                Line0059 = 3; 0;  1 3 3 0 0 0  -1.1301e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  -1.9366e-04
                Line0061 = 3; 4;  1 3 3 0 0 0  -8.9197e-05
                Line0062 = 3; 2;  2 3 3 0 0 0  +1.6738e-04
                Line0063 = 3; 3;  2 3 3 0 0 0  +7.9364e-05
                Line0064 = 3; 2;  0 3 5 0 0 0  +1.8323e-04
                Line0065 = 3; 3;  0 3 5 0 0 0  +3.2942e-05
                Line0066 = 3; 2;  1 3 5 0 0 0  +1.4317e-02
                Line0067 = 3; 3;  1 3 5 0 0 0  +3.2079e-03
                Line0068 = 3; 0;  2 3 5 0 0 0  -2.7607e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  -4.3629e-04
                Line0070 = 3; 4;  2 3 5 0 0 0  -1.3859e-04
                Line0071 = 3; 0;  0 5 5 0 0 0  -4.4592e-04
                Line0072 = 3; 1;  0 5 5 0 0 0  -1.4724e-04
                Line0073 = 3; 4;  0 5 5 0 0 0  +3.2746e-05
                Line0074 = 3; 0;  1 5 5 0 0 0  +7.8268e-03
                Line0075 = 3; 1;  1 5 5 0 0 0  +3.3686e-03
                Line0076 = 3; 4;  1 5 5 0 0 0  -5.7888e-04
                Line0077 = 3; 2;  2 5 5 0 0 0  +1.7136e-02
                Line0078 = 3; 3;  2 5 5 0 0 0  +4.3936e-03
                Line0079 = 3; 2;  3 3 3 0 0 0  -3.1027e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  +6.8765e-07
                Line0081 = 3; 0;  3 3 5 0 0 0  +2.5042e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  +2.8662e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  -1.8637e-04
                Line0084 = 3; 2;  3 5 5 0 0 0  -1.3895e-02
                Line0085 = 3; 3;  3 5 5 0 0 0  -2.7794e-03
                Line0086 = 3; 0;  5 5 5 0 0 0  -1.4519e-02
                Line0087 = 3; 1;  5 5 5 0 0 0  -4.9954e-03
                Line0088 = 3; 4;  5 5 5 0 0 0  +2.8333e-03

[D4_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 12                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 16                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D4_DipoleSettings]
                    Brho = 14.60293             Tm               ; magnetic rigidity
                   Angle = -29.25               degrees          
                  Radius = 12.5                 m                

[D4_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = FMF2-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 0                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
          sextLength_eff = 0                    m                
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = FMF2-TPC,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M3_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK W2 - Wedge ======================================}

[W2_General]
                    Name = MF2-degrader,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W2_Compound]
               contents1 = 0,13,1,26.982                         ; Nomer,Z,Atoms,Mass
               thickness = 4,23.87,2.702,0,0                     ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.09                                ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W2_WedgeSettings]
             ProfileMode = 0                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 0                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = -7.05616             mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = FRF3-slit
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK S5 - Drift ======================================}

[S5_General]
                    Name = FMF2 -> FRF1,1                        ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 26.600000            m                ; Length block for optical blocks
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 84                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\FOR_LISE\LISE_RB14-FRF1.TXT

[S5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S5_optics]
                    row1 = -9.88790e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,-1.01134e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,-1.17123e+00,-9.25400e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+4.17470e-01,-5.23970e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S5_optics2]
                   row11 = +3.46151e-06,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +4.54451e-03,+1.02574e-08,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+2.72864e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-5.85257e-03,-6.00992e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +1.93658e-04,+2.53863e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row21 = -5.94419e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -7.07973e-06,-2.32407e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+6.36795e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+4.66926e-05,+1.37618e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -3.32047e-03,-1.98030e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +1.11124e-03,-1.20396e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = -3.14480e-03,-8.76051e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-4.79941e-02,+1.58942e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +6.79116e-04,-4.20887e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +1.16035e-03,+8.17615e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-3.11856e-02,-5.98210e-02,+0.00000e+00,+0.00000e+00
                   row51 = -1.64162e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = -1.95834e-05,-1.28371e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-2.58361e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+1.52755e-05,-7.17426e-03,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[S5_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  +1.3718e-07
                Line0001 = 3; 1;  0 0 0 0 0 0  -1.0049e-08
                Line0002 = 3; 4;  0 0 0 0 0 0  +3.2308e-08
                Line0003 = 3; 0;  0 0 1 0 0 0  +1.8072e-06
                Line0004 = 3; 1;  0 0 1 0 0 0  +1.2542e-07
                Line0005 = 3; 4;  0 0 1 0 0 0  -2.7377e-08
                Line0006 = 3; 0;  0 1 1 0 0 0  -5.2844e-06
                Line0007 = 3; 1;  0 1 1 0 0 0  -1.8647e-06
                Line0008 = 3; 4;  0 1 1 0 0 0  -2.8265e-06
                Line0009 = 3; 0;  1 1 1 0 0 0  -1.7050e-06
                Line0010 = 3; 1;  1 1 1 0 0 0  -5.3309e-06
                Line0011 = 3; 4;  1 1 1 0 0 0  -2.9404e-05
                Line0012 = 3; 2;  0 0 2 0 0 0  +3.6946e-06
                Line0013 = 3; 3;  0 0 2 0 0 0  +2.0440e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -9.2866e-05
                Line0015 = 3; 3;  0 1 2 0 0 0  -4.1330e-06
                Line0016 = 3; 2;  1 1 2 0 0 0  +1.6726e-04
                Line0017 = 3; 3;  1 1 2 0 0 0  +8.9394e-05
                Line0018 = 3; 0;  0 2 2 0 0 0  +2.2491e-05
                Line0019 = 3; 1;  0 2 2 0 0 0  +4.3136e-06
                Line0020 = 3; 4;  0 2 2 0 0 0  -3.5195e-06
                Line0021 = 3; 0;  1 2 2 0 0 0  -1.8486e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  -1.5296e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  -7.9557e-06
                Line0024 = 3; 2;  2 2 2 0 0 0  +2.8140e-05
                Line0025 = 3; 3;  2 2 2 0 0 0  +6.6160e-06
                Line0026 = 3; 2;  0 0 3 0 0 0  -4.7499e-06
                Line0027 = 3; 3;  0 0 3 0 0 0  +4.5795e-06
                Line0028 = 3; 2;  0 1 3 0 0 0  -6.3625e-05
                Line0029 = 3; 3;  0 1 3 0 0 0  +6.0737e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -7.8577e-04
                Line0031 = 3; 3;  1 1 3 0 0 0  +1.8867e-04
                Line0032 = 3; 0;  0 2 3 0 0 0  -2.9378e-05
                Line0033 = 3; 1;  0 2 3 0 0 0  +2.6708e-06
                Line0034 = 3; 4;  0 2 3 0 0 0  -1.1334e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  +1.3799e-04
                Line0036 = 3; 1;  1 2 3 0 0 0  +6.0942e-05
                Line0037 = 3; 4;  1 2 3 0 0 0  -5.9769e-05
                Line0038 = 3; 2;  2 2 3 0 0 0  -4.6718e-05
                Line0039 = 3; 3;  2 2 3 0 0 0  +9.2481e-07
                Line0040 = 3; 0;  0 0 5 0 0 0  +1.5190e-05
                Line0041 = 3; 1;  0 0 5 0 0 0  +1.5747e-06
                Line0042 = 3; 4;  0 0 5 0 0 0  +3.1459e-06
                Line0043 = 3; 0;  0 1 5 0 0 0  +9.9565e-05
                Line0044 = 3; 1;  0 1 5 0 0 0  +1.4708e-05
                Line0045 = 3; 4;  0 1 5 0 0 0  -8.9800e-07
                Line0046 = 3; 0;  1 1 5 0 0 0  -2.9452e-04
                Line0047 = 3; 1;  1 1 5 0 0 0  -5.0919e-05
                Line0048 = 3; 4;  1 1 5 0 0 0  +2.4432e-05
                Line0049 = 3; 2;  0 2 5 0 0 0  -1.3447e-04
                Line0050 = 3; 3;  0 2 5 0 0 0  -3.2442e-05
                Line0051 = 3; 2;  1 2 5 0 0 0  -3.0977e-04
                Line0052 = 3; 3;  1 2 5 0 0 0  -8.4915e-05
                Line0053 = 3; 0;  2 2 5 0 0 0  -2.2292e-04
                Line0054 = 3; 1;  2 2 5 0 0 0  -3.9354e-05
                Line0055 = 3; 4;  2 2 5 0 0 0  +2.1437e-04
                Line0056 = 3; 0;  0 3 3 0 0 0  -5.8097e-05
                Line0057 = 3; 1;  0 3 3 0 0 0  +6.0898e-06
                Line0058 = 3; 4;  0 3 3 0 0 0  +3.6292e-06
                Line0059 = 3; 0;  1 3 3 0 0 0  -5.5236e-04
                Line0060 = 3; 1;  1 3 3 0 0 0  +4.4065e-05
                Line0061 = 3; 4;  1 3 3 0 0 0  +5.9582e-05
                Line0062 = 3; 2;  2 3 3 0 0 0  -2.8336e-05
                Line0063 = 3; 3;  2 3 3 0 0 0  +4.4958e-05
                Line0064 = 3; 2;  0 3 5 0 0 0  -4.0845e-04
                Line0065 = 3; 3;  0 3 5 0 0 0  -1.0009e-04
                Line0066 = 3; 2;  1 3 5 0 0 0  +4.1056e-04
                Line0067 = 3; 3;  1 3 5 0 0 0  +2.8898e-05
                Line0068 = 3; 0;  2 3 5 0 0 0  -8.7166e-04
                Line0069 = 3; 1;  2 3 5 0 0 0  -1.5514e-04
                Line0070 = 3; 4;  2 3 5 0 0 0  +5.5107e-04
                Line0071 = 3; 0;  0 5 5 0 0 0  +4.2020e-04
                Line0072 = 3; 1;  0 5 5 0 0 0  +6.5020e-05
                Line0073 = 3; 0;  1 5 5 0 0 0  -2.4158e-04
                Line0074 = 3; 1;  1 5 5 0 0 0  +4.2268e-04
                Line0075 = 3; 2;  2 5 5 0 0 0  +3.0992e-03
                Line0076 = 3; 3;  2 5 5 0 0 0  +1.0374e-03
                Line0077 = 3; 2;  3 3 3 0 0 0  -1.2261e-04
                Line0078 = 3; 3;  3 3 3 0 0 0  +5.5653e-05
                Line0079 = 3; 0;  3 3 5 0 0 0  +1.3226e-04
                Line0080 = 3; 1;  3 3 5 0 0 0  +4.3345e-05
                Line0081 = 3; 4;  3 3 5 0 0 0  -1.7003e-04
                Line0082 = 3; 2;  3 5 5 0 0 0  +7.9722e-03
                Line0083 = 3; 3;  3 5 5 0 0 0  +3.2749e-03

[S5_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 22                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 30                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S5_DriftSettings]
                    Mode = 0                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
          sextLength_eff = 0                    m                
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S6 - Drift ======================================}

[S6_General]
                    Name = FRF1-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-60.00,-200.0,160.00,200.0          ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S6_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S6_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S6_DriftSettings]
                    Mode = 0                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
          sextLength_eff = 0                    m                
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK M4 - Material ======================================}

[M4_General]
                    Name = FRF1-TPC,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M4_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M4_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 65473038,-20.00,-50.0,20.00,50.0      ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1073741825,-20.00,-50.0,20.00,50.0    ; joint,Bottom,B-limit,Top,T-limit

[M4_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M4_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK D5 - Dipole ======================================}

[D5_General]
                    Name = FRF1->FRF2,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 25.781000            m                ; Length block for optical blocks
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\FOR_LISE\LISE_RB14-FRF2.TXT
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D3.cal

[D5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D5_optics]
                    row1 = -2.29926e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+6.34979e+01
                    row2 = -4.66200e-02,-4.34920e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.84493e+00
                    row3 = +0.00000e+00,+0.00000e+00,-1.17319e+00,+1.80200e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+1.30310e-01,-1.05252e+00,+0.00000e+00,+0.00000e+00
                    row5 = +3.58100e-01,-2.76170e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-3.64180e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D5_optics2]
                   row11 = +5.28281e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -6.14878e-03,+1.06608e-07,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-1.14144e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+1.30776e-02,-1.97824e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = -2.51818e-02,+3.39628e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.20719e-01
                   row21 = +1.05260e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -3.24529e-04,+5.81545e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-1.23892e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+6.56588e-04,-1.89981e-03,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -7.04828e-03,+1.16496e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+6.81839e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -4.84147e-05,+6.49389e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +8.41121e-03,+8.23043e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+4.36545e-02,+2.11784e-01,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -4.71168e-04,-6.36652e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -1.67108e-04,-5.76226e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-1.14835e-02,-4.50492e-02,+0.00000e+00,+0.00000e+00
                   row51 = -2.87103e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +7.83812e-04,-3.69293e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-1.06697e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,-2.31153e-03,-1.76388e-02,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +5.94363e-03,-3.10669e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.78180e-01
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D5_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  -5.0641e-07
                Line0001 = 3; 1;  0 0 0 0 0 0  -2.8594e-07
                Line0002 = 3; 4;  0 0 0 0 0 0  +1.8811e-08
                Line0003 = 3; 0;  0 0 1 0 0 0  +5.0097e-06
                Line0004 = 3; 1;  0 0 1 0 0 0  +8.0138e-07
                Line0005 = 3; 4;  0 0 1 0 0 0  -1.3494e-06
                Line0006 = 3; 0;  0 1 1 0 0 0  -6.2887e-06
                Line0007 = 3; 1;  0 1 1 0 0 0  -8.2113e-07
                Line0008 = 3; 4;  0 1 1 0 0 0  -1.1370e-06
                Line0009 = 3; 0;  1 1 1 0 0 0  -1.0141e-06
                Line0010 = 3; 1;  1 1 1 0 0 0  -4.8450e-07
                Line0011 = 3; 4;  1 1 1 0 0 0  +5.7602e-06
                Line0012 = 3; 2;  0 0 2 0 0 0  +5.7265e-06
                Line0013 = 3; 3;  0 0 2 0 0 0  +3.1109e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -3.8548e-05
                Line0015 = 3; 3;  0 1 2 0 0 0  +2.3650e-06
                Line0016 = 3; 2;  1 1 2 0 0 0  -1.3604e-04
                Line0017 = 3; 3;  1 1 2 0 0 0  +3.0127e-05
                Line0018 = 3; 0;  0 2 2 0 0 0  +4.4751e-06
                Line0019 = 3; 1;  0 2 2 0 0 0  +1.9557e-06
                Line0020 = 3; 4;  0 2 2 0 0 0  +2.9231e-06
                Line0021 = 3; 0;  1 2 2 0 0 0  -4.0781e-05
                Line0022 = 3; 1;  1 2 2 0 0 0  -3.3293e-07
                Line0023 = 3; 4;  1 2 2 0 0 0  +1.5121e-05
                Line0024 = 3; 2;  2 2 2 0 0 0  -7.3426e-07
                Line0025 = 3; 3;  2 2 2 0 0 0  +1.0059e-06
                Line0026 = 3; 2;  0 0 3 0 0 0  -2.8671e-05
                Line0027 = 3; 3;  0 0 3 0 0 0  -3.3472e-06
                Line0028 = 3; 2;  0 1 3 0 0 0  -3.2508e-05
                Line0029 = 3; 3;  0 1 3 0 0 0  +4.1727e-05
                Line0030 = 3; 2;  1 1 3 0 0 0  -7.5516e-04
                Line0031 = 3; 3;  1 1 3 0 0 0  +1.3256e-04
                Line0032 = 3; 0;  0 2 3 0 0 0  -9.3793e-05
                Line0033 = 3; 1;  0 2 3 0 0 0  -1.1183e-05
                Line0034 = 3; 4;  0 2 3 0 0 0  +1.7990e-05
                Line0035 = 3; 0;  1 2 3 0 0 0  -2.9991e-04
                Line0036 = 3; 1;  1 2 3 0 0 0  +1.1671e-05
                Line0037 = 3; 4;  1 2 3 0 0 0  +1.0616e-04
                Line0038 = 3; 2;  2 2 3 0 0 0  -4.9037e-05
                Line0039 = 3; 3;  2 2 3 0 0 0  +5.4006e-06
                Line0040 = 3; 0;  0 0 5 0 0 0  +2.8017e-05
                Line0041 = 3; 1;  0 0 5 0 0 0  +2.0429e-05
                Line0042 = 3; 4;  0 0 5 0 0 0  -4.0252e-06
                Line0043 = 3; 0;  0 1 5 0 0 0  -3.1890e-04
                Line0044 = 3; 1;  0 1 5 0 0 0  -5.7930e-05
                Line0045 = 3; 4;  0 1 5 0 0 0  +8.2881e-05
                Line0046 = 3; 0;  1 1 5 0 0 0  +3.3663e-04
                Line0047 = 3; 1;  1 1 5 0 0 0  +3.9816e-05
                Line0048 = 3; 4;  1 1 5 0 0 0  +6.6381e-05
                Line0049 = 3; 2;  0 2 5 0 0 0  -2.7713e-04
                Line0050 = 3; 3;  0 2 5 0 0 0  -9.0633e-05
                Line0051 = 3; 2;  1 2 5 0 0 0  +2.9164e-04
                Line0052 = 3; 3;  1 2 5 0 0 0  +1.0708e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  -4.0866e-05
                Line0054 = 3; 1;  2 2 5 0 0 0  -2.6175e-05
                Line0055 = 3; 4;  2 2 5 0 0 0  +6.4281e-05
                Line0056 = 3; 0;  0 3 3 0 0 0  -3.2371e-05
                Line0057 = 3; 1;  0 3 3 0 0 0  +1.4373e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  +1.9022e-05
                Line0059 = 3; 0;  1 3 3 0 0 0  -1.2832e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  -4.0399e-05
                Line0061 = 3; 4;  1 3 3 0 0 0  +1.7678e-04
                Line0062 = 3; 2;  2 3 3 0 0 0  -1.1710e-04
                Line0063 = 3; 3;  2 3 3 0 0 0  +4.8833e-05
                Line0064 = 3; 2;  0 3 5 0 0 0  +1.3383e-03
                Line0065 = 3; 3;  0 3 5 0 0 0  +4.0233e-04
                Line0066 = 3; 2;  1 3 5 0 0 0  -2.3504e-03
                Line0067 = 3; 3;  1 3 5 0 0 0  -4.3229e-04
                Line0068 = 3; 0;  2 3 5 0 0 0  +1.3503e-03
                Line0069 = 3; 1;  2 3 5 0 0 0  +3.0211e-04
                Line0070 = 3; 4;  2 3 5 0 0 0  +1.8386e-05
                Line0071 = 3; 0;  0 5 5 0 0 0  -1.3465e-04
                Line0072 = 3; 1;  0 5 5 0 0 0  -4.4402e-04
                Line0073 = 3; 4;  0 5 5 0 0 0  +8.5663e-05
                Line0074 = 3; 0;  1 5 5 0 0 0  +2.2258e-03
                Line0075 = 3; 1;  1 5 5 0 0 0  +9.7885e-04
                Line0076 = 3; 4;  1 5 5 0 0 0  -1.4476e-03
                Line0077 = 3; 2;  2 5 5 0 0 0  +3.3897e-03
                Line0078 = 3; 3;  2 5 5 0 0 0  +1.6073e-03
                Line0079 = 3; 2;  3 3 3 0 0 0  -4.0636e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  +4.1727e-05
                Line0081 = 3; 0;  3 3 5 0 0 0  -3.2884e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  -5.8898e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  -3.4580e-04
                Line0084 = 3; 2;  3 5 5 0 0 0  -1.7184e-02
                Line0085 = 3; 3;  3 5 5 0 0 0  -3.2080e-03
                Line0086 = 3; 0;  5 5 5 0 0 0  +7.0282e-03
                Line0087 = 3; 1;  5 5 5 0 0 0  +3.0855e-03
                Line0088 = 3; 4;  5 5 5 0 0 0  +2.5049e-03

[D5_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 24                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 16                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D5_DipoleSettings]
                    Brho = 12.17217             Tm               ; magnetic rigidity
                   Angle = 29.25                degrees          
                  Radius = 12.5                 m                

[D5_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S7 - Drift ======================================}

[S7_General]
                    Name = FRF2-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S7_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-190.00,-195.0,20.00,195.0          ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S7_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S7_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S7_DriftSettings]
                    Mode = 0                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
          sextLength_eff = 0                    m                
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK M5 - Material ======================================}

[M5_General]
                    Name = FRF2-TPC,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M5_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 0,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M5_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 0,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M5_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M5_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK D6 - Dipole ======================================}

[D6_General]
                    Name = FRF2->FRF3,1                          ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 26.580000            m                ; Length block for optical blocks
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 89                                    ; Number of lines
               COSY file = D:\winfield\COSY-9.1\FOR_LISE\LISE_RB14-FRF3.TXT
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D4.cal

[D6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D6_optics]
                    row1 = -4.77710e-01,-8.39000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.03109e+01
                    row2 = +3.10500e-02,-2.08786e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.53545e+00
                    row3 = +0.00000e+00,+0.00000e+00,-5.14040e-01,-1.61940e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+4.77510e-01,-4.41040e-01,+0.00000e+00,+0.00000e+00
                    row5 = +2.70000e-02,+6.34980e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-3.64180e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D6_optics2]
                   row11 = -5.49535e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +7.86113e-03,-6.89092e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+2.11118e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+1.61888e-03,-4.86599e-03,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = -1.01781e-02,+5.20859e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-4.19328e-01
                   row21 = -2.26962e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -3.86025e-05,-1.71373e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-7.21974e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,-6.44491e-03,-1.07175e-02,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -4.35369e-03,+9.86264e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.07041e-01
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +6.52054e-04,-1.24570e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +5.14534e-04,-1.58696e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-7.03059e-02,+2.46905e-02,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -1.69257e-03,-5.81373e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -6.36963e-03,+7.11457e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-3.30536e-02,-6.67449e-02,+0.00000e+00,+0.00000e+00
                   row51 = -2.96486e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +2.14975e-04,-2.30074e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-7.52315e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+1.76460e-02,+2.74136e-02,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +4.42714e-03,+7.50578e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,-9.52060e-02
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D6_optics3]
                Line0000 = 3; 0;  0 0 0 0 0 0  +3.3183e-07
                Line0001 = 3; 1;  0 0 0 0 0 0  +1.5213e-07
                Line0002 = 3; 4;  0 0 0 0 0 0  -2.4010e-07
                Line0003 = 3; 0;  0 0 1 0 0 0  -4.4387e-06
                Line0004 = 3; 1;  0 0 1 0 0 0  -3.2293e-06
                Line0005 = 3; 4;  0 0 1 0 0 0  +1.0893e-06
                Line0006 = 3; 0;  0 1 1 0 0 0  +6.7912e-06
                Line0007 = 3; 1;  0 1 1 0 0 0  +2.2472e-05
                Line0008 = 3; 4;  0 1 1 0 0 0  +3.8394e-05
                Line0009 = 3; 0;  1 1 1 0 0 0  +2.7783e-04
                Line0010 = 3; 1;  1 1 1 0 0 0  -2.1820e-04
                Line0011 = 3; 4;  1 1 1 0 0 0  -1.6405e-04
                Line0012 = 3; 2;  0 0 2 0 0 0  -3.0534e-06
                Line0013 = 3; 3;  0 0 2 0 0 0  +2.8564e-06
                Line0014 = 3; 2;  0 1 2 0 0 0  -1.0496e-05
                Line0015 = 3; 3;  0 1 2 0 0 0  +6.1849e-05
                Line0016 = 3; 2;  1 1 2 0 0 0  +1.0161e-03
                Line0017 = 3; 3;  1 1 2 0 0 0  +4.3610e-04
                Line0018 = 3; 0;  0 2 2 0 0 0  -9.6542e-06
                Line0019 = 3; 1;  0 2 2 0 0 0  +1.0190e-06
                Line0020 = 3; 4;  0 2 2 0 0 0  +8.9446e-06
                Line0021 = 3; 0;  1 2 2 0 0 0  -3.7406e-04
                Line0022 = 3; 1;  1 2 2 0 0 0  +1.4377e-05
                Line0023 = 3; 4;  1 2 2 0 0 0  -6.7035e-06
                Line0024 = 3; 2;  2 2 2 0 0 0  +4.4623e-05
                Line0025 = 3; 3;  2 2 2 0 0 0  +1.3983e-05
                Line0026 = 3; 2;  0 0 3 0 0 0  -8.3552e-06
                Line0027 = 3; 3;  0 0 3 0 0 0  +1.2993e-05
                Line0028 = 3; 2;  0 1 3 0 0 0  +5.5958e-05
                Line0029 = 3; 3;  0 1 3 0 0 0  +2.6894e-04
                Line0030 = 3; 2;  1 1 3 0 0 0  -1.2721e-03
                Line0031 = 3; 3;  1 1 3 0 0 0  +1.3286e-03
                Line0032 = 3; 0;  0 2 3 0 0 0  -6.4450e-05
                Line0033 = 3; 1;  0 2 3 0 0 0  +2.3950e-05
                Line0034 = 3; 4;  0 2 3 0 0 0  -4.1570e-06
                Line0035 = 3; 0;  1 2 3 0 0 0  -1.8661e-04
                Line0036 = 3; 1;  1 2 3 0 0 0  +7.9586e-05
                Line0037 = 3; 4;  1 2 3 0 0 0  -4.9678e-04
                Line0038 = 3; 2;  2 2 3 0 0 0  -5.9167e-05
                Line0039 = 3; 3;  2 2 3 0 0 0  +2.3205e-05
                Line0040 = 3; 0;  0 0 5 0 0 0  +6.3026e-05
                Line0041 = 3; 1;  0 0 5 0 0 0  +1.5258e-05
                Line0042 = 3; 4;  0 0 5 0 0 0  +4.9334e-07
                Line0043 = 3; 0;  0 1 5 0 0 0  -8.4951e-04
                Line0044 = 3; 1;  0 1 5 0 0 0  -3.7114e-04
                Line0045 = 3; 4;  0 1 5 0 0 0  +5.7951e-05
                Line0046 = 3; 0;  1 1 5 0 0 0  +2.1714e-03
                Line0047 = 3; 1;  1 1 5 0 0 0  +2.1603e-03
                Line0048 = 3; 4;  1 1 5 0 0 0  +8.8845e-04
                Line0049 = 3; 2;  0 2 5 0 0 0  +4.2953e-05
                Line0050 = 3; 3;  0 2 5 0 0 0  +2.0422e-05
                Line0051 = 3; 2;  1 2 5 0 0 0  -1.4434e-03
                Line0052 = 3; 3;  1 2 5 0 0 0  +4.3196e-04
                Line0053 = 3; 0;  2 2 5 0 0 0  +2.9694e-04
                Line0054 = 3; 1;  2 2 5 0 0 0  -9.9063e-05
                Line0055 = 3; 4;  2 2 5 0 0 0  +2.2280e-04
                Line0056 = 3; 0;  0 3 3 0 0 0  -7.8900e-05
                Line0057 = 3; 1;  0 3 3 0 0 0  +5.8896e-05
                Line0058 = 3; 4;  0 3 3 0 0 0  -1.4873e-04
                Line0059 = 3; 0;  1 3 3 0 0 0  -1.2179e-03
                Line0060 = 3; 1;  1 3 3 0 0 0  +2.3125e-04
                Line0061 = 3; 4;  1 3 3 0 0 0  -9.8165e-04
                Line0062 = 3; 2;  2 3 3 0 0 0  -1.1711e-04
                Line0063 = 3; 3;  2 3 3 0 0 0  +1.3157e-04
                Line0064 = 3; 2;  0 3 5 0 0 0  +6.4908e-04
                Line0065 = 3; 3;  0 3 5 0 0 0  +3.2528e-04
                Line0066 = 3; 2;  1 3 5 0 0 0  +1.9187e-03
                Line0067 = 3; 3;  1 3 5 0 0 0  +7.3035e-04
                Line0068 = 3; 0;  2 3 5 0 0 0  +5.1239e-04
                Line0069 = 3; 1;  2 3 5 0 0 0  +1.4405e-04
                Line0070 = 3; 4;  2 3 5 0 0 0  +3.9967e-04
                Line0071 = 3; 0;  0 5 5 0 0 0  +3.9578e-03
                Line0072 = 3; 1;  0 5 5 0 0 0  +1.0639e-03
                Line0073 = 3; 4;  0 5 5 0 0 0  -4.4137e-06
                Line0074 = 3; 0;  1 5 5 0 0 0  -2.9122e-02
                Line0075 = 3; 1;  1 5 5 0 0 0  -1.0701e-02
                Line0076 = 3; 4;  1 5 5 0 0 0  -4.0161e-04
                Line0077 = 3; 2;  2 5 5 0 0 0  -1.0059e-03
                Line0078 = 3; 3;  2 5 5 0 0 0  -1.0675e-03
                Line0079 = 3; 2;  3 3 3 0 0 0  -1.0232e-04
                Line0080 = 3; 3;  3 3 3 0 0 0  +2.0431e-04
                Line0081 = 3; 0;  3 3 5 0 0 0  +2.3759e-03
                Line0082 = 3; 1;  3 3 5 0 0 0  +4.1023e-04
                Line0083 = 3; 4;  3 3 5 0 0 0  -6.4649e-04
                Line0084 = 3; 2;  3 5 5 0 0 0  +6.0004e-03
                Line0085 = 3; 3;  3 5 5 0 0 0  +2.6363e-03
                Line0086 = 3; 0;  5 5 5 0 0 0  +7.9593e-02
                Line0087 = 3; 1;  5 5 5 0 0 0  +2.3244e-02
                Line0088 = 3; 4;  5 5 5 0 0 0  +1.7691e-03

[D6_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 13                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 12                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D6_DipoleSettings]
                    Brho = 12.17217             Tm               ; magnetic rigidity
                   Angle = -29.25               degrees          
                  Radius = 12.5                 m                

[D6_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M6 - Material ======================================}

[M6_General]
                    Name = FRF3-TPC,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M6_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M6_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M6_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M6_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S8 - Drift ======================================}

[S8_General]
                    Name = FRF3-slit,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL

[S8_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-2.00,-190.0,4.00,190.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S8_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S8_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S8_DriftSettings]
                    Mode = 0                                     ; E-Quad 4, Sext 3, Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; Brho 1 / Length 0
        Length_effective = 0                    m                
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
           CalcualteAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
          sextLength_eff = 0                    m                
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture

