Version 9.9.1

{============================= Main Part ======================================}
[general]
                    File = C:\user\c\lise_pp_99\LISEpp_ActualInstaller\install\files\examples\GSI-SFRS\SFRS-HEB-238U132Sn.lpp
                    Date = 29-12-2014
                    Time = 15:07:37
           Configuration = GSI\Super-FRS.lcn
             Optionsfile = A1900_2006.lopt
                   Title = Super-FRS pfrs3_m.dat
          BlockStructure = DSMWDMSDSDMWSDSDMS

[settings]
                   A,Z,Q = 238U 92+                              ; Mass ElementName Charge+ Beam
                  Energy = 1500                 MeV/u            
               Intensity = 1e+12                pps              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 132Sn                                 ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 1                    (±)mm            ; one-half the horisontal beam extent (x)
                      BT = 6.5                  (±)mrad          ; one-half the horisontal beam divergence(x')
                      BY = 10                   (±)mm            ; one-half the vertical beam extent (y)
                      BF = 2.5                  (±)mrad          ; one-half the vertical beam divergence (y')
                      BL = 0                    (±)mm            
                      BD = 0.5                  (±)%             ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = -56                  degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1

[SlitsBeforeTarget]
                   Shape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-50.00,-50.0,50.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[options]
               NP simple = 64                                    ; Number of points in distribution
        NP charge states = 32                                    ; Number of points in distribution
                NP wedge = 16                                    ; Number of points in distribution
           Charge states = Yes                                   ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 3                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
        Target thickness = 1,2500,2.253,0,0                      ; State,Thickness,density,angle,SolidGas
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
      Degrader thickness = 0,0,2.26,0,0                          ; State,Thickness,density,angle,SolidGas
  Degra use for Q-states = 1
         Degrader Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 6                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 64                                    ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1                                     ; 1-Yes, 0-No
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1                                     ; 1 - yes, 0-no
 Pfaff pickup correction = 1                                     ; 1 - yes, 0-no
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1                                     ; 1-Yes, 0-No
        Coulomb_Friedman = 1                                     ; 1-Yes, 0-No
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
            BarrierShape = 1                                     ; 0- classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
                 AA_fast = 0                                     ; 1-Yes, 0-No
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 3                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 2                                     ; energy loss calculation method 0-3
     Anglular straggling = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 1                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 2                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 0                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 1                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-11    
               FisCS_TKE = 1e-8     
                      N0 = 83                                    ; default 82
                     dU0 = -2.65                                 ; default -2.5
                      C0 = 0.7                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -3.8                                  ; default -5.5
                      C1 = 0.15                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-5     
                 BeamInd = 1e-9     
               BeamTotal = 1e-11    

[convolution]
        Convolution mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
               SigmaConv = 91.5                 MeV/c            ; default 90 for Convolution
              CoefConv_0 = 3.344 
              CoefConv_1 = 5.758 
              CoefConv_2 = 2.936 
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = 0.153 

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1                                     ; 1-Yes, 0-No
          AvoidUnboundCS = 1                                     ; 1-Yes, 0-No
       ProtectedChannels = 1                                     ; 1-Yes, 0-No
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0                                     ; 0 - no, 1 - use
 DissipationStepFunction = 1                                     ; 0 - no, 1 - use
         DissipationBeta = 1                                     ; default 2.0
                 mode_1n = 1                                     ; 1-Yes, 0-No
                 mode_2n = 0                                     ; 1-Yes, 0-No
                 mode_1p = 1                                     ; 1-Yes, 0-No
                 mode_2p = 0                                     ; 1-Yes, 0-No
                  mode_a = 1                                     ; 1-Yes, 0-No
                  mode_d = 0                                     ; 1-Yes, 0-No
                  mode_t = 0                                     ; 1-Yes, 0-No
                mode_3he = 0                                     ; 1-Yes, 0-No
                mode_fis = 1                                     ; 1-Yes, 0-No
             mode_brk_up = 1                                     ; 1-Yes, 0-No
              mode_gamma = 0                                     ; 1-Yes, 0-No

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1                                     ; 1-Yes, 0-No
        ShellCorrections = 1                                     ; 1-Yes, 0-No
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0                                     ; 1-Yes, 0-No
          ThermaTimeCoef = 3e-22                                 ; 2.1e-22 MeV *s/e(t)
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0    
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       

[evapauto]
                  tun_a0 = -0.61392
                  tun_a1 = 0.44559
                  tun_a2 = 0.12008
                 A_Bound = 300                                   ; mass
               A_Pairing =  70                                   ; mass

[plot]
            Start target = Detector                              ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = M5
         dE-detector-1st = M5
         dE-detector-2nd = M6
            TKE-detector = M4
                PlotBrho = D1
               PlotWedge = S4
              X-detector = M4
              Y-detector = M5
                 Tilting = M1
                 Stopper = M2
                RO_Wedge = 
          ConditionBlock = A10
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 1
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension

[cs_file]
              UserDiffCS = 0                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0                                     ; 0/1 - use secondary reactions in calculations
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 22
          fiss_ZdeltaBot = 15
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
                Velocity = 1                                     ; Calculat fissile nuclei speed
           LowEx_nucleus = 237U 92+                              ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 232Th90+                              ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 226Ra88+                              ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 8.000e+02 250.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0                                     ; yes-1, no-0
               UseEnergy = 1                                     ; yes-1, no-0

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0                                     ; yes-1, no-0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 92
                   Dr_n0 = 0
                   Dr_n1 = 146

[cross sections]

[previous]
                 Lowerst = 125In49+                              ; Mass ElementName Charge+ Beam
                 Highest = 137Sb51+                              ; Mass ElementName Charge+ Beam

[MC_options]
                   dXsel = 0
                   dYsel = 2
                  dAZQ_X = 1
                  dAZQ_Y = 5
                  dVEL_X = 1
                  dVEL_Y = 0
               dIso_mode = 0
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 0
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 2
                  CS_use = 1
           envelope_show = 0
                use_bore = 0
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
              AZQ_Xsigma = 0.1   
              AZQ_Ysigma = 0.1   
                 G1_gate = 0 0 -100.0000 100.0000
                 G2_gate = 0 0 -100.0000 100.0000
                 G3_gate = 0 0 -100.0000 100.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 0 0,R1,R1,R1                          ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 0 0,R1,R1,R1
            G3_component = 0 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = TA->PF2,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 35.599000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = +1.72300e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.57620e+01
                    row2 = -5.59300e-01,+5.80400e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,-2.07020e+00,-5.00000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+8.50000e-01,-4.62500e-01,+0.00000e+00,+0.00000e+00
                    row5 = -1.44000e+00,+1.50000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-2.40000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 40                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 20                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 18.66896             Tm               ; magnetic rigidity
                   Angle = 33                   degrees          
                  Radius = 12.5                 m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = F1-slit,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-160.00,-190.0,5.00,190.0           ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = MW11,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M1_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = F1-degrader,1                         ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,29,1,63.546                         ; Nomer,Z,Atoms,Mass
               thickness = 0,6500,8.92,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.006                               ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W1_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W1_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W1_WedgeSettings]
             ProfileMode = 0                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 0                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = -3.38502             mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = MF3->MF4
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = PF2->PF4,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 35.900000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = NULL

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = +1.16080e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+2.99030e+01
                    row2 = -6.05000e-02,+8.61500e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.55840e+00
                    row3 = +0.00000e+00,+0.00000e+00,-8.32800e-01,-1.26200e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+4.10500e-01,-1.13850e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,-2.58000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-2.60000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 27                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 13                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 17.01026             Tm               ; magnetic rigidity
                   Angle = 33                   degrees          
                  Radius = 12.5                 m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = MW21,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,0                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[M2_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = PF4-slits,1                           ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-3.00,-190.0,3.00,190.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK D3 - Dipole ======================================}

[D3_General]
                    Name = PF4->MF1,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 26.581000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D1.cal

[D3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D3_optics]
                    row1 = -2.11330e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+6.50000e+01
                    row2 = +1.02000e-02,-4.73200e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+8.73000e-01
                    row3 = +0.00000e+00,+0.00000e+00,-1.09570e+00,+1.17700e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+1.73100e-01,-9.31300e-01,+0.00000e+00,+0.00000e+00
                    row5 = -2.50700e-01,+3.07570e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-1.98000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D3_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 25                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 15                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D3_DipoleSettings]
                    Brho = 17.01026             Tm               ; magnetic rigidity
                   Angle = 29.25                degrees          
                  Radius = 12.5                 m                

[D3_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = F3-slit,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-194.00,-200.0,194.00,200.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK D4 - Dipole ======================================}

[D4_General]
                    Name = MF1->MF2,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 25.780000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D2.cal

[D4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 1,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Bottom,B-limit,Top,T-limit

[D4_optics]
                    row1 = -4.56500e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-2.96760e+01
                    row2 = -1.72000e-02,-2.19010e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+3.02990e+00
                    row3 = +0.00000e+00,+0.00000e+00,-1.00540e+00,+6.00000e-04,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+2.96400e-01,-9.94900e-01,+0.00000e+00,+0.00000e+00
                    row5 = -1.89400e-01,-6.50000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-1.90950e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D4_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 12                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 16                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D4_DipoleSettings]
                    Brho = 17.01026             Tm               ; magnetic rigidity
                   Angle = -29.25               degrees          
                  Radius = 12.5                 m                

[D4_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = MW41,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M3_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M3_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M3_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK W2 - Wedge ======================================}

[W2_General]
                    Name = F4-degrader,1                         ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[W2_Compound]
               contents1 = 0,29,1,63.546                         ; Nomer,Z,Atoms,Mass
               thickness = 0,7700,8.92,0,0                       ; State,Thickness,density,angle,SolidGas
                  Defect = 1,0.007                               ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0

[W2_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Bottom,B-limit,Top,T-limit

[W2_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No

[W2_WedgeSettings]
             ProfileMode = 0                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 0                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = -1.88101             mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = F6-slit
         ProfileFileName = NULL
        ExternalInternal = 0                                     ; external=0 / internal=1
            ReadInternal = 0                                     ; 1 - Yes / 0 - No
          CustomFileName = NULL
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0                                     ; 1 - Yes / 0 - No
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = F4-slits,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-150.00,-150.0,150.00,150.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-05
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK D5 - Dipole ======================================}

[D5_General]
                    Name = MF2->MF3,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 25.780000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D3.cal

[D5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D5_optics]
                    row1 = -2.19040e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-6.50000e+01
                    row2 = -1.15000e-02,-4.56500e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-1.70800e+00
                    row3 = +0.00000e+00,+0.00000e+00,-8.39300e-01,-1.84000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+2.97600e-01,-1.18500e+00,+0.00000e+00,+0.00000e+00
                    row5 = +2.99600e-01,-2.96750e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-1.90950e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D5_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 26                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 15                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D5_DipoleSettings]
                    Brho = 14.95657             Tm               ; magnetic rigidity
                   Angle = -29.25               degrees          
                  Radius = 12.5                 m                

[D5_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK S5 - Drift ======================================}

[S5_General]
                    Name = F5-slit,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-200.00,-200.0,200.00,200.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S5_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S5_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S5_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= BLOCK D6 - Dipole ======================================}

[D6_General]
                    Name = MF3->MF4,1                            ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 26.580000            m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0                                     ; 0/1 -  no/yes
             Before_Quad = 3                                     ; number of quadrupoles before optic device
              After_Quad = 3                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = GSI\FRS_D4.cal

[D6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-100.00,-100.0,100.00,100.0         ; joint,Bottom,B-limit,Top,T-limit

[D6_optics]
                    row1 = -6.38800e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+4.15220e+01
                    row2 = -5.41000e-02,-1.56540e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.90740e+00
                    row3 = +0.00000e+00,+0.00000e+00,-7.80400e-01,+3.76000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+2.58100e-01,-1.40570e+00,+0.00000e+00,+0.00000e+00
                    row5 = +1.02800e-01,+6.50000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,-1.98000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D6_AngAcceptance]
                   X-Use = 1                                     ; Use 1/0
                 X-Value = 12                   mrad             ; acceptance
                   Y-Use = 1                                     ; Use 1/0
                 Y-Value = 13                   mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D6_DipoleSettings]
                    Brho = 14.95657             Tm               ; magnetic rigidity
                   Angle = 29.25                degrees          
                  Radius = 12.5                 m                

[D6_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1                                     ; Use 1/0
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Use 1/0


{============================= BLOCK M4 - Material ======================================}

[M4_General]
                    Name = MW61,1                                ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks

[M4_Compound]
               contents1 = 0,26,1,55.847                         ; Nomer,Z,Atoms,Mass
               thickness = 1,0,7.866,0,0                         ; State,Thickness,density,angle,SolidGas
                  Defect = 0,0.5                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1                                     ; Use 1/0
             ResolutionE = 0,1                                   ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.5,0.5,0.5          ns,mm,mm         ; Time&X&Y space

[M4_slits]
              SlitsShape = 1                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-190.00,-190.0,190.00,190.0         ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-80.00,-80.0,80.00,80.0             ; joint,Bottom,B-limit,Top,T-limit

[M4_BlockCalibration]
                     TOF = 1,1,0,ns                              ; Input PV(0) or CH(1), A, B, dimension
                      dE = 1,1,0,MeV                             ; Input PV(0) or CH(1), A, B, dimension
                       X = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension
                       Y = 1,1,0,mm                              ; Input PV(0) or CH(1), A, B, dimension

[M4_ProdTarget]
              ProdTarget = 0                                     ; 1 - Yes / 0 - No


{============================= BLOCK S6 - Drift ======================================}

[S6_General]
                    Name = F6-slit,1                             ; Name of Block, Constant name 1/0
               Available = 1                                     ; Use 1/0
                  Length = 0.000000             m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
               COSY file = NULL
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1                                     ; 0/1 -  no/yes

[S6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-5.00,-190.0,2.00,190.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S6_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e-10
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S6_AngAcceptance]
                   X-Use = 0                                     ; Use 1/0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0                                     ; Use 1/0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S6_DriftSettings]
                    Mode = 0                                     ; E-Quad 3, M Sext-Quad 2, Standard 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0                                     ; 1 - Yes / 0 - No
          CorrespondBrho = 0                    Tm               
          CorrespondErho = 0e+0                 J/c              ; for e-quad
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture
        Calibration file = NULL


{============================= Calculations ======================================}

[Calculations]
132Sb 51+ 51+ 51+ 51+ 51+ 51+ =1.7330e-04,1.7330e-04,6,2.8685e+01,4.2823e-05,0,3.2285e-08,1.3625e+03,4.1787e+01,6.7204e-01,1,1,1,1,6.7502e-01,9.9559e-01,1,1,1,1,1,1,1,1,1,1,9.8345e-01,9.8345e-01,1,1,1,8.8558e-02,8.8558e-02,1,1,1,1,1,1,1,1,1,1,1,7.5522e-01,1,1,1,1,7.5611e-01,9.9883e-01,1,8.0877e-01,1,1,1,8.0877e-01,1,1,1,1,1,1,1,1,2.4346e-01,2.4346e-01,1,1,1,6.5017e-01,1,1,1,6.5022e-01,1,1,1,1,1,8.9665e-01,1,1,1,8.9665e-01,1,1,1,1,1,1,1,1,7.1694e-01,1,1,1,1,7.1819e-01,9.9825e-01,1,1,1,1,1,1,7.9731e-01,1,1,1,7.9731e-01,1,1,1,1,1,6.3467e-01,1,1,1,6.3467e-01,1,1,1,1,1,1,1,1,1.7552e-05,1.7552e-05,1,1,1
132Sb 51+ 51+ 51+ 51+ 51+ 51+ =2.6524e-01,2.6524e-01,5,2.8685e+01,4.8665e-02,0,4.3483e-08,1.3632e+03,4.6640e+01,6.7204e-01,1,1,1,1,6.7502e-01,9.9559e-01,1,1,1,1,1,1,1,1,1,1,9.6870e-01,9.6876e-01,1,1,1,1.2103e-01,1.2103e-01,1,1,1,1,1,1,1,1,1,1,1,7.5522e-01,1,1,1,1,7.5611e-01,9.9883e-01,1,8.0004e-01,1,1,1,8.0004e-01,1,1,1,1,1,1,1,1,2.4170e-01,2.4170e-01,1,1,1,6.4660e-01,9.9826e-01,1,1,6.4773e-01,1,1,1,1,1,8.8380e-01,1,1,1,8.8380e-01,1,1,1,1,1,1,1,1,7.1693e-01,1,1,1,1,7.1819e-01,9.9825e-01,1,9.9345e-01,9.9345e-01,1,1,1,7.9308e-01,1,1,1,7.9308e-01,1,1,1,1,1,6.3690e-01,1,1,1,6.3690e-01,1,1,1,1,1,1,1,1,1.8392e-05,1.8392e-05,1,1,1
132Sb 51+ 51+ 51+ 51+ 51+ 51+ =2.8420e+01,2.8420e+01,4,2.8685e+01,4.3823e+00,0,5.1738e-08,1.3637e+03,5.0247e+01,6.7204e-01,1,1,1,1,6.7502e-01,9.9559e-01,1,1,1,1,1,1,1,1,1,1,9.5455e-01,9.5607e-01,1,1,9.9841e-01,1.4486e-01,1.4486e-01,1,1,1,1,1,1,1,1,1,1,1,7.5522e-01,1,1,1,1,7.5610e-01,9.9883e-01,1,7.9474e-01,1,1,1,7.9474e-01,1,1,1,1,1,1,1,1,2.4232e-01,2.4232e-01,1,1,1,6.4046e-01,9.9295e-01,1,1,6.4501e-01,9.9823e-01,9.9823e-01,1,1,1,8.7504e-01,1,1,1,8.7518e-01,1,1,1,1,1,1,1,1,7.1693e-01,1,1,1,1,7.1819e-01,9.9825e-01,1,9.8315e-01,9.8315e-01,1,1,1,7.9157e-01,1,1,1,7.9157e-01,1,1,1,1,1,6.3921e-01,1,1,1,6.3921e-01,1,1,1,1,1,1,1,1,1.9186e-05,1.9186e-05,1,1,1
131Sb 51+ 51+ 51+ 51+ 51+ 51+ =2.1937e-01,2.1937e-01,6,1.0860e+04,5.1134e-04,0,3.4226e-06,1.3622e+03,4.2774e+01,6.7246e-01,1,1,1,1,6.7544e-01,9.9559e-01,1,1,1,1,1,1,1,1,1,1,9.4616e-01,9.4616e-01,1,1,1,4.1173e-02,4.1173e-02,1,1,1,1,1,1,1,1,1,1,1,7.5584e-01,1,1,1,1,7.5670e-01,9.9886e-01,1,8.0707e-01,1,1,1,8.0707e-01,1,1,1,1,1,1,1,1,3.5612e-01,3.5612e-01,1,1,1,6.5005e-01,1,1,1,6.5005e-01,1,1,1,1,1,8.9532e-01,1,1,1,8.9532e-01,1,1,1,1,1,1,1,1,7.1763e-01,1,1,1,1,7.1885e-01,9.9830e-01,1,1,1,1,1,1,7.9650e-01,1,1,1,7.9650e-01,1,1,1,1,1,6.3515e-01,1,1,1,6.3515e-01,1,1,1,1,1,1,1,1,2.8464e-03,2.8464e-03,1,1,1
131Sb 51+ 51+ 51+ 51+ 51+ 51+ =2.8766e+02,2.8766e+02,5,1.0860e+04,4.9389e-01,0,4.6467e-06,1.3628e+03,4.7266e+01,6.7246e-01,1,1,1,1,6.7544e-01,9.9559e-01,1,1,1,1,1,1,1,1,1,1,9.2554e-01,9.2575e-01,1,1,1,6.5305e-02,6.5305e-02,1,1,1,1,1,1,1,1,1,1,1,7.5583e-01,1,1,1,1,7.5670e-01,9.9886e-01,1,7.9999e-01,1,1,1,7.9999e-01,1,1,1,1,1,1,1,1,3.5479e-01,3.5479e-01,1,1,1,6.4772e-01,1,1,1,6.4776e-01,1,1,1,1,1,8.8512e-01,1,1,1,8.8512e-01,1,1,1,1,1,1,1,1,7.1763e-01,1,1,1,1,7.1885e-01,9.9830e-01,1,1,1,1,1,1,7.9568e-01,1,1,1,7.9568e-01,1,1,1,1,1,6.3875e-01,1,1,1,6.3875e-01,1,1,1,1,1,1,1,1,2.5499e-03,2.5499e-03,1,1,1
131Sb 51+ 51+ 51+ 51+ 51+ 51+ =1.0572e+04,1.0572e+04,4,1.0860e+04,1.2404e+01,0,6.7997e-06,1.3633e+03,5.0673e+01,6.7246e-01,1,1,1,1,6.7544e-01,9.9559e-01,1,1,1,1,1,1,1,1,1,1,9.0852e-01,9.1030e-01,1,1,9.9804e-01,8.5372e-02,8.5372e-02,1,1,1,1,1,1,1,1,1,1,1,7.5583e-01,1,1,1,1,7.5670e-01,9.9886e-01,1,7.9669e-01,1,1,1,7.9669e-01,1,1,1,1,1,1,1,1,3.5578e-01,3.5578e-01,1,1,1,6.4586e-01,1,1,1,6.4618e-01,1,1,1,1,1,8.8021e-01,1,1,1,8.8021e-01,1,1,1,1,1,1,1,1,7.1763e-01,1,1,1,1,7.1885e-01,9.9830e-01,1,9.9747e-01,9.9747e-01,1,1,1,7.9335e-01,1,1,1,7.9335e-01,1,1,1,1,1,6.3952e-01,1,1,1,6.3952e-01,1,1,1,1,1,1,1,1,2.9479e-03,2.9479e-03,1,1,1
130Sb 51+ 51+ 51+ 51+ 51+ 51+ =8.7210e+00,8.7210e+00,6,7.0362e+04,2.5307e-03,0,2.7493e-05,1.3619e+03,4.3436e+01,6.7288e-01,1,1,1,1,6.7586e-01,9.9559e-01,1,1,1,1,1,1,1,1,1,1,8.8577e-01,8.8578e-01,1,1,1,1.2973e-02,1.2973e-02,1,1,1,1,1,1,1,1,1,1,1,7.5645e-01,1,1,1,1,7.5729e-01,9.9889e-01,1,8.0591e-01,1,1,1,8.0591e-01,1,1,1,1,1,1,1,1,4.7621e-01,4.7621e-01,1,1,1,6.4970e-01,1,1,1,6.4970e-01,1,1,1,1,1,8.9362e-01,1,1,1,8.9362e-01,1,1,1,1,1,1,1,1,7.1833e-01,1,1,1,1,7.1952e-01,9.9835e-01,1,1,1,1,1,1,7.9609e-01,1,1,1,7.9609e-01,1,1,1,1,1,6.3544e-01,1,1,1,6.3544e-01,1,1,1,1,1,1,1,1,5.8052e-02,5.8052e-02,1,1,1
130Sb 51+ 51+ 51+ 51+ 51+ 51+ =1.2162e+04,1.2162e+04,5,7.0362e+04,1.9442e+00,0,4.9908e-05,1.3625e+03,4.7667e+01,6.7288e-01,1,1,1,1,6.7586e-01,9.9559e-01,1,1,1,1,1,1,1,1,1,1,8.6322e-01,8.6344e-01,1,1,1,2.6994e-02,2.6994e-02,1,1,1,1,1,1,1,1,1,1,1,7.5645e-01,1,1,1,1,7.5729e-01,9.9889e-01,1,7.9928e-01,1,1,1,7.9928e-01,1,1,1,1,1,1,1,1,4.7525e-01,4.7525e-01,1,1,1,6.4714e-01,1,1,1,6.4714e-01,1,1,1,1,1,8.8459e-01,1,1,1,8.8459e-01,1,1,1,1,1,1,1,1,7.1833e-01,1,1,1,1,7.1952e-01,9.9835e-01,1,1,1,1,1,1,7.9424e-01,1,1,1,7.9424e-01,1,1,1,1,1,6.3901e-01,1,1,1,6.3901e-01,1,1,1,1,1,1,1,1,5.3079e-02,5.3079e-02,1,1,1
130Sb 51+ 51+ 51+ 51+ 51+ 51+ =5.8191e+04,5.8191e+04,4,7.0362e+04,6.0976e+00,0,7.6135e-05,1.3630e+03,5.0860e+01,6.7288e-01,1,1,1,1,6.7586e-01,9.9559e-01,1,1,1,1,1,1,1,1,1,1,8.4606e-01,8.4790e-01,1,1,9.9783e-01,4.0802e-02,4.0802e-02,1,1,1,1,1,1,1,1,1,1,1,7.5645e-01,1,1,1,1,7.5729e-01,9.9889e-01,1,7.9634e-01,1,1,1,7.9634e-01,1,1,1,1,1,1,1,1,4.8000e-01,4.8000e-01,1,1,1,6.4601e-01,1,1,1,6.4601e-01,1,1,1,1,1,8.7986e-01,1,1,1,8.7986e-01,1,1,1,1,1,1,1,1,7.1833e-01,1,1,1,1,7.1952e-01,9.9835e-01,1,1,1,1,1,1,7.9347e-01,1,1,1,7.9347e-01,1,1,1,1,1,6.3973e-01,1,1,1,6.3973e-01,1,1,1,1,1,1,1,1,5.4699e-02,5.4699e-02,1,1,1
129Sb 51+ 51+ 51+ 51+ 51+ 51+ =9.0086e+01,9.0086e+01,6,1.5920e+05,2.3465e-02,0,3.0629e-05,1.3616e+03,4.4346e+01,6.7330e-01,1,1,1,1,6.7629e-01,9.9558e-01,1,1,1,1,1,1,1,1,1,1,8.0041e-01,8.0044e-01,1,1,1,2.2611e-03,2.2611e-03,1,1,1,1,1,1,1,1,1,1,1,7.5706e-01,1,1,1,1,7.5789e-01,9.9891e-01,1,8.0406e-01,1,1,1,8.0406e-01,1,1,1,1,1,1,1,1,5.7415e-01,5.7415e-01,1,1,1,6.4909e-01,1,1,1,6.4909e-01,1,1,1,1,1,8.9093e-01,1,1,1,8.9093e-01,1,1,1,1,1,1,1,1,7.1903e-01,1,1,1,1,7.2019e-01,9.9839e-01,1,1,1,1,1,1,7.9568e-01,1,1,1,7.9568e-01,1,1,1,1,1,6.3578e-01,1,1,1,6.3578e-01,1,1,1,1,1,1,1,1,3.4190e-01,3.4190e-01,1,1,1
129Sb 51+ 51+ 51+ 51+ 51+ 51+ =8.9577e+04,8.9577e+04,5,1.5920e+05,8.1607e+00,0,8.7571e-05,1.3621e+03,4.7969e+01,6.7330e-01,1,1,1,1,6.7629e-01,9.9558e-01,1,1,1,1,1,1,1,1,1,1,7.8086e-01,7.8121e-01,1,1,1,6.5698e-03,6.5698e-03,1,1,1,1,1,1,1,1,1,1,1,7.5706e-01,1,1,1,1,7.5789e-01,9.9891e-01,1,7.9873e-01,1,1,1,7.9873e-01,1,1,1,1,1,1,1,1,5.9170e-01,5.9170e-01,1,1,1,6.4715e-01,1,1,1,6.4715e-01,1,1,1,1,1,8.8301e-01,1,1,1,8.8301e-01,1,1,1,1,1,1,1,1,7.1903e-01,1,1,1,1,7.2019e-01,9.9839e-01,1,1,1,1,1,1,7.9530e-01,1,1,1,7.9530e-01,1,1,1,1,1,6.3907e-01,1,1,1,6.3907e-01,1,1,1,1,1,1,1,1,3.3932e-01,3.3932e-01,1,1,1
129Sb 51+ 51+ 51+ 51+ 51+ 51+ =6.9534e+04,6.9534e+04,4,1.5920e+05,3.2972e+00,0,1.6824e-04,1.3626e+03,5.1037e+01,6.7330e-01,1,1,1,1,6.7629e-01,9.9558e-01,1,1,1,1,1,1,1,1,1,1,7.6648e-01,7.6831e-01,1,1,9.9762e-01,1.3228e-02,1.3228e-02,1,1,1,1,1,1,1,1,1,1,1,7.5706e-01,1,1,1,1,7.5789e-01,9.9891e-01,1,7.9581e-01,1,1,1,7.9581e-01,1,1,1,1,1,1,1,1,5.9943e-01,5.9943e-01,1,1,1,6.4576e-01,1,1,1,6.4576e-01,1,1,1,1,1,8.7869e-01,1,1,1,8.7869e-01,1,1,1,1,1,1,1,1,7.1903e-01,1,1,1,1,7.2019e-01,9.9839e-01,1,1,1,1,1,1,7.9319e-01,1,1,1,7.9319e-01,1,1,1,1,1,6.3986e-01,1,1,1,6.3986e-01,1,1,1,1,1,1,1,1,3.2956e-01,3.2956e-01,1,1,1
128Sb 51+ 51+ 51+ 51+ 51+ 51+ =3.7937e+01,3.7937e+01,6,3.2896e+04,1.2278e-01,0,2.4650e-06,1.3612e+03,4.4826e+01,6.7372e-01,1,1,1,1,6.7671e-01,9.9558e-01,1,1,1,1,1,1,1,1,1,1,6.9665e-01,6.9669e-01,1,1,1,1.0266e-04,1.0266e-04,1,1,1,1,1,1,1,1,1,1,1,7.5768e-01,1,1,1,1,7.5848e-01,9.9894e-01,1,8.0303e-01,1,1,1,8.0303e-01,1,1,1,1,1,1,1,1,6.5333e-01,6.5333e-01,1,1,1,6.4868e-01,1,1,1,6.4868e-01,1,1,1,1,1,8.8920e-01,1,1,1,8.8920e-01,1,1,1,1,1,1,1,1,7.1973e-01,1,1,1,1,7.2086e-01,9.9843e-01,1,1,1,1,1,1,7.9540e-01,1,1,1,7.9540e-01,1,1,1,1,1,6.3782e-01,1,1,1,6.3782e-01,1,1,1,1,1,1,1,1,6.1105e-01,6.1105e-01,1,1,1
128Sb 51+ 51+ 51+ 51+ 51+ 51+ =2.4671e+04,2.4671e+04,5,3.2896e+04,1.3067e+01,0,1.5063e-05,1.3618e+03,4.8287e+01,6.7372e-01,1,1,1,1,6.7671e-01,9.9558e-01,1,1,1,1,1,1,1,1,1,1,6.8221e-01,6.8260e-01,1,1,1,6.2728e-04,6.2728e-04,1,1,1,1,1,1,1,1,1,1,1,7.5768e-01,1,1,1,1,7.5848e-01,9.9894e-01,1,7.9839e-01,1,1,1,7.9839e-01,1,1,1,1,1,1,1,1,6.7604e-01,6.7604e-01,1,1,1,6.4692e-01,1,1,1,6.4692e-01,1,1,1,1,1,8.8191e-01,1,1,1,8.8191e-01,1,1,1,1,1,1,1,1,7.1973e-01,1,1,1,1,7.2086e-01,9.9843e-01,1,1,1,1,1,1,7.9498e-01,1,1,1,7.9498e-01,1,1,1,1,1,6.3911e-01,1,1,1,6.3911e-01,1,1,1,1,1,1,1,1,6.1235e-01,6.1235e-01,1,1,1
128Sb 51+ 51+ 51+ 51+ 51+ 51+ =8.1870e+03,8.1870e+03,4,3.2896e+04,1.3723e+00,0,4.7597e-05,1.3622e+03,5.1111e+01,6.7372e-01,1,1,1,1,6.7671e-01,9.9558e-01,1,1,1,1,1,1,1,1,1,1,6.7332e-01,6.7504e-01,1,1,9.9746e-01,2.0242e-03,2.0242e-03,1,1,1,1,1,1,1,1,1,1,1,7.5768e-01,1,1,1,1,7.5848e-01,9.9894e-01,1,7.9537e-01,1,1,1,7.9537e-01,1,1,1,1,1,1,1,1,6.8492e-01,6.8492e-01,1,1,1,6.4551e-01,1,1,1,6.4551e-01,1,1,1,1,1,8.7783e-01,1,1,1,8.7783e-01,1,1,1,1,1,1,1,1,7.1973e-01,1,1,1,1,7.2086e-01,9.9843e-01,1,1,1,1,1,1,7.9299e-01,1,1,1,7.9299e-01,1,1,1,1,1,6.3997e-01,1,1,1,6.3997e-01,1,1,1,1,1,1,1,1,6.0677e-01,6.0677e-01,1,1,1
127Sb 51+ 51+ 51+ 51+ 51+ 51+ =5.1409e-01,5.1409e-01,6,6.9496e+02,6.7512e-01,0,6.0750e-09,1.3609e+03,4.5468e+01,6.7415e-01,1,1,1,1,6.7714e-01,9.9558e-01,1,1,1,1,1,1,1,1,1,1,5.7789e-01,5.7794e-01,1,1,1,3.8266e-07,3.8266e-07,1,1,1,1,1,1,1,1,1,1,1,7.5830e-01,1,1,1,1,7.5908e-01,9.9896e-01,1,8.0175e-01,1,1,1,8.0175e-01,1,1,1,1,1,1,1,1,7.0807e-01,7.0807e-01,1,1,1,6.4838e-01,1,1,1,6.4838e-01,1,1,1,1,1,8.8672e-01,1,1,1,8.8672e-01,1,1,1,1,1,1,1,1,7.2043e-01,1,1,1,1,7.2153e-01,9.9847e-01,1,1,1,1,1,1,7.9402e-01,1,1,1,7.9402e-01,1,1,1,1,1,6.3687e-01,1,1,1,6.3687e-01,1,1,1,1,1,1,1,1,4.5194e-01,4.5194e-01,1,1,1
127Sb 51+ 51+ 51+ 51+ 51+ 51+ =6.5739e+02,6.5739e+02,5,6.9496e+02,2.2282e+01,0,2.3537e-07,1.3614e+03,4.9046e+01,6.7415e-01,1,1,1,1,6.7714e-01,9.9558e-01,1,1,1,1,1,1,1,1,1,1,5.7328e-01,5.7370e-01,1,1,1,1.5523e-05,1.5523e-05,1,1,1,1,1,1,1,1,1,1,1,7.5830e-01,1,1,1,1,7.5908e-01,9.9896e-01,1,7.9762e-01,1,1,1,7.9762e-01,1,1,1,1,1,1,1,1,7.4107e-01,7.4107e-01,1,1,1,6.4648e-01,1,1,1,6.4648e-01,1,1,1,1,1,8.8028e-01,1,1,1,8.8028e-01,1,1,1,1,1,1,1,1,7.2043e-01,1,1,1,1,7.2153e-01,9.9847e-01,1,1,1,1,1,1,7.9256e-01,1,1,1,7.9256e-01,1,1,1,1,1,6.3957e-01,1,1,1,6.3957e-01,1,1,1,1,1,1,1,1,4.2118e-01,4.2118e-01,1,1,1
127Sb 51+ 51+ 51+ 51+ 51+ 51+ =3.7050e+01,3.7050e+01,4,6.9496e+02,1.2192e+00,0,2.4244e-07,1.3619e+03,4.9660e+01,6.7415e-01,1,1,1,1,6.7714e-01,9.9558e-01,1,1,1,1,1,1,1,1,1,1,5.7178e-01,5.7335e-01,1,1,9.9726e-01,1.6065e-05,1.6065e-05,1,1,1,1,1,1,1,1,1,1,1,7.5830e-01,1,1,1,1,7.5908e-01,9.9896e-01,1,7.9618e-01,1,1,1,7.9618e-01,1,1,1,1,1,1,1,1,7.3461e-01,7.3461e-01,1,1,1,6.4604e-01,1,1,1,6.4604e-01,1,1,1,1,1,8.7960e-01,1,1,1,8.7960e-01,1,1,1,1,1,1,1,1,7.2043e-01,1,1,1,1,7.2153e-01,9.9847e-01,1,1,1,1,1,1,7.9353e-01,1,1,1,7.9353e-01,1,1,1,1,1,6.3986e-01,1,1,1,6.3986e-01,1,1,1,1,1,1,1,1,4.2466e-01,4.2466e-01,1,1,1
136Sn 50+ 50+ 50+ 50+ 50+ 50+ =8.9126e-06,8.9126e-06,4,8.9126e-06,1.3855e-07,0,5.1321e-07,1.3667e+03,4.7255e+01,6.7078e-01,1,1,1,1,6.7334e-01,9.9620e-01,1,1,1,1,1,1,1,1,1,1,9.9170e-01,9.9176e-01,1,1,1,7.5082e-01,7.5082e-01,1,1,1,1,1,1,1,1,1,1,1,7.5300e-01,1,1,1,1,7.5389e-01,9.9883e-01,1,7.9389e-01,1,1,1,7.9389e-01,1,1,1,1,1,1,1,1,4.7386e-01,4.7386e-01,1,1,1,3.7061e-01,5.7793e-01,1,1,6.4127e-01,9.6758e-01,9.6758e-01,1,1,1,8.5587e-01,1,1,1,8.5587e-01,1,1,1,1,1,1,1,1,7.1442e-01,1,1,1,1,7.1571e-01,9.9820e-01,1,8.6370e-01,8.6370e-01,1,1,1,7.8156e-01,1,1,1,7.8156e-01,1,1,1,1,1,6.3902e-01,1,1,1,6.3902e-01,1,1,1,1,1,1,1,1,3.8352e-05,3.8352e-05,1,1,1
135Sn 50+ 50+ 50+ 50+ 50+ 50+ =3.8077e-02,3.8077e-02,4,3.8077e-02,3.1077e-06,0,9.7749e-05,1.3664e+03,4.7871e+01,6.7119e-01,1,1,1,1,6.7376e-01,9.9620e-01,1,1,1,1,1,1,1,1,1,1,9.9869e-01,9.9881e-01,1,1,1,6.8506e-01,6.8506e-01,1,1,1,1,1,1,1,1,1,1,1,7.5361e-01,1,1,1,1,7.5447e-01,9.9886e-01,1,7.9207e-01,1,1,1,7.9207e-01,1,1,1,1,1,1,1,1,6.0856e-01,6.0856e-01,1,1,1,4.1823e-01,6.5311e-01,1,1,6.4037e-01,9.6920e-01,9.6920e-01,1,1,1,8.5506e-01,1,1,1,8.5506e-01,1,1,1,1,1,1,1,1,7.1511e-01,1,1,1,1,7.1636e-01,9.9825e-01,1,8.5222e-01,8.5222e-01,1,1,1,7.8143e-01,1,1,1,7.8143e-01,1,1,1,1,1,6.3874e-01,1,1,1,6.3874e-01,1,1,1,1,1,1,1,1,5.5582e-03,5.5582e-03,1,1,1
134Sn 50+ 50+ 50+ 50+ 50+ 50+ =1.2697e-02,1.2697e-02,5,2.6579e+01,3.9846e-08,0,2.5422e-03,1.3656e+03,4.5175e+01,6.7161e-01,1,1,1,1,6.7417e-01,9.9620e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,6.0092e-01,6.0092e-01,1,1,1,1,1,1,1,1,1,1,1,7.5421e-01,1,1,1,1,7.5506e-01,9.9888e-01,1,7.9738e-01,1,1,1,7.9738e-01,1,1,1,1,1,1,1,1,7.2118e-01,7.2118e-01,1,1,1,5.0546e-01,7.8466e-01,1,1,6.4418e-01,9.7356e-01,9.7356e-01,1,1,1,8.6452e-01,1,1,1,8.6452e-01,1,1,1,1,1,1,1,1,7.1579e-01,1,1,1,1,7.1701e-01,9.9829e-01,1,8.9555e-01,8.9555e-01,1,1,1,7.8446e-01,1,1,1,7.8446e-01,1,1,1,1,1,6.3763e-01,1,1,1,6.3763e-01,1,1,1,1,1,1,1,1,1.0647e-01,1.0647e-01,1,1,1
134Sn 50+ 50+ 50+ 50+ 50+ 50+ =2.6566e+01,2.6566e+01,4,2.6579e+01,9.4862e-05,0,2.2342e-03,1.3661e+03,4.8563e+01,6.7161e-01,1,1,1,1,6.7417e-01,9.9620e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5.9355e-01,5.9355e-01,1,1,1,1,1,1,1,1,1,1,1,7.5421e-01,1,1,1,1,7.5505e-01,9.9888e-01,1,7.9103e-01,1,1,1,7.9103e-01,1,1,1,1,1,1,1,1,7.2117e-01,7.2117e-01,1,1,1,4.7470e-01,7.4140e-01,1,1,6.4028e-01,9.7152e-01,9.7152e-01,1,1,1,8.5473e-01,1,1,1,8.5473e-01,1,1,1,1,1,1,1,1,7.1579e-01,1,1,1,1,7.1701e-01,9.9829e-01,1,8.6732e-01,8.6732e-01,1,1,1,7.8069e-01,1,1,1,7.8069e-01,1,1,1,1,1,6.3809e-01,1,1,1,6.3809e-01,1,1,1,1,1,1,1,1,1.0690e-01,1.0690e-01,1,1,1
133Sn 50+ 50+ 50+ 50+ 50+ 50+ =8.9102e-01,8.9102e-01,5,9.6718e+02,6.3226e-07,0,1.1243e-02,1.3653e+03,4.5700e+01,6.7202e-01,1,1,1,1,6.7459e-01,9.9620e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4.8526e-01,4.8526e-01,1,1,1,1,1,1,1,1,1,1,1,7.5482e-01,1,1,1,1,7.5564e-01,9.9891e-01,1,7.9586e-01,1,1,1,7.9586e-01,1,1,1,1,1,1,1,1,7.9217e-01,7.9217e-01,1,1,1,5.8239e-01,9.0391e-01,1,1,6.4430e-01,9.6333e-01,9.6333e-01,1,1,1,8.6521e-01,1,1,1,8.6521e-01,1,1,1,1,1,1,1,1,7.1648e-01,1,1,1,1,7.1767e-01,9.9834e-01,1,9.0035e-01,9.0035e-01,1,1,1,7.8597e-01,1,1,1,7.8597e-01,1,1,1,1,1,6.3714e-01,1,1,1,6.3714e-01,1,1,1,1,1,1,1,1,4.6205e-01,4.6205e-01,1,1,1
133Sn 50+ 50+ 50+ 50+ 50+ 50+ =9.6629e+02,9.6629e+02,4,9.6718e+02,7.4956e-04,0,1.0285e-02,1.3658e+03,4.9120e+01,6.7202e-01,1,1,1,1,6.7459e-01,9.9620e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4.8863e-01,4.8863e-01,1,1,1,1,1,1,1,1,1,1,1,7.5482e-01,1,1,1,1,7.5564e-01,9.9891e-01,1,7.9041e-01,1,1,1,7.9041e-01,1,1,1,1,1,1,1,1,7.9213e-01,7.9213e-01,1,1,1,5.5359e-01,8.6387e-01,1,1,6.4083e-01,9.5485e-01,9.5485e-01,1,1,1,8.5664e-01,1,1,1,8.5664e-01,1,1,1,1,1,1,1,1,7.1648e-01,1,1,1,1,7.1767e-01,9.9834e-01,1,8.8618e-01,8.8618e-01,1,1,1,7.8278e-01,1,1,1,7.8278e-01,1,1,1,1,1,6.3765e-01,1,1,1,6.3765e-01,1,1,1,1,1,1,1,1,4.6207e-01,4.6207e-01,1,1,1
132Sn 50+ 50+ 50+ 50+ 50+ 50+ =2.9004e-01,2.9004e-01,6,9.3656e+04,1.7864e-07,0,1.2953e-02,1.3643e+03,4.1175e+01,6.7244e-01,1,1,1,1,6.7501e-01,9.9620e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3.4314e-01,3.4314e-01,1,1,1,1,1,1,1,1,1,1,1,7.5543e-01,1,1,1,1,7.5623e-01,9.9894e-01,1,8.0319e-01,1,1,1,8.0319e-01,1,1,1,1,1,1,1,1,8.1894e-01,8.1894e-01,1,1,1,6.3581e-01,9.8348e-01,1,1,6.4649e-01,9.9052e-01,9.9052e-01,1,1,1,8.8676e-01,1,1,1,8.8676e-01,1,1,1,1,1,1,1,1,7.1717e-01,1,1,1,1,7.1833e-01,9.9839e-01,1,9.6530e-01,9.6530e-01,1,1,1,7.9385e-01,1,1,1,7.9385e-01,1,1,1,1,1,6.3487e-01,1,1,1,6.3487e-01,1,1,1,1,1,1,1,1,5.7978e-01,5.7978e-01,1,1,1
132Sn 50+ 50+ 50+ 50+ 50+ 50+ =1.9777e+02,1.9777e+02,5,9.3656e+04,1.2475e-04,0,1.2648e-02,1.3650e+03,4.6516e+01,6.7244e-01,1,1,1,1,6.7501e-01,9.9620e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3.7027e-01,3.7027e-01,1,1,1,1,1,1,1,1,1,1,1,7.5543e-01,1,1,1,1,7.5623e-01,9.9894e-01,1,7.9456e-01,1,1,1,7.9456e-01,1,1,1,1,1,1,1,1,8.1869e-01,8.1869e-01,1,1,1,6.1918e-01,9.6107e-01,1,1,6.4426e-01,9.8196e-01,9.8196e-01,1,1,1,8.6770e-01,1,1,1,8.6770e-01,1,1,1,1,1,1,1,1,7.1717e-01,1,1,1,1,7.1833e-01,9.9839e-01,1,9.4351e-01,9.4351e-01,1,1,1,7.8514e-01,1,1,1,7.8514e-01,1,1,1,1,1,6.3719e-01,1,1,1,6.3719e-01,1,1,1,1,1,1,1,1,5.7899e-01,5.7899e-01,1,1,1
132Sn 50+ 50+ 50+ 50+ 50+ 50+ =9.3458e+04,9.3458e+04,4,9.3656e+04,6.2386e-02,0,1.1951e-02,1.3656e+03,5.0166e+01,6.7244e-01,1,1,1,1,6.7501e-01,9.9620e-01,1,1,1,1,1,1,1,1,1,1,9.9759e-01,1,1,1,9.9854e-01,3.8582e-01,3.8582e-01,1,1,1,1,1,1,1,1,1,1,1,7.5543e-01,1,1,1,1,7.5623e-01,9.9894e-01,1,7.8816e-01,1,1,1,7.8816e-01,1,1,1,1,1,1,1,1,8.1855e-01,8.1855e-01,1,1,1,5.9503e-01,9.2946e-01,1,1,6.4018e-01,9.7180e-01,9.7180e-01,1,1,1,8.5804e-01,1,1,1,8.5842e-01,1,1,1,1,1,1,1,1,7.1717e-01,1,1,1,1,7.1833e-01,9.9839e-01,1,9.2282e-01,9.2282e-01,1,1,1,7.8235e-01,1,1,1,7.8235e-01,1,1,1,1,1,6.3757e-01,1,1,1,6.3757e-01,1,1,1,1,1,1,1,1,5.7847e-01,5.7847e-01,1,1,1
131Sn 50+ 50+ 50+ 50+ 50+ 50+ =7.4740e-01,7.4740e-01,6,2.5004e+05,1.7412e-06,0,3.4245e-03,1.3640e+03,4.1860e+01,6.7286e-01,1,1,1,1,6.7543e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2.3105e-01,2.3105e-01,1,1,1,1,1,1,1,1,1,1,1,7.5604e-01,1,1,1,1,7.5683e-01,9.9896e-01,1,8.0655e-01,1,1,1,8.0655e-01,1,1,1,1,1,1,1,1,7.9643e-01,7.9643e-01,1,1,1,6.3920e-01,9.8470e-01,1,1,6.4913e-01,9.9101e-01,9.9101e-01,1,1,1,8.8821e-01,1,1,9.9875e-01,8.8932e-01,1,1,1,1,1,1,1,1,7.1787e-01,1,1,1,1,7.1900e-01,9.9843e-01,1,9.7042e-01,9.7042e-01,1,1,1,7.9510e-01,1,1,1,7.9510e-01,1,1,1,1,1,6.3560e-01,1,1,1,6.3560e-01,1,1,1,1,1,1,1,1,2.2912e-01,2.2912e-01,1,1,1
131Sn 50+ 50+ 50+ 50+ 50+ 50+ =9.6940e+02,9.6940e+02,5,2.5004e+05,2.1990e-03,0,3.5170e-03,1.3647e+03,4.7049e+01,6.7286e-01,1,1,1,1,6.7543e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,9.9655e-01,9.9662e-01,1,1,1,2.6574e-01,2.6574e-01,1,1,1,1,1,1,1,1,1,1,1,7.5604e-01,1,1,1,1,7.5682e-01,9.9896e-01,1,7.9530e-01,1,1,1,7.9530e-01,1,1,1,1,1,1,1,1,7.9502e-01,7.9502e-01,1,1,1,6.2233e-01,9.6487e-01,1,1,6.4499e-01,9.8067e-01,9.8067e-01,1,1,1,8.7234e-01,1,1,1,8.7234e-01,1,1,1,1,1,1,1,1,7.1787e-01,1,1,1,1,7.1899e-01,9.9843e-01,1,9.4207e-01,9.4207e-01,1,1,1,7.8822e-01,1,1,1,7.8822e-01,1,1,1,1,1,6.3647e-01,1,1,9.9747e-01,6.3809e-01,1,1,1,1,1,1,1,1,2.2860e-01,2.2860e-01,1,1,1
131Sn 50+ 50+ 50+ 50+ 50+ 50+ =2.4907e+05,2.4907e+05,4,2.5004e+05,5.9020e-01,0,3.3668e-03,1.3653e+03,5.0973e+01,6.7286e-01,1,1,1,1,6.7543e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,9.9017e-01,9.9210e-01,1,1,9.9805e-01,2.8867e-01,2.8867e-01,1,1,1,1,1,1,1,1,1,1,1,7.5604e-01,1,1,1,1,7.5682e-01,9.9896e-01,1,7.8897e-01,1,1,1,7.8897e-01,1,1,1,1,1,1,1,1,7.9402e-01,7.9402e-01,1,1,1,5.9299e-01,9.2476e-01,1,1,6.4123e-01,9.6732e-01,9.6732e-01,1,1,1,8.6070e-01,1,1,9.9687e-01,8.6339e-01,1,1,1,1,1,1,1,1,7.1787e-01,1,1,1,1,7.1899e-01,9.9843e-01,1,9.1730e-01,9.1730e-01,1,1,1,7.8538e-01,1,1,1,7.8538e-01,1,1,1,1,1,6.3701e-01,1,1,9.9850e-01,6.3797e-01,1,1,1,1,1,1,1,1,2.2725e-01,2.2725e-01,1,1,1
130Sn 50+ 50+ 50+ 50+ 50+ 50+ =8.6560e-01,8.6560e-01,6,1.5325e+05,2.8737e-05,0,2.4030e-04,1.3638e+03,4.2986e+01,6.7328e-01,1,1,1,1,6.7585e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,9.9212e-01,9.9212e-01,1,1,1,1.4482e-01,1.4482e-01,1,1,1,1,1,1,1,1,1,1,1,7.5665e-01,1,1,1,1,7.5742e-01,9.9899e-01,1,8.0618e-01,1,1,1,8.0618e-01,1,1,1,1,1,1,1,1,7.2690e-01,7.2690e-01,1,1,1,6.4767e-01,9.9707e-01,1,1,6.4957e-01,9.9875e-01,9.9875e-01,1,1,1,8.9181e-01,1,1,1,8.9181e-01,1,1,1,1,1,1,1,1,7.1857e-01,1,1,1,1,7.1966e-01,9.9847e-01,1,9.8798e-01,9.8798e-01,1,1,1,7.9569e-01,1,1,1,7.9569e-01,1,1,1,1,1,6.3524e-01,1,1,1,6.3524e-01,1,1,1,1,1,1,1,1,2.7064e-02,2.7064e-02,1,1,1
130Sn 50+ 50+ 50+ 50+ 50+ 50+ =1.3274e+03,1.3274e+03,5,1.5325e+05,3.8977e-02,0,2.7170e-04,1.3644e+03,4.7810e+01,6.7328e-01,1,1,1,1,6.7585e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,9.8187e-01,9.8206e-01,1,1,1,1.7817e-01,1.7817e-01,1,1,1,1,1,1,1,1,1,1,1,7.5665e-01,1,1,1,1,7.5742e-01,9.9899e-01,1,7.9653e-01,1,1,1,7.9653e-01,1,1,1,1,1,1,1,1,7.2599e-01,7.2599e-01,1,1,1,6.3567e-01,9.8485e-01,1,1,6.4545e-01,9.9485e-01,9.9485e-01,1,1,1,8.7657e-01,1,1,1,8.7657e-01,1,1,1,1,1,1,1,1,7.1856e-01,1,1,1,1,7.1966e-01,9.9847e-01,1,9.6724e-01,9.6724e-01,1,1,1,7.9141e-01,1,1,1,7.9141e-01,1,1,1,1,1,6.3495e-01,1,1,9.9389e-01,6.3886e-01,1,1,1,1,1,1,1,1,2.7231e-02,2.7231e-02,1,1,1
130Sn 50+ 50+ 50+ 50+ 50+ 50+ =1.5192e+05,1.5192e+05,4,1.5325e+05,4.2908e+00,0,2.8247e-04,1.3650e+03,5.1451e+01,6.7328e-01,1,1,1,1,6.7585e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,9.6986e-01,9.7227e-01,1,1,9.9752e-01,2.0255e-01,2.0255e-01,1,1,1,1,1,1,1,1,1,1,1,7.5665e-01,1,1,1,1,7.5742e-01,9.9899e-01,1,7.9092e-01,1,1,1,7.9092e-01,1,1,1,1,1,1,1,1,7.2370e-01,7.2370e-01,1,1,1,6.2251e-01,9.6865e-01,1,1,6.4265e-01,9.9042e-01,9.9042e-01,1,1,1,8.6534e-01,1,1,9.9642e-01,8.6845e-01,1,1,1,1,1,1,1,1,7.1856e-01,1,1,1,1,7.1966e-01,9.9847e-01,1,9.4786e-01,9.4786e-01,1,1,1,7.8861e-01,1,1,1,7.8861e-01,1,1,1,1,1,6.3571e-01,1,1,9.9476e-01,6.3905e-01,1,1,1,1,1,1,1,1,2.7069e-02,2.7069e-02,1,1,1
129Sn 50+ 50+ 50+ 50+ 50+ 50+ =6.7354e-02,6.7354e-02,6,2.0814e+03,1.5320e-04,0,3.5074e-06,1.3635e+03,4.3653e+01,6.7370e-01,1,1,1,1,6.7628e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,9.6767e-01,9.6767e-01,1,1,1,7.8348e-02,7.8348e-02,1,1,1,1,1,1,1,1,1,1,1,7.5727e-01,1,1,1,1,7.5802e-01,1,1,8.0592e-01,1,1,1,8.0592e-01,1,1,1,1,1,1,1,1,6.3297e-01,6.3297e-01,1,1,1,6.4960e-01,1,1,1,6.4968e-01,1,1,1,1,1,8.9350e-01,1,1,1,8.9350e-01,1,1,1,1,1,1,1,1,7.1926e-01,1,1,1,1,7.2033e-01,9.9852e-01,1,9.9863e-01,9.9863e-01,1,1,1,7.9607e-01,1,1,1,7.9607e-01,1,1,1,1,1,6.3542e-01,1,1,1,6.3542e-01,1,1,1,1,1,1,1,1,8.4296e-04,8.4296e-04,1,1,1
129Sn 50+ 50+ 50+ 50+ 50+ 50+ =1.3825e+02,1.3825e+02,5,2.0814e+03,2.5054e-01,0,4.4023e-06,1.3641e+03,4.8268e+01,6.7370e-01,1,1,1,1,6.7628e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,9.4969e-01,9.5004e-01,1,1,1,1.0745e-01,1.0745e-01,1,1,1,1,1,1,1,1,1,1,1,7.5727e-01,1,1,1,1,7.5802e-01,1,1,7.9884e-01,1,1,1,7.9884e-01,1,1,1,1,1,1,1,1,6.3259e-01,6.3259e-01,1,1,1,6.4563e-01,9.9810e-01,1,1,6.4686e-01,1,1,1,1,1,8.8266e-01,1,1,1,8.8266e-01,1,1,1,1,1,1,1,1,7.1926e-01,1,1,1,1,7.2033e-01,9.9852e-01,1,9.9172e-01,9.9172e-01,1,1,1,7.9340e-01,1,1,1,7.9340e-01,1,1,1,1,1,6.3498e-01,1,1,9.9396e-01,6.3884e-01,1,1,1,1,1,1,1,1,8.1781e-04,8.1781e-04,1,1,1
129Sn 50+ 50+ 50+ 50+ 50+ 50+ =1.9430e+03,1.9430e+03,4,2.0814e+03,3.1067e+00,0,4.9896e-06,1.3646e+03,5.1704e+01,6.7370e-01,1,1,1,1,6.7628e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,9.3384e-01,9.3647e-01,1,1,9.9718e-01,1.3008e-01,1.3008e-01,1,1,1,1,1,1,1,1,1,1,1,7.5726e-01,1,1,1,1,7.5802e-01,1,1,7.9368e-01,1,1,1,7.9368e-01,1,1,1,1,1,1,1,1,6.3033e-01,6.3033e-01,1,1,1,6.4000e-01,9.9303e-01,1,1,6.4450e-01,9.9750e-01,9.9750e-01,1,1,1,8.7442e-01,1,1,1,8.7442e-01,1,1,1,1,1,1,1,1,7.1926e-01,1,1,1,1,7.2033e-01,9.9852e-01,1,9.8126e-01,9.8126e-01,1,1,1,7.9152e-01,1,1,1,7.9152e-01,1,1,1,1,1,6.3465e-01,1,1,9.9206e-01,6.3973e-01,1,1,1,1,1,1,1,1,8.1316e-04,8.1316e-04,1,1,1
128Sn 50+ 50+ 50+ 50+ 50+ 50+ =2.3055e-03,2.3055e-03,6,6.7606e+00,2.8918e-03,0,6.3604e-09,1.3632e+03,4.5319e+01,6.7413e-01,1,1,1,1,6.7671e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,9.1443e-01,9.1448e-01,1,1,1,3.8130e-02,3.8130e-02,1,1,1,1,1,1,1,1,1,1,1,7.5788e-01,1,1,1,1,7.5862e-01,1,1,8.0302e-01,1,1,1,8.0302e-01,1,1,1,1,1,1,1,1,5.1578e-01,5.1578e-01,1,1,1,6.4874e-01,1,1,1,6.4874e-01,1,1,1,1,1,8.8968e-01,1,1,1,8.8968e-01,1,1,1,1,1,1,1,1,7.1997e-01,1,1,1,1,7.2101e-01,9.9856e-01,1,1,1,1,1,1,7.9553e-01,1,1,1,7.9553e-01,1,1,1,1,1,6.3778e-01,1,1,1,6.3778e-01,1,1,1,1,1,1,1,1,4.0889e-06,4.0889e-06,1,1,1
128Sn 50+ 50+ 50+ 50+ 50+ 50+ =2.0252e+00,2.0252e+00,5,6.7606e+00,1.8324e+00,0,8.8172e-09,1.3638e+03,4.9070e+01,6.7413e-01,1,1,1,1,6.7671e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,8.9555e-01,8.9617e-01,1,1,1,5.6596e-02,5.6596e-02,1,1,1,1,1,1,1,1,1,1,1,7.5788e-01,1,1,1,1,7.5862e-01,1,1,7.9856e-01,1,1,1,7.9856e-01,1,1,1,1,1,1,1,1,5.1507e-01,5.1507e-01,1,1,1,6.4697e-01,1,1,1,6.4699e-01,1,1,1,1,1,8.8252e-01,1,1,1,8.8252e-01,1,1,1,1,1,1,1,1,7.1997e-01,1,1,1,1,7.2101e-01,9.9856e-01,1,1,1,1,1,1,7.9313e-01,1,1,1,7.9313e-01,1,1,1,1,1,6.3934e-01,1,1,1,6.3934e-01,1,1,1,1,1,1,1,1,3.9742e-06,3.9742e-06,1,1,1
128Sn 50+ 50+ 50+ 50+ 50+ 50+ =4.7330e+00,4.7330e+00,4,6.7606e+00,3.5212e+00,0,1.0724e-08,1.3643e+03,5.1942e+01,6.7413e-01,1,1,1,1,6.7671e-01,9.9619e-01,1,1,1,1,1,1,1,1,1,1,8.8044e-01,8.8323e-01,1,1,9.9684e-01,7.3277e-02,7.3277e-02,1,1,1,1,1,1,1,1,1,1,1,7.5788e-01,1,1,1,1,7.5862e-01,1,1,7.9520e-01,1,1,1,7.9520e-01,1,1,1,1,1,1,1,1,5.1143e-01,5.1143e-01,1,1,1,6.4518e-01,1,1,1,6.4544e-01,1,1,1,1,1,8.7830e-01,1,1,1,8.7830e-01,1,1,1,1,1,1,1,1,7.1996e-01,1,1,1,1,7.2101e-01,9.9856e-01,1,9.9698e-01,9.9698e-01,1,1,1,7.9302e-01,1,1,1,7.9302e-01,1,1,1,1,1,6.3794e-01,1,1,9.9699e-01,6.3986e-01,1,1,1,1,1,1,1,1,3.8883e-06,3.8883e-06,1,1,1
134In 49+ 49+ 49+ 49+ 49+ 49+ =1.7016e-04,1.7016e-04,4,1.7016e-04,5.0123e-09,0,2.7084e-04,1.3679e+03,4.7579e+01,6.7196e-01,1,1,1,1,6.7417e-01,9.9673e-01,1,1,1,1,1,1,1,1,1,1,9.7406e-01,9.7412e-01,1,1,1,7.7666e-01,7.7666e-01,1,1,1,1,1,1,1,1,1,1,1,7.5441e-01,1,1,1,1,7.5518e-01,9.9898e-01,1,7.9449e-01,1,1,1,7.9449e-01,1,1,1,1,1,1,1,1,5.1391e-01,5.1391e-01,1,1,1,3.2681e-01,5.0987e-01,1,1,6.4097e-01,9.5379e-01,9.5379e-01,1,1,1,8.5613e-01,1,1,1,8.5613e-01,1,1,1,1,1,1,1,1,7.1603e-01,1,1,1,1,7.1716e-01,9.9843e-01,1,7.9420e-01,7.9420e-01,1,1,1,7.8210e-01,1,1,1,7.8210e-01,1,1,1,1,1,6.3936e-01,1,1,1,6.3951e-01,1,1,1,1,1,1,1,1,2.2794e-02,2.2794e-02,1,1,1
133In 49+ 49+ 49+ 49+ 49+ 49+ =2.5785e-04,2.5785e-04,4,2.5785e-04,6.0140e-07,0,3.4206e-06,1.3676e+03,4.8268e+01,6.7238e-01,1,1,1,1,6.7458e-01,9.9673e-01,1,1,1,1,1,1,1,1,1,1,9.9277e-01,9.9294e-01,1,1,1,7.3128e-01,7.3128e-01,1,1,1,1,1,1,1,1,1,1,1,7.5501e-01,1,1,1,1,7.5577e-01,1,1,7.9240e-01,1,1,1,7.9240e-01,1,1,1,1,1,1,1,1,3.7588e-01,3.7588e-01,1,1,1,3.6253e-01,5.6642e-01,1,1,6.4004e-01,9.5726e-01,9.5726e-01,1,1,1,8.5437e-01,1,1,1,8.5437e-01,1,1,1,1,1,1,1,1,7.1672e-01,1,1,1,1,7.1782e-01,9.9847e-01,1,8.0312e-01,8.0312e-01,1,1,1,7.8151e-01,1,1,1,7.8151e-01,1,1,1,1,1,6.3916e-01,1,1,1,6.3916e-01,1,1,1,1,1,1,1,1,3.6552e-04,3.6552e-04,1,1,1
132In 49+ 49+ 49+ 49+ 49+ 49+ =5.0222e-06,5.0222e-06,4,5.0222e-06,1.9291e-05,0,2.0769e-09,1.3673e+03,4.8940e+01,6.7280e-01,1,1,1,1,6.7500e-01,9.9673e-01,1,1,1,1,1,1,1,1,1,1,9.9869e-01,1,1,1,1,6.5955e-01,6.5955e-01,1,1,1,1,1,1,1,1,1,1,1,7.5562e-01,1,1,1,1,7.5636e-01,1,1,7.9103e-01,1,1,1,7.9103e-01,1,1,1,1,1,1,1,1,2.5224e-01,2.5224e-01,1,1,1,4.0784e-01,6.3743e-01,1,1,6.3981e-01,9.7008e-01,9.7008e-01,1,1,1,8.5348e-01,1,1,1,8.5348e-01,1,1,1,1,1,1,1,1,7.1741e-01,1,1,1,1,7.1848e-01,9.9852e-01,1,8.2867e-01,8.2867e-01,1,1,1,7.8063e-01,1,1,1,7.8063e-01,1,1,1,1,1,6.3866e-01,1,1,1,6.3866e-01,1,1,1,1,1,1,1,1,3.1061e-07,3.1061e-07,1,1,1
